### ISSUE TITLE
[Feature request] Other views

### ISSUE THREAD

**Issue by kTyn9A9Kw3** [SimpleMobileTools/Simple-Calendar#1]
Year view specially, it could be split to 6 months to save screen space on small devices. Other views like week and day/agenda would be nice too.

**Comment by cyberbeat** [comment]
I would like to have a simple list view (listing all future entries)

**Comment by tibbi** [comment]
1.26 will get a yearly view

**Comment by tibbi** [comment]
and 1.27 got a simple list with all events within 1 year, just to have some limit.

**Comment by cyberbeat** [comment]
Wouldn't it make sense, to simply restrict the list-view on xxx entries (for example 100, perhaps configurable)?

**Comment by tibbi** [comment]
sure, i can add it
