### ISSUE TITLE
Simple event list: Swipe-to-refresh ignores limit setting

### ISSUE THREAD

**Issue by rfolo9li** [SimpleMobileTools/Simple-Calendar#1002]
### Observed behaviour
I use the calendar in the "simple event list" mode. When I swipe down, the app loads all events from the past despite the setting "Display events from the past" is set to "1 day". 

Furthermore, the refresh is triggered without any indication so that the refresh is probably always unexpected (and unintended).

###  Expected behaviour
As a user I would expect that the event list does not go back beyond the set limit.

P. S. Nice app, I use it all day =)

**Comment by tibbi** [comment]
it has been changed already, but you can still get to the past by swiping up. It just sets the default visibility.
