### ISSUE TITLE
Disable notifications for specific calendars

### ISSUE THREAD

**Issue by myxor** [SimpleMobileTools/Simple-Calendar#1003]
It should be possible to disable notifications for specific calendars.

For example i have my work calendar on my phone but i do not wish to get notifications for it as i already get the notification on Thunderbird.

**Comment by tibbi** [comment]
You can already disable specific reminder streams by event type from Android 8, that is the proper way of doing it. Just go into the app notification settings through the system settings. Make sure you use the latest Pro version though. I dont plan adding any workaround for older OS versions.

**Comment by al733** [comment]
Hi @tibbi , I don't have such options for disabling streams by event on the app notification settings (through systems settings). I can only enable or disable all notifications (and chose discrete or notifications with sound).

My config:
- Android 14 / Samsung S23
- Simple Calendar (Pro ?) downloaded on F-Droid - v 6.23.1
