### ISSUE TITLE
Unable to remove birthdays.

### ISSUE THREAD

**Issue by 532910** [SimpleMobileTools/Simple-Calendar#1004]
I've pressed "Add contact birthdays". Hot should I remove them now? I've read the Frequently asked questions: "How can I remove the holidays imported via "Add  holidays" button?" -> There are no birthdays in Settings -> Manage event types.

**Comment by tibbi** [comment]
it should be there, what app version are you using?

**Comment by 532910** [comment]
v 6.6.4 Pro from f-droid

**Comment by tibbi** [comment]
and have actually any birthdays get imported?

**Comment by 532910** [comment]
Sure, I see them in the calendar.

**Comment by 532910** [comment]
![image](https://user-images.githubusercontent.com/14617699/68023511-5878bb00-fcb8-11e9-8de6-4389607198c8.png)
![image](https://user-images.githubusercontent.com/14617699/68023667-e6ed3c80-fcb8-11e9-8d4a-dce523487138.png)

**Comment by tibbi** [comment]
I dont see how would this be an apps issue, guess it got sorted out already anyway
