### ISSUE TITLE
Can not enable caldav sync

### ISSUE THREAD

**Issue by Woodhousemelena** [SimpleMobileTools/Simple-Calendar#1006]
Great app. Small gripe.

Trying to connect it to a caldav source, but don't know how....

If I enable caldav sync it tells me to select calendars... after that.. nothing. 

No selection dialog etc. I do have DAVx5 installed to connect to my nextcloud server...

**Comment by tibbi** [comment]
Make sure DAVx5 is working and syncing properly. Do the selected calendars show up well in other apps? What Simple Calendar app version do you have?

**Comment by Woodhousemelena** [comment]
I just figured it out. Some hidden settings needed to be activated in DAVx5. after a sync I could see the calendars in Simple calendar. 

Just a small hint in the settings dialog would be nice for the avg user i think. Example: Works after a fully enabled and working DAVx5. I was guessing about DAVx5, but from the start that was not clear either. I can not seem to find instructions anywhere.... 

Nevertheless great App together with all the other Simple-****

**Comment by tibbi** [comment]
Well the vast majority of users use syncing viaGoogle Calendar, which works just fine. There are many other options, it is not just DAVx5. They should give out some clear instructions themselves.

**Comment by Woodhousemelena** [comment]
Yes, I realize that now. I was performing an experiment getting away from google when I stumbled into this (a degoogled phone)....  You correctly state that having a google account on the phone will automatically allow connection from your app!  Super!! When running into this it is easy to blame the app first. That is why it might be a nice gesture to mention that one would need an external caldav app to facilitate this without google calendar. All running great now. Very happy!

**Comment by tibbi** [comment]
it is described in the FAQ, thats why Im trying to redirect people there first before sending an email to me. It is still called DavDroid there, will fix it soon.

**Comment by Woodhousemelena** [comment]
Yes it is hard to find this info when using a searchengine. Just made a Paypal payment for your efforts!

Thank you!

**Comment by tibbi** [comment]
thanks, enjoy :)
