### ISSUE TITLE
CalDAV problems

### ISSUE THREAD

**Issue by hman2** [SimpleMobileTools/Simple-Calendar#1007]
When I try to activate the "CalDAV synchronisation" toggle, a window pops up "select calendar for synchronisation", and Ok and Cancel buttons. No matter which of those two I press, the window just vanishes and the toggle is still off.

I expected to be asked to give the URL of my OwnCloud server, but I wasn't. Is there additional software needed? OwnCloud app is installed and works, MyOwnNotes works, too. 

Thanks
hman

Btw., this is Simple Calendar 6.6.3 on Nougat, or more precisely, on Fairphone Open OS 19.08.1, which is a Nougat 7.1.2 without Google. So the default Android calendar is not being synced anywhere. Owncloud 2.13.1 is installed.

**Comment by tibbi** [comment]
It is described in FAQ. You need some app taking care of synchronization between the device and the servers. Try either DAVx5, or ACalDAV. Simple Calendar is an offline app so it cannot do anything with urls.

**Comment by hman2** [comment]
Well, on F-Droid your description says "CalDAV calendar sync supported" and now some other app has to do that. MyOwnNotes syncs notes directly to owncloud for instance... But thanks for the info.

**Comment by tibbi** [comment]
Yes, CalDAV is supported, thats how it works. It is also described in FAQ.
