### ISSUE TITLE
Location and travel time based notifications

### ISSUE THREAD

**Issue by Sohalt** [SimpleMobileTools/Simple-Calendar#1013]
When an event has both a time and a location it would be cool to be able to get notified far enough in advance based on the current traffic situation to still make it in time. Specifically I'd like the app to repeatedly query how long it would take from my current position to get to the position of the event and if the start of the event is less than the travel time + some margin in the future I'd like to get a notification.

**Comment by tibbi** [comment]
That is way too advanced for this app and it would also require additional permissions, so dont expect having it. Thanks though
