### ISSUE TITLE
Can not build app

### ISSUE THREAD

**Issue by turlir** [SimpleMobileTools/Simple-Calendar#102]
Hi. I want to help with the solution of some problems, but I can not build this project. Android Studio and gradle `assembleDebug` task give the same result:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
```
It is impossible to develop (debugging) an application made under the limit. How you build debug app?

**Comment by tibbi** [comment]
Im not getting it, but its an easy fix with just a couple lines added. Some info is at https://developer.android.com/studio/build/multidex.html . You have to add 2 lines to build.gradle and extend the MultiDexApplication. I can take a look at it later.
