### ISSUE TITLE
Cannot import event types 

### ISSUE THREAD

**Issue by Applemann** [SimpleMobileTools/Simple-Calendar#1024]
I want to import data from old Simple-Calendar v5.1.4 into Simple-Calendar-Pro v6.7.1 but it doesn't import also my event types with colors:

Old version:
![Screenshot_20191129-111707](https://user-images.githubusercontent.com/2686906/69862479-c5bd4300-129a-11ea-9072-097134f66f0d.png)

New version:
![Screenshot_20191129-111742](https://user-images.githubusercontent.com/2686906/69862493-cb1a8d80-129a-11ea-9c7e-fc967062e055.png)

**Comment by tibbi** [comment]
if you check the exported .ics file, does it contain lines with "CATEGORY-COLOR", or "CATEGORY"? Havent you checked the "Override event types" at the import dialog?

**Comment by Applemann** [comment]
Yes I have there CATEGORY-COLOR but I don't see the CATEGORY:
![Screenshot_20191129-115906](https://user-images.githubusercontent.com/2686906/69864925-47639f80-12a0-11ea-82a2-d88c1170eda0.png)

And during import I checked "overwrite event types"

**Comment by tibbi** [comment]
well so uncheck the "overwrite event types". It makes the "categories" be ignored

**Comment by Applemann** [comment]
Yes. I removed all events and imported again it without check the label and now it is good. :)

Maybe you should fix naming of checkbox because I thought that it will rewrite the event types when it is checked and overlooked the last word about file:
![Screenshot_20191129-121628](https://user-images.githubusercontent.com/2686906/69865817-99a5c000-12a2-11ea-9743-9942a7e40426.png)

**Comment by tibbi** [comment]
well not sure how could it be made more clear, Ill think of it

**Comment by Applemann** [comment]
You can have there: "Přepsat všechny typy událostí v kalendáři" and checkbox checked in default.

**Comment by tibbi** [comment]
it is quite equally confusing :)
