### ISSUE TITLE
Location autocomplete from Openstreetmap

### ISSUE THREAD

**Issue by BuZZ-dEE** [SimpleMobileTools/Simple-Calendar#1026]
It would be great to have location autocomplete from Openstreetmap.

**Comment by tibbi** [comment]
the app is offline, so it cannot be added

**Comment by BuZZ-dEE** [comment]
hmm, where is problem to make requests?

**Comment by tibbi** [comment]
to some OSM app, or what requests?

**Comment by BuZZ-dEE** [comment]
> to some OSM app, or what requests?

To [Nominatim](https://nominatim.openstreetmap.org). Please have a look at [usage policy](https://operations.osmfoundation.org/policies/nominatim/)

* https://nominatim.openstreetmap.org
* https://operations.osmfoundation.org/policies/nominatim

**Comment by tibbi** [comment]
I mean that our app doesnt have internet permission, so it cannot be added

**Comment by BuZZ-dEE** [comment]
@tibbi But why is it  a problem to request the internet permission, if the user wants to use this feature? If the user does not need this feature, Simple-Calendar does not need the internet permission.

**Comment by tibbi** [comment]
because none of our app has internet permission, that is one of our biggest benefits

**Comment by BuZZ-dEE** [comment]
I'm unsure if it is a benefit in this case. Also the benefit is still there, if the user does not grant that permission.

**Comment by BuZZ-dEE** [comment]
Video of how this works in Tasks.
https://github.com/SimpleMobileTools/Simple-Calendar/assets/125954/76847ea0-0740-4729-aff0-fa2a0098173b
