### ISSUE TITLE
Repeat event daily but only Mo-Fr (on weekdays) or weekends

### ISSUE THREAD

**Issue by pokulo** [SimpleMobileTools/Simple-Calendar#1027]
Our daily meeting for SCRUM repeats only on regular working days, not on weekends. Thunderbird can show the recurrent event correctly, but Simple-Calendar also shows this daily event on weekends. This should at least be correctly ommitted on weekends. Adding editable daily recurance would be second step.

**Comment by tibbi** [comment]
just pick weekly repetition, you can specify days there

**Comment by pokulo** [comment]
Thanks for your reply! But I am not the one, who creates these events. Our Team-leader apparently chose the recurrence rule :
`RRULE:FREQ=DAILY;BYDAY=MO,TU,WE,TH,FR`
In favour of your proposed one:
`RRULE:FREQ=WEEKLY;INTERVAL=1;BYDAY=MO,TU,WE,TH,FR`
I can try to convince all our team members to avoid the unsupported combination of `DAILY` and `BYDAY`. Better and future-proof solution would be, to implement support for both variants in this app.
