### ISSUE TITLE
Korean Holiday listing

### ISSUE THREAD

**Issue by temp-uzr** [SimpleMobileTools/Simple-Calendar#1029]
When you add a holiday, you can see the list of name countries in their language. However, Korean was listed as English. It is not a major issue but when people first search for Korean you assume either English "Korean" or "한글/한국어". All this time I missed seeing "Hanguk" because I did not expect it. Can you add the Korean symbol or change the title? I would be more consistent with the current list formate. (Japanese is listed as in their language  "日本" and other countries as well)

My friends and I love the app and using for almost half year! Thank you so much for dedication to the app.

**Comment by Richsea** [comment]
nice. I'll change it and push PR, if it is ok.

**Comment by tibbi** [comment]
good to me, if you say to. Thanks
