### ISSUE TITLE
since last update I get twice the same reminder for new events

### ISSUE THREAD

**Issue by nopeppermint** [SimpleMobileTools/Simple-Calendar#1036]
Hi

since last update I get twice the same reminder for new events, used on android 8, xperia xz1 compact

**Comment by tibbi** [comment]
you mean that you see the reminder twice? Are you using version 6.8.1? It works just fine to me, there havent really been any changes related to that.

**Comment by nopeppermint** [comment]
Yes, I am using 6.8.1
The issue does magically no longer appear..
