### ISSUE TITLE
[ elaborate or explain ] Added time zone support (customization has to be enabled in the app settings)

### ISSUE THREAD

**Issue by leela52452** [SimpleMobileTools/Simple-Calendar#1044]
just now installed 6.8.1 fdroid version.
can you please elaborate and document about `Added time zone support (customization has to be enabled in the app settings)`

i did not find any settings to customize time zone.

**Comment by tibbi** [comment]
you have to enable "Allow changing event time zones" in the app settings, then a time zone picker shows up at event details
