### ISSUE TITLE
In Week View Time slot is not showing properly

### ISSUE THREAD

**Issue by karanbeer123** [SimpleMobileTools/Simple-Calendar#1048]
In Week View Time slot is not showing properly

**Comment by tibbi** [comment]
not sure what you mean. Can you send a screenshot? What app version are you using?

**Comment by karanbeer123** [comment]
> not sure what you mean. Can you send a screenshot? What app version are you using?


![device-2019-12-31-153614](https://user-images.githubusercontent.com/54027599/71617923-64fb9000-2be3-11ea-8a1d-6b5728651600.png)
![device-2019-12-31-153648](https://user-images.githubusercontent.com/54027599/71617924-64fb9000-2be3-11ea-8fc8-d74b695f864a.png)
Please check in this screen shots time is start from the  7 Am but i have print the log in WeekFragmentHolder Class time is print properly.but in view time is start from the 7 AM Please check

**Comment by tibbi** [comment]
and what is the issue there? I still dont understand

**Comment by karanbeer123** [comment]
> and what is the issue there? I still dont understand

The issue is here when i  have select the week view time is start from the 7 Am Rather than it should 
 start from the  1 Am

**Comment by tibbi** [comment]
you can customize in the app settings when should the weekly view start

**Comment by karanbeer123** [comment]
> you can customize in the app settings when should the weekly view start

ok but  last row is not showing properly

**Comment by karanbeer123** [comment]
> you can customize in the app settings when should the weekly view start

Thanks .But last row is not showing Properly.Please check

![device-2019-12-31-155358](https://user-images.githubusercontent.com/54027599/71618543-fff56980-2be5-11ea-9f7c-aba18cfd3227.png)
