### ISSUE TITLE
Fix the all day bar appearing when changing weeks

### ISSUE THREAD

**Issue by newhinton** [SimpleMobileTools/Simple-Calendar#1058]
Currently the 'all day event bar' jumps to existence when you switch to a week containing all day events. It dissapeares when you switch to a week without all day events.

My proposition:

Reduce the size required by the weekletters by changing the text from "M\n9" to "Mon 9" and fix the heigth of the 'all day event bar' and make it permanent.

~~I am willing to help out, and in fact i can already create a pr for the changed text.~~
~~I tried to make the height of the event in the bar fixed, but it seems that there is a general issue with the height of events when the text needs to be cut off. In those cases the height is bigger than wanted and therefore clips over other elements~~

Edit: that can be fixed with defining maxHeight

Edit:  #1059 and  #1060

![Screenshot_20200109-153924_Calendar_debug](https://user-images.githubusercontent.com/25279821/72077199-23f82f80-32f7-11ea-9d6d-8befd1db3b25.png)

**Comment by tibbi** [comment]
I dont like that, those fonts are way too small and the UI crowded. Thanks though
