### ISSUE TITLE
importing from org.sufficientlysecure.ical fails

### ISSUE THREAD

**Issue by olafhering** [SimpleMobileTools/Simple-Calendar#106]
I used org.sufficientlysecure.ical to export the Samsung calendar from a SM-G900FD Android 5. The plan was to import it after installing LineagoOS 14.1. First the built-in google calendar has no offline version, as a result the restore of above app does not work. Then I tried this app. It offers to import an .ics file.

But in the end none of the events in the file was imported. The .ics file is available on request.

**Comment by tibbi** [comment]
send the .ics file to hello@simplemobiletools.com please, to see if its a whole different file, or just some small glitch. Thanks

**Comment by olafhering** [comment]
Done

**Comment by tibbi** [comment]
should be fixed in 2.1.4, Ill release it soon
