### ISSUE TITLE
Add features to the UI

### ISSUE THREAD

**Issue by newhinton** [SimpleMobileTools/Simple-Calendar#1062]
I want to add a more intuitive way to switch between the different views. Basically i want to introduce a navigation drawer which then presents all the views there are.

Also i really like the bottom bar 'Bussiness Calendar 2' has, where you can toggle the different calendars and quickly only show the selected calendar.

As a third, i want to replace the dayview, as #962 already suggested.

However, those changes are quiet big and i am not sure what exactly is the design guideline your apps actually have, or if i break something with those features.
Honestly, i think BC2 has some great ideas, and many of my ideas are heavily inspired by that app, and i am not sure if i can implement some of those features from a legal standpoint, so i'd be happy with support :D

This is more a discussion issue than an actual request, i am open to develop most if not all by myself.

**Comment by tibbi** [comment]
Sorry, but I dont like navigation drawers and they are not used in any app. Having a button at the top left corner is a really ugly thing. I dont really want a bottom bar either, so far not a single person requested it. You just done change event filtering often. Thanks for the effort though.
