### ISSUE TITLE
Allow 'Loop reminders until dismissed' setting to be applied on a per-event basis 

### ISSUE THREAD

**Issue by sudomain** [SimpleMobileTools/Simple-Calendar#1064]
I'm thrilled that this app has the 'Loop reminders until dismissed' setting but if it is enabled then all reminders turn my device into a constant alarm clock. What would be great is if users could enable this setting for only certain events, event types, or reminders. More generally, it might be useful to be able to change any of the 'event reminder' settings (Vibrate, loop, reminder sound...) on a per event basis.

**Comment by tibbi** [comment]
you can change the vibration and sound per event type in your system settings if you have Android 8+

**Comment by tibbi** [comment]
such advanced settings wont be added, you can customize notification on a per event type basis in the system, as written previously
