### ISSUE TITLE
[support question] Microsoft 365 account with 2FA support?

### ISSUE THREAD

**Issue by amnk** [SimpleMobileTools/Simple-Calendar#1066]
I consider buying your calendar app, but I was not able to find if it is possible to connect Microsoft 365 account with 2FA (Microsoft authenticator)?

**Comment by tibbi** [comment]
Simple Calendar is an offline app, so it cannot handle cloud directly. The way it works is that you need a so called "sync adapter" to take care of syncing between your device and the cloud. Not sure which app can handle your case, maybe something from Microsoft itself. For other service people usually use DAVx5 or ACalDAV. Simple Calendar just shows events already located on the device itself, it doesnt care where did the events come from and how.
