### ISSUE TITLE
data loss after exporting and importing .ics file

### ISSUE THREAD

**Issue by leela52452** [SimpleMobileTools/Simple-Calendar#1067]
str :
create and save event
export .ics file
delete event
import .ics file

======

leela52452 created an issue: https://gitlab.com/leela52452/leela52452.gitlab.io/issues/86

Assignee: leela52452

[Firefox for iOS](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox_for_iOS)

-- 
Reply to this email directly or view it on GitLab: https://gitlab.com/leela52452/leela52452.gitlab.io/issues/86
You're receiving this email because of your activity on gitlab.com.

========

desired behaviour :
the event data should not be truncated

actual behaviour :
only this data is imported

=====

leela52452 created an issue: https://gitlab.com/leela52452/leela52452.gitlab.io/issues/86

=====

it must import complete data

**Comment by tibbi** [comment]
theres definitely not enough info, not sure how is it related to firefox on ios anyway

**Comment by leela52452** [comment]
> theres definitely not enough info

@tibbi ? i have provided data of event before and after export and import

to me, it look likes only first paragraph is imported and data below first paragraph is ignored

> not sure how is it related to firefox on ios anyway

the data is related to firefox

its irrelevant whether data belongs to firefox or anything else.

**Comment by leela52452** [comment]
**first paragraph**

> leela52452 created an issue: https://gitlab.com/leela52452/leela52452.gitlab.io/issues/86

**second paragraph**
>Assignee: leela52452

**third paragraph**
> Firefox for iOS

**fourth paragraph**
> --
Reply to this email directly or view it on GitLab: https://gitlab.com/leela52452/leela52452.gitlab.io/issues/86
You're receiving this email because of your activity on gitlab.com.
