### ISSUE TITLE
notification sound in endless loop

### ISSUE THREAD

**Issue by fosBHY** [SimpleMobileTools/Simple-Calendar#1068]
Hello there. I am relatively up to date (f-droid) with the app so I guess its an issue of a newer version as this app was working flawlessly before. For 2-4 weeks now (Im not certain, im sorry) I have the following issue:

When I get a notification, the sound is played in endless loop. it stops when I touch the notification icon (or after login in and touch it when im in screenlock).

If you need further research tell me pls.

currently 
v 6.8.3 Pro

**Comment by tibbi** [comment]
havent you enabled "Loop reminders until dismissed" in the app settings?

**Comment by fosBHY** [comment]
I had, apparently.. and I'm deeply sorry for this issue, it is closed. thank you
