### ISSUE TITLE
Application crashes when creating a new event

### ISSUE THREAD

**Issue by bsuuv** [SimpleMobileTools/Simple-Calendar#1072]
Application crashes when selecting a date and touching the floating plus-button. This started happening for me after the latest update. Neither rebooting my device nor reinstalling the application fixed the issue.

Seems similar to this issue from 2019: https://github.com/SimpleMobileTools/Simple-Calendar/issues/943

Version: 6.8.3
OS: Android 8.0.0

**Comment by tibbi** [comment]
Do you have event time zone customization enabled in the app settings? It is disabled by default.

**Comment by bsuuv** [comment]
I do not! It is disabled and out of curiosity I tried enabling it but it made no difference.

**Comment by bsuuv** [comment]
Lately multiple apps on my phone have started displaying  very similar crashing to this. This is therefore probably something with my phone and not with the app.
