### ISSUE TITLE
Simple event list wrong color for todays all-day events

### ISSUE THREAD

**Issue by lriesebos** [SimpleMobileTools/Simple-Calendar#1073]
Using the simple event list view, all-day events for today have an unexpected font color. Expect today's all-day events to have the same font color as tomorrows all-day events. See provided screenshot.

![Screenshot_20200131-134756](https://user-images.githubusercontent.com/28567817/73567070-8beff080-4433-11ea-850f-dbb3a881c878.png)

**Comment by tibbi** [comment]
orange font color is used for currently running events, not all all-day events
