### ISSUE TITLE
Notifications raised twice sometimes

### ISSUE THREAD

**Issue by NicoHood** [SimpleMobileTools/Simple-Calendar#1078]
I am using version 6.8.4 currently and sometimes events are raised twice. It takes around 10 seconds between the notifications, so me phone rings twice. I've not set multiple reminders, I've checked that. Any ideas why this could happen?

**Comment by tibbi** [comment]
not sure, are they casual one time events, or recurring? Can you reproduce it in some easy way?

**Comment by NicoHood** [comment]
It happens with both (one time and recurring), but not every time. It happens for newly created events (like a week ago), so it is reproducible on my phone "somehow". I tried to create an event in a minute, but that did not reproduce the error.

So I get this error very often, but I dont know how to reproduce or why it happens. :-(

**Comment by NicoHood** [comment]
Another update: When the notification arrives twice I first see the full date + time, and the second time it only shows the time, without the date. The first notification gets overwritten, so the first notification is no longer available. The delay between the two notifications is around 5 seconds.
