### ISSUE TITLE
[Feature Request] Silent Notifications

### ISSUE THREAD

**Issue by NicoHood** [SimpleMobileTools/Simple-Calendar#1079]
Currently you can set the following notifications:
* Email
* Notification

And you can change the alert channel of the notifications in the settings.

What I wish is a separate Notification, that does not play any sound. I want to differentiate between reminders that simply pop up, and those that also play a sound.

The best usecase is a reminder for birthdays. I usually set those reminders 12h earlier, so I get a notification a day before. I do not remove this notification until the next day, but playing a sound is really not needed here. Because then I could also set the birthday reminder to 0 minutes before and I do not get an alarm sound at night.

**Comment by tibbi** [comment]
if you have Android 8+, you can customize the "Birthdays" reminder stream to play no audio. Such things should be handled by the system, not by individual apps.

**Comment by NicoHood** [comment]
I do not know where I should find such a setting. I've got android one on a xiaomi a2 lite, android 9. Can you please help?

**Comment by tibbi** [comment]
well find the app in your device settings, then check the Notifications section. Or on some devices you can also trigger an event reminder from the Calendar by scheduling an event like 1 minute into the future or so, then long press that notification and press the Settings icon there

**Comment by NicoHood** [comment]
Found it, thanks!

**Comment by NicoHood** [comment]
Found it, thanks!
