### ISSUE TITLE
Recurring items are shown wrong

### ISSUE THREAD

**Issue by tobiasKaminsky** [SimpleMobileTools/Simple-Calendar#1083]
Hi, 

first of all, thanks for your great app!

I have an reminder that is scheduled every 4 weeks, and this is what I see on timeline widget and also in calendar:
![Screenshot_20200301-072608_Trebuchet](https://user-images.githubusercontent.com/5836855/75620898-12f8cb80-5b8e-11ea-9eb2-ff9dadecb898.png)

When I export my calendar I see this:
```
BEGIN:VEVENT
DTSTAMP:20200222T132624Z
UID:be6aa83c-20f8-411c-acb4-1583c9d95fe3
SEQUENCE:21
SUMMARY:Server updaten
DTSTART;TZID=Europe/Berlin:20190225T210000
DURATION:PT1H
RRULE:FREQ=WEEKLY;INTERVAL=4;BYDAY=MO
EXDATE:20190225T200000Z,20190325T200000Z,20190422T190000Z,20190520T190000Z,
 20190617T190000Z,20190909T190000Z,20191007T190000Z,20191104T200000Z,201912
 02T200000Z,20191230T200000Z,20200127T200000Z
CREATED:20190225T070355Z
X-MOZ-LASTACK:20190719T044502Z
X-MOZ-GENERATION:22
X-MOZ-SNOOZE-TIME-1560798000000000:20190705T233600Z
BEGIN:VALARM
TRIGGER:PT0S
ACTION:DISPLAY
DESCRIPTION:Server updaten
END:VALARM
END:VEVENT

BEGIN:VEVENT
DTSTAMP:20200222T132624Z
UID:be6aa83c-20f8-411c-acb4-1583c9d95fe3
RECURRENCE-ID;TZID=Europe/Berlin:20190715T210000
SEQUENCE:2
SUMMARY:Server updaten
DTSTART;TZID=Europe/Berlin:20190718T210000
DTEND;TZID=Europe/Berlin:20190718T220000
STATUS:CANCELLED
BEGIN:VALARM
TRIGGER:PT0S
ACTION:DISPLAY
DESCRIPTION:Server updaten
END:VALARM
END:VEVENT

BEGIN:VEVENT
DTSTAMP:20200222T132624Z
UID:be6aa83c-20f8-411c-acb4-1583c9d95fe3
RECURRENCE-ID;TZID=Europe/Berlin:20190812T210000
SEQUENCE:1
SUMMARY:Server updaten
DTSTART;TZID=Europe/Berlin:20190812T210000
DTEND;TZID=Europe/Berlin:20190812T220000
STATUS:CANCELLED
BEGIN:VALARM
TRIGGER:PT0S
ACTION:DISPLAY
DESCRIPTION:Server updaten
END:VALARM
END:VEVENT
```

(I use Nextcloud 18)

**Comment by aGrimRepoMan** [comment]
Also experienced something similar with Simple Calendar on android:
- NextCloud 18
- Weekly repeating event was initially created on Cardbook (Thunderbird email on Windows 10 PC)
- Once instance of the weekly repeating event was moved 3 days earlier to reflect change in meeting schedule.
- Syncing is done via Nextcloud 18 / DAVx5

**Comment by gleonet** [comment]
Same issue with the calendar connected to my Gmail account.
A recurring event is created and it appeared correctly on my phone.
When this event is updated (with all its future occurrences) it appears duplicated in Simple Calendar but not in the default Google Agenda.

**Comment by funkmastergst** [comment]
Similar behaviour on my mobile with Simple Calendar on android:

- repeating event was created on Thunderbird calendar
- Sync from PC to NextCloud 17
- Sync from NC to mobile via DAVx5
- In case of altering a single event of the series within Simple Calendar it is duplicated many many times in the Simple Calendar, but not in the Nextcloud instance or Thunderbird (but the intended change was pushed to NC nevertheless)

**Comment by Obscurax** [comment]
The same issue is happening here. 
Recurring event created in Thunderbird and scyned to Nextcloud.

Nextcloud 19
Thunderbird op PC
DAVx5 on mobile

Any update on this? 
It's a bit annoying seeing the same event repeated x times in the widget and missing the other events.

**Comment by xerus2000** [comment]
I guess I was about to open a similar issue:

I have this repeating event:
<img width="238" alt="image" src="https://user-images.githubusercontent.com/13354331/96283298-49c80880-0fdc-11eb-8af5-8d11f4bc00d0.png">

Which, after a few edits, multiplied itself:
![Screenshot_20201016-181733_Calendar](https://user-images.githubusercontent.com/13354331/96283386-6e23e500-0fdc-11eb-9f26-ab34b364a48f.jpg)

Curiously enough, none of the instance is recognized as a recurring event.
In other calendars this doesn't happen.

**Comment by esprit-libre** [comment]
Hello,
I also have the same issue.
My use-case:
- Nextcloud 19.0.3
- Event created with Thunderbird
- Sync with Davx5

What can be done to help debugging ?
Thanks for this great app !

**Comment by esprit-libre** [comment]
Something has changed in latest version? I don't notice anymore this issue on my LineageOS...

**Comment by tibbi** [comment]
well there have been many related improvements recently, guess this issue was undirectly fixed too. Ill close it for now, reopen if you still have some issues.

**Comment by esprit-libre** [comment]
Unfortunately, this appears on some recurring events but not all... so not solved yet :(
