### ISSUE TITLE
Could not show calendar from DecSyncCC?

### ISSUE THREAD

**Issue by ivysrono** [SimpleMobileTools/Simple-Calendar#1085]
https://f-droid.org/packages/org.decsync.cc/
I can select calendars stored in DecSync by CalDAV .
However, no event show?

Android 10.0
APP 6.8.4

**Comment by tibbi** [comment]
do they show well in other calendar apps on your device?

**Comment by ivysrono** [comment]
Yes, [Etar](https://f-droid.org/packages/ws.xsoh.etar/) is Ok.

**Comment by ivysrono** [comment]
they will show after add/delete/edit them
