### ISSUE TITLE
Setting to stop week view on Friday

### ISSUE THREAD

**Issue by zuphilip** [SimpleMobileTools/Simple-Calendar#1093]
I would like to suggest a feature to make the week view stops on Friday. This is especially handy if you mainly use the app for work, which you do from Monday to Friday. By only having 5 instead of 7 days in the week view there is more space for the other days.

**Comment by tibbi** [comment]
zooming in the weekly view both horizontally and vertically is on the roadmap. It will be more dynamic, not just ending on friday.
