### ISSUE TITLE
[ Feature request ] Assign event to multiple synced calendars

### ISSUE THREAD

**Issue by SkyWheel** [SimpleMobileTools/Simple-Calendar#1094]
**Actual behaviour** : Event creation allows assigning it only to one source of calendar synchronization.

**Desired behaviour** : Event creation allows assigning it to multiple sources of calendar synchronization. 
For example, I'm using DecSync and DAVx5 on my phone. When I create an event the app allows only one sync calendar, so I have to duplicate the same event to assign it to both DecSync and DAVx5.

**Comment by tibbi** [comment]
I dont really plan adding that, it is a too advanced scenario
