### ISSUE TITLE
Lookout Security app identifies Calendar as surveillanceware

### ISSUE THREAD

**Issue by JonTabor** [SimpleMobileTools/Simple-Calendar#1106]
After months of using Simple Calendar with the Lookout Security app on my phone, it suddenly today identified Calendar as surveillanceware. 

Do you know of any reason Lookout would flag this as such?

**Comment by tibbi** [comment]
They must have messed something up, mobile antivires usually cause more harm than good and you shouldnt be using any. Simple Calendar doesnt even have internet access.
