### ISSUE TITLE
java.lang.NumberFormatException: For input string: "-31,1"

### ISSUE THREAD

**Issue by mappu** [SimpleMobileTools/Simple-Calendar#1107]
The error in subject happens when syncing some calendar.

Running 6.9.1 from F-Droid

**Comment by tibbi** [comment]
Could you specify which event is causing the issue and how to reproduce it? This doesnt really help like this.

**Comment by mappu** [comment]
Thanks for the quick response,

I enabled the CalDAV sync option in the settings. I recognize all the calendar events that have appeared, but I don't know if the sync is complete because this message appears in a toast popup. The message happens when syncing one of my personal calendars. I can make it appear reliably when using pull-to-refresh.

Sorry I don't have any more minimal reproducing case + can't give you access to my calendar.

There seems to be no messages in adb logcat neither.

Is there anything more I can do to help?

![Screenshot_20200406-194921_Calendar_1](https://user-images.githubusercontent.com/3959202/78535382-26a7e980-7840-11ea-920a-2f441c2b46fd.png)

**Comment by tibbi** [comment]
Well I at least need to know which field does it happen to. If it is related to some repetition or what. This by itself doesnt help me. Try splitting events into some calendars or so and somehow figure out which event causes the issue. Dont you have some repetition exceptions there, or some unusual repetition rules? Are you syncing via Google, or what service?

**Comment by tibbi** [comment]
reopen the issue if you have more info, it isnt helpful enough like this
