### ISSUE TITLE
Q: Optimize snooze procedure

### ISSUE THREAD

**Issue by J0n1k4** [SimpleMobileTools/Simple-Calendar#1112]
Hi,
I installed Simple calendar due to it's integrated snooze options.
I have tried different calendar snooze apps, and neither one succeed to maintain continuity.
When I found out that Simple cal has a built-in option, I deacided to give it a try.
I like Simple calendar, but I find it quite difficult to snooze events.
The pop-up notofication near status bar disapears very quickly. There is a snooze option, but I almost never get to use it. By the time I hear the sound, and get the phone out of my pocket, the pop-up is gone.
So what are my options?
If I click the event in the status bar, the edit event is opened, so I am not able anymore to postpone the event. So I have to slide the event in the taskbar, to "unhide" the snooze option. But it is quite tricky to do that, as most of the time I slide the taskbar notifications, not able to "extend" the Simple calendar's notification, in order to get the "snooze" option. Then I have to click "snooze", and then to choose the snooze interval. Often, I want to snooze it for a not-predefined period, so I have to select "custom", and then to choose "day", enter the value, and hit OK (but that is a material for another question).
Screen lock notifications:
I have enabled: "Show all notifications on the lock screen". How can I snooze the notification from there? If I click on it and unlock the screen, the edit event is opened, so I am not able anymore to postpone the event.
Is it possible to add an option "default action when the event is selected: open it in calendar / open snooze option"?
Thank you for all your effort,
cheers,
Nika

**Comment by tibbi** [comment]
shorten the issue please, do not write essays here
