### ISSUE TITLE
Q: Optimizing Snooze Command

### ISSUE THREAD

**Issue by J0n1k4** [SimpleMobileTools/Simple-Calendar#1113]
Hi again.
I have one more suggestion, if you don't mind.
Is it possible to optimize the snooze event:
there are  predefined intervals and the option in settings and the "always use the same snooze time" slider, which allow us to use 5 predefined snooze intervals + the kast used, or to define 1 predefined snooze interval.

Would it be possible to configure the snooze intervals?

Suggestions:

When the event triggers, and when I hit the "snooze" button, there is 1,5,10,30 minutes, 1 hour, 1 day and "custom" snooze time available.
Ideally, it would have 3 columns:
FOR EXAMPLE:
________________________________
/check box/ "- (before the event)"
1min               1h                12h
5min               2h                18h
10min             4h                  1d
30min             6h                  2d
45min             8h                  7d
untill 9 o'clock tommorow
custom
________________________________

Explanation: /check box/ "- (before the event)" is a minus sign check box. With "-" checked and, for example, 30 minutes selected, the event would be snoozed until 30 minutes before the event...

If that is not sophisticated enough - under "custom" there could be (among the present options): customize predefined fields, and there could every predefined option be set according one's needs...

Here they are. The few suggestions - I suppose they  are not easy to incorporate into the code, but, this way, we could have a ultimate reminder app incorporated in calendar app. 
In combination with current CalDav sync - it would be the great tool...

Once again, thanks for your effort and already great app.
Cheers,
Nika

**Comment by J0n1k4** [comment]
One could ask "why would anyone need such a spread amount of snooze presets?".
There are distract people, because one's mind is preocupied with other worings.
They could often overlook some event. The events could be of different kinds:
- take the medicine (snooze 5-10 minutes, if you are in the middle of the chemical experiment, for example)
- prolong the car registration (snooze 1,2 days)
- buy the present for your darling for her birthday / Valentine's day, anniversary... (snooze untill the 09:00 tommorow or 1,2 days)
- buy the groceries (snooze 1,2,4,8,12,18 hours, untill 09:00 tommorow)
- call the electrician to repair the wash machine (snooze untill 09:00 tommorow)
and so on. 

Different events needs different postpone intervals.

This works in pair with "add reminder" from "new event" screen. If I know that an aniversery is on 01.09., I set 7-10 DAYS in advance the first reminder, then 1 day before the second, and 1 hour before the event the third reminder. However - do you know now what will you do, for example, on the 25.08 at 11:00? Or should you put 17:00 as reminder time?
With wide pallete of the snooze presets, you could easily postpone the reminder at that time - 1 week before the event, acording the active situation. And postpone again. And again. So if you are preocupied at the reminder time, you wouldn't just dismis the event and miss the aniversary date. 
Or the birthday.
Or pay the fine because you missed to prolong the car registration...

**Comment by tibbi** [comment]
shorten it into a new issue please, do not write essays here
