### ISSUE TITLE
Properly handle weekday repetition with Daily repetition set

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Calendar#1114]
these lines should produce the same result
RRULE:FREQ=DAILY;BYDAY=MO,TU,WE,TH,FR
RRULE:FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR
Currently only the Weekly is handled as thats the way Google works.

**Comment by RuchitaCodingMart** [comment]
Could you please elaborate the issue

**Comment by RuchitaCodingMart** [comment]
> these lines should produce the same result
> RRULE:FREQ=DAILY;BYDAY=MO,TU,WE,TH,FR
> RRULE:FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR
> Currently only the Weekly is handled as thats the way Google works.

Could you please elaborate the issue???

**Comment by tibbi** [comment]
those 2 lines should behave the same when imported from .ics file
