### ISSUE TITLE
Finding the ics file for import (BB)

### ISSUE THREAD

**Issue by setenx** [SimpleMobileTools/Simple-Calendar#112]
Hello,

I have Blackberry (OS10) with an android emulator. In it I am running your calendar application. I am trying to import an ics file (exported from outlook, with ics extension). However I am not able to browse to that file in the file picker. I copied the file to multiple usual folders and no luck. Choosing the "sdcard" folder does nothing. I suppose the links ( ln ) are ignored in your file picker.
Can you please write me where the "internal" storage should point to  or  make the file picker more workable?

Attaching the printscreen from my mobile:
![img_20170215_144920](https://cloud.githubusercontent.com/assets/25795353/22977448/e1768224-f38e-11e6-9e8e-7a818c46f4a5.png)

**Comment by tibbi** [comment]
well Im getting the paths from the device, nothin is hardcoded. The internal storage is the one which usually opens by default if you plug your device to a pc. It usually contains folders like DCIM, Documents, Download, Pictures etc. There are apparently some issues with recognizing SD cards on some devices, using Blackberry could cause even more issues. Hard to say, Ive never tested my apps on BB.

**Comment by nopeppermint** [comment]
I am using your app in BB OS10 directly from the Google Play store and I can import ics files

**Comment by tibbi** [comment]
seems to be a blackberry issue in some cases, not much to do here
