### ISSUE TITLE
Refresh the list of calendars provided by a CalDAV server?

### ISSUE THREAD

**Issue by aurelg** [SimpleMobileTools/Simple-Calendar#1129]
Hi, and thank you for this wonderful calendar!

I connect SimpleCalendar to a CalDAV server (NextCloud) on which I just created a new calendar with another client (NextCloud webUI).

Unfortunately, this newly created calendar does not appear in the list of the synced calendars I can manage, as if this list was not updated by SimpleCalendar.

Is that the expected behavior? If that's the case, and not a bug, then it would be great to consider adding this new feature.

**Comment by tibbi** [comment]
You mean that it doesnt appear after you toggle "CalDAV sync" in the calendar app settings? What app version are you using at all?

**Comment by aurelg** [comment]
> You mean that it doesnt appear after you toggle "CalDAV sync" in the calendar app settings?

Yes.

>What app version are you using at all?

6.9.1 from F-Droid.

I reinstalled SimpleCalendar and deleted its storage/cache. Now I can see all calendars, but it does not seem to be able to sync (there are a lot of events, though, it might just take a long time).

A bit more of context, although possibly irrelevant: after I deleted the storage/cache and reinstalled SC, I haven't been asked for the CalDAV server to connect to. I don't remember if that was also the case when I first installed it. I'm using [CalDAV-Sync](https://play.google.com/store/apps/details?id=org.dmfs.caldav.lib).

**Comment by tibbi** [comment]
the list of available calendars shows up only once you toggle CalDAV sync, not without it. Ill keep an eye on it, not sure what could be wrong there now. But I think it might be an issue on CalDAV-Syncs side. It is a really outdated and poorly rated app, it apparently doesnt work well.

**Comment by aurelg** [comment]
Thanks for your reply. After a while, other calendars now seem to be synchronized :-) The new one is still empty - perhaps it's just queued and others are still synchronizing.

I the meantime, about CalDAV-Sync: I've been using it for a veeeery long time but I'd be happy to use a better one. Perhaps there's one you'd like to recommend?

**Comment by tibbi** [comment]
most people use DAXx5 at https://play.google.com/store/apps/details?id=at.bitfire.davdroid

**Comment by aurelg** [comment]
Thanks a lot, I installed DAVx5 : the initial synchronization has been much faster, and everything seems to be working perfectly! If it's ok for you, you can close the issue! :-)
