### ISSUE TITLE
List view widget flickers

### ISSUE THREAD

**Issue by vdmkenny** [SimpleMobileTools/Simple-Calendar#1131]
I'm using the list view widget on my homescreen.
I often see it flicker between the "loading..." message and my actual calendar.

Running on a Galaxy S9, Observed this in both the standard Samsung homescreen, and the KISS launcher.

**Comment by saunaklogan** [comment]
@tibbi Since I did not find any guidelines for contribution. Can you please help me if I can go ahead and take up bugs and see if I can contribute in a good way

**Comment by tibbi** [comment]
well the casual github way, send pull requests

**Comment by saunaklogan** [comment]
Thanks.

**Comment by tibbi** [comment]
should be better in 6.16.0
