### ISSUE TITLE
Calendar is not visible in standalone configuration

### ISSUE THREAD

**Issue by OpenWarp** [SimpleMobileTools/Simple-Calendar#1144]
My phone is no Gapps, no sync standalone config Android 9. The calendar is not visible to other apps like Todo Agenda widget. The same widget picks up calendars created by Etar Calendar for instance, so this is the problem with Simple Calendar implementation.

I'd like Simple Calendar to pick up other calendars found on the device as well as make it's own calendar visible to Todo Agenda widget.

**Comment by tibbi** [comment]
Just enable "CalDAV sync" in the app settings if you want synchronization.

**Comment by OpenWarp** [comment]
Tried this already. It only allows Simple Calendar to pick up other calendars like those created by Etar Calendar app. Yet, it doesn't make Simple Calendar events visible to Todo Agenda or other apps. My goal is to get rid of other calendars leaving Simple Calendar and Todo Agenda widget.

**Comment by tibbi** [comment]
make sure you store new events into the proper calendar, it is the last field at creating a new event

**Comment by OpenWarp** [comment]
There is no such option in the absence of other calendar apps. When I try to enable "CalDAV sync" in the Simple Calendar a message pops up saying "No calendars to sync found" and the option remains disabled. And hence no field to select a calendar to save new event to.

**Comment by tibbi** [comment]
So make sure you have some "sync adapter" set up properly to see synced calendars. Use an app like DAVx5 or so, it isnt an apps issue.

**Comment by OpenWarp** [comment]
Fair enough. I wonder why Etar calendars are immediately available without the need to set up sync adapters. Same goes for OpenTasks. It's getting harder with every new Android release as Google pushes everything to the cloud. There is a code however (the two mentioned apps) that works fine on a device with no sync accounts and such.

**Comment by tibbi** [comment]
Etar is just the old stock calendar developed by Google with a handful of changes. It is not some app they developed.
