### ISSUE TITLE
Cumbersome updating both start & end times when event needs no end time

### ISSUE THREAD

**Issue by gethob1** [SimpleMobileTools/Simple-Calendar#115]
When modifying an event start time avoid past end times by automatically updating end time to at least start time so I don't have to change the time twice every time I move an event.  The vast majority of my events need no end time so having to update both times is cumbersome.  I've never heard of a case where an event should end in the past so it should just update the end time to at least the start time. Thank you

**Comment by tibbi** [comment]
I was just going to release a new version, so Ive added a quick fix for this one. Should be better indeed.

**Comment by gethob1** [comment]
Sweet, I appreciate it!
