### ISSUE TITLE
Monthly View

### ISSUE THREAD

**Issue by dducted** [SimpleMobileTools/Simple-Calendar#1152]
I change the settings to open only in monthly payment view it it always falls back to daily view. Any idea why that's happening? 

Thanks for your help.

**Comment by tibbi** [comment]
the settings item is only about the Event List widget, not the monthly view. How are you opening the app?

**Comment by dducted** [comment]
Im opening the app via the Pixel "At a glance" click.

See here: [https://i.imgur.com/sN4scD1.png](img)

**Comment by tibbi** [comment]
well that triggers the daily view opening. As I mentioned, the given app setting is related to the Event List widget only, just as mentioned there. If a widget explicitly wants to open the daily view, I dont want to change the behaviour there.
