### ISSUE TITLE
6.9.4 add many "loading" entries in Gadget

### ISSUE THREAD

**Issue by beerisgood** [SimpleMobileTools/Simple-Calendar#1153]
Title.
Even without any calendars activated

**Comment by beerisgood** [comment]
After I remove the gadget and re-add it, the problem disappear.

Strange I never get it before

**Comment by tibbi** [comment]
not sure what you mean. What is Gadget?

**Comment by beerisgood** [comment]
> not sure what you mean. What is Gadget?

Desktop widget

**Comment by tibbi** [comment]
should be improved already
