### ISSUE TITLE
Pull-to-refresh doesn't work in weekly view

### ISSUE THREAD

**Issue by siccovansas** [SimpleMobileTools/Simple-Calendar#1157]
I have pull-to-refresh enabled. It works fine in the yearly, monthly and daily view, but nothing happens when I pull in the weekly view.

I guess this because you can vertical scroll in the weekly view. But I use it all zoomed out so there is no scroll bar left and would love to see pull-to-refresh work in this view :)

**Comment by tibbi** [comment]
yeah, it is because that view can be scrolled. You will have to use the top Menu -> Refresh CalDAV Calendars for now, I dont think the behaviour there will change anytime soon. That menu button triggers the same function as pull-to-refresh.

**Comment by siccovansas** [comment]
Ok, thanks for confirming!
