### ISSUE TITLE
[Feature request]: Abillity to select all search results

### ISSUE THREAD

**Issue by zocker-160** [SimpleMobileTools/Simple-Calendar#1158]
It would be nice, being able to mark all search results (e.g. in order to delete them).
Right now I can only select them manually one by one.

![SimpleCal-issue](https://user-images.githubusercontent.com/36563538/84369287-e87bcd00-abd6-11ea-9dfd-fda78128a46a.png)

**Comment by tibbi** [comment]
not really. As always, there are multiple ways of selecting more contacts. You can either long press 1 item, then long press another one and everything inbetween gets selected, or long press one item and click at the top left counter "1/104" to select them all.

**Comment by zocker-160** [comment]
oh thank you I didn't know that!

yes it works perfectly
