### ISSUE TITLE
6.9.5 possible bug in Weekly View

### ISSUE THREAD

**Issue by Simonp8261** [SimpleMobileTools/Simple-Calendar#1159]
Since 6.9.5 update the **+Add** Event button is missing or obscured and not possible to add or edit events in weekly view. Additionally a right scroll of the weekly display view immediately condenses the screen to displaying 24 hours in one single screen view from whatever the previous user display choice was set to.
Phone Samsung Galaxy A3 (2017) running Android v7.0

**Comment by tibbi** [comment]
the + button has been removed intentionally, but the 24 hours glitch seems to be real :)

**Comment by Simonp8261** [comment]
Thank you for your prompt response can you please advise how to add new or edit existing calendar entries whilst remaining in the "Weekly View" screen which is the only calendar view I use.
  ----- Original Message -----

**Comment by tibbi** [comment]
well just click on some bracket twice to activate the New Event screen with prefilled date/time

**Comment by Simonp8261** [comment]
Apologies for querying this again however I think I may have an additional longer term issue with my setup.

Ever since I have used the Pro and previous free versions when I select any individual grid sector in "Weekly View" I see an instantaneous flash of a blue + symbol within that grid sector but it does not enter the New Event screen hence my use of the + button that has been removed in the latest update.

The issue only appears to exist in the "Weekly View" the "Monthly View" with the grid display enabled, selecting any date takes me to a screen displaying the date at the top & the + button lower right allowing me to access the New Event/Edit screen.

Have reinstalled previously to no avail.


  ----- Original Message -----

**Comment by tibbi** [comment]
once you click on a grid the Plus button should be shown for 5 seconds. Dont you have animations disabled on your device maybe?

**Comment by MegaMarkey** [comment]
I would personally prefer not to have the plus button appearing/disappearing as an animation. "Remove animations" is available without accessing developer options in recent android versions and should therefore not result in features not working properly.

**Comment by tibbi** [comment]
the 24 hour issue has been fixed already, disappearing plus button will be fixed in 6.9.7
