### ISSUE TITLE
Simple Calendar crashes constantly

### ISSUE THREAD

**Issue by gethob1** [SimpleMobileTools/Simple-Calendar#116]
About every 3-5 minutes the app crashes with an error message: "Unfortunately Calendar has stopped."  Then it usually restarts and repeats.  I tried restarting the app and phone to no avail.

**Comment by tibbi** [comment]
I dont see them in the dashboard. Do you have the app from playstore, or f-droid? Which version are you using? Whats your Android version?

**Comment by gethob1** [comment]
What dashboard and what about it?  Using F-Droid version.  I don't use playstore.  It's Android 6.0.1, the same version I've had for awhile.  I only noticed the problem since the last update or two.

Also, when I touch "<- Details" or android back button, the app goes blank
and freezes then minutes later says: "Calendar isn't responding.  Do you
want to close it?"  Sometimes the Android controls don't respond.

**Comment by gethob1** [comment]
Simple Calendar 2.2.0

**Comment by gethob1** [comment]
I would downgrade to see if it would resume working properly but F-Droid warns I might lose my data.

**Comment by tibbi** [comment]
ye downgrading can cause many random issues, as the events are stored in the database which is updated with some versions. 
I meant the google playstore dashboard, which displays all crashes with helpful crashdumps in them. Ill check if I can do anything about it. 
On which view (weekly, monthly...) is it crashing? Theres nothing periodic happening in the background that could crash it, maybe it crashes during swiping?

**Comment by gethob1** [comment]
It crashes in 'day view' just sitting there doing nothing and when I touch '<- Details' to return to monthly view.  Sometimes it will make it back to monthly view, but it can still crash even in monthly view.  Yeah, my Copperhead OS doesn't allow installation of playstore due to security vulnerabilities, so I don't have that dashboard.

**Comment by gethob1** [comment]
I don't find anything running in the background that would interfere.

**Comment by gethob1** [comment]
It's unusable now.  If it's something on my end I can't isolate it.

**Comment by gethob1** [comment]
It will freeze the whole app switching process that occurs when pressing Square.

**Comment by gethob1** [comment]
When the app goes blank I have to ax it and re-launch before I can see the calendar again.  Something definitely happens switching from day view to monthly view.

**Comment by tibbi** [comment]
I guess its related to Copperhead doing something too strict. Theres currently 65k people using the app from playstore, not sure how many from f-droid, but none of them reported any crashes.

**Comment by gethob1** [comment]
I sacrificed my events but uninstalling and reinstalling fixed it.  I don't know how it got corrupted.

**Comment by gethob1** [comment]
Thanks for looking into it.  Please standby and I'll post back if it happens again.

**Comment by tibbi** [comment]
well thats weird. Not sure either, let me know if it happens again. Ill leave it open for a while.

**Comment by gethob1** [comment]
I've had apps become corrupted before, requiring reinstallation.  I never can tell what causes it but lately my phone has been acting strange by randomly powering down all by itself.

**Comment by gethob1** [comment]
I may have malware.  Somebody sent me a link which was full of redirects, popups, and it opened my Fdroid app before I could kill Chrome.  It used some kind of java to crash the browser.  Now I wonder if it managed to install something.  Root is disable by design in Copperhead so not sure how it would succeed.

**Comment by gethob1** [comment]
The only other thing I changed before this problem occured was installing and running another Fdroid app, Auto-away.  I have since uninstalled it because it didn't work and no response to my bug report on git.

**Comment by tibbi** [comment]
i dont think its valid anymore, its an old issue.
