### ISSUE TITLE
Weather Preview

### ISSUE THREAD

**Issue by xerus2000** [SimpleMobileTools/Simple-Calendar#1162]
Samsung Calendar displays little weather icons  below each of the next 7 days, which makes it easy to get an overview over what is possible in the upcoming week.
![image](https://user-images.githubusercontent.com/13354331/84989895-a7d70300-b144-11ea-8d62-fe02c866e85a.png)
Would be great to also have that in this app :)

**Comment by tibbi** [comment]
the app has no internet access so dont expect having that
