### ISSUE TITLE
Calendar only works with interval of hour

### ISSUE THREAD

**Issue by IMDroidude** [SimpleMobileTools/Simple-Calendar#1163]
I want to display day hours with interval of 15 or 30 mins . like 
12:30 am
01:00 am
01:30 am
02:00 am
03:00 am
How can I customize? 
There is not any proper documentation 

I am succeeded in showing date's like above by changing WeekFragmentsHolder.kt

          `var interval = 30
          var iteration = if(interval == 30) 48 else if(interval == 15)  90 else 23

          for (i in 1..iteration) {
            val formattedHours = Formatter.getTime(context!!, hourDateTime.withHourOfDay(0).plusMinutes(interval))
            interval += 30
            (layoutInflater.inflate(R.layout.weekly_view_hour_textview, null, false) as TextView).apply {
                text = formattedHours
                setTextColor(textColor)
                height = itemHeight
                weekHolder!!.week_view_hours_holder.addView(this)
            }
        }`

But when I save event's against these timing . Event's still consider them as interval of 1 hour.  and not adding event's at right location

**Comment by tibbi** [comment]
actually no, it isnt really on the roadmap. And Im not giving support for customizing code.
