### ISSUE TITLE
Multi-week event not shown from second week on, in weekly view

### ISSUE THREAD

**Issue by michaelof** [SimpleMobileTools/Simple-Calendar#1164]
Hi Tibor,

SimpleCalender current 6.9.6, F-Droid.
Event created for the 6 week school summer holiday of our son :)
Only first week is shown in weekly view.
Daily view correct.
Monthly view correct.
Android 6.
calDAV, Nextcloud 19.

Regards,
Michael

**Comment by JohnBenFu** [comment]
Yeah, I can confirm this bug, it is reproducable. Every single event that is long enough not to fit into one weekly-view-screen is only shown on the first weekly-view-screen. It just isn't shown in the following weeks.

Android 10, downloaded from F-Droid

Here a reproduction, the event starts on 2020-06-24 and ends on 2020-07-11, nevertheless it is only shown in the first week, 24.-28. 
![Screenshot_20200627-191941](https://user-images.githubusercontent.com/11487762/85928438-3cf89b00-b8ad-11ea-99d6-098668a2a83e.png)
![Screenshot_20200627-191947](https://user-images.githubusercontent.com/11487762/85928442-484bc680-b8ad-11ea-9a90-b14e89720e9c.png)
![Screenshot_20200627-192001](https://user-images.githubusercontent.com/11487762/85928446-4e41a780-b8ad-11ea-8c3b-dd7e8e0bae49.png)
