### ISSUE TITLE
UI is not (fully?) refreshed after bringing app back to foreground

### ISSUE THREAD

**Issue by sirtoobii** [SimpleMobileTools/Simple-Calendar#1168]
![image](https://user-images.githubusercontent.com/1969330/86211782-6e4fc000-bb66-11ea-8211-1e2ea7e61ace.png)
![image](https://user-images.githubusercontent.com/1969330/86211807-73ad0a80-bb66-11ea-8b8c-57531e66d264.png)
![image](https://user-images.githubusercontent.com/1969330/86211823-7a3b8200-bb66-11ea-93d8-25a527316c04.png)

I just noticed the "current-time-bar" is affected by the same issue

**Edit:** I think I've found the underlying issue: Since it only occurs when the calendar app is sent to background (using home-button, or back-button press) and then opened again I guess its related to some sort of UI-refresh issue. 

@tibbi Is the position of the "current-time-bar" updated whilst the app is open?

Version 6.9.6, F-Droid, Android 9

**Comment by tibbi** [comment]
should be fixed in 6.10.0
