### ISSUE TITLE
Retain ability to have events with no end time?

### ISSUE THREAD

**Issue by gethob1** [SimpleMobileTools/Simple-Calendar#117]
I still find it's extra work to modify both times and dates of my events which only need a start time.  Can you go back to allowing the user to choose if an event should have an end time?

**Comment by tibbi** [comment]
well once you try creating a new event and modify its start date or time, the end date or time is modified together with it. I dont really want to add the checkbox back. What I might do is retain the event duration at editing events. So if you move the start time to 1 hour earlier, the end time will move by 1 hour earlier too.

**Comment by tibbi** [comment]
End time is updating already at changing the Start time, that should be good enough
