### ISSUE TITLE
Contact Birthday not correct when changing timezone

### ISSUE THREAD

**Issue by duesseldorferjung** [SimpleMobileTools/Simple-Calendar#1170]
Good Day, 
when I am switching timezone I noticed that birthdays are shown on the "wrong" day.
I understand why that it is happening but I feel it does not make sense and can be confusing.
The current workaround I applied is to "add contact's birthdays" again when I am in a different timezone.

Best regards

**Comment by Varsha-29** [comment]
Created a PR for this issue : https://github.com/SimpleMobileTools/Simple-Calendar/pull/1181

**Comment by tibbi** [comment]
can it be reproduced by changing the timezone in the app settings too?

**Comment by Varsha-29** [comment]
Yes @tibbi. The birthday was saved in the current time zone. While retrieving it, it was parsed with the current timezone. So when we change the timezone after exporting the birthday, the birthday would be relative to the current timezone. This has been fixed in the PR

**Comment by Varsha-29** [comment]
@tibbi , could you look into the PR and let me know if it is good to be merged?

**Comment by tibbi** [comment]
not working on the app right now, will look at it soon

**Comment by tibbi** [comment]
@duesseldorferjung does it happen on the monthly view only, or everywhere?
