### ISSUE TITLE
Loop reminders behavior seems a little excessive to me

### ISSUE THREAD

**Issue by htsmi** [SimpleMobileTools/Simple-Calendar#1173]
Loop reminders is an essential feature for me so I appreciate that you have implemented it. However, it repeats the notification sound with no delay and I cannot silence it without unlocking my phone! This seems excessive and a little obnoxious when I'm somewhere where I want to silence it quickly. Would you consider (at least as an option) to have a minute or so delay between reminder sounds when they are looped, similar to how this app does it:

https://github.com/quarck/CalendarNotification

Also, it looks like the inability to dismiss the reminder is related to "hide sensitive content" on the lock screen being turned on. I should still be able to silence it though without unlocking.

**Comment by tibbi** [comment]
I cannot really add delay there as Im not playing the audio manually. I can only set the audio to loop, or not to loop.

**Comment by htsmi** [comment]
Ok, how about the inability to silence it when the phone is locked?

**Comment by htsmi** [comment]
Also #1082 I think describes what I was thinking a little better with repeating reminders.

**Comment by tibbi** [comment]
well that might be added someday in the future, we will see. I dont want to add anything related to locking phones and reminders, those things are handled by the system. You can silence a locked phone too.

**Comment by htsmi** [comment]
Thanks for your quick reply. My issue though is it that is not working. At least on my setup, if "hide sensitive content" on lock screen system setting is set, I cannot silence it at all until after I enter my PIN. The lock screen notification can't be swiped away and it continues making sound forever (at least when loop reminders is on). I don't want to unset the "hide sensitive content" because I don't like the security implications.

I could file a new report since this is slightly different from the first request.
