### ISSUE TITLE
All-day events break event creation time

### ISSUE THREAD

**Issue by vn971** [SimpleMobileTools/Simple-Calendar#1176]
Steps to reproduce:
* open "weekly" view with 7 days in it
* click on any empty space
* observe the "+" sign appearing, press on it
![Screenshot_20200721-133920_Calendar2](https://user-images.githubusercontent.com/1547617/88050798-d129eb00-cb57-11ea-8b8c-bfbd306fe6cb.png)

Expected at this point (and worked like that in the past):
* a new event is created with it's timespan identical to that of the "+" sign

Actually in latest release:
* the event is created 1h earlier

![Screenshot_20200721-133927_Calendar2](https://user-images.githubusercontent.com/1547617/88050802-d25b1800-cb57-11ea-9b45-78caa93b220a.png)

**Comment by tibbi** [comment]
I dont think it is related to any update, more like some coincidence with some timezones. What timezone are you in? Do you have some daylight savings active there?

**Comment by vn971** [comment]
@tibbi thanks for a quick response! My timezone is CEST (I live in Amsterdam). Before submitting the issue, I've manually re-selected this timezone checked the time, force-killed Calendar app and re-opened it. Any idea what else can I do to help testing / investigating?

**Comment by tibbi** [comment]
try selecting some different timezones maybe, to see if the time will be set correctly

**Comment by vn971** [comment]
I tried using Moscow/Russia timezone now (which doesn't have daylight saving):
* changed the timezone
* checked Calendar app
* just in case, killed the calendar and restarted it to double-check

Unfortunately, the issue persist. I'm using F-Droid build of the Calendar app now, which is `6.9.7`, Android 8, Operating system/firmware is MicroG

**Comment by vn971** [comment]
By the way, interestingly enough. When I'm in Settings and I click "New events" > "Default start time" > "Other time", calendar will suggest me to use a time that is exactly 1h into the future from now. Should it normally propose the current time in this menu? (Maybe it can help investigating it...)

**Comment by tibbi** [comment]
Well doesnt it say "next full hour"? That is supposed to be used on other views though, not at the weekly view. The selected time should be selected at the weekly one.

**Comment by tibbi** [comment]
The grid on the weekly view seems to be misplaced though, try zooming out with gestures, or scrolling horizontally and vertically to make sure you are really selecting the time range you think. It might be just the labels misplaced.

**Comment by vn971** [comment]
Wow, I think I've found the issue! It was because I have one week where there's a day-long event, and another week where there are no such events. Your message about the grid reminded me of that. Now I need to figure out if the bug is reproducible (and how)

**Comment by vn971** [comment]
When I switch to this "day-long" events week, things get back to normal. When I swipe to another week, it stays normal. So just temporarily visiting that "day-long" week fixed the issue. Have to find a way to trigger it again

**Comment by vn971** [comment]
Yup, there it is again. Steps to repro:
* swipe 1 week in future from now
* create an "all day" event
* swipe back to current week
* escape the calendar app (Android "back" "key")
* re-open the app

**Comment by tibbi** [comment]
alright, will take a look at it. Thanks :)

**Comment by vn971** [comment]
Nice, thanks for the fix!
