### ISSUE TITLE
request: better visibility for days with events

### ISSUE THREAD

**Issue by RAWRR** [SimpleMobileTools/Simple-Calendar#118]
The current underline for days containing events is a bit easy to miss.

The current day designation improved when the circle was added. I wonder if a filled-in circle with negative numbering would work better to signify the current day, and migrate the plain circle to replace the underline for signifying any day containing an event?

Or vice-versa. But being that filled-in circles will be a whole lot noisier visually, it seems best to limit them (if used) by relegating them to only the current day.

**Comment by tibbi** [comment]
will see in the future what can I do

**Comment by RAWRR** [comment]
I still think this template is a good idea!

ping ^_^

**Comment by tibbi** [comment]
version 2.8.0 got a google-calendar like event label displaying at the monthly view
