### ISSUE TITLE
Widget Monthly View

### ISSUE THREAD

**Issue by oxqgit** [SimpleMobileTools/Simple-Calendar#1182]
First of all, thank you for the useful app!
Currently a tap on the montly view widget opens the month view of the month the user tapped on.
It would be really cool, if you could choose what screen is shown after the tap, for example the day view, so you could easily create a new event (same thing like there's already for the list view widget).
Thank you in advance!

**Comment by tibbi** [comment]
well just click on a day and it will open the daily view

**Comment by oxqgit** [comment]
You listed your philosophy as following in the medium article "I just want simple apps that work, don’t make me press 2–3 buttons till I get to taking photos in a camera." Of course I can press on a day on the widget and then again on a widget but that's not the behavior everyone would expect.

**Comment by tibbi** [comment]
I see, guess it broke at some point
