### ISSUE TITLE
Downloads of serveral new versions fail

### ISSUE THREAD

**Issue by hman2** [SimpleMobileTools/Simple-Calendar#1184]
I have version 6.6.5 installed. F-Droid lists 3 newer versions, but for all three the download fails...

Thanks for looking at the repo.
hman

**Comment by tibbi** [comment]
what Android OS version do you have? If you try uninstalling your app version, can you download the new ones?

**Comment by hman2** [comment]
This is Fairphone Open OS 19.11.2 (AOSP 7.1.2), F-Droid is version. F-Droid was version 1.8. I upgraded that to 1.9, now it could download & install 6.15.1 and .2, so maybe it was F-Droid's fault...
