### ISSUE TITLE
No way to synchronize .ics links

### ISSUE THREAD

**Issue by davidmoseler** [SimpleMobileTools/Simple-Calendar#1187]
Most services (such as trello) make available a .ics link which can be used for synchronization. Simple-Calendar only allows you to import a .ics file, such that, in order to synchronize, one would have to constantly put the .ics link in a browser, download the file, and import to Simple-Calendar.

Edit: the trello .ics url actually supports CalDav. I find it weird that Simple-Calendar doesn't.

**Comment by tibbi** [comment]
there is CalDAV, just enable it in the app settings. But since Simple Calendar has no internet access, you will need some third party sync adapter app like DAVx5 or ACalDAV to take care of the synchronization between your device and the servers.

**Comment by jplatte** [comment]
Note to other people wanting to subscribe to ical urls: There's also [ICSx⁵](https://icsx5.bitfire.at/) by the same developers as [DAVx⁵] which does exactly that.
