### ISSUE TITLE
Cannot open app from icon nor widget 

### ISSUE THREAD

**Issue by lzambarda** [SimpleMobileTools/Simple-Calendar#1189]
Hello, as of the most recent version the app seems to crash every time I open it via the widget or the app icon.
Notifications and creatinf new events events work flawlessly.

**Comment by tibbi** [comment]
well, hard to say from this what could be wrong, I dont see related crashes. Do you have CalDAV sync enabled, or you had events stored locally only?

**Comment by lzambarda** [comment]
Thanms for the prompt reply, more than happy to provide more info.
I do have CalDav sync enabled and notifications are indeed working fine.

**Comment by tibbi** [comment]
what device do you have? Maybe I can find some related crashdump

**Comment by lzambarda** [comment]
I have a huawei p smart

**Comment by tibbi** [comment]
I see some Security exceptions thrown by a Huawei with Android 9. Havent you received some system update recently?

**Comment by lzambarda** [comment]
No I don't think so.
It also looks like I can edit events, but when I press on the back arrow, the screen flashes black and then I am brought back to edit event. Mysterious!

**Comment by tibbi** [comment]
Dont you have a rooted device, or modified in a similar way? Maybe enabled some developer options like "Dont keep activities", or some memory cleaner/battery saver enabled?

**Comment by lzambarda** [comment]
I tried uninstalling the app and wiping the cache. Now it seems to be working fine again. Not sure what was the problem but it could indeed be a system update.
Thanks for your help and sorry for the loss of time.
