### ISSUE TITLE
does not pick up new events

### ISSUE THREAD

**Issue by TjrGithub** [SimpleMobileTools/Simple-Calendar#1198]
Hi,
simple-calendar has stopped picking up new events coming from sync.

steps to reproduce:
1. setup up a mailbox.org account
2. setup ox sync and simple calendar and etar on a lineageos 16.0 device
3. sync calendars, make a few events, use them a while
4. create an event on mailbox.org
5. sync with os sync
6. check if the event is there in both etar and simple-calendar

expexted result: event present in both
actual result: event present only in etar

versions: 
lineageos 16.0 beryllium (via microg) as of 31. march 2020
ox sync 1.1.5 via play store
calendar 6.10.0 via fdroid
etar 1.0.23 via fdroid

**Comment by br4nnigan** [comment]
Funny, I found it not working the other way around. Pushing new events won't work, pulling does.

**Comment by tibbi** [comment]
should be solved already
