### ISSUE TITLE
Endless event sound notifcation

### ISSUE THREAD

**Issue by BuZZ-dEE** [SimpleMobileTools/Simple-Calendar#1199]
Some of my events in Simple-Calendar  causes endless sound notifcations. (Really annoying if this happens in meetings.)

Please let me know, what you need for debugging.

**Comment by tibbi** [comment]
havent you enabled "Loop reminders until dismissed" in the app settings?

**Comment by tibbi** [comment]
no, surely not. Maybe you toggled it accidentally during scrolling
