### ISSUE TITLE
Bug: unable to import

### ISSUE THREAD

**Issue by egils-consulting** [SimpleMobileTools/Simple-Calendar#1203]
After pressing import the file list on both internal and sdcard are empty.
![Screenshot_20200925-083804](https://user-images.githubusercontent.com/68460690/94234811-f04b4d00-fef9-11ea-8d82-1ed6ef845cfd.png)
I'm on an old lineage version from 2018 on a Samsung GT-I9300
Do you want a debug log?

**Comment by tibbi** [comment]
try granting the "Storage" permission in your device settings manually. What app version and Android OS version are you using?

**Comment by egils-consulting** [comment]
Restarted the app and now it works 😃
