### ISSUE TITLE
Switching to next day when creating a date after 23:00hrs

### ISSUE THREAD

**Issue by gerhardbeck** [SimpleMobileTools/Simple-Calendar#1205]
When I create a date after 23:00hrs the preset time is 00:00hrs (which is great). Unfortunately it is 00:00hrs on the _same_ day, so basically in the _past_
It would be great if it would be 00:00hrs the next day

**Comment by tibbi** [comment]
what app version are you using? It should work in the Pro version from https://play.google.com/store/apps/details?id=com.simplemobiletools.calendar.pro

**Comment by gerhardbeck** [comment]
I'm using 6.10.0 from f-Droid

**Comment by tibbi** [comment]
tell the steps for reproducing it please. What is the default event duration set in the app settings?

**Comment by gerhardbeck** [comment]
it's not about the event duration, it's about the starting time. The starting time is set to "next full hour". If the next date is after 23:00hrs it will be 00:00hrs but not the next day. The same one (= in the past)

**Comment by tibbi** [comment]
oh ok, I though you mean a different issue
