### ISSUE TITLE
[Feature Request] Change Widget Layout of Calendar Entries

### ISSUE THREAD

**Issue by bigboipete** [SimpleMobileTools/Simple-Calendar#1211]
Currently the widget shows entries for the same day like the following:
```
15:00 Entry 1
15:30 Location 1
16:00 Entry 2
17:00 Location 2
```
Even though there is a color indicator on the left for each event, each event could be far better perceived by laying it out like this:
```
15:00 - 15:30
Entry 1
Location 1
16:00 - 17:00
Entry 2
Location 2
```
It could be made optional to show end time or not. All-day events wouldn't need any time-equivalent prefix. It would be sufficient to just list the Entry and Location on top of the day's event listing.

I know layout topics are also a matter of taste. But to me this change would improve the ability to distinct the events from each other.

**Comment by tibbi** [comment]
some UI changes will be added in 6.16.0, more will come
