### ISSUE TITLE
Nov. 2, 2020 entries appear on Nov. 3, 2020

### ISSUE THREAD

**Issue by jwilliams0** [SimpleMobileTools/Simple-Calendar#1213]
When I try to add a calendar entry to Nov. 2, 2020, the event appears on Nov. 3, 2020.

**Comment by tibbi** [comment]
at what time are you creating it? What app version are you using?

**Comment by jwilliams0** [comment]
Version 6.10.3.  I have tried many different times and durations, and they all appear on Nov. 3, instead of Nov. 2.

Thanks

Oct. 7, 2020 2:54:56 a.m. Tibor Kaputa <notifications@github.com>:

**Comment by tibbi** [comment]
no other date has this issue? How about repeating events?

**Comment by jwilliams0** [comment]
I haven't noticed this with any other date.  Yes, even repeating events schedule for Nov. 2, appear on Nov. 3.  Are you able to display events on Nov 2?

Oct. 7, 2020 9:19:44 a.m. Tibor Kaputa <notifications@github.com>:

**Comment by tibbi** [comment]
ye sure, and not a single person reported any issue like that.

**Comment by shanks1337** [comment]
I have the same Issue and I've screen recorded it. See https://imgur.com/a/l8aadFC

v 6.10.3 Pro from F-Droid. 
German Language Setting
Android 11

Video 1: Note that I clicked on _June 5th_ and when I try to add a new appointment it is _June 6th_. I restarted my phone and app and it seemed persistent. But now it seem to be fine for now.

Video 2: The event goes clearly over 2 days and is not properly displayed on the month view. It didn't work for other dates as well when I created new events. Now seems fine again just like the one in video 1.  I can still reproduce it for this event as you can tell from the video. If I deleted it and re added it, my guess would be that it would probably work properly.

**Comment by tibbi** [comment]
in what views does it happen. Only the monthly?

**Comment by jwilliams0** [comment]
It happens in the week view.  The entry appears on the correct day in the month and day views.

Oct. 25, 2020 5:40:10 p.m. Tibor Kaputa <notifications@github.com>:

**Comment by tibbi** [comment]
I see, do you have 7 days shown at the weekly view, or some other amount? Do you have week number displayed enabled in the app settings?

**Comment by jwilliams0** [comment]
I have 7 days showing, and yes, the week number is displayed.

Thanks,
Joy

Oct. 25, 2020 5:52:51 p.m. Tibor Kaputa <notifications@github.com>:

**Comment by algorithminflux** [comment]
Having this same issue. Running version 6.11.0. Any events I add to November 2 will get shifted by one day to November 3, any events I schedule for November 3 will move to 4, etc etc. Only happens in weekly view. Monthly and day view are fine.

My weekly view is 7 days, starting on Sunday.

**Comment by tibbi** [comment]
ye it will be fixed in the next version 6.11.1 released soon
