### ISSUE TITLE
Translate Holidays

### ISSUE THREAD

**Issue by maverick74** [SimpleMobileTools/Simple-Calendar#1214]
Hi.

I would like to translate Holidays to Portuguese
where/how can I do it?

Thanks

**Comment by tibbi** [comment]
Hey, the file is at https://github.com/SimpleMobileTools/Simple-Calendar/blob/master/app/src/main/assets/portugal.ics . instructions at https://github.com/SimpleMobileTools/General-Discussion#how-can-i-suggest-an-edit-to-a-file . Thanks

**Comment by maverick74** [comment]
Hi.

I've created the pull request. Please check if it is ok :)

thanks

**Comment by tibbi** [comment]
there is none, guess you havent confirmed it properly. Press the green button twice, as written at the instructions.

**Comment by maverick74** [comment]
ok... please re-check.

i was in doubt about this (if i had to press the "create pull request" button two different times or not)

**Comment by maverick74** [comment]
Is it there already?

**Comment by tibbi** [comment]
ye, thanks

**Comment by maverick74** [comment]
Thank You :+1: 
When will it be available for download?

**Comment by tibbi** [comment]
not sure when will I release a new version, should be within a couple weeks. We will see.
