### ISSUE TITLE
[Feature Request] Longer presets for time of reminder

### ISSUE THREAD

**Issue by markuscosinus** [SimpleMobileTools/Simple-Calendar#1218]
Hello,

I just bought this app and am very happy with it! The only thing, that is bothering me is that the options for reminders are only from 1 minute two 30 minutes before the event. I know that you can set a custom time, but this takes a lot longer and since I am regularly setting reminders to one day before the event, this got quite annoying.

Would it be possible to add some longer times like
- 3 hours
- 24 hours
- 2 days
- 1 week

to the default options?

**Comment by markuscosinus** [comment]
Even more amazing would be if we could change the default values in the options, but this would probably take longer to implement and the other solution is probably sufficient for most users.

**Comment by tibbi** [comment]
you can already change the default values by unchecking "Use the last events reminders as the default for new events" in the app settings

**Comment by markuscosinus** [comment]
Thanks a lot for the fast answer. I guess I missed/misunderstood that feature. This is exactly what I need!

Should I delete this request or keep it for future reference?
