### ISSUE TITLE
show Event Type color in monthly_view/simple_event_list 

### ISSUE THREAD

**Issue by nopeppermint** [SimpleMobileTools/Simple-Calendar#122]
It would be nice if you could show the Event Type color as well in the monthly_view/simple_event_list and on the Details view of an Event.

It would be nice if you could select the Event Type to which the imported ics Events are added

**Comment by tibbi** [comment]
ics events have a parameter CATEGORIES, I want to make use of it in the future. To create new event types with those names if needed

**Comment by nopeppermint** [comment]
nice

**Comment by tibbi** [comment]
colored dots for event types have been added
