### ISSUE TITLE
[Bug] Daylight Savings ignored for events in Different Timezones

### ISSUE THREAD

**Issue by ghost** [SimpleMobileTools/Simple-Calendar#1220]
Whenever a a recurring event is schedules using a different time zone, the app does not seem to take into account Daylight Savings. For example, if I am currently in Phoenix, and schedule a recurring event at 8am using Chicago's time zone, I would expect the event to be at 6am Phoenix time in October, and at 7am Phoenix time in November (after daylight savings). What actually happens is that the event shows up as being at 6am Phoenix Time year round.

This type of behavior also occurs when importing a CalDav calendar with events schedulled for different time zones. 

(Tested on F-Droid version 6.10.3)

**Comment by Sharabaddin** [comment]
+ reproduct bug

**Comment by individual-it** [comment]
Also happens to me when using ICS calendars with ICSx5

**Comment by rhysviz** [comment]
I am also seeing this with a google calendar.

**Comment by sparagi** [comment]
This may be the same issue as #1973 (which has the most detailed information) and/or #1680.

**Comment by aog2000a** [comment]
I am lost, was this fixed? I am seeing the same behaviour with the current F-Droid version 6.23.1 Pro.

Also importing an event (sometimes) ignores the timezone (and my event is then 4 or 6 hours wrong!), but sometimes not... it is very confusing/potentially dangerous.
