### ISSUE TITLE
Enabling "Start week on Sunday" now starts the week on Saturday

### ISSUE THREAD

**Issue by algorithminflux** [SimpleMobileTools/Simple-Calendar#1223]
In the new version 6.11.1, when I enable the "Start week on Sunday" setting, my week now starts on Saturday on Week View. 

Not sure what other info to provide that might help other than I'm running Android 9, and that my week view is 7 days. 

Let me know what else might help!

**Comment by tibbi** [comment]
what time zone are you in? Do you use 7 days long weeks? Send a screenshot please

**Comment by tibbi** [comment]
should be fixed in 6.11.2 released soon
