### ISSUE TITLE
SC adds an hour when adding appointment by tipping on week view

### ISSUE THREAD

**Issue by maste9** [SimpleMobileTools/Simple-Calendar#1225]
I guess it does since shift to winter time.

Concrete example:

When i tap on 10 in the week view to add an appointment the form doesn't default 10 to 11 but 11 to 12 now. 

That's for sure just a minor bug but nevertheless increases risk of human failure. And it seems to stay all over the winter like this.

**Comment by tibbi** [comment]
duplicate of #1226
