### ISSUE TITLE
Appointment form adds 1 hour when opened by tapping on week view

### ISSUE THREAD

**Issue by maste9** [SimpleMobileTools/Simple-Calendar#1226]
I guess it does since shift to winter time.

Concrete example:

When i tap on 10 in the week view to add an appointment the form doesn't default 10 to 11 but 11 to 12 now. 

That's for sure just a minor bug but nevertheless increases risk of human failure. And it seems to stay all over the winter like this.

**Comment by tibbi** [comment]
Ye, a new version will start rolling out soon. If you are willing to test it let me know at hello@simplemobiletools.com, it is easier to send via email. Thanks

**Comment by maste9** [comment]
Just to let you know:

The last official update from 2020-11-03 didn't fix this issue for me. Clicking on 14:00 still defaults the new appointment to 15:00.

**Comment by tibbi** [comment]
on what day? What time zone are you in? Try creating an event in september and december too, just to see if it always happens.

**Comment by maste9** [comment]
Fault's on me. After today's update 2020-11-12 everything works well as far as I could test yet.

Thank you very much!
