### ISSUE TITLE
[Bug] Ellipsis icon color isn't affected by settings

### ISSUE THREAD

**Issue by oxqgit** [SimpleMobileTools/Simple-Calendar#1227]
Hey! While changing the primary color in the settings I realized that the color of the ellipsis (three dots) in the upper-right corner sometimes remains in the old color. This stays until you restart the app, so it's no big deal.
Thank you for the app!
Best regards
Oxq

**Comment by tibbi** [comment]
that is the expected behaviour, updating some colors needs a restart indeed. Not much to do with it.
