### ISSUE TITLE
add option to delete all events

### ISSUE THREAD

**Issue by nopeppermint** [SimpleMobileTools/Simple-Calendar#123]
it would be nice to have an option to delete all events or select multiple events on the same time to delete

**Comment by tylerbobella** [comment]
Can you not do this now? You can hold down on a specific event and select multiple events to delete...or perhaps I am misunderstanding the request -- just curious as I would like to contribute to this project!

**Comment by tibbi** [comment]
You mean I should not be implementing it yet? Sure, it doesnt have high priority for now :)

**Comment by tibbi** [comment]
You mean I should not be implementing it yet? Sure, it doesnt have high priority for now :) At least Delete all events wont be added anytime soon. For deleting multiple events you can switch to "Simple event list" and delete by longpressing indeed.

**Comment by tylerbobella** [comment]
No no no! if you already started please do not stop because of me! I was looking at issues so see what would be a good fit for a beginner. Thought this would be a good one but if you recommend any other issues / features please tag me in it and I would be happy to contribute!

**Comment by tibbi** [comment]
I havent started yet, I dont think we need a feature for deleting all events, that can be done by clearing the app cache. You can check the reminders, theres a couple reports related to them. Like https://github.com/SimpleMobileTools/Simple-Calendar/issues/109 and https://github.com/SimpleMobileTools/Simple-Calendar/issues/88
