### ISSUE TITLE
[Feature Request] Add intent, so that Simple-Calendar can be used as default calendar

### ISSUE THREAD

**Issue by xam-ps** [SimpleMobileTools/Simple-Calendar#1233]
**Expected bahaviour:**  
When I click on a widget that opens the calendar (e. g. cLock in my case), I can choose Simple-Calendar after the installation as the default app to launch.

**Actual behaviour:**  
Simple-Calendar is not listed in the list of calendar apps.

After a (really) short research, I think the `CATEGORY_APP_CALENDAR` intend has to be added. As I'm no Android developer and I've basically no clue, don't take this proposal to serious though ;)

**Comment by tibbi** [comment]
what app version and OS version are you using?

**Comment by xam-ps** [comment]
v 6.11.2 Pro
OS: Android 10 (QKQ1.191002)

**Comment by tibbi** [comment]
can you give a link to cLock? Theres obviously a ton of results at searching for it, it is hard to find what you mean.

**Comment by xam-ps** [comment]
It provides basically a clock + weather + calendar widget:
![](https://i0.wp.com/www.smartdroid.de/wp-content/uploads/2013/08/screenshot_2013-03-11-21-02-15.jpg)

When you tap on the little calendar icon (in the screenshot the one with the number 1), the standard calendar app opens up. Here the Simple-Calendar never get's offered. When I click on one of the upcoming calendar entries in the middle, the first time after installation, I get asked, which app should be used and I can select your app. But that's not the case for opening up the calendar in general.

**Comment by tibbi** [comment]
but I mean a link to Google Play or so, so that I can install the app too. There are way too many apps with that name.

**Comment by xam-ps** [comment]
Actually that specific app is not on the Google Play Store. I got it from here: [https://www.apkmirror.com/apk/lineageos/lineageos-clock/](https://www.apkmirror.com/apk/lineageos/lineageos-clock/)

I got used to it during my cyanogenmod/lineageos time and reinstall it ever since on my new phones, as I like the slim design.

**Comment by tibbi** [comment]
I cannot reproduce it, the widget never shows any events. It happens to casual widget on the home screen too, or just at the lock screen? That app hasnt been updated for almost 3 years now, it is heavily outdated. Categories didnt even exist back then.

**Comment by viktoracoric** [comment]
Hey mate, same problem.

You can reproduce it with these apps: https://github.com/viktoracoric/Ultra, https://play.google.com/store/apps/details?id=app.olauncher.ultra

If you check the code, it's the line ```intent.addCategory(Intent.CATEGORY_APP_CALENDAR);``` in MainActivity.java file.

My current workaround is just to install Etar calendar, but I prefer your app to that, and it would be nice to have just one calendar app.

**Comment by tibbi** [comment]
those apps basically arent used by anyone though... That category isnt used in the real world.
