### ISSUE TITLE
It doesn't produce any notification

### ISSUE THREAD

**Issue by lifeBalance** [SimpleMobileTools/Simple-Calendar#1240]
As the title says. 
Great looking app, but not very useful if it doesn't fulfill the main purpose of a calendar: remind events!

**Comment by tibbi** [comment]
Check your device battery and notification settings, if there is nothing blocking the reminders, or killing the app in the background. You might also want to take a look at https://appgenix.uservoice.com/knowledgebase/articles/1827433-why-are-my-reminders-not-working , it has some useful tips.

**Comment by lifeBalance** [comment]
Not sure why you closed the issue. 
Device battery: fine
Notifications for Simple Calendar: allowed
The link you provided: it's dead

**Comment by tibbi** [comment]
well it must be something in your device, not an apps issue. But it is hard to say what exactly, there are too many possible device specific issues. The link works just fine to me, you cannot see the website at all?

**Comment by lifeBalance** [comment]
No worries about the site, I'm in Russia, lots of sites are blocked here. 
Regarding the app, I solved it by uninstalling and installing it again, now reminders work without issue.
It's a really good program, and now that it's working, I would say the perfect calendar. Thanks

**Comment by tibbi** [comment]
Alright thanks, enjoy :)
