### ISSUE TITLE
Notification when Do Not Disturb is enabled

### ISSUE THREAD

**Issue by sanderbaas** [SimpleMobileTools/Simple-Calendar#1243]
I have the same issue as vaseer in issue #939, I receive calendar notifications with sound even when Do Not Disturb is enabled.
I am using Simple Calendar version 6.11.2 and Android version 10.

Do Not Disturb is set to 'Allow Alarms', but not 'Allow Events'. When I receive the notification while DND is on, I long press the notification, but there the option 'Override Do Not Disturb' is disabled. I can only completely disable sound and vibrations, but this would influence notifications when DND is disabled as well.

Also when checking the Exceptions of DND, 'Allow events' is not enabled.

**Comment by tibbi** [comment]
as mentioned in the issue you linked, it is not an apps issue. Check the reminders of the app in your device settings

**Comment by sanderbaas** [comment]
@tibbi: could you elaborate please? Which specific setting is incorrect? I listed all settings that I thought were imporrant for this issue

**Comment by tibbi** [comment]
check the settings in the device itself, not in Simple Calendar. There is a section for Notifications.

**Comment by sanderbaas** [comment]
Yes, I know there is. I am describing these settings in the first post. As far as I can see all the settings are correct, but somehow calendar event notifications are still coming in DND

**Comment by sanderbaas** [comment]
I think I figured out what is going wrong. Simple Calender notifications are silenced when I disable the exception 'Allow alarms'. I was expecting the notifications would be silenced when 'Allow events' is disables. See the screenshot below

![Screenshot_20201128-195050](https://user-images.githubusercontent.com/4152895/100523741-11a70e80-31b3-11eb-8dfa-885deaba3c2e.png)

**Comment by k3a** [comment]
Simple calendar woke me up in the morning during DND with exactly the same settings mentioned here - alarms on during DND but keep calendar event sounds silent. It seems that Simple Calendar is playing event notification sounds as "alarm" type.

**Comment by tibbi** [comment]
ok, Ill change something and see how it works in the next app version
