### ISSUE TITLE
copy and paste/cut and paste events

### ISSUE THREAD

**Issue by nadennmallos** [SimpleMobileTools/Simple-Calendar#1246]
For daily work, I need to copy and paste or cut and paste (when day and time ist changing) events from the calendar quickly. When I had to duplicate the event and to edit date and time, it needs a lot of time. Most of the events are coming more then one time in a week. I had to copy and paste it to the next week on several days and at several times. The old dates I had to store for documentation and for billing process.
My question is: Would it be possible in future to copy and paste events? It would be very helpful for daily work.

**Comment by tibbi** [comment]
that isnt really on the roadmap, just use duplicate event.
