### ISSUE TITLE
sync with local ics file

### ISSUE THREAD

**Issue by br4nnigan** [SimpleMobileTools/Simple-Calendar#1247]
While it's possible to import an ICS file, the connection ends at that point. 

Thunderbird's calender for example can do just that, keeping the calendar synced with a locally saved ics file.

And using something like SyncThing, you would be able to sync a calendar between devices without using a (most often payed) CalDav service in an utterly simple, user friendly manner.

Honestly when I first tried setting up a synced calendar I naturally went with this approach and was SHOCKED when I learned this wasn't widely used (yea other apps don't have this feature either).

**Comment by tibbi** [comment]
right, I can keep it here, but dont expect having it anytime soon

**Comment by br4nnigan** [comment]
I guess this ticket is basically a duplicate https://github.com/SimpleMobileTools/Simple-Calendar/issues/1209
