### ISSUE TITLE
Event color support

### ISSUE THREAD

**Issue by nunesgh** [SimpleMobileTools/Simple-Calendar#1251]
Hi @tibbi!

First of all, thank you for your Tools!

I have found some previous issues here regarding categories and colors, but I was not sure whether they were referring to the feature I am missing or not. So I decided to open this issue.

I currently use DAVx5 to sync with my cloud. One of its features that I really like is what they call 'Event color support', as you can see [here](https://www.davx5.com/manual/settings.html#caldav). This feature allows me to sync not only a calendar's color, but the color of a single event within that calendar.

I currently know of at least one app able to use this feature, [Etar](https://github.com/Etar-Group/Etar-Calendar).

Is this after all a duplicated issue or a new one? And would it be possible to add this feature to Simple Calendar?

Thank you!

**Comment by tibbi** [comment]
ye it is already reported ages ago, duplicate of #360
