### ISSUE TITLE
Are files meant to be in Files drectory

### ISSUE THREAD

**Issue by brianWreaves** [SimpleMobileTools/Simple-Calendar#1252]
v6.11.2 Pro on Android 9+
 
In the Android > data > com.simplemobiletools.calendar.pro > files folder (as well for Contacts), are there meant to be any files as mine is empty?
 
I ask as I'm troubleshooting why the .ics export files are coming up as "cannot be parsed" when trying to import them in Nextcloud.  Or is this not meant to be possible?  I'm just looking to see if there are other .ics files, or anything else, I can try to restore a deleted calendar on Nextcloud.

**Comment by tibbi** [comment]
well you set the destination of the file before exporting, not sure what place you select. It shouldnt be in Android/Data by default
