### ISSUE TITLE
[Bug] Calendar force closes

### ISSUE THREAD

**Issue by dhammel** [SimpleMobileTools/Simple-Calendar#1261]
Hello,

Per updating simple calendar pro via F-Droid to version 6.11.4.189 from version 6.11.3.188 it just force closes, doesnt even launch.  Tried rebooting, clearing cache and data. Rolling back to prior version works.

My device: Pixel 4, Android 11 Janurary 2021 update. Stock AOSP.

Would have attached a log, if I knew how to generate one for this app, without being able to launch it.

**Comment by tibbi** [comment]
I dont really see any related crashes in the dashboard, not sure what is happening there. Try restarting your device.

**Comment by dhammel** [comment]
As mentioned, I've already tried the basic troubleshooting steps, such as rebooting. The only fix, is to downgrade to previous version

**Comment by dhammel** [comment]
Some reason it started working after reverting back two versions via fdroid, rebooting between each downgrade and then jumping back to the newest version. Might have been something device specific, its very odd how that seemed to fix it (I was just messing around testing other things, this is all I re-call doing), but at first it didn't appear so. As I managed to get it fixed, I will close this issue.
