### ISSUE TITLE
Simple event list menu doesn't show all event's

### ISSUE THREAD

**Issue by pokegamer5547** [SimpleMobileTools/Simple-Calendar#1263]
When I'm in simple event list, I selected it to only show birthday's event's list in filter. But the app doesn't show all birthday's event's in list. ![IMG_20210115_150723.jpg](https://user-images.githubusercontent.com/65234485/104708324-91794000-5743-11eb-861c-0b566e3ca05c.jpg)
Tapping on empty space for atleast 3-7 times revealed my another event.i don't know this is a bug or feature but it can't be good for users who want complete list. ![IMG_20210115_150758.jpg](https://user-images.githubusercontent.com/65234485/104708409-aeae0e80-5743-11eb-844f-279a4820e2c9.jpg)

**Comment by tibbi** [comment]
what app version is that?

**Comment by pokegamer5547** [comment]
> what app version is that?

6.11.4

**Comment by tibbi** [comment]
guess it was limited for the given year timespan, should be better now.
