### ISSUE TITLE
Support ProtonCalendar?

### ISSUE THREAD

**Issue by vdmkenny** [SimpleMobileTools/Simple-Calendar#1268]
ProtonCalendar (from the people from protonmail) is now in early access on android.
https://protonmail.com/blog/calendar-android-beta/

As they don't offer a widget, would it be possible to support their calendar in this widget?
Currently it's not detected in "calendars to sync".

**Comment by tibbi** [comment]
how does it work, not with sharing via CalDAV?

**Comment by vdmkenny** [comment]
It seems like they haven't opensourced the calendar app yet. Does simple-calendar detect all present calDAV calendars via some android API?

**Comment by tibbi** [comment]
ye, CalDAV is the way calendars share events inbetween them

**Comment by tibbi** [comment]
Im closing it as there is nothing special about ProtonCalendar. If they will use CalDAV protocol as everyone does, it will be supported. If they add some extra encryption, I wont be able to access them.
