### ISSUE TITLE
Basque short and long description not appearing on F-Droid

### ISSUE THREAD

**Issue by avtkal** [SimpleMobileTools/Simple-Calendar#1270]
Some time ago I translated Simple Calendar's short and long description but does not appear on F-Droid. It is still in English.

![photo_2021-01-21_20-37-43](https://user-images.githubusercontent.com/63205014/105403069-897c3d00-5c28-11eb-8282-25dd92a216ac.jpg)

**Comment by tibbi** [comment]
it should be updated when the next app version gets released, thanks

**Comment by avtkal** [comment]
Thank you!
