### ISSUE TITLE
Repeating Events not working as intended

### ISSUE THREAD

**Issue by marissa999** [SimpleMobileTools/Simple-Calendar#1271]
Today, I made a Nextcloud appointment, which repeats every second Friday of the month. It appears properly in the nextcloud web app and in Evolution.

But Simple Calendar shows this event as every third Thursday (which btw is today).

Expected behaviour is that simple calendar shows the repeating event on the correct day. 

I assume Simple Calendar checks for the creation date for repeating events? 

Edit: The version I am using is v 6.11.4 Pro

Might be related to:
https://github.com/SimpleMobileTools/Simple-Calendar/issues/963
https://github.com/SimpleMobileTools/Simple-Calendar/issues/1201

**Comment by thealoneeditor** [comment]
how to tell the enterauge I am working on rebuilding all these apps from
source for being private production  candidates?

**Comment by tibbi** [comment]
what app version are you using?

**Comment by marissa999** [comment]
Oh yeah, I should have added that.
According to the About Page I am using v 6.11.4 Pro
