### ISSUE TITLE
[Feature request] Customizable widget size or additional widget sizes

### ISSUE THREAD

**Issue by TheRealCrusher** [SimpleMobileTools/Simple-Calendar#1274]
Screen real estate is precious. The 4x4 widgets use up too much of that precious commodity, more than half of it in my case. If the calendar widget uses up too much space, its usefulness declines, compared to just opening the calendar itself.

Customizable widget sizes, or at least some additional sizes, like 4 (wide) x 3 (high) and 3x3 would go a long way to keep some space free. 

For my specific use case, a long list of upcoming dates is not necessary. The current and the next one or two upcoming eventy would totally suffice. I suppose that this is true for a lot of people, if not for most.

Even smaller fonts, as suggested in #897 would also be adding to smaller widgets' usefulness. If it were possible to change the level of detail for event data displayed, they could be even more useful.

**Comment by tibbi** [comment]
you can resize widgets by long pressing them, then dragging the sides

**Comment by TheRealCrusher** [comment]
Thanks for your reply to my request that was made out of ignorance. - I took the liberty to donate a little bit, so that you might find the time to answer not just my stupid questions. ;)

**Comment by tibbi** [comment]
thanks, enjoy :)
