### ISSUE TITLE
Invalid ICS-file when exporting

### ISSUE THREAD

**Issue by crazyminecuber** [SimpleMobileTools/Simple-Calendar#1276]
I wanted to export my calendar from my phone to an ics-file so that I could import it into my nextcloud server but nextcloud was unable to parse it. So I uploaded my ics-file to [https://icalendar.org/validator.html](https://icalendar.org/validator.html) and it reported the following errors

    Problem! Found 1 warning
    Warnings

    Line length should not be longer than 75 characters near line # 79Reference: RFC 5545 3.1. Content Lines

    Problem! Found 18 errors
    Errors

    Lines not delimited by CRLF sequence near line # 1Reference: RFC 5545 3.1. Content Lines
    Missing DTSTAMP property near line # 4Reference: RFC 5545 3.6.1. Event Component
    Missing DTSTAMP property near line # 14Reference: RFC 5545 3.6.1. Event Component
    Missing DESCRIPTION property in VALARM near line # 24Reference: RFC 5545 3.6.6. Alarm Component
    Missing DTSTAMP property near line # 29Reference: RFC 5545 3.6.1. Event Component
    Missing DESCRIPTION property in VALARM near line # 39Reference: RFC 5545 3.6.6. Alarm Component
    Missing DTSTAMP property near line # 44Reference: RFC 5545 3.6.1. Event Component
    Missing DTSTAMP property near line # 56Reference: RFC 5545 3.6.1. Event Component
    Missing DTSTAMP property near line # 67Reference: RFC 5545 3.6.1. Event Component
    Missing DTSTAMP property near line # 78Reference: RFC 5545 3.6.1. Event Component
    Missing DTSTAMP property near line # 89Reference: RFC 5545 3.6.1. Event Component
    Missing DTSTAMP property near line # 100Reference: RFC 5545 3.6.1. Event Component
    Missing DESCRIPTION property in VALARM near line # 110Reference: RFC 5545 3.6.6. Alarm Component
    Missing DTSTAMP property near line # 115Reference: RFC 5545 3.6.1. Event Component
    Missing DTSTAMP property near line # 126Reference: RFC 5545 3.6.1. Event Component
    Missing DTSTAMP property near line # 137Reference: RFC 5545 3.6.1. Event Component
    Missing DTSTAMP property near line # 148Reference: RFC 5545 3.6.1. Event Component
    Missing DESCRIPTION property in VALARM near line # 158Reference: RFC 5545 3.6.6. Alarm Component

That leads me to believe that there are some problems in the exporting function. Cound someone verify that I am right or tell me what I have done wrong?

**Comment by tibbi** [comment]
lines are properly split, but the validator still complains about missing LF characters. Let me know if you still cannot import it.

**Comment by crazyminecuber** [comment]
Tried to export a calendar with a single event named "Gurka", and now nextcloud swallows the ics-file without complaining, but it removes the event in the process. Output file from simple calendar

> BEGIN:VCALENDAR
> PRODID:-//Simple Mobile Tools//NONSGML Event Calendar//EN
> VERSION:2.0
> BEGIN:VEVENT
> SUMMARY:Gurka
> UID:1fb40c25c9304696bc72f84553512eef1613749997654
> CATEGORY_COLOR:-689152
> CATEGORIES:Regular event
> LAST-MODIFIED:20210219T155317Z
> DTSTART:20210222T130000Z
> DTEND:20210222T140000Z
> STATUS:CONFIRMED
> BEGIN:VALARM
> ACTION:DISPLAY
> TRIGGER:-P0DT0H10M0S
> END:VALARM
> END:VEVENT
> END:VCALENDAR


Resulting file after importing to nextcloud and then exporting from there:


> BEGIN:VCALENDAR
> VERSION:2.0
> CALSCALE:GREGORIAN
> PRODID:-//SabreDAV//SabreDAV//EN
> X-WR-CALNAME:Imported Events_2021_02_19_16_53_51.ics
> X-APPLE-CALENDAR-COLOR:#5B64B3
> REFRESH-INTERVAL;VALUE=DURATION:PT4H
> X-PUBLISHED-TTL:PT4H
> END:VCALENDAR

Example result of exporting from nexcloud with similar event added manually. 

> BEGIN:VCALENDAR
> VERSION:2.0
> CALSCALE:GREGORIAN
> PRODID:-//SabreDAV//SabreDAV//EN
> X-WR-CALNAME:Imported Events_2021_02_19_16_53_51.ics
> X-APPLE-CALENDAR-COLOR:#5B64B3
> REFRESH-INTERVAL;VALUE=DURATION:PT4H
> X-PUBLISHED-TTL:PT4H
> BEGIN:VTIMEZONE
> TZID:Europe/Stockholm
> BEGIN:DAYLIGHT
> TZOFFSETFROM:+0100
> TZOFFSETTO:+0200
> TZNAME:CEST
> DTSTART:19700329T020000
> RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
> END:DAYLIGHT
> BEGIN:STANDARD
> TZOFFSETFROM:+0200
> TZOFFSETTO:+0100
> TZNAME:CET
> DTSTART:19701025T030000
> RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
> END:STANDARD
> END:VTIMEZONE
> BEGIN:VEVENT
> CREATED:20210219T161118Z
> DTSTAMP:20210219T161132Z
> LAST-MODIFIED:20210219T161132Z
> SEQUENCE:3
> UID:40251881-86a4-4d74-9123-1cf534faa45b
> DTSTART;TZID=Europe/Stockholm:20210223T100000
> DTEND;TZID=Europe/Stockholm:20210223T110000
> SUMMARY:Gurka
> END:VEVENT
> END:VCALENDAR

So I am still not able to import correctly but I do not know if it it due to a bug in your application or nextcloud. It definitely appears like Nextcloud is removing some information that was in the file when it was exported from simple calendar.

**Comment by crazyminecuber** [comment]
I found an error message in nextcloud that could be useful!
> Sabre\DAV\Exception\UnsupportedMediaType: This resource only supports valid iCalendar 2.0 data. Parse error: Invalid Mimedir file. Line starting at 8 did not follow iCalendar/vCard conventions

**Comment by tibbi** [comment]
guess they only accept their own .ics files, there is nothing wrong with the one from Simple Calendar. I dont plan adding tons of boilerplate there.
