### ISSUE TITLE
new Event created on wrong day

### ISSUE THREAD

**Issue by Baaaaaaatz** [SimpleMobileTools/Simple-Calendar#1282]
When Default Time for new Events is set to "next full hour" and an event is created between 23:00 and midnight, the new event will be jumping to one day after the day initially selected.

Reproduce: 
1 Set default event time to next full
2 wait till 11pm
3 create event on monday
4 select whatever time you want
5 new event will be created in Tuesday

Took me a while to figure it out, since I often schedule my next days at the end of the day and stumbled across this a couple of times without getting to the core of it.

Workaround: Double check the date, after selecting a day in the calendar for the new schedule, or set a custom default time (didnt check what happens if custom default is Midnight). 

I thought its still worth mentioning, since Default time "next full hour" is the installation default.

**Comment by tibbi** [comment]
well it says "Next full hour", so it is the expected behaviour

**Comment by Baaaaaaatz** [comment]
Thanks for the quick reply!
Just a side note: Lets say its Saturday 11pm now, and i schedule for a Wednesday event and select "new event" on Wednesday in the calendar it will open Thursday for new event. 
My initial selection was Wednesday, so i would expect the new event to be created Wednesday Midnight, not Thursday. 
Since its a minor with easy workaround, and maybe only my expectation its ok to close i guess.
