### ISSUE TITLE
[Feature request] List of snoozed events (sorted by alarm time)

### ISSUE THREAD

**Issue by r0polach** [SimpleMobileTools/Simple-Calendar#1292]
Hi, this an idea of one useful feature.

When I have a lot of events and some of them have set an alarm to different
time intervals (one to 10 minutes, another to 1 hour, etc.) and I have some of
them snoozed also for different times, I would easily lose track of them in my
mind. When I open the app, I can check only event start and end times, but
not the times the events alarms are currently snoozed to. So I have no option
to check when the next alarm will start.

It would be nice to have a list with alarm times of (both snoozed and not yet
alarmed) events, or at least those snoozed ones. May be this list could be
merged to the existing *simple event list* by adding a sort switch: one sort
option would be by event start time, another by next event alarm (snoozed
or not). But probably separate "list of alarms" or "snoozed list" sorted by
next alarm time always would be more clear for users.

**Comment by tibbi** [comment]
that sounds really confusing, dont really expect having something like that

**Comment by r0polach** [comment]
What is confusing? This list is for example the main screen of the app
https://play.google.com/store/apps/details?id=com.ryosoftware.calendareventsnotifier
(for google calendar).
It can edit alarm time for events that are already snoozed and gives overall list of
when alarms will be triggered. Very useful.

**Comment by r0polach** [comment]
Is there any possibility to view time of an already snoozed alarm in Simple Calendar?
If not, why there is such important information impossible to retrieve?

**Comment by tibbi** [comment]
not really, you cannot do it. Noone has requested anything like that so far and the app you linked basically isnt used by anyone.
