### ISSUE TITLE
Crash when the apo is being launched

### ISSUE THREAD

**Issue by buongiorgio** [SimpleMobileTools/Simple-Calendar#1294]
On android 10, the la test aversion (6.13) downloaded from f-droid crashes at start up; here's the log.

https://del.dog/acutaypelu

**Comment by tibbi** [comment]
dont you have a rooted device, or one modified in a heavy way? Like disabling the system calendar functionality etc?

**Comment by buongiorgio** [comment]
I have a custom ROM (crdroid), not rooted, and as a matter of fact I deactivated the default calendar as I use simple calendar as my main calendar app; I restored the original calendar and now everything works as expected.
