### ISSUE TITLE
document/ explain .ics file import and event types

### ISSUE THREAD

**Issue by linuxcaffe** [SimpleMobileTools/Simple-Calendar#130]
I'm a taskwarrior.org user, and I'd like to start exporting tasks with due-dates and scheduled-dates to .ics, for import into Simple-Calendar, but I have a few questions. 

When importing from .ical, are the imported events stored natively in sql-lite db, or somesuch?

Would it be possible for Simple-Calendar to access .ics files, perhaps within a given folder, without "importing" them? (ie. just re-read text files)

When importing from .ics, are those events added to the current data, or does the import replace the current events?

Could events being imported from .ics have their event-type pre-defined (as in, is event type maintained as iCalendar field?) ?

thanks again for the excellent software!

**Comment by tibbi** [comment]
Hey, the events are stored in a native sqlite db. There is a menu button for exporting the file as "events.db", which might change soon. You cannot import that file, just read it through some viewer like http://inloop.github.io/sqlite-viewer/ .

**Comment by tibbi** [comment]
Hey, the events are stored in a native sqlite db. There is a menu button for exporting the file as "events.db", which might change soon. You cannot import that file, just read it through some viewer like http://inloop.github.io/sqlite-viewer/ .

.ics files are basically simple text files, you can open them with any text editor, even some notepad.

Events are added to the current data, they will not delete any current events.

As you press the "Import events from an .ics file" menu button, then select the ics file, another dialog appears, where you can select the default event type. If the event in the .ics file contains a CATEGORIES field, that is set as the event type. If not, the default (set in the dialog) is used.

Exporting events as ics is on the roadmap too, just havent got to it yet.

**Comment by tibbi** [comment]
if you still have questions open a new ticket please
