### ISSUE TITLE
App crashes when trying to export .ics file in Android 11

### ISSUE THREAD

**Issue by BlizzardWizzard** [SimpleMobileTools/Simple-Calendar#1309]
I'm trying to export my calendar to backup my files, but whenever I press 'ok' on the export dialogue, the app crashes.

Phone: Samsung Galaxy S20+ (SM-G985F/DS)
Android Version: 11

[Android changed the way apps can access storage in Version 11](https://developer.android.com/about/versions/11/privacy/storage), so I'm guessing that's where the issue lies?

I'm using your [Simple File Manager](https://github.com/SimpleMobileTools/Simple-File-Manager), if that helps.

**Comment by tibbi** [comment]
storage access shouldnt be the issue, the app uses the new way already. If you select some events by long pressing on some list view and use Share at the top Menu, does it properly generate the .ics file that you can share?

**Comment by BlizzardWizzard** [comment]
It does generate the .ics file correctly when using the share function.

**Comment by tibbi** [comment]
what app version are you using at all?

**Comment by BlizzardWizzard** [comment]
v 6.13.1 Pro

**Comment by tibbi** [comment]
havent you disabled some system functions responsible for handling documents, mediastore or so?

**Comment by BlizzardWizzard** [comment]
I don't think I disabled anything like that... How do I check?

**Comment by BlizzardWizzard** [comment]
You were right, it was broken - I accidentially uninstalled that when debloating. Sorry for wasting your time.
