### ISSUE TITLE
[Feature Request] Add option to update "this and future occurrences" in repeating events

### ISSUE THREAD

**Issue by Yairks** [SimpleMobileTools/Simple-Calendar#1310]
Like the title says. I'm a heavy user of repeating events and I frequently change them, so this is an important addition for me.

I've also implemented the feature already (it's a pretty simple addition). I'm raising this as an issue first before submitting a pull request because I'm not sure what the standard protocol is for contributing here.

**Comment by tibbi** [comment]
will be added in 6.13.3
