### ISSUE TITLE
new events are added for the next day 

### ISSUE THREAD

**Issue by NotSoImportant** [SimpleMobileTools/Simple-Calendar#1314]
Already happens for a longer time (multiple versions) now:
When having a day open, clicking the plus button actually creates an event for the next day.

![image_2021-03-18_23-53-24](https://user-images.githubusercontent.com/35758921/111707900-32b86b80-8845-11eb-8688-68e364acf015.jpg)

![image_2021-03-18_23-45-02](https://user-images.githubusercontent.com/35758921/111707727-e10fe100-8844-11eb-92d9-7eb865b60ff6.jpg)

Version: 6.13.0 from F-Droid
Android: LineageOS, Android Version 7.x.x
Locale: German, (happens with and without 24 hour date format) 
Sync: CalDav sync by DAV5

**Comment by tibbi** [comment]
so the time zone is in germany too? Does it matter at what time of the day are you creating it? Maybe just before midnight?

**Comment by NotSoImportant** [comment]
Yes (although I thought I saw it during the day as well, but my memory might by wrong).
At the current time (09:35) it is working fine.
This behavior is probably due to the "default start time" set to "next full hour" (or similar translation) - _by the was: "use app in english" seems not to work_

This behavior is confusing. While having the current day selected, this might be valid, but in all other cases it is not what you expect.
Maybe #1224 has actually the same issue.

Workflow:
1. click day
1.  click "+"
1. enter name
1. change time
1. uups wrong date

Selecting a fix default start time is a work around.

The proper fix for me would be to handle the last hour differently - my suggestion would be using 0:00 of that same day. Optionally the current behaviour could be kept for the current day, however different user might expect different things here.
