### ISSUE TITLE
can only create events stored in phone, not in DAVx

### ISSUE THREAD

**Issue by pcastela** [SimpleMobileTools/Simple-Calendar#1315]
**System Info**
v 6.13.1 Pro downloaded from F-Droid

**Steps to reproduce**
1. create new event
2. chose type of event > only local options are displayed ![Screenshot_20210319_143306_com simplemobiletools calendar pro](https://user-images.githubusercontent.com/77405857/111789271-3c7fb480-88c1-11eb-8932-4e6612b6c600.jpg)

**Workaround**
1. chose an event from a DAVx calendar
2. duplicate
3. you are not able to see synced calendars (until you chose a to "Store locally only")
![Screenshot_20210319_143853_com simplemobiletools calendar pro_1_1](https://user-images.githubusercontent.com/77405857/111789267-3b4e8780-88c1-11eb-87ce-7a23dc8aa85c.jpg)

**Comment by tibbi** [comment]
do you have write access to those calendars?

**Comment by pcastela** [comment]
Yes, read write permissions on all of them. Could you reproduce it?

**Comment by tibbi** [comment]
actually it is because you have "Store locally only" selected, so only the local types show up. Try clicking at the bottom 2 lines to see what I mean.

**Comment by pcastela** [comment]
Sorry, I guess it was not a bug. My apologies 🙏
