### ISSUE TITLE
Calendars not showing with DAVx5 & ICSx5

### ISSUE THREAD

**Issue by hubortje** [SimpleMobileTools/Simple-Calendar#1324]
Hey there,

I am using DAVx5 & ICSx5 to implement my calendar from Nextcloud, and an .ics-calendar from my university.
I am currently only seeing the .ics-calendar, my Nextcloud calendar is not shown, despite being enabled in DAVx5. The whole thing works when using a different calendar app like Etar, so this should not be an issue created by DAVx5/ICSx5 but by their respective implementation into Simple Calendar.

When only using DAVx5 to implement my Nextcloud calendar as CalDAV, without using ICSx5 to implement the .ics-calendar, the Nextcloud calendar is shown with no issues. As soon as I import the .ics-calendar via ICSx5 into DAVx5, there is only the .ics-calendar shown in Simple Calendar.

This also leads to the problem, that I can only save entries locally.

In Etar, both calendars are shown without a problem.
 
I'm using GrapheneOS 2021.03.30.02 on a Pixel 3a, if it helps.

Cheers,
hubortje

**Comment by tibbi** [comment]
Do you see any calendars if you enable "CalDAV sync" in Simple Calendars app settings?

**Comment by hubortje** [comment]
This was an easy fix, thank you.

The nextcloud-calendar was enabled previous to importing the .ics-calendar, did not disable it myself – is it possible, that newly imported calendars deactivate older ones, or did I simply mess up?
