### ISSUE TITLE
The United Kingdom holidays pack is missing many important dates.

### ISSUE THREAD

**Issue by Trakoro** [SimpleMobileTools/Simple-Calendar#1329]
When you add the UK holidays pack (_Add holidays -> United Kingdom_) , the following dates are missing:

- St. George's Day
- St David's Day
- Mothering Sunday
- Father's Day
- Hallowe'en
- Guy Fawkes Night
- Remembrance Day
- Burns Night
- Start and End of British Summer Time

**Comment by tibbi** [comment]
what app version are you using?

**Comment by Trakoro** [comment]
> what app version are you using?

I am using version 5.2.6 of the free version on the Google Play Store.

**Comment by tibbi** [comment]
try the Pro one from https://play.google.com/store/apps/details?id=com.simplemobiletools.calendar.pro , if it works better

**Comment by Trakoro** [comment]
Is the Pro version also open source?

**Comment by tibbi** [comment]
sure
