### ISSUE TITLE
exportation of raw database

### ISSUE THREAD

**Issue by Demonkunga** [SimpleMobileTools/Simple-Calendar#133]
Not really an issue, but not sure where else to ask about this, I'm wondering what the export raw database option is used for.
I was hoping it'd be able to save a backup, so to speak, of my events and calendar settings, then re import them back in, say after a factory wipe.
But there's only an option to import an ics file or export a raw db file.
In the meantime, I've just been backing up the entire application folder via root. I'm just a little surprised we'd have the option to import and export two different formats.

Edit: read your comment at https://github.com/SimpleMobileTools/Simple-Calendar/issues/130 ~ nice to see exporting ics is coming!

**Comment by tibbi** [comment]
Hey yea, its weird. The export raw DB has been added just as a quick solution for people who crutially needed some kind of a backup so nothins gets lost. You can view the exported DB at http://inloop.github.io/sqlite-viewer/ , cannot import it anywhere. Importing the db wont be possible even in the future, as that could easily create conflicts when some columns change. 
However a proper solution, exporting as .ics is on the roadmap, that should be added someday. Optional google sync is on the roadmap too, but that might take more time.
