### ISSUE TITLE
[Feature Request] widget that displays only today

### ISSUE THREAD

**Issue by kevincianfarini** [SimpleMobileTools/Simple-Calendar#1335]
I'd love for the option to restrict my home screen widget to display events for only today! I tend to take life one day at a time :).

**Comment by Aga-C** [comment]
@tibbi Should it be a separate widget similar to daily view in the app, or should it be just an option while creating the event list widget?

**Comment by tibbi** [comment]
lets use the existing event list one with a config at the widget config screen, like "Show events happening" and options like "Today only", "within the next xxx days/months/years", make that a free selection like at custom reminders. Add an edittext and add days/weeks/months. That way it closes https://github.com/SimpleMobileTools/Simple-Calendar/issues/1051 too
