### ISSUE TITLE
App kept crashing

### ISSUE THREAD

**Issue by gthbusrr** [SimpleMobileTools/Simple-Calendar#1336]
App kept crashing for no reason, even when in background...
Importing ics files also crashes...

This phenomenon existed for several versions already.

Version: 6.13.3
Android 11
Syncing over DAVx5

Will there be a way to extract crash logs? Thanks

**Comment by siccovansas** [comment]
I have the same problem using version 6.13.3 on Android 11. The app crashes after a 3-20 seconds, even when I do nothing. I had no issues with previous versions.

**Comment by tibbi** [comment]
I dont really see any related crashes, is it related to CalDAV? Try disabling it
