### ISSUE TITLE
Please add: Reminder value "15 Minutes"

### ISSUE THREAD

**Issue by pm-pm** [SimpleMobileTools/Simple-Calendar#1337]
Could you please add the predifined reminder value "15 Minutes"? :-)
It is a typical value to be reminded in front of a meeting.

Now you have:
None
1 Minute
5 Minutes
10 Minutes
(ad here)
30 Minutes
1 Hour
User defined

Thank you very much

**Comment by tibbi** [comment]
you can already set default reminders in the app settings, just disable the "Use the last events reminders as the default for new events"
