### ISSUE TITLE
Stop reminder at midnight for events in the future

### ISSUE THREAD

**Issue by gcoimbra** [SimpleMobileTools/Simple-Calendar#1338]
First of all. Thanks a lot for the app. It's simply awesome.

Description:
 An reminder is heard while I'm already almost sleeping for an event that is going to happen a week after.

Steps to replicate:
 1) Add any reminder that is multiple of a day for an event. Example: 1 day before
 2) In that 1 day before, exactly at midnight an reminder will be sound.

Expected behaviour:
 Don't sound an alarm at midnight, but some configurable time.  Or at least in the morning?

**Comment by tibbi** [comment]
you can already set specific time of all-day event reminders in the Pro app version

**Comment by gcoimbra** [comment]
@tibbi Yes. You can if the reminder is going to be at that day. But, as I said in the issue description, the problem is when you want to be reminded N days before, as an example. If you choose that, the calendar will remind you at midnight 7 days before. At least with my case.

**Comment by tibbi** [comment]
well just select reminding like 30 hours before then, do not select x days
