### ISSUE TITLE
[FR] Pressing Back on a New Event, if no data entered, should not ask to save or discard

### ISSUE THREAD

**Issue by JohnVeness** [SimpleMobileTools/Simple-Calendar#1340]
If I press the "+" FAB to create a new event by accident, then press the Android back button without having entered any data, I would *not* expect to see the "You have unsaved changes" dialog.

**Comment by tibbi** [comment]
it doesnt ask me, do you have a CalDAV calendar set as default? Or you are storing events locally only?

**Comment by JohnVeness** [comment]
Ah that's interesting. Yes, it only seems to happen if my default calendar is a CalDAV one (in this case, using DecSync). It doesn't occur if using "Store locally only".
