### ISSUE TITLE
[FR] Smart pick new event day in Simple Event List view

### ISSUE THREAD

**Issue by JohnVeness** [SimpleMobileTools/Simple-Calendar#1341]
I use the "Simple event list" view. I have moved from Etar, which had a nice feature in its similar view which they call Agenda, that I miss in your app:

If you scroll down the list a bit, then click the "+" FAB to create a new event, it would be nice if the date for the new event was not today's date, but instead the date currently at the top of the screen in the list.

Alternatively have another way of adding an event to a particular day I've already scrolled to in "Simple event list" view - e.g. a "+" button beside each date heading rather than the FAB.

At the moment, if I've scrolled down to find a good time to do something then click "+", it is jarring to have to pick the date again.

**Comment by tibbi** [comment]
I dont really want to add that, sounds confusing
