### ISSUE TITLE
Setting availability

### ISSUE THREAD

**Issue by Netskeh** [SimpleMobileTools/Simple-Calendar#1349]
Hello, 
I was wondering if setting ones availability is possible? (eg free vs busy)
The reason I ask is I have an other app which automatically handles the DnD mode for me, such that on _free_ it leaves the phones as it currently is, while on a _busy_ availability it switches it to the corresponding DnD mode.

Did I miss it in this app or is this kind of setting / feature not available?

**Comment by tibbi** [comment]
nope, the app has no internet access so this is too advanced
