### ISSUE TITLE
Unable to translate "Customize notifications"

### ISSUE THREAD

**Issue by ldmpub** [SimpleMobileTools/Simple-Calendar#1351]
**Bug**
I did not find any string in resources files for this "Settings label"=> neither for french nor for english.

![Simple Calendar - Unable to translate Customize notifications](https://user-images.githubusercontent.com/1452146/115156242-97085e00-a083-11eb-8daa-fc40a3200164.jpg)

**Suggestion**
Please allow this string to be translated and add it to all resources translation files (for all languages).

Thanks in advance,

**Comment by tibbi** [comment]
it is in Simple Commons, the explanation is at the bottom of every string file. They are at https://github.com/SimpleMobileTools/Simple-Commons/tree/master/commons/src/main/res

**Comment by ldmpub** [comment]
Ok => big french translation review done, see https://github.com/SimpleMobileTools/Simple-Commons/pull/1064
