### ISSUE TITLE
No translation Key found to translate App strings (in search)

### ISSUE THREAD

**Issue by ldmpub** [SimpleMobileTools/Simple-Calendar#1352]
Quite the same issue as #1351.

This time: translation key may exist somewhere but are missing in the "Calendar" soruce project and can not be "customized" for the Calendar app (yet).

![No translation Key found to translate these strings - 2021_04_18_12_25_22](https://user-images.githubusercontent.com/1452146/115156633-73461780-a085-11eb-8f83-d2710ec401ec.jpg)

It looks like there is an "hidden search bundle" ... please tell me how to adapt these strings for calendar (for instance "Aucun élément trouvé" should become "Aucun événement").

**Comment by tibbi** [comment]
like I wrote in the previous issue, strings reused by multiple apps are in Simple Commons at https://github.com/SimpleMobileTools/Simple-Commons/tree/master/commons/src/main/res . It is written at the bottom of every strings file.

**Comment by ldmpub** [comment]
Thanks => see my pull request https://github.com/SimpleMobileTools/Simple-Commons/pull/1064
