### ISSUE TITLE
Week view overlapping labels

### ISSUE THREAD

**Issue by gmc1986** [SimpleMobileTools/Simple-Calendar#1354]
Since latest update on my pixel 4xl running grapheneOS the week view is unreadable overlapping labels different size entries for the same time period. Trying to downgrade returns constant failure error.

**Comment by tibbi** [comment]
Hey, what app version are you using? The glitch should have been fixed in 6.13.5

**Comment by gmc1986** [comment]
Hi im running 6.13.4

I have no option showing to download 6.13.5 image attached.

Many thanks

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by tibbi** [comment]
It should be available soon whatever source are you getting it from, Ill close it so I wont forget.
