### ISSUE TITLE
unable to sync simple calendar with nextcloud calender using DAVx5

### ISSUE THREAD

**Issue by whopila** [SimpleMobileTools/Simple-Calendar#1359]
Hi,

I am using the simple calendar but would like to synchronize it with one of my nextcloud calendars.
I have 2 nextcloud accounts.
So here's what I do:
settings in simple calendar on my android phone:
CalDAV-sync is on
managing synchronised calendars: default calendar is on

then i go to the nextcloud app and from the settings menu I choose synchronize calendar and contacts
DAVx5 opens: I enter my nextcloud username and password and enable 'personal' under CALDAV tab
it doesn't give any errors and the CalDAV address shows up correctly.
Then when I go to my nextcloud calendar it is empty. I was hoping to see a copy of the simple calendar here.
When I enter my other nextcloud account username and password in DAVx5 same thing happen:
my nextcloud calendar stays empty even when it seems a correct set up in DAVx5.
Am I missing something?

 kind regards, Joris

**Comment by tibbi** [comment]
You mean that events created in Simple Calendar are not synced to NextCloud? Are you sure you are saving them at the proper calendar? I mean the last field at creating a new event.

**Comment by whopila** [comment]
I missed that one, thanks for noticing. so I was creating local events all the time.
I changed some of the events to default calendar to check, but still it isn't working
in the options menu, selecting synchronisation calendars, I switched on everything, just to be sure..
but still, my nextcloud calendars are staying empty..
 any other guess?

**Comment by tibbi** [comment]
So if you open an event created in Simple Calendar, you see the proper synced calendar as the source at the bottom?

**Comment by whopila** [comment]
Ah got it now! Yesterday I switched on everything in the settings menu of simple calendar under selecting calendars to synchronize with.
But now i see this gave a lot more options in choosing the calendar in the bottom of the event, and now I can choose 'personal'.
Synchronisation works, thank you!
