### ISSUE TITLE
notifications out of sync after change to the summer time

### ISSUE THREAD

**Issue by knezi** [SimpleMobileTools/Simple-Calendar#136]
Hi,
I've set a notification to 7PM before the time was changed to the summer time.
After the change, the notification is shown in the calendar at 7PM, but it actually rings at 8PM (that's 7PM in the old time). So I guess that the notification time is set in advance and doesn't count on the summer time.
New notifications are fine. This is potentially very dangerous as there's no way to find out whether the note will ring on time or one hour later.

**Comment by tibbi** [comment]
should be better already
