### ISSUE TITLE
Monthly + daily view doesn't show an event from the next month

### ISSUE THREAD

**Issue by jewiet** [SimpleMobileTools/Simple-Calendar#1361]
First of thank you so much for the application. I use it daily and I love it. Well done!

I am using the latest version (6.13.5) of the Simple Calendar Pro.

I am viewing April's events and I can see the first week of the next month's (May) events. There is an indication of an event on May 8 but when I click on that day, I get a message that says No items found. 

When I swipe to the month of May and I can see the event with its details.

I think it must be a bug.

 (refer to the screenshot)
![Screenshot_2021-04-28-09-17-09-57](https://user-images.githubusercontent.com/43566553/116388240-e71db800-a81b-11eb-8022-54dfbe87a478.jpg)
![Screenshot_2021-04-28-09-17-17-45](https://user-images.githubusercontent.com/43566553/116388242-e7b64e80-a81b-11eb-8419-2513b1f0d94f.jpg)

**Comment by tibbi** [comment]
I cannot reproduce it. Does it matter what time is the event held at? I mean if in the morning or night? If you try clicking +- one day, so like May 7 or 9, does the event maybe show up?

**Comment by jewiet** [comment]
Thank you for the reply. I tried by clicking one day after the event and one day before still the event doesn't show up.

Here are some examples where the event shows for the 1st day of June but not for the event on the 5th of the same month(screenshot 1 and 2).

When I swipe to June and click on the 5th then i can see the event. You can see the event of the 5th on the last screenshot but you can see the event of 5th June from May's view..

![Screenshot_2021-05-16-12-37-57-27](https://user-images.githubusercontent.com/43566553/118394357-7c0a1900-b644-11eb-9fb4-ad740bcae49b.jpg)
![Screenshot_2021-05-16-12-38-01-56](https://user-images.githubusercontent.com/43566553/118394359-7e6c7300-b644-11eb-82c6-896dfda084ff.jpg)
![Screenshot_2021-05-16-12-41-11-87](https://user-images.githubusercontent.com/43566553/118394360-80cecd00-b644-11eb-9435-1e0d6e3ee8d6.jpg)

**Comment by breadsanta** [comment]
Running the latest version (6.14.0) I've encountered the same issue. Upon further testing, I discovered that the events more than 35 days away from the start of the month aren't shown.
Example: June has 30 days, you can see the events up to (and including the 5th of July).
July has 31 days, you can see the events up to (and including the 4th of August).
February has 28 days, you can see the events up to (and including the 7th of March).
This can be easily reproduced by creating a test event that repeats daily.
