### ISSUE TITLE
Exported .ics can't be imported by Apple Calendar

### ISSUE THREAD

**Issue by CWBHV** [SimpleMobileTools/Simple-Calendar#1362]
This used to work fine, now when I send an exported event to a Mac user, they click it, Calendar opens up and asks to import .ics, but nothing is actually imported.

The problem seems to be the block between BEGIN:VALARM and END:VALARM.
If I manually remove this from the exported .ics, it works as expected.

**Comment by tibbi** [comment]
could you find out which line exactly is breaking it? What app version are you using at all?

**Comment by CWBHV** [comment]
Thank you for the fast reply!

Version 6.13.5 pro

> BEGIN:VALARM
> DESCRIPTION:Erinnerung
> ACTION:DISPLAY
> TRIGGER-P0DT1H0M0S
> END:VALARM

The line TRIGGER-P0DT1H0M0S seems to cause the problem.

**Comment by tibbi** [comment]
oh i see, there seems to be a colon missing for some reason, will take a look at it. Thanks
