### ISSUE TITLE
Repeat the audio notification every x seconds  [feature request]

### ISSUE THREAD

**Issue by sleep2well** [SimpleMobileTools/Simple-Calendar#1363]
I don't want to have a short one time few seconds notification on the audio notification, nor a never ending audio until you turn it off.

If you could set the notification sound to repeat every x seconds, that would be great.

(It would also be great to turn off the audio notification by shaking the phone, for example).

**Comment by tibbi** [comment]
it isnt really on the roadmap, dont really expect having it
