### ISSUE TITLE
event end time wrong

### ISSUE THREAD

**Issue by Glasses8448** [SimpleMobileTools/Simple-Calendar#1364]
the event should only last one day. But the end time of the event is interprated as 0:00 on the next day, instead 23:59 on the same day.

screenshots
https://www.dropbox.com/sh/xjnok6ulzbpim42/AAArJl0ONeSK2HaxVBwEqURKa?dl=0

**Comment by tibbi** [comment]
what app version are you using?

**Comment by Glasses8448** [comment]
6.13.5 Pro

**Comment by Glasses8448** [comment]
I exported the event. You can find it in the dropbox

**Comment by tibbi** [comment]
well the exported one already shows the wrong data. Do other calendars show it well?

**Comment by Glasses8448** [comment]
it was exported from the simple mobile calendar...
In etar everything ia fine. I now also added the original file to.dropbox

**Comment by tibbi** [comment]
well you can open it with any text editor, it says DTEND:20210501T220000Z . There is nothing about 23:59 in it, I dont think the issue is on our side.
