### ISSUE TITLE
6.13.6 - events are not updated, apps keeps crashing

### ISSUE THREAD

**Issue by toxpal** [SimpleMobileTools/Simple-Calendar#1365]
Updated to 6.13.6 from F-Droid yesterday and since then I experience these issues:

1. Events (from remote calendar via CalDAV) can't be updated. If I change event time or date and save, nothing happens.
2. If I try to update the same event 2-3 times (hoping it will finally work), app crashes.

Running stock Android 11 and calendar is loaded from NextCloud (CalDAV). The issue is not related to calendar itself - tested it by downloading another app (Etar Calendar) and event updates work perfectly. After events are updated via other app, Simple Calendar also displays updated dates/times.

**Comment by tibbi** [comment]
just update to 6.13.7 whenever it becomes available, the crash has been fixed right after introducing it
