### ISSUE TITLE
Simple calendar pro issues.

### ISSUE THREAD

**Issue by gmc1986** [SimpleMobileTools/Simple-Calendar#1369]
Hi since latest update on f-droid the calendar is not usable at all. Cannot add new entries cannot edit current entries cant even change the colour of current entries without it crashing. 

Google pixel 4xl
GrapheneOS
Version 6.13.6

Many thanks

**Comment by tibbi** [comment]
just get 6.13.7 once it becomes available, it has been released right after the bug. F-droid is just delayed.
