### ISSUE TITLE
Do not show toast of exception

### ISSUE THREAD

**Issue by BuZZ-dEE** [SimpleMobileTools/Simple-Calendar#1374]
Please do not show a toast with an exception that does need a long time to disappear. It blocks the screen, so I can not see for example my keyboard.

**Comment by tibbi** [comment]
what toast you mean?

**Comment by BuZZ-dEE** [comment]
![Screenshot_20210513-205020](https://user-images.githubusercontent.com/125954/118176430-b2237f00-b431-11eb-8251-bab7cf09cb61.jpg)

**Comment by tibbi** [comment]
well that is a separate issue, the toast has a reason. Duplicate of #1037
