### ISSUE TITLE
Unable to open calendar

### ISSUE THREAD

**Issue by jinghuashang** [SimpleMobileTools/Simple-Calendar#1375]
系统自带的com.simplemobiletools.calendar.pro一打开就闪退，怎么解决？

**Comment by tibbi** [comment]
Not sure what you mean, the app is crashing at launching? What app version are you using?

**Comment by jinghuashang** [comment]
6.1.0

**Comment by jinghuashang** [comment]
![Screenshot_20210514-173313](https://user-images.githubusercontent.com/77230776/118252034-e606af00-b4da-11eb-9b48-024508438c4b.png)

**Comment by tibbi** [comment]
that is a really old app version, just update it please
