### ISSUE TITLE
Modifying past event displays notification soon after

### ISSUE THREAD

**Issue by ElektroVirus** [SimpleMobileTools/Simple-Calendar#1378]
If modifying a past event, a notification is sent soon. I think this is unnecessary because the notifications should appear only to current or incoming events.

**Comment by tibbi** [comment]
It is there on purpose because if you are creating/modifying a past event with a reminder, you might set it in the past unintentionally. So it works as a warning that it has passed already.

**Comment by ElektroVirus** [comment]
Okay, thanks for the quick reply! I understand, it's actually a good thing. Just wanted to document it if it was be a bug, since it may not be common to modify past events. 

ElektroVirus
