### ISSUE TITLE
Google Sync

### ISSUE THREAD

**Issue by LeshaRB** [SimpleMobileTools/Simple-Calendar#138]
Can you add sync with google calendar?

Calndaer is small and beatiful but it's small this disapear=(

**Comment by tibbi** [comment]
Hey, it is on the roadmap and will be added, but it might take a few more months to get there and polish it.

**Comment by Grossstadtkind** [comment]
The feature should be programmed in a way that it can be reliably switched off. For me a plus of this calendar is, that it does **not** synchronize like mad with google (like the wast mayority of the calendars). In the worst case synchronisation takes place without any notification. Google is not our friend and data protection should be supported. Not synchronisation here is a unique selling point.

**Comment by tibbi** [comment]
It will be disabled by default, thats for sure. However many people want to have their events backed up and synchronized between devices so if I want to scale the app, its a must have.

**Comment by LeshaRB** [comment]
I believe that without synchronization this is a meaningless calendar. All of my events are stored in the Google Calendar. There and edit them.

**Comment by ar-jan** [comment]
Is it possible to use Android's built-in calendar storage for a separate calendar app like this?

Then one could sync either via Google or via a self-hosted option. For example I'm now using [DAVDroid (via F-Droid app store)](https://f-droid.org/repository/browse?fdid=at.bitfire.davdroid) to sync with my own Radicale server (which I installed in one click using the [Sandstorm port of Radicale](https://apps.sandstorm.io/app/8kr4rvyrggvzfvc160htzdt4u5rfvjc2dgdn27n5pt66mxa40m1h)).

**Comment by tibbi** [comment]
google sync has been added, will receive some improvements in the future

**Comment by relan** [comment]
JFY, the inclusion of `com.google.android.gms:play-services-auth` make it impossible to bring Calendar 2.6.0 and later to F-Droid.

**Comment by tibbi** [comment]
Im looking at Caldav sync nowadays, looks like it will replace google sync as is. Im still a bit confused about those syncs, needs more research ;)
