### ISSUE TITLE
6.14.0, changing an alert on a repeating Event no longer prompts for option to not change future events

### ISSUE THREAD

**Issue by bsaunder2002** [SimpleMobileTools/Simple-Calendar#1381]
Hello,
Thanks for a great product!

Trying to use it as my daily schedule.  Have many events such as "Wake" to wake myself up at the same time each day.

Found making a calendar in Evolution, then saving as ICS, deleting all events in Simple Calendar Pro, then importing the ICS is an easy way to manage all of my events.

A previous (6.13.4??) version, when you changed the alarm setting for an event, it would prompt you something like "do you want to change all events or just this one".

Was great for not getting waken up early on Saturdays!

So now, if I remove the alarm from an event and save, it automatically removes it from all events.  I tried to find an option in Settings but nothing seems relevant.

**Comment by tibbi** [comment]
retry with 6.14.1 please, I cannot reproduce it. Not sure what related to that changed.
