### ISSUE TITLE
Reimporting birthdays from contacts creates duplicates

### ISSUE THREAD

**Issue by Robbendebiene** [SimpleMobileTools/Simple-Calendar#1382]
When importing birthdays from contacts, already imported birthdays will be added again.

Sounds similar to https://github.com/SimpleMobileTools/Simple-Calendar/issues/938#issuecomment-563923748 but the local calendar is only used for birthdays, everything else is managed via CalDAV.

<img src="https://user-images.githubusercontent.com/13716661/119628403-5e3f6f80-be0d-11eb-966e-70f107415a93.png" width="300">

Simple Calendar: 6.13.7
Android: 10

**Comment by tibbi** [comment]
duplitate of #938 then. It doesnt matter where are other events stored, only the birthdays are important.
