### ISSUE TITLE
Reminder only plays notification sound regardless of audio stream setting

### ISSUE THREAD

**Issue by dennis2society** [SimpleMobileTools/Simple-Calendar#1384]
I am using the calendar in version 6.14.0 Pro on a Samsung S21 running Android 11.
The event reminder always plays the notification sound instead of any ringtone or alarm, regardless of the selected "Audio stream used for reminders" option. 
To not disturb colleagues in a shared office I have set the notification sound to something really subtle (a short "pop" sound), so the notification sound is not a suitable reminder for important events such as meetings.
Since there is no official way to select an alarm sound anymore I have also tried the ringtone setting which is provable different from the notification sound, but the result is the same.

**Comment by tibbi** [comment]
you can customize the notifications even more than before, just use the "Customize notifications" button at the top of the app settings. There you can make a specific event type ignore DND mode or other crazy things.
