### ISSUE TITLE
compact view: past dates of the month are shown, though I restricted to 1 day

### ISSUE THREAD

**Issue by raschid** [SimpleMobileTools/Simple-Calendar#1391]
Hi there,

in _preferences > dates_  I restricted _show past dates_ to 1 day. 
It works in the day-view, but in the _compact list-view_ all past dates of the current month are shown. Is there a way to make this restriction work?

Thank you for this beautiful app ;-)
Ralf

**Comment by tibbi** [comment]
well that setting is for default visibility, but if you scroll the Simple Event List view up, it will show older ones too
