### ISSUE TITLE
Calendar not syncing with DAVx5

### ISSUE THREAD

**Issue by dequegorg** [SimpleMobileTools/Simple-Calendar#1402]
I have LineageOS for microG (lineage_sargo-userdebug 11 RQ2A.210405.005 eng.root.20210411.235807 dev-keys) installed on Pixel3a, together with Line App.

Installed Simple Calendar Pro 6.14.0 from F-Droid.
Installed DAVx5 3.3.11-ose. Synced my Google Calendar via DAVx5. The calendar now visible in Etar and default branch of Etar that comes with LineageOS, so I can confirm the sync works.

However, opening Simple Calendar, no event visible (no refresh button?). Going to settings, enabling CalDav sync, it says there are no calendars to Sync.

It seems Simple Calendar fails to see the newly added calendar (or I failed to see how to make it work).

**Comment by tibbi** [comment]
Do you have Google Calendar app installed and enabled?

**Comment by dequegorg** [comment]
No I don't. I've read Simple Calendar + DAVx5 would be a way around using Gapps on LineageOS.

**Comment by dequegorg** [comment]
Okay I think I found the solution. I toyed with the tick box on by Calendar on the DAVx5 app. Didn't realize the tick box means activating the calendar. I thought it was some selection toggle. So anyway, I ticked it again, and now Simple Calendar finds my calendar and I'm happy!
