### ISSUE TITLE
  Keep selected date when changing view

### ISSUE THREAD

**Issue by michaelof** [SimpleMobileTools/Simple-Calendar#1403]
Hi Tibor,

not sure if duplicate or denied already by you, can't find an open issue at least. 

E.g navigating in monthly view to a future month, tap on a day to see it's details, and switch then to weekly view. It's IMHO confusing that Simple Calendar then switches to the current date (today) and does not stay in the week of the current, selected day.

Happens to me quite often.

**Comment by Apahadi73** [comment]
can I take this up @tibbi?

**Comment by tibbi** [comment]
ye
