### ISSUE TITLE
Feature request: Override Do not Disturb option

### ISSUE THREAD

**Issue by davidhedlund** [SimpleMobileTools/Simple-Calendar#1408]
Simple-Calendar overrides the Do not Disturb by default which makes it useful without any configuration, you don't miss the alarm clock. However, there are cases where Simple-Calendar could be used with Do not Disturb active, so I suggest a **Override Do not Disturb** on/off button under Settings that can be turned off to activate Do not Disturb.

**Comment by tibbi** [comment]
such things are handled by the system, starting from Android 8 you can customize the notifications in your device settings. If you use the Pro app version you can get there easily by using the "Customize notifications" button at the app settings.

**Comment by davidhedlund** [comment]
> such things are handled by the system, starting from Android 8 you can customize the notifications in your device settings. If you use the Pro app version you can get there easily by using the "Customize notifications" button at the app settings.

Thanks for your reply tibbi.
