### ISSUE TITLE
Sorting of events with identical start date&time

### ISSUE THREAD

**Issue by lfriese** [SimpleMobileTools/Simple-Calendar#1410]
There's a bug (at least to me it is one) in the Calendar app concerning the order in which events on the same day, with the same start time are displayed in Monthly View.

Example:
Event "A" starts at 7:30 a.m. and ends at 9:00 a.m.
Event "B" starts at 7:30 a.m. and ends at 8:00 a.m.

In the Monthly View, those events are sorted alphabetically (A before B). When I click on a date to open the Daily View, the shorter event will come before the longer one (B before A). I personally think this (B before A) is the way it should be, because in a case of two overlapping events, I will be able to attend the longer one after the shorter one has ended. To me, sorting the events alphabetically makes no sense here, therefore I'd call it a bug.

Thanks for your time!

Sincerely,
lfriese

**Comment by tibbi** [comment]
what app version are you using?

**Comment by lfriese** [comment]
Version 6.14.1 Pro

**Comment by tibbi** [comment]
should be fixed in 6.15.1
