### ISSUE TITLE
Quick calendar filtering

### ISSUE THREAD

**Issue by chaptergy** [SimpleMobileTools/Simple-Calendar#1411]
If you have calendars from e.g. family members or coworkers, you might want to usually hide them and only periodically show them. For now you have to go though the overflow menu and filter the events by type, which works but could be more efficient. For example with a custom row of toggleable calendars at the bottom. This should be optional and probably disabled by default.

Basically the same thing as the second paragraph from https://github.com/SimpleMobileTools/Simple-Calendar/issues/1062.

This issue is less a feature request for you to implement but instead I'm asking whether you are open to the idea, and would accept a merge request if I get around to adding this.

**Comment by tibbi** [comment]
well if it gets implemented nicely and disabled by default, I can add it
