### ISSUE TITLE
[HELP] Caldav Sync with Nextcloud

### ISSUE THREAD

**Issue by cyb31** [SimpleMobileTools/Simple-Calendar#1418]
Hello, 
Is there a way to Sync a Nextcloud account with caldav on Android phone? 
Because when I would like to do this, there are only Gmail account choice.
Thank you

**Comment by michaelof** [comment]
Sure. Perfectly working e.g. is DAVx5: https://play.google.com/store/apps/details?id=at.bitfire.davdroid
