### ISSUE TITLE
Suggestion for an alternate separated days and events display on monthly calendar view. 

### ISSUE THREAD

**Issue by arkydon** [SimpleMobileTools/Simple-Calendar#1420]
The current monthly calendar view is: numbered days with corresponding events below each.

It would be nice if we had the option to set a different view where it is separated into two with numbered days at the top (marked if there is an event )and events list at the bottom. Calendar apps like Digical+ and Today Calendar Pro do this and it looks cleaner.

**Comment by tibbi** [comment]
you can use the monthly + daily view for that, not sure what else you mean
