### ISSUE TITLE
List view: events of multiple days or weeks are shown only on the first day

### ISSUE THREAD

**Issue by sanderbaas** [SimpleMobileTools/Simple-Calendar#1425]
When I enter a vacation into the calendar, on the list view this event is only shown once in the calendar. On the first day and there I can see what the last day is. But on the other days I don't see anything. Would it be possible to show this event on each of the days, similar to a whole day event? I can work around this by adding a repeating event that repeats daily for all the days, but I'd rather not 😉

**Comment by sparagi** [comment]
May be a duplicate of #742.
