### ISSUE TITLE
How to install last app version?

### ISSUE THREAD

**Issue by ldmpub** [SimpleMobileTools/Simple-Calendar#1428]
Hi,

I'm trying to update app from GitHub release page (see https://github.com/SimpleMobileTools/Simple-Calendar/releases/tag/6.15.0)

Installation of the app fails without any clear error message (Android only returns: "App can not be installed" 😥).

Note: I'm used to install APKs on my smartphone (option "allow unknown sources setup" is activated).

Thanks for your help,

**Comment by tibbi** [comment]
try launching the file from some file manager if it will behave the same way.

**Comment by ldmpub** [comment]
Confirmed:
Whatever Android File Manager I use, the behavior is the same => app does not install from the APK 😕.

**Comment by tibbi** [comment]
try googling around then, it must be some device specific system restriction not really related to our apps.
