### ISSUE TITLE
"Sunday as first day" setting not honored by date picker

### ISSUE THREAD

**Issue by cos64** [SimpleMobileTools/Simple-Calendar#143]
Steps to reproduce:

- Go to "Settings"
- Turn off "Sunday as first day"
- Observe that the week now starts on Monday
- Create an event
- When editing the event, tap on the start date or end date

Actual behavior:

- in the date picker, the week starts on Sunday

Expected behavior:

- in the date picker, the week starts on Monday

**Comment by tibbi** [comment]
the date picker is a system one, but I can check in the future if I can edit it like that.

**Comment by tibbi** [comment]
will be fixed in the next release from Android 5.0, not sure how to change it in Android 4.x

**Comment by cos64** [comment]
Verified and it works, thank you!
