### ISSUE TITLE
Enabling CalDAV only offers "Calendar" (ie, Google), no others

### ISSUE THREAD

**Issue by paul1149** [SimpleMobileTools/Simple-Calendar#1431]
Sorry if this has already been covered. I did search but couldn't come up with a solution.

On Android I installed OpenSync and synced it to my online cal/card service. It shows them both, so I think that part is accomplished:
![Screenshot_20210803-190937](https://user-images.githubusercontent.com/13952246/128098502-0aa52cee-34bf-481d-a0d0-e1fc75c2526d.png)

But in Simple Calendar, enabling CalDAV only brings up the google calendar. So I can not make the connection. Apparently I'm missing something here. Thanks.

**Comment by tibbi** [comment]
try triggering a manual syncing in DAVx5, you might not have it set up properly yet

**Comment by paul1149** [comment]
I switched from Open Sync to DAVx5. Still no availability of anything beside Google. Then I installed One Calendar, and it immediately synced to vivaldi webmail successfully in both directions.

**Comment by tibbi** [comment]
it definitely isnt an issue on our side, those were always related to some wrong setup. Trigger a synchronization manually in DAVx5.

**Comment by paul1149** [comment]
I did do a man sync in Davx5. Cal and Card dav tabs show synced. Webcal tab shows "no calendar subscriptions (yet)", and refreshing produces nothing. not sure what that means.

**Comment by stonecrusher** [comment]
@paul1149 DavX5 can't handle WebCal / .ics via http subscription properly. You additionally need [ICSx5](https://icsx5.bitfire.at/) and then it works (at least for me). See corresponding question in [DavX5 FAQ](https://www.davx5.com/faq/subscribe-ics-file).
