### ISSUE TITLE
Option to remove the number of days slider in the weekly view

### ISSUE THREAD

**Issue by tleydxdy** [SimpleMobileTools/Simple-Calendar#1434]
The slider is very buggy. For example when you slide to 9 days, scroll right, and slide to 7 days, there will be two days in between that won't get displayed anymore. And be cause of how new android gestures work, I'm hitting those sliders constantly when I try to switch apps.

Thank you so much for the great work!

**Comment by tibbi** [comment]
will be added in 6.15.1
