### ISSUE TITLE
Indexing days in month view is broken

### ISSUE THREAD

**Issue by ElektroVirus** [SimpleMobileTools/Simple-Calendar#1439]
I updated yesterday the Simple Calendar to v. 6.15.0 Pro, from F-Droid and since then there is a bug which makes the month view almost unusable.

In month view, tapping any day in the first row (e.g. now in August, days 26.7.-1.8.) will open up correctly. However, the days on the second row are indexed with +7 in days, that is one week later. For example clicking the day 4.8. will open 11.8. On the third row, the difference is two weeks: tapping 10.8. opens up day view of 24.8. 

From the 4. row the actions are unpredictable, I think: sometimes they don't open anything at all, sometimes they also open up the day view for the date +14 days. Mostly they don't open anything at all which also seems to be the case for rows 5 and 6. Please note, I used the human range of indexing: first row is #1. 

However, interesting is that by changing month (e.g. to September) and then pressing the button "Go to today", the indexing again works as expected, until the application is closed and started again.

Hopefully this report helps, and hopefully you can fix this soon! :)

Simple Calendar version  6.15.0 Pro
OS: LineageOS 18.1
Device: OnePlus 5

**Comment by tibbi** [comment]
What time zone are you in?

**Comment by ElektroVirus** [comment]
> What time zone are you in?

GMT+03:00 Eastern European Summer Time

**Comment by ElektroVirus** [comment]
I just noticed, that also changing the month via the month picker, which opens by tapping the month name in the top row, fixes the issue. However, the issue is not fixed by changin the month by sliding to the next or previous month.

I also tried reinstalling the app, didn't help.

**Comment by ElektroVirus** [comment]
Hello again, now that I updated Simple Calendar to version 6.15.1, this issue seems to gone away. Thanks for fixing it! :)
