### ISSUE TITLE
ics import V2.2.6: last recurring event using UNTIL & EXDATE handled faultily? Location?

### ISSUE THREAD

**Issue by Grossstadtkind** [SimpleMobileTools/Simple-Calendar#144]
Thanks for your really offline calender while the rest of the world is publishing and spreading his data like there's no tomorrow and treat big anonymous companies are their "friend".

The last recurring event is droped when recurring events are defined using a last occurence date, no? I had to set the UNTIL-value at least one second after the finish of the last occurence to let it appear. I think the last occurence should taken into acount already when in UNTIL the time is equal to the time in DTSTART.

EXDATE values have also  been ignored.
I checked the attached file (renamed .ics) against RFC 5545 using [https://icalendar.org/validator.html#results](url)

Would be great to have a LOCATION field.

[raumtreffen.txt](https://github.com/SimpleMobileTools/Simple-Calendar/files/907159/raumtreffen.txt)

Thanks

**Comment by tibbi** [comment]
Ive just published a fixed version 2.3.1, can you test the UNTIL value? 
Also please check if EXDATE works fine, as it has been improved in 2.3.0 and it works fine to me.
Thanks

**Comment by tibbi** [comment]
should be fixed

**Comment by Grossstadtkind** [comment]
I had some other things to do. Now: From my side: Confirmed to be solved.

**Comment by vendelin8** [comment]
Hi,

When I import a .ics file, it is okay, but when I use a remote calendar through ICSDroid, EXDATE doesn't seem to work. I'm not sure in which app is the bug though.

Thanks for the nice app anyway! :)

**Comment by tibbi** [comment]
it will probably be my calendar. How are you using EXDATE? I mean have you excluded just a single day, or something more complicated?

**Comment by vendelin8** [comment]
This time I tried with a single day like:
EXDATE:20171214T103000
Working directly with a .ics file, failed through ICSDroid

**Comment by tibbi** [comment]
ok thanks, Ill take a look at it someday.

**Comment by tibbi** [comment]
should be fixed in 6.0.2 already
