### ISSUE TITLE
Feature Request : Add option to archive event too (apart from deleting it)

### ISSUE THREAD

**Issue by Sgt-Miller** [SimpleMobileTools/Simple-Calendar#1449]
First off, great app. Simple yet powerful and very very fast. So I use this app to set reminders, tasks, events etc. and then delete it when I'm done with them. 
But would be nice if there was an "archive" option. Basically, "the event has been completed and is no longer relevant, but I still want to keep a record of it somewhere". And maybe a toggle option to show the archived events in calendar (would not show by default).    
One option I have is to use the .ics export feature, but would be nice if there was an in-built way to do this.

**Comment by tibbi** [comment]
I dont really want to add such things, I dont see it being useful. Thanks
