### ISSUE TITLE
[Feature Request] Set default storage location for new events

### ISSUE THREAD

**Issue by Octofoxy** [SimpleMobileTools/Simple-Calendar#1455]
I'm using Simple Calendar to sync events with my Nextcloud (and, in extension, to Thunderbird on my desktop). However, every time I create a new event in Simple Calendar, I have to manually change the storage setting from "store locally only" to "Nextcloud".

I mainly work on my desktop and I don't ever need to store an event locally on my phone. It would be great if I could choose a default storage location for new events in the "New Events" section in the options menu, instead of having to manually change the setting for each and every new event.

**Comment by tibbi** [comment]
it should work like that by default already. If it doesnt, make sure the "Default event type" is set to "Last used one" in the app settings.
