### ISSUE TITLE
[Feature request] Add birthdays only from selected contacts

### ISSUE THREAD

**Issue by ema-pe** [SimpleMobileTools/Simple-Calendar#1465]
Hi, I have lot of contacts but only few of them I want to know the birthdays. I would propose to add a whitelist of contact of which I want the birthdays, other should be ignored.

**Comment by tibbi** [comment]
I dont really want to add that, feels too advanced. Just delete the ones you dont need.

**Comment by ema-pe** [comment]
> I dont really want to add that, feels too advanced. Just delete the ones you dont need.

The problem arises when you sync the birthdays with the contact list, the deleted birthdays will reappear.
