### ISSUE TITLE
Silent notifications - no alarm

### ISSUE THREAD

**Issue by PinkPlasticBeach** [SimpleMobileTools/Simple-Calendar#1469]
For many events (like returning books to library) I would like to choosr a silent notification with text only and no alarm.

Right now I can choose e-mail in online-calendats, but I wish for a silent android-notification for online and offline-calendars.

Works best with convenient and custom notification times: https://github.com/SimpleMobileTools/Simple-Calendar/issues/1470

Thanks for the app!

**Comment by tibbi** [comment]
If you have Android 8+ you can customize notifications in your device settings on a per event type basis, it shouldnt be handled by the app itself. Just press "Customize notifications" in the app settings to get there.

**Comment by PinkPlasticBeach** [comment]
Thats not a Solution.

I use Android 10. Settings in Android will only work for the whole app, unless the app uses multiple "channels" for notifications, like some apps do. Thats exactly what I'm asking for: To choose something like "Urgent Notification" and "Not-Urgent Notification". Android does the rest.

I have meetings, were I want to hear an alarm half an hour before.
I have lots of stuff that needs preparation like a day before. I dont want an alarm to go off for that. Reading it when I open my Phone in a good moment is much more convenient.

Please Consider this again. It is not a luxury request in my eyes. A Calendar on smartphone is the basic form of a personal assistant for many people. It doesn't need to be an AI, but I'd really like to choose whether It "shouts" at me or leaves a simple "note". My old Nokia dumb Phone had that choice.

**Comment by tibbi** [comment]
event types are used as channels, you can create multiple ones at the app Settings -> Manage event types.

**Comment by PinkPlasticBeach** [comment]
Oh yes I see,
this helps in some cases and I will use it as workaround, Thank you.

Still a problem in calendars shared with other people, cause I can only choose to silence the whole calendar or not.
As a workaround we will create a second calendar for "urgent" stuff i guess.

As this is about Notifications I think it's straight-forward to choose the type of notification.
Where I can already choose "Notification" / "E-mail" I could easily choose "alarm notification" or "silent notification".
As I can add multiple Notifications already I could have a silent notification 3 days in advance and an alarm 2 hours before start. This is a very common use-case in my world.
