### ISSUE TITLE
Notification times like day before

### ISSUE THREAD

**Issue by PinkPlasticBeach** [SimpleMobileTools/Simple-Calendar#1470]
I would like to choose notification-times like
"the day before at hh:mm"
"At yyyy:MM:dd hh:mm"

Or better:
"X days before at evening" (evening being customizable time)

At best fully customizable "time"-sets

Most important function of calendar for me is to be reminded of events planned so long ago that I might completely forget them.
So I don't need an alarm an hour or two before but mostly a day, sometimes a week before.

Right now I can set custom number of days or weeks. Weeks (and days) is often unhandy because it would ruin my relaxed Saturday a week before I really need to get up early the next saturday.

So I need to calculate days into hours adding/substracting the time I really want to be notified relative to the start of the event.

Works for me, but as I regard this as a key function of calendars it should be convenient, I think.

Works best combined with silent notifications:
https://github.com/SimpleMobileTools/Simple-Calendar/issues/1469

Thanks for the app ;)

**Comment by tibbi** [comment]
That sounds quite confusing, dont really expect having it. You could have multiple events created previous day too.

**Comment by PinkPlasticBeach** [comment]
Hey Tibbi,
Thanks for the quick answer.

Theres a very simple way of it: You already have the Setting: "During the day at hh:mm" for all-day events"

Just make this setting available for all events and let us choose the day, too:
"At Day X at hh:mm"
The app can translate this to something like 32 hours, 30 Minutes if there's no other way to save it.
The app is much better at calculating this than I am in a bad moment.

I Don't want to add multiple events for reminders. That will clutter my calendar-view with too many events.
I want to see the event only at the correct date, but notifications (visual and audio) at other times. Its basicaly the key function of a computer-calendar for me.

Please consider this again.

**Comment by PinkPlasticBeach** [comment]
As you said it was unusual, please think about it again with this perspective:

- Is it "too complicated" for a Calendar(/Timetable/Scheduling)-App to _schedule_ the alerts?

Make it your way.
There's enough space in the notification-dialogues:
here and there
![Imagepipe_21](https://user-images.githubusercontent.com/4244635/132598756-311e6f51-d7ee-496b-a6a5-002c499d53c4.jpg)
![Imagepipe_20](https://user-images.githubusercontent.com/4244635/132598770-b7a1495d-72e4-4a51-a494-006a1cf75977.jpg)
