### ISSUE TITLE
[Feature request] Repeated event with randomly timed reminder

### ISSUE THREAD

**Issue by gcoimbra** [SimpleMobileTools/Simple-Calendar#1471]
First of all, thanks for the app, it's very well done!

I'd like to propose a way to be reminded in a random time about some event. 
Example for weekly reminder:
1. Event repeats every week
2. Some day during that week Simple Calendar will notify you about the event.

Example for daily reminder:
1. Event repeats every day
2. Some hour during that day Simple Calendar will notify you about the event.

This is a nice way to do when you don't have a specific time when you need to be notified.

**Comment by tibbi** [comment]
I dont plan adding random reminder, that sounds weird.. You can already set during-day reminders for all-day events
