### ISSUE TITLE
Saving edits of imported event for the first time doesn't show confirm dialog

### ISSUE THREAD

**Issue by AllanChain** [SimpleMobileTools/Simple-Calendar#1478]
### Steps to reproduce

1. delete all events for clean start
1. create regular event named "test", and set repetition to weekly
2. save it
3. export to `test.ics`
4. delete all events
5. import `test.ics`
6. edit event test, rename it to "tes"
7. save

### Expected result

Dialog "this event is repeatable" appears

### What happened

No dialog. Silently saves the edit to all occurrences

### Extra info
Second edit is fine

Version: v6.15.1 Pro, from F-Droid
Android: 11

**Comment by nic3-14159** [comment]
I'll take a look at this one.
