### ISSUE TITLE
All-day events sometimes registered one day behind.

### ISSUE THREAD

**Issue by NaofumiHonda** [SimpleMobileTools/Simple-Calendar#1480]
My timezone is Asia/Tokyo and my caldav server is davical through davx5.

Usualy all-day events are registered in the server correctly, but
when the registration of an all-day event is done from about 23 PM to 1 AM(GMT+9), 
they are registered in the server with their event dates being one day behind.

If UTC timezone is selected in the simple calendar app, then every thing goes well.
Furthermore, in my investigation, other clients like thunderbird lightning, evolution calendar, etc
use the UTC timezone for all-day events (of course, they use a local timezone for other type of events).

I am now thinking that the UTC timezone is better to be selected as a default timezone for all-day events
even if the simple calendar app. Or such a setting will exist.

**Comment by tibbi** [comment]
what app version are you using?

**Comment by NaofumiHonda** [comment]
The most recent pro version: v6.15.1

**Comment by Naveen3Singh** [comment]
@NaofumiHonda 

If you are willing to test, here is a test APK with a possible fix: https://github.com/Naveen3Singh/Simple-Calendar/releases/download/all_day_event_fix/calendar-prepaid-debug.apk ([info](https://github.com/Naveen3Singh/Simple-Calendar/releases/tag/all_day_event_fix))

APK is for testing only and should be uninstalled afterward.

Lmk if it works (or not)

Thanks.

**Comment by tibbi** [comment]
should be fixed in 6.20.2 released soon
