### ISSUE TITLE
Prefer client-side email scheduling option

### ISSUE THREAD

**Issue by Blop3474** [SimpleMobileTools/Simple-Calendar#1484]
Hi all,

I'm used to use simple calendar ... Great simple tool. As for Thunderbird, is there the option "Prefer client-side email scheduling".
I don't see it ?
If there is no option possible to implement it ? 

Many thanks for your support / reply.

Best regards

Lionel

**Comment by tibbi** [comment]
emails are handled by the CalDAV server, our app has no internet access
