### ISSUE TITLE
Weekly view only shows 6 days instead of 7 days

### ISSUE THREAD

**Issue by eomanis** [SimpleMobileTools/Simple-Calendar#1487]
As it says in the title, see attached screenshot.

## System info
- com.simplemobiletools.calendar.pro 6.15.2 from the F-Droid app store
- Google Pixel (sailfish), LineageOS 17.1 from September 25, 2021
- Build number: lineage_sailfish-userdebug 10 QQ3A.200805.001 10035364

## App settings
- "Start week on Sunday" is OFF
- "Weekly view: Allow customizing day count" is OFF

Temporarily switching to a different view and then back to the weekly view does not resolve the issue.

![Screenshot_20210930-204827_Calendar 540x960](https://user-images.githubusercontent.com/5933155/135515232-87b53b75-5973-411b-b992-003e3bbf7879.png)

**Comment by tibbi** [comment]
well, just enable "Allow customizing day count" and set it to 7. Then disable it again if you want to hide the seekbar.

**Comment by eomanis** [comment]
Oh wow I am dumb. There is a "Number of days" slider at the bottom when "Allow customizing day count" is enabled 🤦
