### ISSUE TITLE
A Bug & Feature Request

### ISSUE THREAD

**Issue by HonestAbe7** [SimpleMobileTools/Simple-Calendar#1494]
Thank you for the improvements to this app! I like how I can now just view holidays and/or events.

The bug I noticed is when I try to change colors for each of the widgets. It does work for a small period of time to have different colors but I guess they need to all be the same color? I restarted my phone and noticed this.

Would like the day of the week to be an option for the date widget. Also, a way to resize the date and/or day would be nice since the widget stretches but the font text doesn't get bigger.

**Comment by tibbi** [comment]
Report things one by one please. All widgets use the same color, they are not set individually.
