### ISSUE TITLE
Day back arrow in details view navigates two days previous instead of one

### ISSUE THREAD

**Issue by picklecat** [SimpleMobileTools/Simple-Calendar#15]
This bug is new in v1.16

To reproduce problem:
1. Launch calendar app or widget.
2. Touch/select any day in any month
3. Touch '<' arrow and the day will change to two days previous (n-2 instead of n-1).

**Comment by tibbi** [comment]
Hello, what timezone are you in? Is anything wrong with going forward too?

**Comment by picklecat** [comment]
Hi. GMT-7 (US Pacific Time Zone). The going forward bug remains; the '>' button registers the touch, but the date is not advanced.
