### ISSUE TITLE
CalDav support

### ISSUE THREAD

**Issue by nopeppermint** [SimpleMobileTools/Simple-Calendar#150]
are there any plans to support CalDav import/export/sync ?

**Comment by tibbi** [comment]
it is on the roadmap, not sure when will I get there. Currently Im working on adding more advanced repeat rules like "every tuesday and friday", as events often have those and I dont want to trim them away at importing events from calvas or google.

**Comment by wibrt** [comment]
This would really be an added value, as the aosp in f-droid is from some years ago

Integration davdroid and others..

**Comment by mdkuser** [comment]
I second the feature request of implementing CALDAV sync! (maybe this can be done supporting bidirectional sync via acaldav or davdroid?)

**Comment by wibrt** [comment]
I have a good experience with the usage of davdroid. (> works fine in my
opinion)

Op 19-05-17 om 13:06 schreef mdkuser:

**Comment by tibbi** [comment]
caldav is already available in the f-droid build too
