### ISSUE TITLE
Bug or Preference With Monthly/Daily View Not Showing Day Without Clicking Current Day 

### ISSUE THREAD

**Issue by GithubContributor832** [SimpleMobileTools/Simple-Calendar#1508]
I'll include two pictures. When opening your monthly/daily view it shows me month only with all events. I have to click date in order to get monthly/daily view. Shouldn't it show the monthly/daily view without clicking specific day. I suppose this could be preference. 

This is what I get opening view

![Screenshot 3](https://user-images.githubusercontent.com/92182796/136850158-11652db2-21ba-40ab-b6b1-a6e488813bf0.png)

This is what I get after clicking date

 ![Screenshot 2 (1)](https://user-images.githubusercontent.com/92182796/136850218-fce0f38a-d013-4c5d-b2de-5a6860aeea4e.png)

**Comment by tibbi** [comment]
right, that isnt really planned. I want to show the whole month by default

**Comment by GithubContributor832** [comment]
Ok thanks for informing me. To each their own. That's just my preference and what I thought you intended.
