### ISSUE TITLE
Adding comments to files or functions or variables

### ISSUE THREAD

**Issue by desmondCTNG** [SimpleMobileTools/Simple-Calendar#1515]
I am new to the project, but I want to try to contribute on the project. As the project is now quite big, with a lot files, I think it would be better if there are comments on files or functions, so that others can understand it faster.

With so many people forking or watching this repository, I think it is worth to add comments to files or functions, so that people can fix bugs, or add new features by themselves.

**Comment by tibbi** [comment]
hello, it isnt really on the roadmap now
