### ISSUE TITLE
Importing ics file as default entries shifts all dates backward 1 day

### ISSUE THREAD

**Issue by Sepero** [SimpleMobileTools/Simple-Calendar#1521]
Reproducibility 100%

Actions to Reproduce:
1. Export all entries
2. Delete all entries
3. Reimport all entries as CalDev (ignoring event types in the file and use the default)
4. All entries appear correct at first, but leave the app and come back, and they are all shifted backward in time by 1 day

Important Note: If I reimport the entries without using CalDev (retain event types in the file), then the import is correct and dates are Not shifted.

This bug may be related to #1480 . My timezone is also in Asia, and all of my events are all-day events.

Android v10
Simple Calendar v6.15.4

**Comment by Naveen3Singh** [comment]
@Sepero 

If you are willing to test, here is a test APK with a possible fix: https://github.com/Naveen3Singh/Simple-Calendar/releases/download/all_day_event_fix/calendar-prepaid-debug.apk ([info](https://github.com/Naveen3Singh/Simple-Calendar/releases/tag/all_day_event_fix))

APK is for testing only and should be uninstalled afterward.

Lmk if it works (or not)

Thx much.

**Comment by Sepero** [comment]
I'll try to make time to test it. Thank you very much 🙂👍🏻
