### ISSUE TITLE
multiple calendar entries of all appointments

### ISSUE THREAD

**Issue by danield5732** [SimpleMobileTools/Simple-Calendar#1532]
I use the app since several months but recently entries occure four-times as duplicates.
The calendar is synced with DAVx5, but the original calendar does not show multiple entries.

How to fix this?

**Comment by tibbi** [comment]
What app version are you using? Are you syncing via NextCloud or what service is on the other side?

**Comment by danield5732** [comment]
The version is v 6.15.4 Pro
and I sync the caldav calendar provided by www.posteo.de via DAVx5

Thanks a lot for your support!

**Comment by tibbi** [comment]
Do other downloaded calendar apps show them properly?

**Comment by danield5732** [comment]
Yes, I just tried Google calendar and their I see each event once.


Am 2. November 2021 15:56:54 MEZ schrieb Tibor Kaputa ***@***.***>:
>Do other downloaded calendar apps show them properly?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/SimpleMobileTools/Simple-Calendar/issues/1532#issuecomment-957756180
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by tibbi** [comment]
Okay, any way to reproduce it? Are they simple one time events, or some repeating ones? Maybe repetition exceptions?

**Comment by danield5732** [comment]
There seems to be no difference between one time and repetative events.
A newly added event appears only once.
I cannot say when it turnes into multiple events, but also in the past all other events are shown four-times.

When deleting one event, three of them remain in the calendar.


Am 2. November 2021 16:32:24 MEZ schrieb Tibor Kaputa ***@***.***>:
>Okay, any way to reproduce it? Are they simple one time events, or some repeating ones? Maybe repetition exceptions?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/SimpleMobileTools/Simple-Calendar/issues/1532#issuecomment-957832448
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by danield5732** [comment]
Well, now I switched off the respective calendar in the settungs of the simple calendar app, waited the entries to disappear, and finally after again switching on the calendar, it looks fine with only single entries.

I hope it will stay this way. Otherwise I will report it again.

Kind regards



Am 2. November 2021 16:32:24 MEZ schrieb Tibor Kaputa ***@***.***>:
>Okay, any way to reproduce it? Are they simple one time events, or some repeating ones? Maybe repetition exceptions?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/SimpleMobileTools/Simple-Calendar/issues/1532#issuecomment-957832448
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by tibbi** [comment]
okay, will keep an eye on it then

**Comment by eoli3n** [comment]
I face this too. It completely broke my calendar. I have 800 events, UIDs and DATE are differents (only SUMMARY match), that's a big mess to clean...
