### ISSUE TITLE
App crashes when trying to export ics file

### ISSUE THREAD

**Issue by fossingit** [SimpleMobileTools/Simple-Calendar#1541]
Thank you for all of your work on this project! I've been using it for years and it's been such a great alternative to Google and other products. 

I've been having an issue lately trying to export a local calendar I created on my phone to an ics file. Each time I try the app just crashes. 

I'm on a OnePlus 7 Pro with Oxygen OS 11.0.3.1.GM21AA and Android 11 using Simple Calendar v 6.15.4 Pro from F-droid.

**Comment by tibbi** [comment]
At which point does it crash? Immediately as you press Export at the top menu? Havent you disabled some file picking related system services?

**Comment by fossingit** [comment]
It crashes immediately after pressing okay. I haven't intentionally disabled any file picking system services. I'm using Simple File Manager.

**Comment by tibbi** [comment]
the destination folder is handled by the system, not any file manager app. Does for example attaching files into emails work?

**Comment by fossingit** [comment]
Yes, I can attach files to emails or export individual events from the calendar as an ics file.

**Comment by fossingit** [comment]
Anything else I should try to troubleshoot? Thanks!

**Comment by tibbi** [comment]
not really, I still see no reason for it on our side. You must have done something with your system that broke it, it is hard to say what exactly though

**Comment by fossingit** [comment]
Oh okay, well I will continue to troubleshoot, although I haven't made any drastic changes on my end. Is there any other way to access local calendar files created by the app? I would like to preserve the data and I assume if I uninstall it will be lost?

**Comment by tibbi** [comment]
by default all events are stored locally only inside the app, you cannot access them. Ye, you will lose it by uninstalling. If you try using the Event List view and selecting some events by long pressing then using the top Menu -> Share, does that work?

**Comment by fossingit** [comment]
Yep, that works!

**Comment by fossingit** [comment]
It is working after I reset all of apps - something must have been disabled. Thanks for your help.
