### ISSUE TITLE
Support landscape orientation

### ISSUE THREAD

**Issue by trubitsyn** [SimpleMobileTools/Simple-Calendar#155]
Currently layout does not change when device is rotated. If it did, it would be easier to scan week view horizontally in some cases.

**Comment by mthor1234** [comment]
Hey,

I started looking at this. Noticed that R/values/booleans holds the power for screen rotation.
By setting:     <bool name="portrait_only">false</bool>

Is there any major issues I should worry about or can I go ahead and create the landscape layout versions

**Comment by tibbi** [comment]
it is disabled mostly because of other views. You would have to change the column/row counts to make them readable. If you think you can solve it nicely, just go ahead. But it has to be enabled or disabled for all views, not just toggle it at the weekly one.

**Comment by trubitsyn** [comment]
Thanks for getting this fixed!
