### ISSUE TITLE
An error message that makes editing an event a pain

### ISSUE THREAD

**Issue by gethob1** [SimpleMobileTools/Simple-Calendar#156]
Create an event and enter a title only, set it to All-day, and tap the check-mark to complete its creation.  Then tap on the new event and add a description and tap check-mark.
It will not okay the change and say "The event cannot end earlier than it starts"
Being an all-day event I don't see how this is supposed to occur but upon turning off All-day the start and end times are displayed as 1:00 and 12:59.
Every time I want to edit an event in this way I have to disable All-day, manually adjust the end time, and enable All-day again.

Please fix, this bug makes this calendar app very impractical for even casual use.  Thank you.

**Comment by tibbi** [comment]
ye handling of all-day events needs to be changed for sure, its weird now
