### ISSUE TITLE
today isn't corret.

### ISSUE THREAD

**Issue by ZhuSniffsTheRose** [SimpleMobileTools/Simple-Calendar#1563]
In China,  today is Wednesday, but the calendar indicates today is the next day: Thursday.

the app version:
versionCode 208
versionName "6.15.4"

**Comment by tibbi** [comment]
on which view does it indicate the wrong day?

**Comment by ZhuSniffsTheRose** [comment]
> on which view does it indicate the wrong day?

weekly
