### ISSUE TITLE
Switch from 3rd party launcher resets view

### ISSUE THREAD

**Issue by n89h** [SimpleMobileTools/Simple-Calendar#1565]
Returning to calendar pro via other app may reset view to daily.
Experiencing this via Lawnchair 'at a glance' widget. This issue only applies to the pro version.
Switching through app drawer to the calendar maintains the view selection as intended.
[I just bought the pro calendar and need this feature to bring me to my monthly/last selected view. Lawnchair discord guessed this happens on your end. I apologize if its on them, I would forward any hints about where to look for a bug, thanks]

**Comment by tibbi** [comment]
some widgets specifically require the view that should be open, guess that is your case too

**Comment by n89h** [comment]
so you are saying that that lawnchair widget specifically tells the pro version of simple calendar to open in the daily view, while it opens both the free version of simple calender and the samsung calendar in the currently selected view? its so weird both ways, but i will forward it to lawnchair then, thank you for your time.
