### ISSUE TITLE
4000 Event notifications per day since 6.15.4

### ISSUE THREAD

**Issue by sn0west** [SimpleMobileTools/Simple-Calendar#1566]
I do get around 4000 eventnotifications per day sind version 6.15.4. I actualy tried version 6.16..1 from fdroid but it is still a big problem there. Now I don't see version 6.15.2 wich do not have this problem. Can anyone point me to the apk for 6.15.2? 

I do have a fairphone 3 with eOS android 10. Three calender are synced with caldav davX and one is frome bextcloud. 

Event notification can't be disabled. It's just anoying seeing ecery five second the calender icon popping up. 

Thanks for a fix or a solution.

**Comment by tibbi** [comment]
well, dont you have many events stored? Or how many notifications should you have?

**Comment by sn0west** [comment]
On the push it's called event notifications. If I go to settings it's called alarm synchonisation. 
This is not the same as a reminder for a specific event in my calender. Those works without problems. 

Just the alarm sync is going crazy since version 6.15.4

![Screenshot_20211125-112309_Einstellungen.png](https://user-images.githubusercontent.com/9918649/144652288-c8dcb253-fc46-4803-b5bb-7cddf9e606ab.png)

![Screenshot_20211125-112445_Einstellungen.png](https://user-images.githubusercontent.com/9918649/144652310-5f12b08c-5cae-4c02-999c-b7140f631c6e.png)


![Screenshot_20211125-112507_Einstellungen.png](https://user-images.githubusercontent.com/9918649/144652348-c7d74784-d87c-4fe3-a36a-1a09172cd448.png)

**Comment by tibbi** [comment]
well it is hard to reproduce or fix such issues, they are likely related to your setup. Try looking around a bit more and try finding the reason first.

**Comment by sn0west** [comment]
> well it is hard to reproduce or fix such issues, they are likely related to your setup. Try looking around a bit more and try finding the reason first.

How? 

Befor 6.15.4 it was fine! After this it wasn't anymore.  Setup is the same. 

It consume more battery in my opinion. 

Uninstalling simple calendar fix the problem. 
Version downgrade to 6.15.2 fix the problem. 

I read that others also had troubles and recomended downgrading. I have to find thoses posts. 

How can I help fixing the problem? 
Is it the first time you hear that?

**Comment by sn0west** [comment]
Found thd thread

[](https://community.e.foundation/t/calendar-alarm-synchronisation-event-notification/35998/13)

But its in german

**Comment by sn0west** [comment]
Could you provide me verdion 6.15.2 please?

**Comment by tibbi** [comment]
you can find all versions at https://github.com/SimpleMobileTools/Simple-Calendar/releases

**Comment by sn0west** [comment]
Great thanks a lot. I hope the problem will be fixed quickly. I realy lie your work! 
Thank you

**Comment by Honk2** [comment]
> Found thd thread
> https://community.e.foundation/t/calendar-alarm-synchronisation-event-notification/35998/13

Within this thread, there is a link to an issue in /e/ https://gitlab.e.foundation/e/backlog/-/issues/2049
Basically this seems to be a problem in /e/ and not only related to this calendar app but also to Etar.

Anyway, maybe some of the commits to 6.15.3 triggered this behaviour in /e/ as also others report in that thread 6.15.2 to be the last version of SimpleCalender not being affected.

**Comment by tibbi** [comment]
should have been solved already
