### ISSUE TITLE
Show elapsed time

### ISSUE THREAD

**Issue by lelkese** [SimpleMobileTools/Simple-Calendar#1568]
Hi,

This is a very nice app. It would be very useful for time tracking purposes to show the elapsed time of an event in the list view (+ daily view, monthly and daily view), when the starting and finishing time is different and the event isn’t an all-day event.

Thank you.

**Comment by tibbi** [comment]
it isnt the purpose of this app, it is a calendar

**Comment by lelkese** [comment]
Thank you for your answer. I agree, that the [time tracking](https://github.com/SimpleMobileTools/Simple-Calendar/issues/1569) is out of the scope of your application. However to show the elapsed time/time needed for the event in the daily views can used not for time tracking purposes. For example it could be useful to see how long meeting should you prepare (without calculating in your head each time as it is not always just multiply of half and whole hours). E.g a consultant (who doesn’t spend the same time for each costumer), a hairdresser and so on. This feature is even part of the Microsoft Office.
I think it is a quite small feature, which give additional advantage for a lot of people/purpose and do not complicate the app itself. (It could also have a settings to not show always.) So I would happy if you could reconsider your decision and just include the elapsed time/time needed for the event in the daily views.
