### ISSUE TITLE
Time tracking statistic

### ISSUE THREAD

**Issue by lelkese** [SimpleMobileTools/Simple-Calendar#1569]
Hi,

Your app is usable as an time tracking application. For examples: Work, study, sport, sleep, online social ... (These are the different event types.)

Currently you can set up “default start time: current time” in settings. So by adding a new event you can define the title of the exact tasks, what you are performing. E. g. working with project X, Y; learning subject X, Y; running, strengthening, yoga; R: rate of the sleep; Facebook timeline, Instagram…). The starting time will the actual starting time. After you finished the activity you change the end time to the current time. (Here a Now button or symbol would be good.) In the weekly view you can get a really nice graphical overview. In the list view you could see the [elapsed time](https://github.com/SimpleMobileTools/Simple-Calendar/issues/1568).

An event type summary would be good to see your progress. For example a weekly event type summary view could like as the followings:
in columns: event types, M, T, W, T, F, S, S, total time, average time
in rows: the the different event type names and the times
(The event day could be counted to that day, where you have spent more time on that activity or the ending day, if it continues after midnight. For example: sleep, if you started today night, then it can be counted as tomorrow sleep, because probably you spent the most of the time with it on the next day.) This view would be super useful and a save/export function would be a nice addition. (For example to csv with a header: day in YYYY-MM-DD format, event type, elapsed time.)

What is your opinion?

Thank you.

**Comment by tibbi** [comment]
not really, it isnt the purpose of this app at all
