### ISSUE TITLE
memory-using issue

### ISSUE THREAD

**Issue by ZhuSniffsTheRose** [SimpleMobileTools/Simple-Calendar#1573]
there's a memory-using issue. it could cause oom that events too many to count. when the user adds an event, the app updates all events. Can Simple-calendar support just update the event just added instead update all?

**Comment by tibbi** [comment]
duplicate of #1530

**Comment by ZhuSniffsTheRose** [comment]
Is there a plan to fix it?

**Comment by tibbi** [comment]
sure, but it is hard to reproduce and fix

**Comment by ZhuSniffsTheRose** [comment]
It's not necessary to reproduce, just supports updating only one event instead of all when adding an event.
