### ISSUE TITLE
Notifications stopped working

### ISSUE THREAD

**Issue by peter099** [SimpleMobileTools/Simple-Calendar#1576]
I have Simple Calendar installed from fdroid on my moto x play phone with LineageOS 17. I did a format on my phone and re-installed LineageOS,, but before that i backup my apps with SwiftBackup. After finishing reinstalling LineageOS i restored my apps with SwiftBackup but i have noticed that Simple Calendar notifications stopped working. The events are restored but the notifications are not working. Any idea what could be the reason?

**Comment by tibbi** [comment]
check your device battery and notification settings, if there is nothing blocking the reminders, or killing the app in the background. You might also want to take a look at https://dontkillmyapp.com , it has some useful tips.

**Comment by peter099** [comment]
Notifications started working again, though i don't know what fixed them.
