### ISSUE TITLE
EXDATE "only" accepted as one per line, not comma separated

### ISSUE THREAD

**Issue by Grossstadtkind** [SimpleMobileTools/Simple-Calendar#158]
EXDATE have to be written as one EXDATE per line. RFC5545 allows EXDATE -values separated by a comma. Comma (or semicolon) did not work for me, but for me that was acceptable. However support of comma-separated EXDATE would be better.

**Comment by tibbi** [comment]
If you are still around, can you send me a sample line? Or what app/web generates exdates like that? Thanks
