### ISSUE TITLE
Cannot send end date to recurring event

### ISSUE THREAD

**Issue by IcedQuinn** [SimpleMobileTools/Simple-Calendar#1581]
S6 Lite, current version on F-Droid as of 2021-12-16.

When trying to change the end date of a repeating calendar reminder you can choose to set it to repeat until the current date. This will mark the event as ending on today. However if you tap the date button and attempt to change to one week prior and hit OK, the window will close and Calendar will mark the event as recurring forever.

This makes it impossible to correct a calendar entry for something that expired a week ago.

**Comment by tibbi** [comment]
Im not sure what you mean here, you can customize the repetition limit in the Edit event screen. It is right at the repetition rule.

**Comment by IcedQuinn** [comment]
> Im not sure what you mean here, you can customize the repetition limit in the Edit event screen. It is right at the repetition rule.

It doesn't commit the change when setting it to stop recurring on a certain date. It's like it closes the window without actually saving it.

**Comment by tibbi** [comment]
use the checkbox at the top menu to save the changes
