### ISSUE TITLE
Wrong language code

### ISSUE THREAD

**Issue by FTno** [SimpleMobileTools/Simple-Calendar#1585]
The norwegian language code was recently changed from 'nb' to 'no' (values-nb to values-no folder).
The code should be 'nb' and not 'no', so the folder name should be 'values-nb' or alternatively 'values-nb-rNO'.
(The app displays the english source strings when 'no' is used)

Exactly the same issue also applies to Simple Commons.

**Comment by tibbi** [comment]
Google Play uses "no" and also translations via https://weblate.org/ use "no". They complained about an error if "nb" was used. Guess Ill keep an eye on it.

**Comment by Aga-C** [comment]
Weblate uses nb_NO for Norwegian (e.g. look at this URL which contains all Norwegian localizations: <https://hosted.weblate.org/languages/nb_NO/>). Also, nb_NO is a standard locale name for this language, please check these:
- https://stackoverflow.com/questions/7973023/what-is-the-list-of-supported-languages-locales-on-android/7989085#7989085
- https://www.localeplanet.com/icu/nb-NO/index.html

**Comment by FTno** [comment]
Other applications like OsmAnd (https://github.com/osmandapp/OsmAnd/tree/master/OsmAnd/res/values-nb - https://hosted.weblate.org/projects/osmand/main/nb_NO/),
Trail Sense (https://github.com/kylecorry31/Trail-Sense/tree/main/app/src/main/res/values-nb-rNO - https://hosted.weblate.org/projects/trail-sense/trail-sense-android/nb_NO/) and
OpenTracks (https://github.com/OpenTracksApp/OpenTracks/tree/main/src/main/res/values-nb - https://weblate.bubu1.eu/projects/OpenTracks/opentracks/nb_NO/)
use Weblate with 'nb'.

**Comment by tibbi** [comment]
can you try Simple App Launcher from https://play.google.com/store/apps/details?id=com.simplemobiletools.applauncher ? That seems to use nb-rNO. Check if the app specific strings are good, not those reused by all apps

**Comment by FTno** [comment]
It displayed some strings in norwegian as did Simple Contacts which also use nb-rNO. So this works.

**Comment by tibbi** [comment]
alright, will change it to nb-rNO everywhere then, hope it will work ;)
