### ISSUE TITLE
Massive ErrorS in UK Calendar

### ISSUE THREAD

**Issue by faxotherapy** [SimpleMobileTools/Simple-Calendar#1587]
Hello,
Good Friday for UK is 15 April on Friday only and NOT on 2 April, Saturday. Good Friday is also shown for 2 dates: 2 April and 15 April. It should not be shown twice and surely not on 2 April.

Issue 2: Easter is 18 April only and not on 2 April nor 5 April as shown on calendar…

So, the app is SimplyNotUsable if relying on those provided holiday's dates to organise trips around these dates. SimplyTooBad.

**Comment by tibbi** [comment]
what app version are you using?

**Comment by faxotherapy** [comment]
6.16.2

**Comment by Wintandre** [comment]
Looks like Good Friday and Easter were set to annual repeating events from 2021. I have fixed these and others and have created Pull Request #1676.
