### ISSUE TITLE
overlapp issue

### ISSUE THREAD

**Issue by ZhuSniffsTheRose** [SimpleMobileTools/Simple-Calendar#1588]
When adding several events with the following overlapping times, they are not ordered sequentially but overlapped.
start1: 2021-12-23 07:00
end1: 2021-12-23 08:00

start2: 2021-12-23 07:00
end2: 2021-12-23 08:45

start3: 2021-12-23 08:00
end3: 2021-12-23 08:45

<img width="1781" alt="Pasted Graphic 12" src="https://user-images.githubusercontent.com/21290038/147311706-294bd5bd-dbcd-43bf-9dc9-859898fec1c4.png">

**Comment by tibbi** [comment]
what app version are you using?

**Comment by ZhuSniffsTheRose** [comment]
the latest version

**Comment by ZhuSniffsTheRose** [comment]
it is easy to reproduce and create tasks using the following times:

start1: 2021-12-23 07:00
end1: 2021-12-23 08:00

start2: 2021-12-23 07:00
end2: 2021-12-23 08:45

start3: 2021-12-23 08:00
end3: 2021-12-23 08:45

**Comment by tibbi** [comment]
which latest? I need the number from the bottom of the About page

**Comment by ZhuSniffsTheRose** [comment]
![image](https://user-images.githubusercontent.com/21290038/147348494-d13344f1-770d-4892-a514-9d783d4f3934.png)

**Comment by GithubContributor832** [comment]
Thanks for reporting this as I have the same issue.

**Comment by tibbi** [comment]
this has been fixed in 6.17.3, some more improvements will be added in 6.17.4
