### ISSUE TITLE
value of PREFILLED_WEEKS

### ISSUE THREAD

**Issue by ZhuSniffsTheRose** [SimpleMobileTools/Simple-Calendar#1589]
Could weekly view support infinity scrolliing? 

current  value of PREFILLED_WEEKS is 151.
![image](https://user-images.githubusercontent.com/21290038/147326327-a4ddcdca-f2d7-4433-89cb-b8c652ab4d3e.png)

**Comment by tibbi** [comment]
I dont know how to make infinite scrolling without it being too hacky, this should be perfectly enough
