### ISSUE TITLE
[Feature Request] Repeat/recurring event option

### ISSUE THREAD

**Issue by picklecat** [SimpleMobileTools/Simple-Calendar#16]
There are various types of events that people might want to have recur at a given interval (weekly, bi-weekly, monthly, quarterly, yearly), such as birthdays, bill pay reminders, etc.

On the edit event screen this could be added after the reminder option.

**Comment by tibbi** [comment]
added daily, weekly, monthly, yearly recurring to 1.21. It will most likely get more advanced, but its good enough for the beginning.

**Comment by picklecat** [comment]
Works as expected. Cheers! Many thanks.

**Comment by evitalis** [comment]
Would it be possible to add at least a bi-weekly option as well?

**Comment by tibbi** [comment]
yes Ill add it, bi-weekly repetition is one of the simpler ones

**Comment by tibbi** [comment]
added biweekly repetition to 1.25

**Comment by nopeppermint** [comment]
I am using v1.27 and there is no yearly repetition :-(

**Comment by tibbi** [comment]
O.o there should be. Anyway please update your app, the latest one is 1.38 already.

**Comment by nopeppermint** [comment]
even if your code contains the yearly option
 app/src/main/kotlin/com/simplemobiletools/calendar/activities/EventActivity.kt 
`    private fun setupRepetition() {
        event_repetition.setSelection(
                when (mEvent.repeatInterval) {
                    DAY -> 1
                    WEEK -> 2
                    BIWEEK -> 3
                    MONTH -> 4
                    YEAR -> 5
                    else -> 0
                }
        )
}`

I just have the options:
  "none"
  "daily"
"weekly"
"monthly"

**Comment by nopeppermint** [comment]
> latest one is 1.38 already.
I would like to but F-Droid has still apk 1.37 ..
https://f-droid.org/repository/browse/?fdid=com.simplemobiletools.calendar

**Comment by tibbi** [comment]
aha you mean 1.37 then, not 1.27. I dont see any reason why the biweekly and yearly repetition wouldnt be shown, try reinstalling :)

**Comment by nopeppermint** [comment]
maybe it's a translation bug, where your app gets the language from? There is no way to change the language?

**Comment by tibbi** [comment]
values are taken from https://github.com/SimpleMobileTools/Simple-Calendar/blob/master/app/src/main/res/values/array.xml , there cannot be a missing translation. Try scrolling the list, maybe yearly just didnt fit in there

**Comment by nopeppermint** [comment]
I found the problem, it was just 20 cm before the screen ;-)
I was a scaling problem as Android Apps are somehow scaled not perfect on a Blackberry Q5 ;-)

**Comment by tibbi** [comment]
more advanced monthly repetition rules like "Last day of the month" or "Third Monday" will come in the next version.

**Comment by bjchau** [comment]
Can you have it repeat on specific days?

**Comment by tibbi** [comment]
You mean weekdays like Monday, Tuesday etc? You can select specific days if you choose the Weekly repetition. Initially it was under Daily repetition, but Ive checked some other apps and all had it under the weekly one, so I put it there too.

**Comment by newsgrep** [comment]
Would be great if you could add something like repeat every 1. and 3. Friday of the month.

**Comment by tibbi** [comment]
that is already a too advanced option, dont really expect it anytime soon

**Comment by dumblob** [comment]
@newsgrep @tibbi does caldav support multiple repetitions? If so, then the easiest step towards more advanced repetitions would be to add "Add another repetition" button just like there is "Add another reminder".
