### ISSUE TITLE
Unable to import .ics files

### ISSUE THREAD

**Issue by oldschool001** [SimpleMobileTools/Simple-Calendar#1604]
Of late I've had issues importing .ics files. Initially, it wasn't correcting for different time zones, just using the time from the zone in which invite was sent. Now, it says this, "importing... no new items have been found." Nothing is imported. I've tried closing the app and reopening and rebooting. I'm using an updated version of grapheneOS. All permissions are enabled to do this as far as I know... It was working fine. Any ideas?

**Comment by tibbi** [comment]
havent you just filtered out some event type? Check the top Menu -> Filter

**Comment by oldschool001** [comment]
It's not a filter, but I just noted that I could add an .ics file from another sender. I reverified I could not on the original sender. Seems to be linked to the sender. So, I then took the same problematic .ics file and tried importing it into my computer's calendar, which it did without problem. Odd.
