### ISSUE TITLE
Colors of different calendars not stored properly

### ISSUE THREAD

**Issue by erazer1** [SimpleMobileTools/Simple-Calendar#1620]
Hello!

I am using Simple Calendar on a OnePlus Nord phone. I try to change the colors of the different calendars using Settings->General->Manage event types.
I use different colors to quickly see which calendar an event belongs to.
After selecting the different colors and escaping the settings view the colors in the calendar view seem to be correct.
However, after i minimize the application and reopen it again the default colors are restored.
It seems to me that the calendar color-settings of the android application are not correctly serialized/deserialized upon closing/opening the application?
If it helps I could also capture debug output.

Regards, erazer

**Comment by tibbi** [comment]
What serialization? It is totally unrelated. Is that event type stored locally only or CalDAV synced? What app version are you using?

**Comment by tibbi** [comment]
that is unrelated to pausing and resuming. If you use DAVx5, for each individual account, DAVx5 allows you to change the setting for "Manage calendar colors" from (1) 'Calendar colors are reset at each sync' to (2) 'Calendar colors can be set by other apps'. You have to use the second option now.

**Comment by erazer1** [comment]
Thank you for the help!
This has fixed the problem.
Regards, erazer
