### ISSUE TITLE
Widget to the future

### ISSUE THREAD

**Issue by Henry78** [SimpleMobileTools/Simple-Calendar#1621]
When opening calendar from it's widget, itbtakes me to the Jan 1st of year YYYYMMDD, so clicking on in today (Jan 23, 2022), opens the calendar focused on Jan 1, 20220123.

![Screenshot_2022-01-23-11-15-54-04_0b56eaa842d517ef6af8336822f6ad77__01.jpg](https://user-images.githubusercontent.com/1314735/150673911-4f0c6dc8-ee69-46ac-a937-fc37ac96579f.jpg)

**Comment by tibbi** [comment]
it has been solved already, will be fixed in the next app version released soon
