### ISSUE TITLE
Entries automatically deleted after some months

### ISSUE THREAD

**Issue by sandoxy** [SimpleMobileTools/Simple-Calendar#1631]
Thank you for this great app!

I use this calender with nextcloud synchrinisation. Today I wanted to see a former entry and recognized, that there are no enrties older than september 2021. Is this issue related to this cakender ir to nextcloud?

**Comment by tibbi** [comment]
It is NextCloud not syncing old past events, try looking somewhere in their settings if it cannot be changed. Nothing we can do about it on our side.
