### ISSUE TITLE
Incorrect date formatting for non-english locales

### ISSUE THREAD

**Issue by worstje** [SimpleMobileTools/Simple-Calendar#1632]
I started using Simple Calendar Pro yesterday, and it is a nice app except that the localization for dates and times is abysmal. Sure, it has translations.. but when the date formatting completely ignores everything about how the language works and just applies English formatting rules, it makes for a very inconvenient experience. (And it is particularly grating since I know that every programming language since the dawn of time has cultures and format strings that figure that stuff out without the app having to worry about it!)

My language (Dutch) does not do the entire 'month date year' format. We format 'date month year'. When we include the day, it is written as 'day date month year'; none of this weird '(bracketed day)' notation behind it.

Example screenshots of the widget on my home screen(because it is an easier comparison with another widget that does it better):

# Broken Dutch   (compare with weather widget directly beneath for proper formatting, although that one abbreviates the month)

![Screenshot_20220207-074152_Quickstep](https://user-images.githubusercontent.com/399950/152738589-24cf37af-dedb-4cbb-89f0-70d6502e14e2.png)

# 'Correct' English

![Screenshot_20220207-074408_Quickstep](https://user-images.githubusercontent.com/399950/152738580-ad4b1d3b-5753-47cd-96b9-9ede9eff1904.png)

Note 1: You can also see how the month and 'date day' headers continues to stay in dutch even after I forced english in the app...

Note 2: The 'date day' format used for appointments isn't a proper translation either, but I can understand wanting to have the number on the left for usability. Perhaps give people a knob to tweak for that to appease their preferences?

Note 3: Similar broken formatting is everywhere in the app; I just don't see a purpose in screenshotting every single instance.

(On a sidenote, I'd love to have way more knobs to tweak about the widget; I don't care at all about the top row with current day and icons, and the full uppercase month as a heading underneath also looks awkward as hell! I just want to see my upcoming appointments listed, but all of those warts are things that don't belong in this issue...)

**Comment by Aga-C** [comment]
This issue is already reported here: https://github.com/SimpleMobileTools/Simple-Calendar/issues/1055.

**Comment by worstje** [comment]
Apologies; I swear I checked to see if it had already been reported. I must have used the wrong terms when searching.
