### ISSUE TITLE
drag and drop events

### ISSUE THREAD

**Issue by zikobad** [SimpleMobileTools/Simple-Calendar#165]
Add drag and drop events to modify date and time in the weekly view.

**Comment by nivritgupta** [comment]
@tibbi  did this feature available  ?

**Comment by tibbi** [comment]
not yet

**Comment by nivritgupta** [comment]
@tibbi  I am able to implement the drag and drop feature in this calendar (please check my attached video) , but I need some help  , how can I get the  time while trying to drag the event just like in this screenshot  .


![Screen Shot 2019-04-02 at 6 07 28 PM](https://user-images.githubusercontent.com/1904874/55402963-4e4fdc00-5572-11e9-9bd4-587af197bd62.png)

https://www.dropbox.com/s/znz2nq0926zdpjn/Record_2019-04-01-22-18-54.mp4?dl=0

**Comment by tibbi** [comment]
well the toast message contains the timestamp, no? You can use some function in the Formatter for converting that to the time

**Comment by nivritgupta** [comment]
toast message contain  and  picked  the previous event timestamp , I  can convert the time but  the real questions is how can I get the time when trying to drag the events .

**Comment by tibbi** [comment]
Im not sure what you mean. You want the start time of the dragged event, or what?

**Comment by nivritgupta** [comment]
@tibbi  We need to get time stamp from grids y position while we dragging the event

for example:  view.setOnDragListener{v:View,event:DragEvent ->
        when (event.action) {
            DragEvent.ACTION_DRAG_ENTERED->{ val hour = (event.y / mRowHeight).toInt()
                val timestamp = mWeekTimestamp + index  DAY_SECONDS + hour  60 * 60
            }

**Comment by tibbi** [comment]
well Im not sure now from the top of my head, I wasnt working that feature yet

**Comment by mjray** [comment]
@nivritgupta is your code available and does it work on the current head? (or at least as much as it ever did)

This would be a really useful feature not in any of the other replacements I've tried.

**Comment by sangeetaggomes** [comment]
@nivritgupta It would be great if you could post your code. Which will help  us to achieve drag drop functionality. Also if possible we can also add our inputs. Thanks in advance

**Comment by petrarca-arezzo** [comment]
What a pity this feature is not moving ahead right now. It's one of the main missing features in my viewpoint. I keep fingers crossed @nivritgupta will reply soon.

**Comment by tibbi** [comment]
will be added in 6.15.2
