### ISSUE TITLE
Select default view on startup

### ISSUE THREAD

**Issue by MarZagh** [SimpleMobileTools/Simple-Calendar#1661]
Hi,

I really don't use much the daily view and wondered if it's possible to set a default view showed at startup.
I could not found anything in the settings so I thought this would be a great feature to request :)

Kind Regards
Mario

**Comment by tibbi** [comment]
The view you selected as the last one will be used by default at launching the app.

**Comment by SamuXzX** [comment]
Excusme but: are you sure?
It seems it does work when opening the app from its icon, but when opening it through the action of this widget it doesn't. I think the widget uses some sort of standard call for the calendar in Android instead of specifically

**Comment by tibbi** [comment]
this issue isnt about widgets, they work differently

**Comment by SamuXzX** [comment]
> this issue isnt about widgets, they work differently

Should I open an issue specifically to talk about default views when opening from widgets?

**Comment by tibbi** [comment]
no, they work as expected now. Some views that you click specify which view should be open.

**Comment by SamuXzX** [comment]
I understand. Then, how can I make so that when I tap on such widget the monthly view opens? Given that the widget itself shows my day/week events, it's pretty useless that it opens the daily view again.
Is there some selection that I haven't seen in the app's options?

**Comment by tibbi** [comment]
you cannot open the monthly one directly from the day/week. Just open the day/week and pick the monthly view in the app, if thats what you want.

**Comment by SamuXzX** [comment]
But I'm not talking about the widget included in this app. I'm tapping on a different widget, that opens the default calendar. But as you can see it opens your calendar app only in day view, completely bypassing the fact that Simple Calendar remembers the last view used.

**Comment by tibbi** [comment]
sure, because some widgets specifically request a view that should be open

**Comment by SamuXzX** [comment]
I fear that's not the case: I'm trying different calendar apps and they all remember the last view selected. Here two examples:

https://user-images.githubusercontent.com/30182251/160651336-4c61702f-15cd-4520-ad61-590f5d289dd7.mp4

Is the widget requesting a specific view at all? Unless Simple Calendar is the only app correctly interpreting the request from the widget. Is this the case?

**Comment by tibbi** [comment]
hard to say from this

**Comment by SamuXzX** [comment]
I'll talk to the developer and let you know.

**Comment by SamuXzX** [comment]
So it seems that yes, the widget is requesting a specific time, but no: it isn't requesting a specific "view":
![immagine](https://user-images.githubusercontent.com/30182251/161705893-84a1ba56-81bc-45ba-bb1c-ad08c759556e.png)

![immagine](https://user-images.githubusercontent.com/30182251/161705956-0121d2e2-c7f6-49b9-a607-56a93e67bc55.png)

This explains why with other calendar apps open the default view: they remember the last view used and answer to the widget call showing the right date in the default view.
It seems to me that Simple Calendar always answer a call for a specific time with the "day view".
Could it be possible to tell to Simple Calendar to open the requested day in the last view used, like with other calendar apps? It would add an useful customization and lighten the workflow of some of us.
