### ISSUE TITLE
Crash at switching to weekly view

### ISSUE THREAD

**Issue by uli-on** [SimpleMobileTools/Simple-Calendar#1663]
Simple Calendar v6.17.3 crashed when I activated the weekly view. But worse, it now crashes each time I start the app, rendering Simple Calendar unusable as I can't even try to change views.

The Scoop app (available from F-Droid) caught the following

```
FATAL EXCEPTION: main
Process: com.simplemobiletools.calendar.pro, PID: 12269
java.lang.NoClassDefFoundError: u3.f0
	at u3.p0.e3(SourceFile:31)
	at u3.p0.G3(SourceFile:7)
	at u3.p0.c2(SourceFile)
	at u3.l0.run(SourceFile)
	at android.os.Handler.handleCallback(Handler.java:746)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

Technical data:
Android 6.0.1 (with GMS upd. to 21.18.16, cn=M sdk=23)
Webview 98.0.4758.87
Motorola Moto G4
device not rooted

**Comment by tibbi** [comment]
try creating the monthly widget and use it to launch the app to some other view

**Comment by uli-on** [comment]
> try creating the monthly widget and use it to launch the app to some other view
I can access the app again. Thanks! :)

Is the above log information enough for you to find a fix or would you need
a complete log file?

**Comment by tibbi** [comment]
not really, there is nothing useful in it. I dont think you can create a readable log file though.

**Comment by uli-on** [comment]
> I dont think you can create a readable log file though.

Depends on your definition of readable. I'd certainly not post one, I'd rather email it ***@***.***…?)  

Or is Android 6 too insignificant to support?

**Comment by tibbi** [comment]
you can send it at hello@simplemobiletools.com. But ye, Android 6 is on the edge of being no longer supported by us

**Comment by tibbi** [comment]
should be solved already
