### ISSUE TITLE
Time picker not displayed in landscape mode

### ISSUE THREAD

**Issue by smichel17** [SimpleMobileTools/Simple-Calendar#167]
See https://github.com/raatmarien/red-moon/issues/143 for details.

Since this issue affects every common solution I found when searching for time picker preferences, and they are rather common, I'm planning on pulling Red Moon's time picker preference out into a library when I fix this; I'll let you know when that's done.

**Comment by sachincool** [comment]
I'll like to try this issue out. Can i work on this ?

**Comment by trubitsyn** [comment]
I don't think it's still reproducible, can pick time well in landscape mode. Am I doing something wrong?
cc @smichel17 @tibbi 
![screenshot_20180122-004642](https://user-images.githubusercontent.com/27303196/35199395-043ee8c4-ff0e-11e7-87a1-f6c3e2ce3bce.png)

**Comment by tibbi** [comment]
not sure, I never really cared much about landscape mode, its just not worth it. The date and timepickers show fine on my Android 6, maybe it glitches on some devices only

**Comment by smichel17** [comment]
I can confirm this is no longer reproducible.
