### ISSUE TITLE
Tasks Doesn't sync right with Evolution

### ISSUE THREAD

**Issue by sibeliusg** [SimpleMobileTools/Simple-Calendar#1675]
Hi! I'm using Posteo.de as my CalDav-Server. When Syncing the server (with DavX5 on Android), the tasks are uploaded from Simple-Calendar as well as from Evolution (on Manjaro Linux). But for some reason tasks created with one app, don't appear in the other one. So when I create a task in Evolution, it doesn't appear in Simple-Calendar and vice versa. If I can help, with more information, let me know. I just don't know where to look for it right now.

**Comment by tibbi** [comment]
tasks have no CalDAV support yet

**Comment by tibbi** [comment]
actually Ill close it as a child of #1742
