### ISSUE TITLE
Recurring events in a non-DST timezone do not adjust correctly

### ISSUE THREAD

**Issue by zootboy** [SimpleMobileTools/Simple-Calendar#1680]
I have a recurring event scheduled in Honolulu time (HST), while my phone is in Pacific time. HST does not adjust for daylight saving time, so these events should adjust relative to my local time when DST becomes active. The events do not adjust, however, staying in their time as if DST were not active. This happens in all views of the calendar as well as the widget.

App version: 6.17.4 (F-droid)
Android version: LineageOS 17.1 (Android 10)

**Comment by sparagi** [comment]
This may be the same issue as #1973 (which has the most detailed information) and/or #1220.
