### ISSUE TITLE
Bug: Editing an event created by evolution kills custum a "run a program" reminders 

### ISSUE THREAD

**Issue by mstyp** [SimpleMobileTools/Simple-Calendar#1686]
Around half of my calendar events have associated bash scripts set to trigger when calendar event fires, very useful for automation.

But when the event is synced over via caldav, or even if just uploading an .isc file, simple calendar *overrides the alarm and kills the automation script*. Thunderbird and nextcloud do not do this, so its not like evolution is doing something crazy unexpected.

Here is what evoltion does to an isc file when it wants to run a script:

```
BEGIN:VALARM
X-EVOLUTION-ALARM-UID:A_BIG_LONG_STRING
TRIGGER;RELATED=START:PT0S
ACTION:PROCEDURE
ATTACH:/home/user/wakeup
DESCRIPTION:radio
END:VALARM
```

I imagine something about the parser that looks at isc or caldav files is killing those lines.

**Comment by tibbi** [comment]
that is way too advanced, dont expect having that

**Comment by dumblob** [comment]
@mstyp we are considering forking Simple Calendar where such PRs would be accepted - see https://github.com/SimpleMobileTools/Simple-Calendar/issues/1771#issuecomment-1176585779 and feel free to express your opinion. Thanks!
