### ISSUE TITLE
Touch animation in pop-up menu

### ISSUE THREAD

**Issue by rhynec** [SimpleMobileTools/Simple-Calendar#1687]
The options on the three-dot pop-menu don't seem to have any touch feedback (highlighting when pressing them like in the settings menu). This is also the case with Simple Gallery. On the other hand, Simple Music Player does show the highlighting animation on the pop-up menu. But maybe it's a bug on my phone?

I use a Moto G Fast running Android 11, with Simple Calendar version 6.17.4 Pro from F-Droid.

**Comment by tibbi** [comment]
the menu has been redesigned since then
