### ISSUE TITLE
Accent color of black and white theme replaces primary color

### ISSUE THREAD

**Issue by emmatebibyte** [SimpleMobileTools/Simple-Calendar#1695]
I want to be able to make all of the app, including the header bar, black, while also having colored icons using the primary color. This is not happening on this and a few other Simple Mobile apps. Instead, the accent color is also being used for the header in the app.

**Comment by tibbi** [comment]
it has been fixed already, just needs an app update

**Comment by emmatebibyte** [comment]
Understood, thank you
