### ISSUE TITLE
Coloured headerbar

### ISSUE THREAD

**Issue by victormihalache** [SimpleMobileTools/Simple-Calendar#1696]
The black headerbar is the expected result, the red one is after the recent update.

![Screenshot_20220419-195949_Calendar](https://user-images.githubusercontent.com/82441538/164066855-ddd5941d-e4b0-4eb8-a215-04342e3bdd82.jpg)
![Screenshot_20220419-195954_Calendar](https://user-images.githubusercontent.com/82441538/164066860-9d1e4bb8-3177-41cb-8982-383f8a445382.jpg)

It temporarely shows black when I click some options.

**Comment by tibbi** [comment]
it has been fixed already, just need an app update
