### ISSUE TITLE
Changed recurrence events are not shown

### ISSUE THREAD

**Issue by ccplatz** [SimpleMobileTools/Simple-Calendar#1698]
Hi guys,
when I change the starting time in Nextcloud or Etar of a recurrence event it completly disappears from simple calendar. In NC or Etar it is still there, of course in the changed version. When I change it in SC it works as expected.

I use version 6.18.1 Pro.

Thanks for help.

**Comment by tibbi** [comment]
can you reproduce it reliably?

**Comment by ccplatz** [comment]
Yep, I tried it with different apps on different series. They always disappear in SC and not in the others. I also deleted all data.

**Comment by tibbi** [comment]
please tell exact steps for reproducing, just to ensure we get it right

**Comment by ccplatz** [comment]
* create an recurring event in any client app
* change the starting time of one item in any client app, but not in SC
* reload the calendars in SC
* the changed item disappears

**Comment by aurisnoctis** [comment]
Thanks, it is fixed for me with Simple Calendar version `6.22.0 Pro` available on F-Droid.

All missing changed single items of calendar series magically reappeared now 🙌. I am using DAVx5 and Nextcloud (as already tested by the provider of the bug fix pull request).

Thank you very much for the calendar and the bug fix. 👍
