### ISSUE TITLE
Export should have past events selected as default and all categoreies selected

### ISSUE THREAD

**Issue by hexarch** [SimpleMobileTools/Simple-Calendar#1699]
The bug I reported #1662 https://github.com/SimpleMobileTools/Simple-Calendar/issues/1662 is not fixed yet so today I decided to update to the latest version 6.18.1 Pro via f-droid.
Since the upgrade was not working I decided to uninstall and install again, so I did a backup first. I did not noticed the option "Export past events too" was NOT selected. And it only picks three categories.

I cannot understand why. This should be the default "export past events" and all categories should be selected to export and there is no option to select more than 3 categories. Why?

It was my mistake I get that, but now I've lost all my calendar events. 

I'm sad to stop using this calendar but the other critical bug was already bad because it does not allow me to view correctly the whole week, but now this.

**Comment by tibbi** [comment]
it is not a bug. As you mentioned, you just didnt notice it.
