### ISSUE TITLE
Month title always says "Llll" since upgrade to v1.16

### ISSUE THREAD

**Issue by memeticks** [SimpleMobileTools/Simple-Calendar#17]
Since I upgraded to v1.16 the month title always says "Llll" in the app and in the widget. Every month has the same title. I tried downgrading, re-upgrading, uninstalling, re-installing, wiping all the apps stored settings then reinstalling, reinstalling older versions... I tried everything I could think of, but no matter what I do, every month is now called "Llll" and this wonderful simple lil app is now unusable for me. I've got a motorola droid razr m running non stock and rooted android v4.1.2. I did not see this bug at all before the upgrade to v1.16, but since the upgrade all versions show the same issue.
Any and all help / ideas would be very gratefully received, thanks...

**Comment by memeticks** [comment]
![screenshot_2016-08-11-16-46-09 png](https://cloud.githubusercontent.com/assets/20962877/17579037/abbd9bce-5fe4-11e6-8d8b-689badfb3eb9.png)
![screenshot_2016-08-11-16-46-38 png](https://cloud.githubusercontent.com/assets/20962877/17579038/ad0869a0-5fe4-11e6-9f76-b43be79f03d9.png)

**Comment by picklecat** [comment]
Alternative info: This was not my experience upgrading from v1.15 to 1.16 on CM13.1 (Nightly) Android 6.0.1 (US-English). I upgraded to v1.16 via FDroid. The month titles remain accurate.

**Comment by memeticks** [comment]
I also upgraded using fdroid. I guess this is something specific to my ROM. I was hoping someone would have an idea how to fix it...some file or folder that needs to be deleted or something.

**Comment by tibbi** [comment]
try changing your system language what will it do

**Comment by memeticks** [comment]
I also upgraded using fdroid. I guess this is something specific to my ROM. I was hoping someone would have an idea how to fix it...some file or folder that needs to be deleted or something.

**Comment by memeticks** [comment]
I tried changing the language, uninstalling, reinstalling, wiping settings, uninstall, change language again... several times. But I still get the same thing every time. I tried looking through the file structure for any files which simp calandar may store somewhere as I think it has written this corrupt data somewhere and every time i reinstall it reads the corrupt data. I have another calendar on my home screen and that has the month just fine. Is there any files which simple calendar writes somewhere on the phone which are not obviously named simple calendar or simple mobile tools? Perhaps if i can delete them I can get it back to the 'virgin' state as it was in the beginning?

**Comment by tibbi** [comment]
some things were changed related to translations, probably that broke it. I will handle it in a different way and rewrite it soonish.

**Comment by tibbi** [comment]
retest with 1.17 please

**Comment by memeticks** [comment]
Build 1.17 fixed the bug for me, all months displaying correctly, you can close this or whatever.
Thanks for your help with this.
