### ISSUE TITLE
Editing single instances of recurring events not possible

### ISSUE THREAD

**Issue by daxcore** [SimpleMobileTools/Simple-Calendar#1707]
In Etar I get a widget like that 
![Screenshot_20220504-080807_1](https://user-images.githubusercontent.com/1872366/166634713-25a389c2-7c63-4a1c-9b01-3626d0b12f9d.jpg)
* just change the current event
* change all events of series
* change this event and upcoming 

I do not see something like that in this app, so I can just change the series properties, but not a single instance.

**Comment by tibbi** [comment]
what app version are you using? We have it too.

**Comment by daxcore** [comment]
6.18.1 from fdroid.

**Comment by daxcore** [comment]
I got it. this widget will not shown on entering the event, it will show on storing it if changes are done. my fault. sorry & thanks :-)
