### ISSUE TITLE
seperate default reminder reminder for all-day events

### ISSUE THREAD

**Issue by rms-joe** [SimpleMobileTools/Simple-Calendar#1710]
[feature request]

it would be nice to have a seperate default reminder for all day events.

use case:
normally i would like to be reminded of all day events the day before in the evening, so i get everything ready.

so for me personally two defaults are handy:
normal events: 30 minutes before
all day events: 5 hours before

//btw, really love the changes and features you added to the calendar. keep up the great work. highly appreciated!

**Comment by tibbi** [comment]
that isnt really on the roadmap, might be added as a part of Templates

**Comment by rms-joe** [comment]
that's what i meant 👍
