### ISSUE TITLE
Overlay error message java.lang.SecurityException

### ISSUE THREAD

**Issue by michaelspunkt** [SimpleMobileTools/Simple-Calendar#1714]
I repeatedly receive an overlay error or warning although the app is not on screen (the message appears with the simple-calendar icon). It obviously appears when updating/syncing calendars (I have _caldav sync with Nextcloud Hub II [23]_ enabled).
It says
`Es ist ein Fehler aufgetreten: java.lang.SecurityException: Caller com...`
I cannot tap it to expand the whole message nor copy to clipboard and I cannot find any error logs in the app.
Though everything seems to work normally this is a bit annoying. Can you help me with that? Which further information do you need?

_SGS7, LineageOS 19.1 with microG - build from 28.04.22, no Google stuff, app Form F-Droid (v 6.18.1)._

**Comment by tibbi** [comment]
try reenabling CalDAV sync in the app settings

**Comment by michaelspunkt** [comment]
That was it! THX
