### ISSUE TITLE
Cannot delete "regular event" event type

### ISSUE THREAD

**Issue by zethra** [SimpleMobileTools/Simple-Calendar#1723]
Even after changing the default event type, I get an error "Default event type cannot be deleted" even after changing the default event type.

**Comment by tibbi** [comment]
that is the expected. If you want to use it, just rename it.

**Comment by zethra** [comment]
Also I am able to delete the default event type if it's something other than "Regular event". The above mentioned error message would imply that shouldn't be allowed.
