### ISSUE TITLE
Customize event colors of imported calendars

### ISSUE THREAD

**Issue by Dunrar** [SimpleMobileTools/Simple-Calendar#1743]
A thing missing for me is the ability to customize event colors for imported calendars. Not super important, as one can work around this by using multiple calendars for different event types, but still worth considering. Thanks.

**Comment by tibbi** [comment]
you can already customize any colors in the app Settings -> Manage event types

**Comment by Dunrar** [comment]
> you can already customize any colors in the app Settings -> Manage event types

Thank you, but that does not really achieve what I want. All events of an imported CalDav Calendar share the same color, that of the event type which is auto-created for every imported calendar. What I would like is to be able to give different colors to events of the same imported calendar (multiple event types per imported calendar).

**Comment by tibbi** [comment]
customizing colors on a per event basis isnt possible yet, but it has been reported already

**Comment by IgorPolyakov** [comment]
Hi, is there any news on this feature?
