### ISSUE TITLE
[Feature request] Add an option to hide calendars names at the bottom of the screen

### ISSUE THREAD

**Issue by brunetton** [SimpleMobileTools/Simple-Calendar#1745]
Hi

My use of this app is quite always the same: I'm using quite exclusively the month view. I click on some days to view details.
But I often do missclicks and hide a calendar while I wanted to open the day view for a day that is at the bottom of the screen.

I never use the show/hide calendars feature, so I'd like to have an option to hide it (if I want to modify the displayed calendars I can go to preferences and manage them anyway).

Thanks

**Comment by tibbi** [comment]
you can already remove it by disabling all items in "Manage quick filter event types" at the app setings

**Comment by brunetton** [comment]
> you can already remove it by disabling all items in "Manage quick filter event types" at the app setings

Oh this is great ! Sorry for the noise then, I was actually wondering what is the utility of this option
