### ISSUE TITLE
Radical changes to the UX and UI inspired by Blackberry 10 (BB10) Calendar

### ISSUE THREAD

**Issue by dumblob** [SimpleMobileTools/Simple-Calendar#1749]
I was recently forced to abandon my Blackberry phones and use Android (or iOS) as my daily driver. I struggle a lot - mainly due to really non-smooth calendar experience (most of the time I spend on my phones is in calendar).

Out of all calendars I have tried Simple Calendar is the smoothest! Good job!

I wonder whether you would be willing to make some not so simple changes (few of which could be considered "radical" in the Android UX world I would say) to Simple Calendar.

I already prepared detailed steps and issues with pictures and suggestions. But first I would like to briefly discuss the attitude you (@tibbi and community) would have towards this. Generally most of these suggestions come from the Blackberry 10 Calendar which is truly a gem IMHO.

I am a former dev and know how much effort it is to change stuff - therefore in my unpublished list of detailed suggestions I have tried to come up with the simpliest (programmatically) ways to accomplish 80% of the desired functionality instead of just saying "hey, reimplement Blackberry 10 Calendar from scratch".

What do you think?

**Comment by dumblob** [comment]
Ok, understood.

As an example would an addition of the "day numbers line" (as found in the monthly view) to the daily view (while highlighting the currently selected day) be considered too radical?

Because that is probably the most radical thing I have in my stash :wink:.

**Comment by tibbi** [comment]
yep :(

**Comment by dumblob** [comment]
Ok, I will then proceed only with some tiny suggestions :wink:. Thanks anyway!

Btw. looking forward to the new "offline" smartphone you (and your colleagues or related companies) want to bring to the market! I hope I can buy it and hope it will get major updates for 3 years at minimum (even if they are paid - only security updates should stay unpaid IMHO).
