### ISSUE TITLE
CalDav color does not get updated

### ISSUE THREAD

**Issue by rEnr3n** [SimpleMobileTools/Simple-Calendar#1750]
Version: 6.18.3

My calendars are hosted on nextcloud. I use DAVx5 to get the calendars (Manage calendar colors = disabled, Event color support = enabled). Then I enabled CalDav sync on the calendar app.

Then I changed one of the calendar's color on nextcloud. I updated the calendars in DAVx5 and the color got updated to the new one. When I refresh the CalDav on the calendar app, nothing changes. I tried to wipe the app data and reconfigure it. It's still not using the new color. Issue does not happen when I enable `Manage calendar colors` in DAVx5. Is this a bug?

**Comment by tibbi** [comment]
For each individual account, DAVx5 allows you to change the setting for "Manage calendar colors" from (1) 'Calendar colors are reset at each sync' to (2) 'Calendar colors can be set by other apps'. You have to use the second option.

**Comment by rEnr3n** [comment]
I did use the second option `Calendar colors can be set by other apps`. This was when I had the issue. However I have no issue using the first option `Calendar colors are reset at each sync`.
