### ISSUE TITLE
Delete this and all past occurrences (Request)

### ISSUE THREAD

**Issue by dapgo** [SimpleMobileTools/Simple-Calendar#1756]
I understand the use case of deleting future event and keep the past ones as a register to track.

But other  use case is to delete past events, completed or not, however simplecal doesn't offer this option in dialog whereas other calendar apps have this option (see screenshot).

![example](https://user-images.githubusercontent.com/4981669/175534929-15eaba6a-14a3-4474-b8a2-0164256830f2.png)

**Comment by tibbi** [comment]
just edit the event, that will reset the start date and remove all past occurrences
