### ISSUE TITLE
Bug: view selection dialogue does not reflect the current view

### ISSUE THREAD

**Issue by dumblob** [SimpleMobileTools/Simple-Calendar#1762]
Steps to reproduce:

1. select `Monthly view`
2. touch/select any day - this opens a `Daily view`
3. open the view dialogue and voila - there is `Monthly view` preselected which is false as the current view is actually a `Daily view`

**Comment by tibbi** [comment]
but the default one is still monthly, just dismiss the app after opening a daily view

**Comment by tibbi** [comment]
press Recents button at the bottom navigation bar and swipe it away to kill the app

**Comment by dumblob** [comment]
Thank you for clarification.

Now I am pretty certain this is a misunderstanding. Pardon my ignorance but I still fail to see how closing/killing the Calendar app instance solves the issue.

After killing Calendar you can open it again. Then touch the "9-box matrix" icon in the upper right corner, then select `Monthly view`. Then select an arbitrary day by touching it. It will open the day in a `Daily view`. If you then touch the "9-box matrix" icon in the upper right corner, you will be presented with preselected `Monthly view` which is **wrong** (it shall show `Daily view` because it is in fact in a daily view).

Fortunately touching the wrongly preselected `Monthly view` works - i.e. brings you to `Monthly view`. But if selecting `Daily view` another strange thing happens - the title bar changes from `<- Calendar` to `Calendar`.

I think both strange confusing things are caused by opening the daily view as a child of the monthly view instead of just switching between them. From the UX perspective this is counter-intuitive and shall not happen.

Does this make more sense now?

**Comment by dumblob** [comment]
A friendly ping :wink:.
