### ISSUE TITLE
Improve "Monthly and daily view" to avoid confusion and increase utility

### ISSUE THREAD

**Issue by dumblob** [SimpleMobileTools/Simple-Calendar#1763]
The `Monthly and daily view` has a very high potential in usefulness - especially as a "default view".

In its current form it is though very confusing and brings more issues than it solves due to chaotic orientation through the list. The following could fix this chaos.

1. A day has to always be selected (either the day from another view used a second ago or today if the current month was selected in another view a second ago or the first day of the displayed month otherwise).
2. The event list part shall show only events from the selected day (i.e. retain the current behavior).
3. Swiping left/right on the list part of screen shall switch to the previous/next day.
4. Swiping left/right on the monthly overview part shall switch to the previous/next month (i.e. retain the current behavior).

Without this the user perception is the same as `Simple event list` view which mostly defeats the purpose of existence of the `Monthly and daily view`.

**Comment by tibbi** [comment]
1. already by default no day is selected
2. it already shows the given days events only, if you have a day selected
4. already works like that
So only 3 is valid, will keep an eye on it.

**Comment by dumblob** [comment]
Any progress with (4) which you are "keeping an eye" on?

**Comment by dumblob** [comment]
A friendly ping :wink:.
