### ISSUE TITLE
Wrong default time in case "Next full hour" is on

### ISSUE THREAD

**Issue by dumblob** [SimpleMobileTools/Simple-Calendar#1764]
### Steps to reproduce

1. open "Settings"
2. select "Default start time"
3. set it to "Next full hour"
4. switch to arbitrary view which allows day selection (e.g. "Monthly and daily view")
5. select a different day than today
6. click the big "+" circlic button at the bottom right
7. you will see the time set to "Next full hour" even though it definitely is **not** next full hour as it is another day than today

### Envisioned potential solution

Variant A: The settings dialogue with the 3 options (Current time, Next full hour, Other time) shall have two sections - one for "today" and one for "not today". Both "today" and "not today" would offer the same three options.

Variant B: Make "Next full hour" a non-changeable (hard-coded) default for today and leave all the rest as it is now (i.e. the settings dialogue unchanged, etc.).

Btw. Variant B is what Blackberry 10 does :wink: (actually Blackberry 10 does not use a next full hour but next multiple of 15 minutes IIRC).

**Comment by tibbi** [comment]
the current is the expected behaviour

**Comment by tibbi** [comment]
Not really, changing it isnt planned. If the user sets next full hour, he expects next full hour. No need to complicate things unnecessarily.

**Comment by dumblob** [comment]
I see.

I still have some hopes that UX will get precedence over implementation details (you refer to them as "unnecessarily complicated things") in SimpleMobileTools apps once your user base will rapidly jump thanks to your efforts to bring an exclusively genuinely SimpleMobileTools-based smartphone on the market.

I am fully aware of how daunting this work on mobile apps is and even more in an open source environment where everybody comes with different ideas all the time in an ever-increasing pace.

It is just a great pity that even these tiny things significantly contributing to iron all the sharp edges are considered unnecessary despite them **not** being new nor different ideas but simply just last obstackle-removing observations from heavy calendar every day use.

Let me express one more aspect of my position on this. Namely I would welcome if such "unnecessary" things were actually planned with low-priority behind big important features instead of up-front rejection. Now after rejection I begin to feel like a fork is the only way out of this as PRs tackling these issues would be rejected. But OTOH forking is almost always the worst path forward...

All in all despite me understanding the situation to a certain degree I feel sad about this.

Any insights I am missing?
