### ISSUE TITLE
Indicate when events span multiple days in daily view

### ISSUE THREAD

**Issue by Happosai-san** [SimpleMobileTools/Simple-Calendar#1765]
When viewing an event that spans multiple days in daily view, it isn't clear whether the event starts or ends on the currently-viewed day.

For example: an event starts at 9pm today and ends at 2am tomorrow. Viewing it in daily view for today shows it starting at 9pm and ending at 2am. However, viewing it in daily view for tomorrow also shows it starting at 9pm and finishing at 2am, with no easy way of telling that it actually started at 9pm the day before.

I'm pretty sure it used to include some indication of this.

**Comment by tibbi** [comment]
will be fixed in 6.19.0
