### ISSUE TITLE
Option "Show events spanning across midnight at the top bar" does not work correctly

### ISSUE THREAD

**Issue by dumblob** [SimpleMobileTools/Simple-Calendar#1767]
As described in https://github.com/SimpleMobileTools/Simple-Calendar/issues/1241#issuecomment-1153982721 the option `Show events spanning across midnight at the top bar` does not work as if I **de-select** it, then `all-day` events are still shown at the top:

![Screenshot_20220613-162013](https://user-images.githubusercontent.com/2451044/173375519-f0855b53-bc64-4935-9718-ab2d06fbf376.jpg)

**Comment by tibbi** [comment]
what events are those? I mean start/end dates and times? What app version are you using?

**Comment by dumblob** [comment]
> what events are those? I mean start/end dates and times?

`all-day` set as "All day" (i.e. no start/end times), June 13 - June 18, UTC, No reminder, No repetition, Store locally only, Regular event

`non-all-day` June 13 17:00 - June 17 17:30, Europe/Amsterdam, No reminder, No repetition, Store locally only, Regular event

>What app version are you using?

Version 6.18.3 Pro
