### ISSUE TITLE
Standard Android offline Calendar Storage

### ISSUE THREAD

**Issue by ivan-volnov** [SimpleMobileTools/Simple-Calendar#1772]
Hello. Firstly thanks for the app. It's great.

Can't grant access to calendar events to 3rd party apps.

For instance Etar calendar supports Offline Calendar storage that shareable.

Would you consider moving calendar storage to the internal Android one?

**Comment by tibbi** [comment]
you can already do that by enabling CalDAV sync in the app settings and pick the calendar you want to use

**Comment by ivan-volnov** [comment]
@tibbi Thanks. It works)
