### ISSUE TITLE
[Feature Request] Widget Private mode, Represent events with dots, hide all events

### ISSUE THREAD

**Issue by joelchrono12** [SimpleMobileTools/Simple-Calendar#1776]
I would like a way to show the calendar widget without any events, only showing the numbers.
Another option would be to have it show only colored dots without any content, that's good for privacy and also quite aesthetic
Its also good for screenshots and customization, I have to make my calendar widget too small for it to be clean, since all events are hidden when the height is small.

Thank you! I am sorry if this is a duplicate, I searched but couldn't find something.

**Comment by tibbi** [comment]
I dont really plan adding that

**Comment by dumblob** [comment]
@joelchrono12 we are considering forking Simple Calendar where such PRs could potentially be accepted - see https://github.com/SimpleMobileTools/Simple-Calendar/issues/1771#issuecomment-1176585779 and feel free to express your opinion. Thanks!
