### ISSUE TITLE
"Add contact anniversaries" makes multiple event types on renaming and/or change of language

### ISSUE THREAD

**Issue by lianergoist** [SimpleMobileTools/Simple-Calendar#1778]
If I use the function "Add contact anniversaries" it creates a new event type. In Danish, the default name for this event type is "Mærkedage". If I change that name to something else (via Settings - General - Manage event types - <select event type> - Edit), Simple Calendar first just rename the event type, but soon after it makes a copy of the event type, so there will be two event types with same colour, but with the old (default) and the new (renamed) name. 

Also, if I don't rename anything, and I only have one event type with the default Danish name, and then select "Settings - General - Use English language", it creates a copy of the event type, so I now have two event types with same colour, but with the default Danish and default english name.

**Comment by tibbi** [comment]
related to #1658
