### ISSUE TITLE
Landscape breaks year view

### ISSUE THREAD

**Issue by kTyn9A9Kw3** [SimpleMobileTools/Simple-Calendar#178]
When in landscape the months are cut in half, I think a solution would be to adjust the font size, margins and number of rows according to the rotation mode. For example in landscape can be displayed 3 rows of 4 months while in portrait must be 3 of 4. This can be combined with #179 

![calendar](https://cloud.githubusercontent.com/assets/20364510/26807136/26ef4686-4a44-11e7-8912-0baf766ea268.png)

**Comment by S2606** [comment]
@kTyn9A9Kw3 I would love to contribute but i am facing as issue.On testing in the phone, the landscape mode isnt working at all it seems.Could you help me with this?

**Comment by tibbi** [comment]
landscape is available only on devices with at least 600dp width, which means tablets

**Comment by Progern** [comment]
Testing on ASUS Nexus 7 (Android 5.1.1) landscape mode doesn't work. Sorry for the bad quality image.
![screen shot 2017-08-04 at 11 21 44 am](https://user-images.githubusercontent.com/16916594/28960397-248387ee-7907-11e7-8b42-92cd121840d9.png)

**Comment by tibbi** [comment]
I havent been optimizing any app for tablets, its just currently not worth the time.

**Comment by Progern** [comment]
Wouldn't you mind if I will try to find some solution or workaround?

**Comment by tibbi** [comment]
well if you can find some simple solution just go ahead, Im not sure how should it look like on tablet landscape. Maybe 4 columns and 3 rows will make it look better. You can check some other apps and do it as they generally do. Thanks

**Comment by Progern** [comment]
I have found fast workaround adding some margins and re-designing the way of calculating each day cell size for portrait mode and landscape mode independently.
I guess it looks a lot better now, at least on my tablet and phone.
Will work further with it today and tomorrow and try to find a better solution
![screenshot-1501842389184](https://user-images.githubusercontent.com/16916594/28965255-d203b91e-7918-11e7-9e74-89be8278f25f.jpg)

**Comment by Progern** [comment]
Please, take a look. I tested it on Nexus 7, Nexus 9 and Pixel C (last two were emulators) and I guess it looks not bad. 
![screenshot-1501842389184](https://user-images.githubusercontent.com/16916594/28965976-66283568-791c-11e7-9cc5-62df594ebe33.jpg)
![screen shot 2017-08-04 at 1 42 27 pm](https://user-images.githubusercontent.com/16916594/28965996-72b467ca-791c-11e7-8eb0-537ecebada3e.png)
![screen shot 2017-08-04 at 1 53 09 pm](https://user-images.githubusercontent.com/16916594/28965995-72ae8daa-791c-11e7-9ab4-0bf9ff2e1bde.png)

**Comment by tibbi** [comment]
ye imo it looks great. Find some way of modifying it only for tablet landscapes and we are good to go :) Not sure about tablet portrait, it works fine?

**Comment by Progern** [comment]
I will send you screenshots of what it looks like on three different tablets in portrait and landscape and also on one phone so you can not worry if anything is broken.
Btw, on my phone (big screen size) the landscape was also broken, so should I restrict that changes only for tablets or maybe it's a good idea to test on different screen sizes and keep those changes if they are ok? I can do this testing within 3-4 hours and send you the results :)

**Comment by tibbi** [comment]
For now just handle the tablets, I dont really worry about landscape phones as nobody uses them like that. We can improve those too in the future.

**Comment by Progern** [comment]
Okay, so in that case take a look here
**Nexus 7 device:**
Portrait:
![nexus_7_portrait](https://user-images.githubusercontent.com/16916594/28967244-f06f1e84-7922-11e7-8e4c-b2bd732224ea.jpg)
Landscape:
![nexus_7_landscape](https://user-images.githubusercontent.com/16916594/28967248-f78ecfc0-7922-11e7-850d-b79a4c17de60.jpg)

**Nexus 9 emulator:**
Portrait:
![nexus_9_portrait](https://user-images.githubusercontent.com/16916594/28967278-1acfbb2a-7923-11e7-8aa4-9f6decf055dd.png)
Landscape:
![nexus_9_landscape](https://user-images.githubusercontent.com/16916594/28967281-1fd36fc2-7923-11e7-92ed-2a593ee5921a.png)

**Pixel C emulator:**
Portrait:
![pixel_c_portrait](https://user-images.githubusercontent.com/16916594/28967301-31451b34-7923-11e7-884e-64d8738d51ae.png)
Landscape:
![pixel_c_landscape](https://user-images.githubusercontent.com/16916594/28967306-36975e6c-7923-11e7-99db-94131d11c9e4.png)

Take a look and say your decision. I also changed a bit that circle (current day circle) because it was broken  (it was shifted to left a bit) on both tablets and phones (emualtors and real devices)

**Comment by tibbi** [comment]
You can increase the font size a bit, its too small. In portrait modes, the empty space between columns could be a bit bigger, so its visually clearer. Other than that it looks fine.

**Comment by Progern** [comment]
Do you want to make these changes for tablets separately, yes?

**Comment by tibbi** [comment]
yes, the text size on phones is fine now

**Comment by Progern** [comment]
Okay, so previously text size for days was taken from some Android constant which was 8sp. I have added two constants (in dimens and sw600dp-dimens) which are responsible for text size. Nothing changed on phone (8sp) and text size increased on tablet(12sp)
**Very big screen:**
![screenshot_1501846725](https://user-images.githubusercontent.com/16916594/28968427-92066d42-7928-11e7-97f3-e98996ab280a.png)
![screenshot_1501849234](https://user-images.githubusercontent.com/16916594/28968440-a2dbfe7a-7928-11e7-917d-1086b33a0347.png)

**Plain tablet screen:**
![screenshot-1501848974933](https://user-images.githubusercontent.com/16916594/28968519-fd6c74e6-7928-11e7-913b-a5b1b090faaf.jpg)
![screenshot-1501848965789](https://user-images.githubusercontent.com/16916594/28968523-0388bfa6-7929-11e7-8474-8164a90bb395.jpg)

**Comment by tibbi** [comment]
ye this looks a lot better now
