### ISSUE TITLE
Button "go to today" is missing in list view since the last update

### ISSUE THREAD

**Issue by Npa972** [SimpleMobileTools/Simple-Calendar#1792]
![Capture d’écran_2022-07-28_08-25-06](https://user-images.githubusercontent.com/49346431/181504361-f4da9440-4fea-44fa-96d4-cab86fc8f520.png)
Thanks you

**Comment by Aga-C** [comment]
@tibbi There is  still a minor bug, because when you click "go to today" button, it scrolls correctly, but this button is still visible.
