### ISSUE TITLE
Feature Request : Mark Tasks as completed from calendar widget

### ISSUE THREAD

**Issue by wisdom420** [SimpleMobileTools/Simple-Calendar#1802]
I use the widget for calendar view instead of the app.When I want to mark tasks as completed I have to open the task in the app and then mark it as completed from there.The interface would get much easier if we can do the same from widget using a checkbox.

**Comment by tibbi** [comment]
that isnt really on the roadmap, sadly widgets are very limited elements and they support only a couple views
