### ISSUE TITLE
Support "every weekday" repetition

### ISSUE THREAD

**Issue by mwllgr** [SimpleMobileTools/Simple-Calendar#1807]
Hello,

I'm using Nextcloud as my CalDAV server and created an entry in the Thunderbird calendar starting on Aug 1 which repeats every weekday until the end of April:
![Thunderbird calendar entry](https://user-images.githubusercontent.com/25794895/184477899-e5226a56-5580-4bdc-9068-9ee10f412c12.png)

This way, Thunderbird and the Nextcloud interface only shows the appointment from Monday to Friday, whilst keeping the weekends (Saturday/Sunday) free. Problem is: **Simple Calendar shows the entry too, but ignores the "on weekdays" setting** - thus showing the entry on Saturdays and Sundays too.

Is there a simple client-side fix for this or is it the way repetition is implemented in the app's source code?

**Comment by tibbi** [comment]
you can already select specific weekdays at weekly repetition

**Comment by mwllgr** [comment]
Yes, but shouldn't the app be compatible with the entry that Thunderbird and Nextcloud understands, too? Right now, that's just not the case.
