### ISSUE TITLE
Feature Request: Do Not Disturb on certain events

### ISSUE THREAD

**Issue by betsythefc** [SimpleMobileTools/Simple-Calendar#1813]
I'd like to have an option for Do Not Disturb to come up on events that I select. For example, I have a weekly appointment and I set Do not disturb everytime. I'd like Simple Calendar to do that for me.

**Comment by tibbi** [comment]
If you have Android 8+, you can use a specific event type for those events and mute the notification in the app settings -> Customize notifications.

**Comment by betsythefc** [comment]
I think I didn't explain what I wanted. I want a calendar even to turn ON do not disturb when it starts, and turn it OFF when it ends. If I have do not disturb already on, I know I can configure notifications to override that, but that is not the functionality I'm requesting.

**Comment by tibbi** [comment]
such things are handled by the system, not the app itself
