### ISSUE TITLE
Doubt about translating on the web?

### ISSUE THREAD

**Issue by gallegonovato** [SimpleMobileTools/Simple-Calendar#1824]
Good afternoon:

First of all thank you for all your time and help.

Then I would like to comment something that I am finding on the web to help you to translate the applications.

It turns out that I find (attached screenshot)

https://ibb.co/d6t7QYN

If I go by the top. English Clave video.txt:1 . That translation would be video or video.txt

But just below it is empty and of course I don't know whether to translate it or leave it.

Thanks for your help and time. I apologize for putting it only here. But as it happens to me in several places I didn't know where to ask. Please excuse me if I did something wrong

**Comment by tibbi** [comment]
Hi, that is supposed to be a url to the video, but if it isnt available in the original file, just leave it empty. It is empty in 99% cases.

**Comment by gallegonovato** [comment]
> Hola, se supone que es una URL del video, pero si no está disponible en el archivo original, déjalo vacío. Está vacío en el 99% de los casos.

Thank you very much for your help. I was already messing up. I apologize for that
