### ISSUE TITLE
v2.5.3 missing in F-Droid-Store

### ISSUE THREAD

**Issue by Krawei** [SimpleMobileTools/Simple-Calendar#183]
When I take a look in the playstore I notice, that the app's current version is v2.5.3.

In the F-Droid store the current version is v2.5.2. There's no "unstable"-marked version in the F-Droid store so far.

What's the reason for the difference on the versions? Is there a failure in build process?

Kind Regards,

Krawei

**Comment by tibbi** [comment]
F-droid is usually delayed by a couple days. They are fully in charge of that tho, nothing I can do about it. 2.5.3 has been released just 2 days ago, it should get to f-droid soon.
