### ISSUE TITLE
Sorting order of events in monthly event view

### ISSUE THREAD

**Issue by cyberius0** [SimpleMobileTools/Simple-Calendar#1834]
Hello,
we are using Simple Calendar with CalDAV and multiple calendars (e.g. one for travel events, one for work events, one for private events).

Those calendars  have different colors.

Monthly view only shows 3 events for one day, if there are more than 3 events then these white little dots are shown.

Is it possible to prioritize different calendars so that e.g. events from my "work" calendar will always be shown on top of a event list, also in monthly view?

This would help us, because some events are more important than others and it is nice if they are always shown in monthly view and not hidden.

Thank you

**Comment by tibbi** [comment]
that isnt really on the roadmap now
