### ISSUE TITLE
Whole day events are not displayed the whole day in the widget

### ISSUE THREAD

**Issue by igitti** [SimpleMobileTools/Simple-Calendar#184]
When an event is configured for a whole day then choosing the time is no longer possible. So far so good.
But the time that was shown until swichting to a whole day event still matters. In the widget the event is displayed only until that time and not until end of day.

Nevertheless if an alert is configured this alert is still relative to the "vanished" time. Sure an alert must be bound to time but the event is not supposed to have any assigned. Maybe it could better be bound to the beginning = midnight (of the first day if the event is longer then one day).

SimpleMobileTools are great work!

**Comment by tibbi** [comment]
Hey, what app version do you use?
Ill take a look at the widget issue.
The alert should be configured to midnight already, counting backwards from there.

**Comment by igitti** [comment]
Hey tibbi,

sorry for the late reply. Meanwhile I updated to version 2.5.3
The alert works perfectly.

**Comment by tibbi** [comment]
seems to be working fine already
