### ISSUE TITLE
Make Past events and tasks appear less bright 

### ISSUE THREAD

**Issue by lamyergeier** [SimpleMobileTools/Simple-Calendar#1840]
In the widget that shows the entire month with events and tasks, make the old events and tasks less bright.

**Comment by tibbi** [comment]
you can already enable dimming past events in the app settings, that should apply at widgets too

**Comment by tibbi** [comment]
that is currently the expected behaviour, will consider changing it in the future

**Comment by lamyergeier** [comment]
Thanks, IMO it is better when it is easy to differentiate between the events in past and in next month with the current month.
