### ISSUE TITLE
Feature: smooth scrolling

### ISSUE THREAD

**Issue by mankoff** [SimpleMobileTools/Simple-Calendar#1843]
Allow smooth scrolling of month and week views. 

If the month view scrolled down rather than horizontal, you could allow users to scroll by week rather than by month. There's no good reason to force us to view the first of the month at the top of the screen. 

Similarly week view, as it scrolls horizontal now jumps by the view amount. Should be an optional behavior.

**Comment by tibbi** [comment]
that isnt on the roadmap now

**Comment by mankoff** [comment]
See #498
