### ISSUE TITLE
Automatic ics-file download from internet

### ISSUE THREAD

**Issue by ElektroVirus** [SimpleMobileTools/Simple-Calendar#1845]
It's great this calendar has support for ICS. However, the ICS must be always manually added when some new events are added to the ICS. 

The problem is, someone is maintaining an ICS-file for some events. At this time, I have to regularly download the ICS-file and feed into Simple Calendar. Could the ICS support be also implemented so that a web URL could be given into the Simple Calendar, where it would regularly download the ICS itself?

E.g. Google Calendar is capable of doing this.

Thanks for your consideration, this would be really beneficial for me.

**Comment by tibbi** [comment]
you can already set up syncing via so called CalDAV protocol, you have to enable it in the app settings. As our app itself has no internet access itself, it needs a so called "sync adapter" to take care of syncing the data between your device and the servers. You can set up an app like DAVx5 for that. Once it is set up and calendars are periodically synced to your device, you will see it show up in Simple Calendar Pros app settings at enabling CalDAV sync.

**Comment by ElektroVirus** [comment]
Thanks for fast reply. 
I Didn't know it had to do through the CalDAV-protocol, which I in fact had already been using with NextCloud. I got the synchronization for the online-ics working now. Thanks and have a nice day! :)
