### ISSUE TITLE
Feature Request: Travel Time

### ISSUE THREAD

**Issue by betsythefc** [SimpleMobileTools/Simple-Calendar#1851]
Similar to `Calendar.app` on macOS/iOS, I would love a travel time option when creating an event. The way I see this implemented is:

An option on the create/edit screen to enter a travel time duration, with the entry either always being no travel time, or a default setting. It would then create a secondary event that starts X minutes before, and ends at the start time of the new event. This would use the iCalendar `RELATE` property:

`4.2.15 Relationship Type` in https://www.ietf.org/rfc/rfc2445.txt

Setting the new event as the `PARENT` of the travel time event, and the travel time event as the `CHILD`. I would then recommend that modifying the start time of the `PARENT` event would update the start/end times of the `CHILD` event. Similarly to how Simple Contacts has the ability to modify which fields are present for editing, I think is how this would work.

I'm unsure if the `RELATE` property allows for references to other events, like `DTSTART:<PARENT-ID>-15` or whatever.

**Comment by tibbi** [comment]
that is way too advanced for this app, just enable time zone customization in the app settings
