### ISSUE TITLE
Add option not to display tasks in the calendar or widget

### ISSUE THREAD

**Issue by sbstn87** [SimpleMobileTools/Simple-Calendar#1854]
Hi,

is it possible to add an option **not** to display planned tasks (not events) in the calendar view or in the widget with upcoming events?

It would be useful if I for example wanted to create a daily task with a reminder, like: "Breakfast at 7:00". It clutters the calendar or the events view, but I only need a notification to appear on my screen.

**Comment by tibbi** [comment]
just use a different event type for it, then it is easy to filter out in the app
