### ISSUE TITLE
Export events to an .ics file does not follow RFC 5545 formatting guidelines

### ISSUE THREAD

**Issue by Para-lyzed** [SimpleMobileTools/Simple-Calendar#1863]
Hello, I was having trouble importing an .ics file that was exported from Simple Calendar to another program, so I ran a validation check on https://icalendar.org/validator.html to see what the issue was. The .ics file exported from Simple Calendar appeared to use the LF line break, whereas the standard for .ics files as per [RFC 5545](https://icalendar.org/iCalendar-RFC-5545/3-1-content-lines.html) is CRLF line breaks. This caused the error, and converting all the LF breaks to CRLF using [this tool](https://app.execeratics.com/LFandCRLFonline/?l=en) fixed the issue and allowed the new .ics file to pass the iCalendar verification, as well as become importable in the aforementioned program that would not previously accept the file.

Additionally, while I know less in this area, I believe .ics files should *ideally* not have empty fields, but I found that every single event in the .ics file has an empty "DESCRIPTION:" and "LOCATION:" field (since I never use them when setting an event). This is also a potential compatibility issue, because it's outside the standard, and has caused issues with certain data types before (see [kewisch/ical.js#462](https://github.com/kewisch/ical.js/issues/462#issuecomment-776623539)). I have not personally seen either of these types causing problems when empty, but excluding them is the best option for compatibility. If a field is left blank by the user, it should not be included in the .ics file.

I believe this should hopefully be a very simple fix, and I'm surprised to see that it is not currently in the open issues.

My device details are below, but I highly doubt this is a device specific issue:

OnePlus 7 Pro
Android 11
LineageOS 18 (build 18.1-20221016-nightly-guacamole)

**Comment by tibbi** [comment]
should be fixed in 6.20.2
