### ISSUE TITLE
Incorrect TZID in DTEND after specifying time for All-day event

### ISSUE THREAD

**Issue by ZelenyeShtany** [SimpleMobileTools/Simple-Calendar#1866]
After I specify time for all-day event and synchronize it via CalDAV, i get DTEND property set with UTC timezone instead of default one(as it is in DTSTART):

```BEGIN:VEVENT
DTSTAMP:20221026T222910Z
UID:c584bc8f-0d7d-4ee5-b3f8-c6db5d42f217
SUMMARY:test
DTSTART;TZID=Asia/Almaty:20221025T130000
DTEND;TZID=UTC:20221025T080000
END:VEVENT
```

Maybe it's somehow related to recently added commits, applied by @Naveen3Singh:
https://github.com/SimpleMobileTools/Simple-Calendar/commit/cf20782fd908260dfb5aa60f6ff0fce4a4bb98ba
https://github.com/SimpleMobileTools/Simple-Calendar/commit/c444c476b3b97a541e6564054afa87e2bb26044a

**Comment by tibbi** [comment]
what app version are you using?

**Comment by ZelenyeShtany** [comment]
I'm using 6.20.1 Pro/prepaid version compiled from master branch(last commit), sorry for not mentioning it

**Comment by tibbi** [comment]
was it working well previously?

**Comment by Naveen3Singh** [comment]
@ZelenyeShtany
> specify time for all-day event

where are you creating this event? perhaps not in Simple Calendar?

**Comment by ZelenyeShtany** [comment]
### compiled at commit https://github.com/SimpleMobileTools/Simple-Calendar/commit/88241f734 (right before https://github.com/SimpleMobileTools/Simple-Calendar/commit/cf20782fd908260dfb5aa60f6ff0fce4a4bb98ba, https://github.com/SimpleMobileTools/Simple-Calendar/commit/c444c476b3b97a541e6564054afa87e2bb26044a) ###

#### creating new all-day event in the app; syncing ####

```
BEGIN:VEVENT
DTSTAMP:20221027T093836Z
UID:6287510f-b0c8-4268-b522-a3e1da99b430
SUMMARY:test 2
DTSTART;VALUE=DATE:20221019
DTEND;VALUE=DATE:20221020
STATUS:CONFIRMED
BEGIN:VALARM
TRIGGER:-PT10M
ACTION:DISPLAY
DESCRIPTION:test 2
END:VALARM
END:VEVENT
```

Everything is OK.

#### changing this event in the app to time-specific(13:00-14:00, Asia/Almaty /+6); syncing ####

```
BEGIN:VEVENT
DTSTAMP:20221027T095806Z
UID:6287510f-b0c8-4268-b522-a3e1da99b430
SEQUENCE:1
SUMMARY:test 2
DTSTART;TZID=UTC:20221019T070000
DTEND;TZID=UTC:20221019T080000
CLASS:PUBLIC
STATUS:CONFIRMED
BEGIN:VALARM
TRIGGER:-PT10M
ACTION:DISPLAY
DESCRIPTION:test 2
END:VALARM
END:VEVENT
```

Everything's fine here, I guess? Or should TZID be the one that's
default for my android device?(Asia/Almaty in this case)

### compiled at commit https://github.com/SimpleMobileTools/Simple-Calendar/commit/b9f18ba06 (merge of commits https://github.com/SimpleMobileTools/Simple-Calendar/commit/cf20782fd908260dfb5aa60f6ff0fce4a4bb98ba, https://github.com/SimpleMobileTools/Simple-Calendar/commit/c444c476b3b97a541e6564054afa87e2bb26044a) ###

#### creating new all-day event in the app; syncing ####

```
BEGIN:VEVENT
DTSTAMP:20221027T102353Z
UID:40c13a42-8c14-46c1-a9e2-8d78b91e8b42
SUMMARY:test 3
DTSTART;VALUE=DATE:20221020
DTEND;VALUE=DATE:20221021
STATUS:CONFIRMED
BEGIN:VALARM
TRIGGER:-PT10M
ACTION:DISPLAY
DESCRIPTION:test 3
END:VALARM
END:VEVENT
```

OK.

#### changing this event in the app to time-specific(13:00-14:00, Asia/Almaty /+6); syncing ####

```
BEGIN:VEVENT
DTSTAMP:20221027T102749Z
UID:40c13a42-8c14-46c1-a9e2-8d78b91e8b42
SEQUENCE:1
SUMMARY:test 3
DTSTART;TZID=Asia/Almaty:20221020T130000
DTEND;TZID=UTC:20221020T080000           <<<----------
CLASS:PUBLIC
STATUS:CONFIRMED
BEGIN:VALARM
TRIGGER:-PT10M
ACTION:DISPLAY
DESCRIPTION:test 3
END:VALARM
END:VEVENT
```

Not OK: TZID in DTEND and DTSTART are different

### Note: #####

Synchronization is performed with Baikal CalDAV server via DAVx5
android app

**Comment by ZelenyeShtany** [comment]
**CREATING time-specific event(13:00-14:00, Asia/Almaty /+6); syncing**

Results for builds before and after commits https://github.com/SimpleMobileTools/Simple-Calendar/commit/cf20782fd908260dfb5aa60f6ff0fce4a4bb98ba, https://github.com/SimpleMobileTools/Simple-Calendar/commit/c444c476b3b97a541e6564054afa87e2bb26044a are correct and equal:

```
BEGIN:VEVENT
DTSTAMP:20221027T112305Z
UID:e741f39e-d5e3-4285-8e20-55611a616680
SUMMARY:test 4
DTSTART;TZID=Asia/Almaty:20221025T130000
DTEND;TZID=Asia/Almaty:20221025T140000
STATUS:CONFIRMED
BEGIN:VALARM
TRIGGER:-PT10M
ACTION:DISPLAY
DESCRIPTION:test 4
END:VALARM
END:VEVENT
```

**Comment by Naveen3Singh** [comment]
I haven't tried installing Baikal yet but with Nextcloud and google calendar, so far I'm unable to reproduce the mentioned issue.
I have changed my device and server timezone to "Asia/almaty".

**All-day event created on the app and exported via Nextcloud:**
```
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//SabreDAV//SabreDAV//EN
X-WR-CALNAME:Personal
X-APPLE-CALENDAR-COLOR:#0082c9
REFRESH-INTERVAL;VALUE=DURATION:PT4H
X-PUBLISHED-TTL:PT4H
BEGIN:VEVENT
DTSTAMP:20221027T214126Z
UID:9495a8f6-3a08-4246-9b2e-ed8ecb53fd85
SUMMARY:test 2
DTSTART;VALUE=DATE:20221020
DTEND;VALUE=DATE:20221021
STATUS:CONFIRMED
BEGIN:VALARM
TRIGGER:-PT10M
ACTION:DISPLAY
DESCRIPTION:test 2
END:VALARM
END:VEVENT
END:VCALENDAR
```

**The same all-day event is now converted to a time-specific event in the Simple Calendar app and then exported via Nextcloud:**
```
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//SabreDAV//SabreDAV//EN
X-WR-CALNAME:Personal
X-APPLE-CALENDAR-COLOR:#0082c9
REFRESH-INTERVAL;VALUE=DURATION:PT4H
X-PUBLISHED-TTL:PT4H
BEGIN:VTIMEZONE
TZID:Asia/Almaty
LAST-MODIFIED:20220816T024022Z
BEGIN:STANDARD
TZNAME:+06
TZOFFSETFROM:+0700
TZOFFSETTO:+0600
DTSTART:20041031T030000
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
DTSTAMP:20221027T214203Z
UID:9495a8f6-3a08-4246-9b2e-ed8ecb53fd85
SEQUENCE:1
SUMMARY:test 2
DTSTART;TZID=Asia/Almaty:20221020T130000
DTEND;TZID=Asia/Almaty:20221020T140000
STATUS:CONFIRMED
BEGIN:VALARM
TRIGGER:-PT10M
ACTION:DISPLAY
DESCRIPTION:test 2
END:VALARM
END:VEVENT
END:VCALENDAR
``` 

In your event:
```
DTSTART;TZID=Asia/Almaty:20221020T130000
DTEND;TZID=UTC:20221020T080000           <<<----------
```

it's worth pointing out that this 'might' be a bug on the server side as your export is from there (UID is a [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier) and Simple calendar doesn't use it yet)
and also that the exported time is still correct (T080000 + T060000 = T140000), it's just converted to UTC for some reason.

**Comment by ZelenyeShtany** [comment]
> it's worth pointing out that this 'might' be a bug on the server side
Yes, you were right, the problem is related to https://github.com/pimutils/vdirsyncer, not due to Simple Calendar and not due to Baikal server. Thanks a lot for help, guys
