### ISSUE TITLE
Feature request: Option to additionally display date & time in local time zone

### ISSUE THREAD

**Issue by andreasmjg** [SimpleMobileTools/Simple-Calendar#1868]
Hi, 

It would be great if there was an option to enable display of local time zone in addition to event time zone, in the screen of event details (when opening an event / event details screen).

![Screenshot from 2022-10-28 09-13-32](https://user-images.githubusercontent.com/34312687/198538625-3fd15e23-50bf-4ff8-a1ba-cda2def6c7bc.png)

The above screenshot shows only event time & time zone. 

To contrast, in Thunderbird the following is displayed if event time zone differs from mobile phone/local time zone: 

`mobile phone/local time according to time zone set in calendar app (event time, event time zone)`

![Screenshot from 2022-10-28 09-07-10](https://user-images.githubusercontent.com/34312687/198537458-ad14745d-2052-4ce1-89a0-173258c67268.png)

Although this would require some additional screen real estate on the edit event screen, personally I would greatly benefit from this feature. I often have events in different time zones and I need to see event time zone by opening the event, then I need to close the event to see my time zone (by zooming in a lot if I'm in week view to make sure I get the right time, see https://github.com/SimpleMobileTools/Simple-Calendar/issues/1740 ) 

I hope this can be considered.

Thank you for all the good work with this app!!

Andreas

**Comment by tibbi** [comment]
I dont really want to add that, it is way to advanced and would flood the ui
