### ISSUE TITLE
Allow to set different ringtones for each event type (enhancement request)

### ISSUE THREAD

**Issue by nursoda** [SimpleMobileTools/Simple-Calendar#1874]
Please allow to use a different notification than the default / system ringtone.

My usecase: I use a different calendar app for scheduled meetings, and this one for daily reminders. I'd like to be able to audibly distinguish them.

**Comment by tibbi** [comment]
If you have Android 8+ you can already use the "Customize notifications" in the app settings, that takes you to the device settings where you can customize the notification streams.

**Comment by nursoda** [comment]
You're right, I did not see that. Sufficient for me.
However, this is then not "per event type" but "per application".

**Comment by tibbi** [comment]
there is only 1 application, the customization is per event type. At least thats how most systems do it
