### ISSUE TITLE
Version 2.5.8 missing in F-Droid Store

### ISSUE THREAD

**Issue by Krawei** [SimpleMobileTools/Simple-Calendar#188]
Dear team,

when I take a look in the play store I see the version mentioned above. 
When I look to F-Droid the current version is 2.5.7.

What is the reason for this? Is there a failure in the build process?

Kind Regards,
Krawei

**Comment by tibbi** [comment]
Hey, that was just a hotfix fixing some issues with people unable to start the app after update. The build was created from some older code with 1 minor change, I cannot build it like that on f-droid as it always takes the latest code. The next version will be normally available on f-droid already.

**Comment by tpo** [comment]
I'm not sure this is just "that was just a hotfix fixing some issues with people unable to start the app after update". See #195 for why.
