### ISSUE TITLE
Android Calendar Provider API support

### ISSUE THREAD

**Issue by Crisis82** [SimpleMobileTools/Simple-Calendar#1880]
Does this app uses Android Calendar API?

more in depth explanation:
I'm using this app for some time now and really appreciate the simplicity of it, but I just changed my android launcher, which supports the Calendar Provider API to show calendar events in a more clean and minimal way and none of the events from Simple Calendar are showed.

**Comment by tibbi** [comment]
you have to enable CalDAV sync in the app settings if you want to sync your events with other apps/people, by default everything is stored locally in the app only
