### ISSUE TITLE
It can't show all Notifications.

### ISSUE THREAD

**Issue by Pranab009** [SimpleMobileTools/Simple-Calendar#1890]
It can't show all Notifications.
Some time it shows notifications sometimes not.
Other hand side Google Calendar runs parallel and google Calendar shows all events notification but Simple Calendar don't show all notifications.

This is an old issue
App version: 6.20.2
Android version: 10

![Screenshot_20221124-210902](https://user-images.githubusercontent.com/65340361/204036936-b57014e9-416a-4fcc-8fe6-24fedcbee37e.png)

**Comment by tibbi** [comment]
Check your device battery and notification settings, if there is nothing blocking the reminders, or killing the app in the background. You might also want to take a look at https://dontkillmyapp.com , it has some useful tips.
