### ISSUE TITLE
Current date at calendar Icon.

### ISSUE THREAD

**Issue by Pranab009** [SimpleMobileTools/Simple-Calendar#1891]
Current date at Calendar icon.
If today is 25 then it shows 25.

![Screenshot_20221125-234333_1](https://user-images.githubusercontent.com/65340361/204038082-7be62b61-dbf1-4fff-9dae-d558e21d6952.png)

**Comment by tibbi** [comment]
you can use the Current Date widget for that. We dont plan adding it to the icon itself as there are many possible color combinations and adding 31 days into all colors would increase the app size quite a bit.

**Comment by dumblob** [comment]
I believe OP had in mind real-time synthetization of the icon instead of bundling all possible combinations (which is a total nonsense, of course).

**Comment by tibbi** [comment]
the icon cannot be generated dynamically, we have to add all variants as files
