### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Pranab009** [SimpleMobileTools/Simple-Calendar#1893]
If event is set for any particular time (9 am) and set remainer at 1 day before. Then it remind  1day before at 9 am. That is ok but 
If Event is set for "All day" and reminder set at 1day before. Then when(time) it remind?
I know there is an option  custom & durning the day at hh:mm but I want to set remainer at 1 day before at 12:30pm. How to set please tell me.

One Simple solution maybe merged both option together custom & durning the day at hh:mm.
Custom date and time option together.

**Comment by tibbi** [comment]
well, if sets the reminder to X minutes/hours before midnight

**Comment by Pranab009** [comment]
Is this a joke ???
This is not a solution.
If I told you wait till midnight for set an alarm for next day.
Is it meaningful?
I don't expect this kind of supid answer.
You're a professional developer.
If you are busy then you can closed it by saying this is not in my road map or add this feature in near future.

![Screenshot_20221130-231540](https://user-images.githubusercontent.com/65340361/204966809-2e83bb7b-e7d0-4be4-a558-60cea61a8690.png)

**Comment by tibbi** [comment]
you can also set the reminder to trigger during the day, if thats what you want

**Comment by Pranab009** [comment]
No that is not possible because
I set all remainders at one day.
Total January month reminder set on January 1.
That is impossible to set remainder day by day.
And if I remind every events earlier date then what is the use of it. sounding very funny, Is it really possible?
