### ISSUE TITLE
RFE: Always use standard starting day for non current weeks in weekly view

### ISSUE THREAD

**Issue by andy-berg** [SimpleMobileTools/Simple-Calendar#1895]
The setting "Start week with the current day" is a very useful option. When selected, non current weeks (e.g. in the future or past) however are also displayed starting with the current week day, which is not very intuitive. When navigating to non current weeks it would be nice if the standard starting day could be used instead, e.g. Monday (respectively Sunday if the option "Start week on Sunday" is selected).

**Comment by tibbi** [comment]
that sounds like a really big mess, I prefer the current version
