### ISSUE TITLE
Simplify overlapping events in weekly view

### ISSUE THREAD

**Issue by petrarca-arezzo** [SimpleMobileTools/Simple-Calendar#1896]
The logic of showing overlapping events in the weekly view is somewhat weird and wasting space. See the two screenshots (one from the app, the other one from nextcloud) - the two shorter events should be on the same side (preferably on the right, as nextcloud does it):

![Screenshot](https://user-images.githubusercontent.com/74855438/205616302-756855b6-cc90-4876-9ff6-28820211d0bc.png)
![Screenshot NC](https://user-images.githubusercontent.com/74855438/205616327-a183acb8-2632-4f0f-a481-ea948d8d7ea7.png)

**Comment by tibbi** [comment]
some related improvements are on the roadmap, but it is quite tricky to do it right. Anyway, it is already reported somewhere so Ill close this one.
