### ISSUE TITLE
All notifications can't show.

### ISSUE THREAD

**Issue by Pranab009** [SimpleMobileTools/Simple-Calendar#1898]
It missed many notification

**Comment by Pranab009** [comment]
It skipped many notifications.
Battery optimization is disabled but it don't show many notifications.

![Screenshot_20221207-080831](https://user-images.githubusercontent.com/65340361/206075815-75974fdf-8ff3-4ebd-9a65-41d8e669fbd9.png)

![Screenshot_20221205-234258](https://user-images.githubusercontent.com/65340361/206075793-23ad2bc2-0249-44ae-8789-01aeea93d86d.png)

![Screenshot_20221205-234314](https://user-images.githubusercontent.com/65340361/206075805-fef3c46e-1647-4a8e-bf19-4bcf6ea26c6c.png)

**Comment by Pranab009** [comment]
I set this reminder at Simple Calendar on 
5th December and set two time one day ago and at start, It don't notify me but Google Calendar show notification.
If battery optimization is disabled then why this happened ??

**Comment by tibbi** [comment]
Hey, check your device battery and notification settings, if there is nothing blocking the reminders, or killing the app in the background. You might also want to take a look at https://dontkillmyapp.com , it has some useful tips.

**Comment by Pranab009** [comment]
See this... I check all things..

![Screenshot_20221207-153243](https://user-images.githubusercontent.com/65340361/206149107-0568d1a1-674d-411f-bcf0-2c7dc1e30513.png)
![Screenshot_20221207-153310](https://user-images.githubusercontent.com/65340361/206149113-7798a03b-c60f-4190-b88b-0892b1b0b414.png)
![Screenshot_20221207-153322](https://user-images.githubusercontent.com/65340361/206149115-3e232af2-47f5-4f19-9460-38e54330a3a1.png)
