### ISSUE TITLE
[Feature] Add option to create multiple offline calendars and a related BUG.

### ISSUE THREAD

**Issue by Rexadev** [SimpleMobileTools/Simple-Calendar#1901]
1. I have using [Etar ](https://github.com/Etar-Group/Etar-Calendar) to create Offline Calendars and to Import/Export calendars (Online ones too).

Would be nice to have this functionality in Simple-Calendar.

2. Etar show I have 1 offline calendar and 2 Google Synced Calendars but Simple Calendar at the bottom show I have 3 Calendars - 1. "Offline Calendar", 2. "Regular event", 3. An Offline Calendar I created on Etar .

1 and 2 are empty
and Simple Calendar doesn't show Google Synced Calendars.

**Comment by tibbi** [comment]
you can already create any amount of local calendars...

**Comment by RokeJulianLockhart** [comment]
> https://github.com/SimpleMobileTools/Simple-Calendar/issues/1901#event-11571001549

@Rexadev, you shouldn't have expunged the title and content of this issue. It renders comments like https://github.com/FossifyOrg/Calendar/issues/92#issuecomment-1962011387 difficult to understand.
