### ISSUE TITLE
CalDAV Improvements

### ISSUE THREAD

**Issue by tunbridgep** [SimpleMobileTools/Simple-Calendar#1913]
Hey there, I have 2 suggestions to make using Simple Calendar with CalDAV much better for certain use cases. I am one of those people who exclusively uses CalDAV for my calendars, I don't use offline calendars at all, as I run a Radicale server. I have no need for offline calendars at all and frankly they just get in the way,

1. For the "automatically add birthdays" feature, let us specify an event type (aka a calendar), since it uses an offline built-in "Birthdays" event type by default, and many CalDAV calendars (especially google calendar) already come with a Birthdays calendar already.
2. Allow us to delete the "Regular Event" event type if we already have a different event type selected as default.

**Comment by tibbi** [comment]
those arent really on the roadmap, just ignore the types you dont want to use
