### ISSUE TITLE
Monthly view only swipes to previous month

### ISSUE THREAD

**Issue by rightsaidfred99** [SimpleMobileTools/Simple-Calendar#1915]
I've noticed if you use monthly view, and swipe with a thumb, Simple Calendar only goes to previous months. 

One can swipe forwards, but try it with a thumb and its practically next to impossible.

**Comment by tibbi** [comment]
no idea what you mean here, doesnt matter what finger you use for swiping

**Comment by rightsaidfred99** [comment]
Try it out yourself. Its the only app I've ever seen in 10 years of using android that swipe is different between left and right when using one band.

**Comment by tibbi** [comment]
it is all handled by the system, not us. Arent you triggering Pull to refresh from the top?
