### ISSUE TITLE
Widget Specifically For Reminders, and Specifically For Calendar

### ISSUE THREAD

**Issue by seniorm0ment** [SimpleMobileTools/Simple-Calendar#1916]
I love having the calendar widget, however it also shows reminders.
It would be very nice to be able to have that same exact widget, but an option to enable and disable reminders and calendar events.

So I can place a widget on the left for only calendar events, and then a widget on the right for only reminders so my reminders are very obviously separated from my calendar events.

**Comment by tibbi** [comment]
that isnt really on the roadmap

**Comment by seniorm0ment** [comment]
I can't really see why adding a simple toggle to just hide reminders, and hide calendar events from the widget wouldn't suffice or be difficult to do.
Reminders and calendar events are already two different entities in the app. 

All the user would have to do is place one widget, select hide reminders. Then it will only show calendar events.
Then place one more widget, and select hide calendar events, and it will show only reminders.

Just ensuring you understand my request.
But ok, I hope to see it considered again in the future.

**Comment by tibbi** [comment]
nope, reminders and events arent different entities at all... Reminders belong to events.

**Comment by seniorm0ment** [comment]
Sorry, I was using the incorrect terminology.
I meant Tasks! Tasks and Events separation is what I was requesting. Not reminders.

**Comment by seniorm0ment** [comment]
Any further consideration behind this, after my clarification that I meant Tasks not reminders.
