### ISSUE TITLE
Saving new events: merge "synced calendars" and "locally stored calendars"

### ISSUE THREAD

**Issue by hinkywin** [SimpleMobileTools/Simple-Calendar#1917]
When creating a new event, I can select whether to save it in one of my synced calendars or whether to store it locally only. If I choose the latter, I then have to select the "type" (i.e. which locally stored calendar) in a second step. Could you merge these two options into one? To distinguish them, maybe it can say "CalDAV" and "local" in small letters within the 'color circle' on the right. Thanks!

**Comment by tibbi** [comment]
not really, you dont have to do it. As soon as you pick Store locally only, the last used local calendar is selected

**Comment by tibbi** [comment]
well, then you obviously have to change it yourself, we cannot prodict it

**Comment by tibbi** [comment]
makes no sense merging it, it works as expected
