### ISSUE TITLE
"Show events spanning across midnight at the top bar" option in weekly view confusing or bug?

### ISSUE THREAD

**Issue by JohannesGGE** [SimpleMobileTools/Simple-Calendar#1918]
## Confusion/Bug

As shown in the screenshots below an all-day event lasting more than one day isn't shown at the top bar as I would expect it to be when "Show events spanning across midnight at the top bar" = false. 
Because this Issue was fixed in 6.20.3 for an all-day event lasting only one day, as shown in the screenshot, I'm confused if that is an intended behaviour.

| "Show events spanning across midnight at the top bar" = true | "Show events spanning across midnight at the top bar" = false |
|---|---|
| ![01](https://user-images.githubusercontent.com/74607597/210285732-29377142-4e2e-49d8-a3f6-910810c22d80.jpeg) | ![02](https://user-images.githubusercontent.com/74607597/210285738-c74d0fc0-f5b0-4a29-9f2e-3cf41b53eb4c.jpeg) |

## Recreation
Add an all-day event lasting min. two days and disable "Show events spanning across midnight at the top bar".

## Version: 
6.20.3

**Comment by tibbi** [comment]
well, if you have the option disabled, of course it isnt shown there.. Seems to be working just fine

**Comment by dumblob** [comment]
@JohannesGGE yeah, I also dislike this behavior - see https://github.com/SimpleMobileTools/Simple-Calendar/issues/1767 .

Actually I would welcome a second separate boolean option **"Do NOT show events spanning across midnight at the top bar"** covering this additional case (and ideally renaming both options to indicate the difference which is not apparent judging based on the multiple issue reports in this bug tracker related to the current boolean option).

See also https://github.com/SimpleMobileTools/Simple-Calendar/pull/1821 .
