### ISSUE TITLE
Feature Request: Add setting to scroll by number of days in weekly view

### ISSUE THREAD

**Issue by dwettstein** [SimpleMobileTools/Simple-Calendar#1919]
Currently the weekly view always scrolls by the number of days that have been set. While this makes sense when having the number of days set to 7 or lower, it can be confusing with any number above 7, e. g. 10, especially when the view does not start with the current day.

My suggestion would be to add a setting for the weekly view to set the number of days to scroll or to simply add a checkbox to always scroll by 7 days.

**Comment by tibbi** [comment]
you can already use the bottom day count slider in the Pro app version

**Comment by dwettstein** [comment]
I have seen that and I'm also using it. This request is about how many days the weekly view is scrolling at a time.
When having the view set to 10 days, I'd still like it to scroll by only 7 days.

A simple checkbox option for the weekly view called "Scroll by 1 week" or similar would be enough.

**Comment by tibbi** [comment]
that would be super confusing...
