### ISSUE TITLE
Feature Request: Add a weekly view widget

### ISSUE THREAD

**Issue by dwettstein** [SimpleMobileTools/Simple-Calendar#1920]

**Comment by tibbi** [comment]
duplicate of #488

**Comment by dwettstein** [comment]
This is not really a duplicate of #488. This request here is about having a (1) week widget similar to the weekly view, not a customized month widget showing multi weeks.

**Comment by Aga-C** [comment]
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Calendar/issues/398.
