### ISSUE TITLE
Caldav sync missing

### ISSUE THREAD

**Issue by mdkuser** [SimpleMobileTools/Simple-Calendar#193]
This app now can sync with google calendar, however it does NOT shows all calendars configured in google calendar. Rather than adding gsync support I'd like so have caldav supported so owncloud/nextcloud and others that support caldav could be used.
Btw, rather than reinventing the wheel implementig calendar sync, why don't you just let the app use the standard android calendar store, so the sync can be done with 3rd party apps like davdroid or acaldav?
That's the way it works for other calendar apps as well.

**Comment by tibbi** [comment]
caldav support will be added too, its already reported at #150 .
From Google calendar it currently takes only the primary calendar, you cannot pick one. That will be added in the future.

**Comment by ddebny** [comment]
When will be caldav? It is very important future :) Calendar design is greate.

**Comment by tibbi** [comment]
it is already in the calendar, 2.7.4. It might take 1-2 more days before it appears on f-droid
