### ISSUE TITLE
Improve search, do not limit it by time

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Calendar#1934]
partially revert https://github.com/SimpleMobileTools/Simple-Calendar/commit/80234487da698913009aadd5ef4a74b65866a93b

**Comment by christian179717** [comment]
Is it on purpose that the issue is still in Version 6.12.2?

**Comment by tibbi** [comment]
what 6.12.2? That is an ancient version

**Comment by christian179717** [comment]
There was a mistake: real version 6.21.2

**Comment by tibbi** [comment]
the fix has been added only after releasing that app version, it will be added in 6.21.3
