### ISSUE TITLE
UK holiday updates required

### ISSUE THREAD

**Issue by Wintandre** [SimpleMobileTools/Simple-Calendar#1939]
There is a one-off holiday in 2023 for the coronation of the King (see https://www.gov.uk/bank-holidays).

I can make the change and submit a PR if desired.

**Comment by Wintandre** [comment]
Or just add the following to "app/src/main/assets/unitedkingdom.ics"

BEGIN:VEVENT
STATUS:CONFIRMED
UID:uni_56
SUMMARY:Coronation of King Charles III
DTSTART;VALUE=DATE:20230508
DTEND;VALUE=DATE:20230509
END:VEVENT

**Comment by eneller** [comment]
see #1978

**Comment by tibbi** [comment]
will be added in 6.21.7
