### ISSUE TITLE
Overlapping events.

### ISSUE THREAD

**Issue by Tech-Devil** [SimpleMobileTools/Simple-Calendar#194]
In **weekly view**, if I add events having same/overlapping timing, then their view is overlapped. It would be better if they are side-by-side.

If timing of two events is exactly same, one completely overlaps the other event.

**Comment by robinpaulson** [comment]
Sometimes it is useful to have them overlap; if side-by-side the titles are hard to read.

**Comment by knut-hildebrandt** [comment]
I agree to both opinions. Thus I'd propose to distinguish them by little vertical lines. Only problem then, if they do not only overlap partially they later added covers the other and thus the old one is not shown at all.

**Comment by tibbi** [comment]
Some initial overlapping handling will be added in version 6.3.0 released soon. Some more advanced cases wont be handled yet, but it should be good enough for now.

**Comment by llevrel** [comment]
Can you tell how it is handled now, please? Maybe a screenshot? Thanks.

**Comment by tibbi** [comment]
its just cut in half or third, nothing advanced

![overlap](https://user-images.githubusercontent.com/528931/98103720-ba549d80-1e95-11eb-9699-59272422852f.jpg)

**Comment by tibbi** [comment]
actually, this should work just fine already
