### ISSUE TITLE
Search not working for past events

### ISSUE THREAD

**Issue by pfertyk** [SimpleMobileTools/Simple-Calendar#1941]
Hi!

Thanks a lot for developing Simple Calendar, it's a really great app and one of the pillars of my productivity :heart: 

After one of the recent updates, however, I believe that the search function stopped taking past events into account. I hoped for a new setting to become available to fix that (like "include past events", similar to "dim past events") but I can't find anything like that. Could you please take a look?

Searching for future events still works without problems.

Cheers,
Paweł

**Comment by tibbi** [comment]
ye it has been fixed already, will be added into the next app version
