### ISSUE TITLE
[feature request] allow user to change to a different time picker

### ISSUE THREAD

**Issue by anp369** [SimpleMobileTools/Simple-Calendar#1956]
Since one of the last updates the app uses the 24h time picker  for selecting times of appointments which I personally find quite unintuitive to use. 
The only option for me to get the 2x12 h time picker back is to disable 24h support, but then I have to deal wth AM/PM which isn't common in my region. 

My suggestion would be to make another setting to let the user choose which timepicker they prefer. 

Thank you for your great apps. I use quite a lot of them. 
Cheers!

**Comment by tibbi** [comment]
it is a system design, not ours. If you use other than Material You theme, you will have the old desing.

**Comment by anp369** [comment]
Thanks for the hint. Works perfectly 👍
