### ISSUE TITLE
Can not delete CalDAV calendar

### ISSUE THREAD

**Issue by budda85** [SimpleMobileTools/Simple-Calendar#1958]
I cannot delete a CalDAV calendar.
I have subscribed to a calendar with ICSx5. I have activated this in Simple-Calendar so that this is displayed to me.
Now I have deleted the subscribed calendar in the ICSx5 app. In the Simple-Calendar it is still displayed. If I go to `Settings --> General --> Manage event types` (no idea if the English name is correct, I only have German here :)  ) I see the subscribed calendar, but I can't delete it. Here I get the message: `To delete a CalDAV calendar you have to desyncronize it.`
However, under `Settings --> CALDAV` the calendar is no longer displayed and I can not desyncronize it.

**Comment by tibbi** [comment]
Hi, enable CalDAV sync and use Manage CalDAV synced calendars, then disable it there

**Comment by budda85** [comment]
Hi @tibbi, That is my problem. It is missing at the manage CalDAV menu!

![Screenshot_20230127-094231](https://user-images.githubusercontent.com/20152200/215045604-dba47b43-94c2-4268-b0d3-296490d0b7a9.png)
![Screenshot_20230127-094159](https://user-images.githubusercontent.com/20152200/215045617-a8b70c87-1bd7-483b-9316-1892d8f4fdbc.png)

**Comment by budda85** [comment]
Ah, disable and enable CalDAV sync fixed it.
Sorry for the ticket :-)
