### ISSUE TITLE
Improvement: Change the background colour for previous and upcomming month days in the month view

### ISSUE THREAD

**Issue by Moostek** [SimpleMobileTools/Simple-Calendar#1960]
Hello, it will be nice to distinguish the days from previous and upcomming month days with different background colour in the month view. I use the dark skin, the actual month days are black. So it will nice to set up for previous and upcomming month days dark grey colour. 

It will help to better resolve the actual month days. 

Thank you!

**Comment by tibbi** [comment]
we dont plan changing the background there

**Comment by Moostek** [comment]
How about "completed"? I do not understand. I try to use SMT Calendar and i tell you that this is the imperfection, i.e. it is hard for me to orientate in the dates of the actual month. Can you understand my words? The colour differentiation is absolutely in place, it is reasonable demand!

**Comment by tibbi** [comment]
we will try making it somehow clearer, but definitely not by changing the background
