### ISSUE TITLE
Improvement: Highlight the background colour of the actual day in the month view (differentiation)

### ISSUE THREAD

**Issue by Moostek** [SimpleMobileTools/Simple-Calendar#1961]
Hello, it will be nice to highlight the actual day box in the month view: 1) with the light grey background colour., 1) the colour around the date (small circle) lengthen horizontally from one corner to another. 

Both these updates can help to better orientate in the month view, esp. in the dark mode. It is a reasonable reguest! 

Thank you,

**Comment by tibbi** [comment]
the current day is already circled

**Comment by Moostek** [comment]
**I'am sorry, but your moderation here is a bit despotic. You close the topics without any discussion here! I never experienced such attitude!**

**Comment by Moostek** [comment]
And I tell you again: the small circle is not enough on my phone. Can you understand? On my phone it looks not so good. So better differentiation is a must. And change the colour is reasonable request. Maybe you are the developer, but i tell you that not everything that YOU like is suitable for the others. 

Can you understand this? What about some kind of empathy?
