### ISSUE TITLE
Improvement: Hour selection in the day view (24 lines) 

### ISSUE THREAD

**Issue by Moostek** [SimpleMobileTools/Simple-Calendar#1962]
Hello, i really miss the hour list in the day view with 24 lines as each one will represent one hour. So when i click on desired hour, it will automaticaly set up the hour in the event settings. It will help to speed up the event creation. By the way in week view they are those "hour lines".

**Comment by tibbi** [comment]
that is available at the weekly view, isnt planned for daily view

**Comment by Moostek** [comment]
I am sorry, but i disagree. The day view with 24 lines for 24 hours could be really practical feature. There is NO reason that the day view does not contain the lines. On the contrary: the day view is design for this! 
Btw, the day consists from what? From 24 days. And 1 line for 1 hour is reasonible. Again: It will help to speed up the event creation. 

Anyway, I do not understand your attitude here. You completely do not understand the user's demands - you see things only with your eyes, with your perception. Why are you here, inside of this community? I iniciated some tips for better work with your Calendar, but you closed them all (ok, some of them they were duplicities). I know that it is your project, but maybe it is better when you start your apps as closed-source, according to your mind. 

You waste time of users that try to contribute and make the apps better!
