### ISSUE TITLE
Bug: Problems with moving to previous or upcomming month in the Month+day view

### ISSUE THREAD

**Issue by Moostek** [SimpleMobileTools/Simple-Calendar#1965]
Hello, i face to one bug. When I want to move backward and forward (to previous or upcomming month) in the Month+day view, then it many times does not work, I can not move to previous or upcomming month. It works mostly with some special finesse. Maybe the field for grabbing should be expanded.

**Comment by tibbi** [comment]
what exacty doesnt work on it?

**Comment by Moostek** [comment]
1. I open the Calendar on the Month+day view
2. I try to move to upcomming month by swiping the finger on the name of month in the middel of the display screen  
3. I can not move forward (to upcomming month), it is stuck. Sometimes it works, but sometimes not. Sometimes i have to swipe many times to move to the upcomming month. 
Even worst situation is when i first go backward (from January to December, Novemeber..) and then i want to to go back to January. Typicaly to move backward works better, but to move forward in the month list is mostly impossible (than it is better to use the Home button to go on actual month).

**Comment by tibbi** [comment]
dont you have the "Enable pull-to-refresh from the top" enabled in the app Setttings, under CalDAV section?

**Comment by Moostek** [comment]
You are right, after the disablement of the "pull-to-refresh from the top" setting it works smoothly. So this is it. I also found the finesse to move back and forward with enabled "pull-to-refresh from the top" setting: i move the finger over the month name slightly skew (from down to up-left/up-right).
