### ISSUE TITLE
Improvement: The "Delete" button in notification (beside the "Postpone" button) 

### ISSUE THREAD

**Issue by Moostek** [SimpleMobileTools/Simple-Calendar#1966]
Hello, i found that there will be really practical the feature to delete the event right from the event notification in smartphone's notification area. So far there is just button called "Postpone". It will be nice to have there the button "Delete" right beside the "Postpone" button. It will help the effeciency, to manage (delete) resolved events. 

This is finding from my own practical use of the Calendar app.

**Comment by tibbi** [comment]
that isnt really on the roadmap

**Comment by Moostek** [comment]
But it is a relevant and wanted feature. So put it on the roadmap, please.
