### ISSUE TITLE
Improvement: "Choose date" item in the postponement "Own" menu

### ISSUE THREAD

**Issue by Moostek** [SimpleMobileTools/Simple-Calendar#1967]
Hello, it is nice that i can postpone the event with the "Own" setting. But i would like to see there the calendar mechanism that allows me to select the concrete day from the calendar. In actual "Own" version i can choose from "Minutes", "Hours" and "Days". It will be great if there will be fourth item **"Choose date**" to allow users choose concrete day (even the distant one). 

Because i do not know what number of days is egual to tuesday (in 3 weeks for example). I am sorry, but for this kind of postponement it is cumbersome and not practical. I really miss the **"Choose date**" button. 

This is finding from my own practical use of the Calendar app.

**Comment by tibbi** [comment]
Im not sure what you mean here, is it related to snooze?

**Comment by Moostek** [comment]
It is realated with postponement of the event. After i click "Postpone" and set the "Own" item, there is no way to set up the postponement on a concrete day. There are just items "Minutes", "Hours" and "Days". All this is about to add there (as the last item) an item "Choose date" which will will guide user to postpone the event on concrete day + the selection of this day will be made via calendar GUI.

**Comment by Aga-C** [comment]
I think it's the same as https://github.com/SimpleMobileTools/Simple-Calendar/issues/1911.

**Comment by Moostek** [comment]
It seems so. I mean to select the exact day/time inside of the postponement process.
