### ISSUE TITLE
Past events go missing!

### ISSUE THREAD

**Issue by lineinthesand** [SimpleMobileTools/Simple-Calendar#1970]
To my great dismay, I just found out that my past events I had in my CalDAV calendar in my nextcloud server just went missing. I can't figure out how that might have happened. Are they regularly deleted? If so, how can I turn that off?

I should add that when I look at the calendar in my nextcloud instance, all events are still there but refreshing the calendar in the Simple Calendar app does not make them appear in the app.

**Comment by tibbi** [comment]
you mean in the free version? Just reenable CalDAV sync in the app settings, guess you were using it previously too and those events weren't stored locally in the app only.

**Comment by lineinthesand** [comment]
No, the Pro version. Despite the sync being enabled, I can't get seem to get past events except for recurring ones.

**Comment by tibbi** [comment]
how far into the past you mean? Some services sync only 1 year to the past.

**Comment by lineinthesand** [comment]
Well, the event I'm looking for in particular way in October last year but not one year ago. So which services are you referring to? My nextcloud instance in my own server or DAVx5?

**Comment by lineinthesand** [comment]
I'm very sorry! I've checked DAVx5 now more thoroughly after your last comment and found that there was in fact a 90 day limit to synced events set for some reason. Nope that I deleted that I see all events again. I'm so happy!
