### ISSUE TITLE
Synchronize with .ics file from URL at a given interval

### ISSUE THREAD

**Issue by qz4** [SimpleMobileTools/Simple-Calendar#1971]
I find myself wanting to keep my Simple Calendar in sync with a .ics calendar provided from a website.

Currently I am able to manually download the file and import the events through the app interface, however this approach makes it possible to miss out on events, that may have been added to the up-to-date online calendar on a short notice.

The idea is to have Simple Calendar sync with the online .ics file once every 6 or 24 hours.

**Comment by tibbi** [comment]
The app itself has no internet access, so you have to use a sync adapter app for it, like DAVx5. Once it is set up, enable CalDAV sync in our app settings.
