### ISSUE TITLE
Different reminder settings for specific calendars

### ISSUE THREAD

**Issue by sevmonster** [SimpleMobileTools/Simple-Calendar#1972]
I have a primary calendar that I want loud repeat reminders for, but I also have a lower priority calendar whose notifications should ping once and not repeatedly. I would like to use the Alarm stream + loop for the primary calendar and Notification stream + no loop for the secondary priority one. Could per-calendar settings for reminders be added? (e.g. in event type edit dialog)

**Comment by tibbi** [comment]
you can already use the "Customize notifications" settings button on Android 8+, that allows customizing per audio stream

**Comment by sevmonster** [comment]
That doesn't change the repeat or the audio stream. I want a notification sound but not using the alarm volume as it is always set to very loud, and I don't want it to repeat. Unless I am missing something there is no way to accomplish this with Android notification settings.

**Comment by tibbi** [comment]
not sure if it is that much customizable, such things are system specific

**Comment by sevmonster** [comment]
So it's not possible to automate changing the audio stream/repeat, like how you can change it in the settings, before an alarm is triggered?

**Comment by tibbi** [comment]
nope, you cannot do that

**Comment by sevmonster** [comment]
That's lame. Thanks for looking into it. I will just make a quieter version of my notification sound with silence at the end to get around this limitation.
