### ISSUE TITLE
Widget Highlighting Day & Event

### ISSUE THREAD

**Issue by HonestAbe7** [SimpleMobileTools/Simple-Calendar#1976]
I love this free app. Is there a way to highlight the day and any events of the day with a custom color from the widget?

**Comment by tibbi** [comment]
which widget?

**Comment by HonestAbe7** [comment]
The calendar widget

**Comment by tibbi** [comment]
but the event list, monthly or current date?

**Comment by HonestAbe7** [comment]
The event list. Just wondering because it was Valentine's Day yesterday and it wasn't highlighted at all to stand out. Yeah, I could make a reminder though. Thanks for considering this.

**Comment by tibbi** [comment]
right, I see. Ill close this though as we dont plan adding such color customizations or highlighting
