### ISSUE TITLE
Attendee

### ISSUE THREAD

**Issue by Pyrrex** [SimpleMobileTools/Simple-Calendar#1977]
Attendee autocompletion (based on Contact name) when creating event used to work in version 6.21.3

Now, I have to type the whole email address for attendee name to show and synchronize with Nextcloud through DavX5. When I save the event, the email address is correctly converted to contact name. I just wish for prompt and autocompletion of attendees to work again.

**Comment by tibbi** [comment]
not sure what you mean here, nothing related has been changed

**Comment by Pyrrex** [comment]
Hmm, downgraded to 6.21.3 (which I should've done prior to opening a ticket) and you're right, the issue remains so the problem seems to be elsewhere.
