### ISSUE TITLE
move holiday assets to external repo

### ISSUE THREAD

**Issue by eneller** [SimpleMobileTools/Simple-Calendar#1978]
i think the [holiday ics files ](https://github.com/SimpleMobileTools/Simple-Calendar/tree/master/app/src/main/assets) could be located in an external repository and integrated via a git submodule or subtree.

This would allow for commits and issues on the external repo.

Also, a more in-depth disussion needs to be had if handling holidays as ics files is the way to go and if they need to be provided within the app.

**Comment by tibbi** [comment]
that isnt really planned
