### ISSUE TITLE
feature request: skip notifications if task marked as 'done'

### ISSUE THREAD

**Issue by Jens173** [SimpleMobileTools/Simple-Calendar#1980]
I have the following feature request:
if tasks are marked 'done', before notification shown, then notifications shall be skipped and not displayed any more

**Comment by Aga-C** [comment]
It's related to https://github.com/SimpleMobileTools/Simple-Calendar/issues/1838.

**Comment by junktext** [comment]
I concur with this feature request to help improve the UX.
