### ISSUE TITLE
Time picker in 24-hour time format looks weird

### ISSUE THREAD

**Issue by lka23** [SimpleMobileTools/Simple-Calendar#1987]
Hello,

I noticed a strange behavior of the time picker after updating to Android 12 and Simple Calender 6.21.5 Pro:
When creating a new event, it shows all 24 hours on the dial, see attached image:
![Screenshot_20230221-213153](https://user-images.githubusercontent.com/82543443/220452277-3a99498e-eb94-4b36-81ce-34fbf888887f.png)

I would expect hours 0/12 on the top, and 6/18 on the bottom, like on an analog watch.

Is this an issue with Simple Calender or is the time picker completely inherited by Android 12?

Let me know if you need more information and thank you so much for your great software,
lka23

**Comment by tibbi** [comment]
that is the system design, not ours. It will use the old design if you pick some other theme, not Material You.

**Comment by toxpal** [comment]
I have the same problem with 3 phones and can confirm switching to other theme fixed everything, but I have some questions:

1. It only happened about 3 weeks ago (after app update), time picker was "normal" for months. If it's really related to system theme, why did it work before update?
2. How it comes this "system design" works fine for other apps, but doesn't work with Simple Calendar? For example, system clock app (which is pre-installed) has "normal" time picker. Including all other apps I use.

Thanks.

**Comment by tibbi** [comment]
the date and time picker is set by us. We could revert to the old version, but I dont really want to. Those old dialog colors couldnt be customized so I want to go with the new one.

**Comment by toxpal** [comment]
That's very sad to hear (honestly, I can't think of a reason to re-invent a new time picker), but you provide a great calendar at no cost, which I'm thankful for and have no right to complain then.

**Comment by lka23** [comment]
FYI: Signal had the same issue (https://github.com/signalapp/Signal-Android/issues/12792) and solved it by updating the material library to 1.8.0 (https://github.com/signalapp/Signal-Android/commit/7bdb5fd76c3f0164392da2b5eb74d2793e27a3c1). Maybe that's an option for future releases.

**Comment by tibbi** [comment]
right thanks, will be fixed in the next app version
