### ISSUE TITLE
Feature request: open event when clicking on it on the widget

### ISSUE THREAD

**Issue by moshpirit** [SimpleMobileTools/Simple-Calendar#1988]
Right now if we press/click the widget it does nothing. It would be cool to open the task or the day view at least to open the event.

**Comment by tibbi** [comment]
which widget you mean?

**Comment by moshpirit** [comment]
"List of events" (4×5)

**Comment by Aga-C** [comment]
Where are you clicking the widget? Are you clicking a task/event, date in the header, name of the month, or the `No upcoming events.` text?

**Comment by moshpirit** [comment]
Ok, seems like this is already implemented but the widget didn't work. I tried removing it and putting it there again and seems like it works wonderfully :heart: 

Sorry for bothering, and congratulations on the magnificent software!
