### ISSUE TITLE
Event Title text alignment

### ISSUE THREAD

**Issue by poojagoswami7070** [SimpleMobileTools/Simple-Calendar#1990]
https://drive.google.com/file/d/1YCulRU2HZSkfbOGtojQQfUZ9Xvw8bgvH/view?usp=share_link

Unable to make event title text alignment in center.
Tried below code but didn't work :
eventTitlePaint = TextPaint(Paint.ANTI_ALIAS_FLAG).apply {
            color = textColor
            textSize = smallerTextSize.toFloat()
            textAlign = Paint.Align.CENTER
        } 
Testing device : android 12 version

**Comment by tibbi** [comment]
we dont give out such coding support

**Comment by poojagoswami7070** [comment]
https://github.com/SimpleMobileTools/Simple-Calendar/blob/master/fastlane/metadata/android/en-US/images/phoneScreenshots/1_en-US.jpeg

Here I can see text in center in your official snapshot so how is it possible as I am getting event title text in LEFT align only
