### ISSUE TITLE
Yearly view through Clock Widget

### ISSUE THREAD

**Issue by ConConner** [SimpleMobileTools/Simple-Calendar#1996]
My father uses a Motorola One as his smartphone. These Motorola phones have a special widget that combines the date, time and weather like with all other android smartphones. He used to open his Simple Calendar through that widget and it would instantly display the yearly view. Now after some random update it always displays the daily view and he has to switch to the yearly view manually. If the app is launched through the actual icon it remembers the last used view. While this is quite the minor problem its a big annoyance for my father and he has since been looking for a new Calender app even though this one was perfect before.

I am honestly not sure if this is intended behaviour, but if it is I would suggest to add an option for the default view when launched through the Weather/Clock widget just like the similar option with the task list widget.

**Comment by tibbi** [comment]
some widgets require a specific view to be open so that might be this case too. Some customization might be added in the future on our side, but it is already reported somewhere.
