### ISSUE TITLE
Add a few more alarm times

### ISSUE THREAD

**Issue by PanderMusubi** [SimpleMobileTools/Simple-Calendar#1997]
Please add at least the following alarm times:
- 15 minutes
- 45 minutes
- 2 hours
- 3 hours

See below the difference between Etar and this app. This would be a hurdle less for others and me to completely switch to this app.

![Screenshot_20230302-115431_Calendar_1_1](https://user-images.githubusercontent.com/198964/222592128-568287b4-d879-4a0a-bb19-58a7bcd8e21c.png)

![Screenshot_20230302-115503_Etar_1_1](https://user-images.githubusercontent.com/198964/222591890-3f45603d-768a-4d43-a045-eb19237cd407.png)

**Comment by tibbi** [comment]
you can use Custom

**Comment by PanderMusubi** [comment]
Since there is enough space and these are very common alarm times, I hope you reconsider. :shamrock:
