### ISSUE TITLE
Plan to display synced calendars 

### ISSUE THREAD

**Issue by EtienneM** [SimpleMobileTools/Simple-Calendar#2]
Hi! 

I just saw your projects and loved the idea. For this one, I am wondering if you plan to display the synced calendar? Or will you keep it simpler?

**Comment by tibbi** [comment]
what do you mean by synced calendar? Adding some google calendar events, or just syncing this one through multiple devices somehow?

**Comment by EtienneM** [comment]
I set up some caldav account on my phone. So I have a couple of calendar synced with an Owncloud installation and stuff like that. I would like to use your software to display these events.

**Comment by tibbi** [comment]
I will have to check how does it work as I dont have any experience with it. It will not be on high priority for now :)

**Comment by Yowlen** [comment]
I believe they're referring to the built-in Android Calendar Storage. When a calendar is synced (either by OwnCloud, Google, or wherever), it's stored here. There's some open source calendars on F-Droid such as Etar that you can probably get some ideas from to help implement it.

And yes, I have to agree this would be a nice addition.

**Comment by kinclma1** [comment]
Not having what @Yowlen says makes the app useless for me.

**Comment by Docbroke** [comment]
use of built in calendar storage would be disastrous for someone who is not using gapps or those who have removed all proprietery google apps from their system.

**Comment by Yowlen** [comment]
@Docbroke Actually, the Calendar Storage is part of AOSP, not Google's proprietary stuff. Android-based CalDAV sync apps use this independent of GApps, for example.

**Comment by mdkuser** [comment]
Yes, please support CALDAV sync support!

**Comment by tibbi** [comment]
caldav sync is already available in the f-droid build too
