### ISSUE TITLE
Workaround for webcalendars?

### ISSUE THREAD

**Issue by voidscuttle** [SimpleMobileTools/Simple-Calendar#2007]
I would like a method of subscribing to webcals but as I understand it the Simple suite explicitly does not make use of network functions. Is there a recommended solution to this? 

- I have tried ICSX⁵ but it does not show up in Simple Calendar as an alternative. 
- DAVx⁵ cannot import webcals to Simple Calendar.
- I was looking at Nextcloud CalDAV to DAVx⁵ to Simple Calendar but it seems Nextcloud's calendar does not import webcal to the CalDAV calendar.
- Most webcals do offer ics files however I do not want to have to do manual re-downloads and re-imports of these files whenever an event is updated.  

How have others solved this problem?

**Comment by voidscuttle** [comment]
The reason the calendar wasn't showing under the CalDAV setting was because I had disabled the system calendar, which apparently is required.

**Comment by mullimanko** [comment]
I have the same problem. Can you please describe how you managed to subscribe to webcals? You listed several points in your first post, which one worked then?
