### ISSUE TITLE
[Feature request] option to create links between events

### ISSUE THREAD

**Issue by User2564** [SimpleMobileTools/Simple-Calendar#2011]
I hope this message finds you well.
I am a very happy user of "Simple-Calendar" and would be more than happy to be a beta tester if desired.

I have a nightly week long shift job and use ShiftCal, which is being successfully sync'd.

To be very detailed, it would be very helpful I could click on an instance (in this case the first on Monday) and then automatically set a reminder task to repeat for the following Monday.

Ideally it would be nice if I could also enable an option to delete the reminder task if the conditions are not meet, i.e the associated event/calendar has been deleted.

**Comment by tibbi** [comment]
it isnt on the roadmap
