### ISSUE TITLE
Enhancements from a Student

### ISSUE THREAD

**Issue by Osiris-Team** [SimpleMobileTools/Simple-Calendar#2012]
I couldn't find a good calendar app until I stumbled on this. Thank you for making this great app open source!
I have a few enhancements that would help a student like me a lot:
- Life sections. Simply a special event type that has a start and end date, that normally covers multiple months.
Recurring events then can be assigned to such a life section and automatically end when the life section ends.
In my case, a life section would be a single semester.
- Event tags. Small bits of information which can be easily added to each event, and
are also shown in the week view. You can add multiple tags to an event. In my case room number or name of the teacher giving the course. Its pretty annoying to have to enter the same room number and the teacher's name multiple times for each new event thus this would be really helpful. Example:
![image](https://user-images.githubusercontent.com/59899645/226191258-093d645e-d006-4691-a061-55a1ec64b047.png)

**Comment by tibbi** [comment]
those are way too advanced and user specific, dont really expect having that

**Comment by Osiris-Team** [comment]
Np I'll create a fork then.

**Comment by dumblob** [comment]
@Osiris-Team please post a link to your fork repo - I would be very interested in collaboration.

I have asked about forking this repo in https://github.com/SimpleMobileTools/Simple-Calendar/issues/1771#issuecomment-1176585779 . Feel free to read all the comments and related issues (#1764 #1686 #1776 #1779 #1806 ...) to get a better understading how the discrepancy between the community and Simple-Calendar dev team looks like.

@jaimet could be of interest to you too.

**Comment by Osiris-Team** [comment]
@dumblob Sure there you go: https://github.com/Osiris-Team/Simple-Calendar
But Im not planning on investing much time in this. It took the complete day already only to add the database part for my Event Tags idea...

**Comment by dumblob** [comment]
Thanks!

>But Im not planning on investing much time in this. It took the complete day already only to add the database part for my Event Tags idea...

Do you plan to provide a build through some repo (e.g. IzzyOnDroid)? That would necessitate renaming of the project though.

If so, will you turn on the "Issues" tab of your fork?

**Comment by Osiris-Team** [comment]
@dumblob yeah I guess if there is demand for my changes, sure I can also do a release with the apk.

**Comment by dumblob** [comment]
This issue tracker is a strong evidence that there is demand for **any** changes incl. yours :wink:. Feeling like turning on the "Issues" tab in your fork repo?
