### ISSUE TITLE
Feature request: ui colors based on calendar colors

### ISSUE THREAD

**Issue by paskalito** [SimpleMobileTools/Simple-Calendar#2016]
Thank you so much for your apps, they are very good and to me provide a lot of usability and stability to android. making it a ton more usable/bearable!

i was confused/bewildert about the lately added use the material you color for the ui change. (because a i really hate material you) but b, i thought i was in the wrong calendar. (since i have a calendar in the current accent color, which is not my main calendar though)

spending 7 seconds in the preferences let me revert back to the before behaviour, thank you for making that easy and straight forward.

but it made me think that if the colors in the "create/edit an event" dialog would match the calendar colors it would actually be helpfull in a functional and also somewhat unconscious way.

still think it should be an optional option, but probably it could be a usefull ui element.

thanks a lot
paskalito

**Comment by tibbi** [comment]
that isnt really on the roadmap, it could become too messy
