### ISSUE TITLE
Weekly view "Start week with the current day" only uses UTC?

### ISSUE THREAD

**Issue by aschaap** [SimpleMobileTools/Simple-Calendar#2018]
With "Start week with the current day" enabled, the concept of today seems to be defined by UTC+0 time rather than the timezone my events and my system settings are configured as.

I found `DateTime().withZone(DateTimeZone.UTC).toString()` was added to MainActivity.kt (line 833) for this setting in #1491, which I surmise may need to use the current timezone for this behaviour to work correctly in any timezone other than UTC+0.

**Comment by naveensingh** [comment]
@tibbi I believe this was fixed by https://github.com/SimpleMobileTools/Simple-Calendar/pull/2077
