### ISSUE TITLE
Can't find my main google account when using calendar sync

### ISSUE THREAD

**Issue by jobplays21** [SimpleMobileTools/Simple-Calendar#2031]
I want to sync my calendar from my main google account but i can't find it on the list
![Screenshot_2023-03-28-16-53-04-251_com simplemobiletools calendar pro jpg_1](https://user-images.githubusercontent.com/126670924/228184827-44e3042b-5632-4259-9e1f-d22b14f63b1f.png)
. It only shows 3 google account but i have 20+ google accounts signed in to my device

**Comment by jobplays21** [comment]
> does any other calendar app show them? We show whatever is available on your device

I tried google calendar but it shows my google account

**Comment by tibbi** [comment]
isnt the dialog scrollable?

**Comment by jobplays21** [comment]
> isnt the dialog scrollable?
Not scrollable, i also tried clear data and downgrade app version but not working

**Comment by tibbi** [comment]
do you have write/read permission to the wanted calendar? I dont think it is an issue on our side
