### ISSUE TITLE
Feature: change account calendar colors 

### ISSUE THREAD

**Issue by hansaplasst** [SimpleMobileTools/Simple-Calendar#2035]
I'm using 4 calendars. Would be nice to have an option to give all calendars their own color. 

I used to use pascalfree's [calendar-color](https://github.com/pascalfree/calendar-color). But this doesn't work anymore since it was build for an older android version.

**Comment by tibbi** [comment]
are you syncing through Google or some other CalDAV calendar through DAVx5?

**Comment by hansaplasst** [comment]
Through DAVx5

**Comment by tibbi** [comment]
You should be able to change the color in our app already. For each individual account, DAVx5 allows you to change the setting for "Manage calendar colors" from (1) 'Calendar colors are reset at each sync' to (2) 'Calendar colors can be set by other apps'. You have to use the second option.

**Comment by hansaplasst** [comment]
Yes! Found the option. It's in: `Settings -> Manage event types`
BTW: Nice of you to give some DAVx5 support :wink: :+1:
