### ISSUE TITLE
Notification "mark competed" action

### ISSUE THREAD

**Issue by R715B** [SimpleMobileTools/Simple-Calendar#2037]
Task notifications that aren't completed within a close enough timeframe to when the notification was generated will not mark said task as completed in the Simple Calendar (F-Droid) app itself.  I'm aware there is another submitted issue that has addressed notifications not being cleared by completing tasks within the app.  Between these two issues, more often than not it feels as though completing tasks within the app and in the notifications are independent of one another.

**Comment by Aga-C** [comment]
How it's different from https://github.com/SimpleMobileTools/Simple-Calendar/issues/1838 and https://github.com/SimpleMobileTools/Simple-Calendar/issues/1980/?
