### ISSUE TITLE
[QUESTION] What event triggers data backup in latest version?

### ISSUE THREAD

**Issue by HarriBuh** [SimpleMobileTools/Simple-Calendar#2051]
While I'm very happy to see this feature finally getting to Simple Calender, there is no hint or option how to specify the backup action itself yet. Since the update the app hasn't done a single backup, for example.

I ask for a more detailed explanation and option inside the app to determine it, like a schedule (max. amount of backups per day etc.)
The current function is almost useless, because it doesn't work at all.

**Comment by tibbi** [comment]
it triggers at 6 AM every day (or at the time the device is turned on), there are no other triggers yet. We just implemented the easiest solution to begin with.

**Comment by HarriBuh** [comment]
The app does not create an automated update, either when I turn on my phone (~ 6 am every morning), nor at a later hour.

**Comment by HarriBuh** [comment]
Android 13
App version 6.21.7
I do use Android's energy saving, BUT this doesn't affect other backup app doing their jobs effectively.
So should I try disabling battery saving for your app and observe it's behaviour again?

P.S.: And you are 10% certain this issue is not related to Android 13‘s quite aggressive rights management?

**Comment by tibbi** [comment]
it is hard to say what is breaking such features, there are just too many possible device or system specific issues :/ Maybe check https://dontkillmyapp.com/ for some potential issues.

**Comment by HarriBuh** [comment]
I just rebooted my phone and got a tiny error notification from your app. It was too fast to read, but it definitely contained something with "java" and "Io".

**Comment by tibbi** [comment]
does manual exporting work from the top Menu -> Export events?

**Comment by HarriBuh** [comment]
Yes, I have been doing out this way for months, no issues.

**Comment by Naveen3Singh** [comment]
@HarriBuh Hi!

Can you share a screenshot of your "Manage Automatic Backups" dialog configuration? 
(The IO error might happen if the export file already exists and it was created by some other app or an uninstalled version of Simple Calendar)

**Comment by HarriBuh** [comment]
> @HarriBuh Hi!
> 
> Can you share a screenshot of your "Manage Automatic Backups" dialog configuration? (The IO error might happen if the export file already exists and it was created by some other app or an uninstalled version of Simple Calendar)

Sure:

![markup_1000008560](https://user-images.githubusercontent.com/123186113/233800498-5b172ad2-e291-4e5c-a4d9-cd2d4e59d7c1.png)

**Comment by Naveen3Singh** [comment]
Here's a test APK with a fix: https://github.com/Naveen3Singh/Simple-Calendar/releases/download/file_perm_fix/calendar-prepaid-debug.apk

Please check if it's working for you now.

**Comment by HarriBuh** [comment]
![Screenshot_20230424-064050](https://user-images.githubusercontent.com/123186113/233903499-01593a2d-6b3d-49d2-ad50-7f9c3cddea98.png)

I can confirm it's finally working. 👌

**Comment by HarriBuh** [comment]
I was hoping for this apk to become a hotfix to be released soon after. Will this patch be included in the next release then?
