### ISSUE TITLE
Feature Request: Add View "Weekly and daily view"

### ISSUE THREAD

**Issue by ReaderGuy42** [SimpleMobileTools/Simple-Calendar#2052]
Could you maybe add a view type that works like the "Monthly and daily view" but instead has "Weekly and daily view"? I think that would be super useful since you could get more information at a glance than the monthly which just shows whether a day has any events or not.

Thanks :)

**Comment by ReaderGuy42** [comment]
Hi there, any plans for this, or is it even possible? Thanks :)

**Comment by tibbi** [comment]
you can already see all days events at the weekly view

**Comment by ReaderGuy42** [comment]
Yes, I see that, but I meant a similar view to the Monthly and daily, but instead with the weekly view on the top and the list view for daily on the bottom. Is this possible?

**Comment by tibbi** [comment]
It is possible, but doesnt really make sense to me..

**Comment by ReaderGuy42** [comment]
That's too bad, but no worries. 

I just thought the Weekly view gives me a lot more information than the monthly view, because Monthly just shows if there is ANY event or task, and Weekly shows more info on the schedule of when something happens. But I also need the List view because I need the context that I give in the Description or Location field that I can't see in the Weekly (or the Monthly of course).
