### ISSUE TITLE
Feature request: created tag

### ISSUE THREAD

**Issue by kevinde91** [SimpleMobileTools/Simple-Calendar#2054]
Hello,

First of all: you are doing a great job with this app!

Is it possible to display the creation and last-modified dates in the event editor?
This would be fetched from the tags 'created' and 'last-modified' according to IETF: https://datatracker.ietf.org/doc/html/rfc5545#section-3.8.7.3

In the [Tasks-App](https://github.com/tasks/tasks) this looks like that:
![IMG_20230420_111344](https://user-images.githubusercontent.com/77301944/233321386-163abce5-5d11-43ea-8e99-8ff47b8df1db.jpg)

Thank you.

Kind regards,
Kevin

**Comment by tibbi** [comment]
not really, it isnt on the roadmap
