### ISSUE TITLE
Export to CSV

### ISSUE THREAD

**Issue by bovergaauw** [SimpleMobileTools/Simple-Calendar#2055]
It would be great to be able to export events and tasks to CSV files and not only to ICS files, especially as I haven't found any open source ICS-to-CSV converters for Android (or Windows or Linux for that matter).

**Comment by tibbi** [comment]
we definitely dont plan exporting events into a .csv, that sounds like a very bad idea

**Comment by bovergaauw** [comment]
Dear Tibor,

Can you tell me */why/* you consider exporting of events to CSV very bad idea? AFAIK Lightning/Thunderbird, Google Calendar and Outlook support it or supported it at some time.

Thanks in advance.

Best regards,
Bo

22 Apr 2023 23:05:59 Tibor Kaputa ***@***.***>:

**Comment by tibbi** [comment]
because there are many possible fields that are difficult to separate as .csv. It is a really primitive format, .ics is a lot better standard recognized by any popular calendar app

**Comment by bovergaauw** [comment]
Dear Tibor,

I fully agree that a generic ICS-to-CSV converter is hard to write, but an export from Simple Calendar which only uses a handful of fields should be much easier than a generic converter. ICS is great for calendars, but I use Simple Calendar as a basic diary which I then import in Calc.

I'll try to create a PHP command-line tool to convert Simple Calendar generated ICS files to a CSV file.

Best regards,
Bo

23 Apr 2023 09:42:53 Tibor Kaputa ***@***.***>:
