### ISSUE TITLE
Events ending at midnight are displayed at a wrong day in the week view

### ISSUE THREAD

**Issue by bodqhrohro** [SimpleMobileTools/Simple-Calendar#2067]
![Screenshot_20230506_082037_com simplemobiletools calendar pro](https://user-images.githubusercontent.com/2134486/236601847-860745a0-ce28-4dda-a32f-9b265fab784d.jpg)
![Screenshot_20230506_082045_com simplemobiletools calendar pro](https://user-images.githubusercontent.com/2134486/236601858-5055a87b-4495-4aa2-aad0-23e964ab2aa3.jpg)

**Comment by tibbi** [comment]
what app version is that?

**Comment by bodqhrohro** [comment]
6.21.7 Pro.

I had a much older version before and upgraded to check if the bug is still relevant; the behaviour was the same there.

**Comment by tibbi** [comment]
what is exactly the issue there? The event is displayed properly there. You can toggle showing events spanning across midnight at the top bar in the app settings

**Comment by bodqhrohro** [comment]
The problem is that it is inclusive. IMO, if an event ends exactly at 00:00, is should still be displayed at the end of the day rather than be classified as "spanning *across* midnight". It can be circumvented by ending an event at 23:59, but that's merely a kludge.

I disabled the setting and now the event ending at 00:00 shares a cell with an event from 00:00 to 00:30. This does not happen for events whose beginning time matches the ending time of the previous event at any time other than 00:00.

**Comment by tibbi** [comment]
it works as expected, 0:00 is already next day
