### ISSUE TITLE
[help] how to access the "automated periodic background export" feature? 

### ISSUE THREAD

**Issue by serverless76** [SimpleMobileTools/Simple-Calendar#2068]
I cannot find any setting or option related to triggering automated exports. 
how does this feature work?

App version: 6.21.7 via Fdroid.
Android version: 10
Device: POCO M3

**Comment by tibbi** [comment]
it is in the app settings

**Comment by serverless76** [comment]
I really can't find the setting... 
Here is a long screenshot of my settings screen:-
![Screenshot_2023-05-07-07-05-09-528_com simplemobiletools calendar pro](https://user-images.githubusercontent.com/128665931/236653419-2ed38e4b-5d48-4c11-b3d7-d7b471f389a8.png)

**Comment by Aga-C** [comment]
> This feature is only available on Android 11 and above (for now)

https://github.com/SimpleMobileTools/Simple-Calendar/pull/2027

**Comment by tibbi** [comment]
right, didnt notice your low OS version
