### ISSUE TITLE
UK holidays incorrect

### ISSUE THREAD

**Issue by Woodzrul** [SimpleMobileTools/Simple-Calendar#207]
Device - OnePlus 2
Simple Calendar - 2.5.7

Menu -> Add holidays -> United Kingdom

UK holidays appear with incorrect dates. An example below;

Correct: August 28th Monday, Summer Bank Holiday
Incorrect: August 30th Wednesday, Summer Bank Holiday

Can confirm the date & time on phone are correct.

Please resolve.

Thanks

**Comment by Woodzrul** [comment]
When importing an .ICS file from the below site then all public holidays for the United Kingdom display correctly (only check 2017). 

http://holidays.kayaposoft.com/public_holidays.php

If you're able to amend your database with those same dates from the link above then I'd greatly appreciate it.

**Comment by tibbi** [comment]
Hey, Ive updated 2 holidays, not sure about the rest. Theres some extra events in the list you provided, some events are missing. If you want to help cleaning it up please go to https://github.com/SimpleMobileTools/Simple-Calendar/blob/master/app/src/main/assets/unitedkingdom.ics , log into github, press the pencil at the top right corner of the file, update the strings as necessary, then submit the changes with some commit message. That would make it a lot easier for me, as Im not sure how to handle the differences between files. The updated holidays will be added in the next version 2.7.0 released soon.  Thanks!

**Comment by Woodzrul** [comment]
Appreciate this. Thanks
