### ISSUE TITLE
An event occasionally gets invisible if dragged back into the same place

### ISSUE THREAD

**Issue by bodqhrohro** [SimpleMobileTools/Simple-Calendar#2070]
After an app restart, it's displayed well again.
https://user-images.githubusercontent.com/2134486/236712641-fbb570ac-6cb0-48e3-b3bd-2386a91c8364.mp4

**Comment by bodqhrohro** [comment]
6.21.7 Pro
EMUI 9.1.0

**Comment by Dragurashiphylax** [comment]
Same on Redmi Note 8 Pro (Android 11 RP1A.200720.011, MIUI Global 12.5.15 Stable)
