### ISSUE TITLE
[feature] Export specific entries & "Export past entries too" clarification

### ISSUE THREAD

**Issue by QuestioningEspecialy** [SimpleMobileTools/Simple-Calendar#2073]
I'd like to import my phone's events to my email's calendar without having duplicates, so the mass export isn't an option.

It's not clear what entries get excluded if the "Export past entries too" box is unchecked. Mind explaining that somewhere?

**Comment by tibbi** [comment]
well, the ones that happened in the past... And the recurring ones that wont have any future occurrence anymore.

**Comment by QuestioningEspecialy** [comment]
@tibbi So leaving "Export past entries too" unchecked would cause the export to only have entries from _today_ then?

**Comment by tibbi** [comment]
ye, either ones happening today, or the repeating ones starting in the past and still have some occurrences in the future too
