### ISSUE TITLE
Add SimpleMobileTools app's on accrescent

### ISSUE THREAD

**Issue by guilamoff** [SimpleMobileTools/Simple-Calendar#2081]
Could you add your SimpleMobileTools app's to the new Accrescent application store. 
Accrescent is an open-source, next generation application store and is very easy to use. Here is the link https://accrescent.app/features

Sincerely

**Comment by tibbi** [comment]
move it at the General Discussion repo please as it affects all apps

**Comment by guilamoff** [comment]
Ok
