### ISSUE TITLE
widget shows events from previous day, cluttering the display

### ISSUE THREAD

**Issue by kubuntu-newbie** [SimpleMobileTools/Simple-Calendar#2082]
Using Simple Calendar version 6.21.9 Pro

to duplicate:
add widget "Calendar today's date" to the screen
configure to show events happening "Today only"

expected behavior - widget displays today's events _only_

instead, widget displays events from the previous day also and you have to scroll to see today's events

as a feature request - it would be really nice to be able to "show next event only" or "show next N events" so you can have a smaller widget and only see next N events

**Comment by tibbi** [comment]
what events are those, dont they end just today?

**Comment by kubuntu-newbie** [comment]
> what events are those, dont they end just today?

just various short events from day before, 30 min - 1 hour long, but since there a few of them and they are listed first, makes it hard to see upcoming events without scrolling. at least "yesterday's" events show up greyed out

**Comment by seniorm0ment** [comment]
Can confirm, I see stuff from yesterday in the widget

**Comment by WhiteNight121** [comment]
Seeing the same thing

**Comment by e-t-l** [comment]
This might actually just be a misconfigured setting. It took me a bit to figure out. Open the app, go to Settings, and scroll down to the Event List section. The first item is "Display events from the past [     ]." Is this currently set to something like "1 day"? If so, try setting it to something more reasonable, like "1 hour" or "30 minutes" (or even "0 minutes" if you don't want to see any event after its end time!)

Does that solve your issue?

**Comment by WhiteNight121** [comment]
Well ya I think that did it as far as I can tell I'll know for sure tomorrow night

**Comment by e-t-l** [comment]
> Well ya I think that did it as far as I can tell I'll know for sure tomorrow night

An easy way to check is to open your calendar and create an event for _yesterday_, save it, then go to the widget and see if that event shows up.

And if this did solve your problem, please close this Github issue :)

**Comment by WhiteNight121** [comment]
> > Well ya I think that did it as far as I can tell I'll know for sure tomorrow night
> 
> An easy way to check is to open your calendar and create an event for _yesterday_, save it, then go to the widget and see if that event shows up.
> 
> And if this did solve your problem, please close this Github issue :)

That looks to of fixed it thanks

**Comment by kubuntu-newbie** [comment]
that worked! thank you.
Perhaps the description in the settings for this option could be a bit more clear.
