### ISSUE TITLE
Recurring events from one day to another doesn't use space correctly on month view

### ISSUE THREAD

**Issue by Dragurashiphylax** [SimpleMobileTools/Simple-Calendar#2084]
![IMG_20230521_130244.jpg](https://github.com/SimpleMobileTools/Simple-Calendar/assets/99643690/b2b9ae6c-def6-47d7-aad3-51786fb816df)

Basically the reccuring event is going only down and down instead of using free space on the top of the day tiles.

**Comment by tibbi** [comment]
that is part of a wider optimalization of used space, already reported somewhere
