### ISSUE TITLE
feature to simply add notes

### ISSUE THREAD

**Issue by cosmin86** [SimpleMobileTools/Simple-Calendar#2087]
Please consider adding the feature to quickly add simple notes from the "+" sign, in addition to Task and Event. Another useful feature would be the possibility to drop a pin to automatically record the date/time of an action - for example it would be useful as a record of coming to and leaving from the workplace times based on which monthly worked hours may be calculated.

**Comment by tibbi** [comment]
those arent really on the roadmap
