### ISSUE TITLE
App breaks when changing months after the actual

### ISSUE THREAD

**Issue by anonimou0** [SimpleMobileTools/Simple-Calendar#21]
I can browse months from before the actual. Like from August to July, June..
Changing from June to July and August works normal. If I try to advance to September, the app freezes.

[logcat.txt](https://github.com/SimpleMobileTools/Simple-Calendar/files/421272/logcat.txt)

**Comment by tibbi** [comment]
retest with 1.17 please

**Comment by anonimou0** [comment]
that seems solved! thanks =)
