### ISSUE TITLE
2.6.1 not in F-Droid because it links against com.google.android.gms:play-services-auth 

### ISSUE THREAD

**Issue by tpo** [SimpleMobileTools/Simple-Calendar#210]
I'd like to document the current state of Simple-Calendar in F-Droid so people looking for a solution to their problem (see #195 and #188) can read up on what's the situation.

Currently the build of 2.6.1 is disabled in F-Droid, because Simple-Calendar links against com.google.android.gms:play-services-auth. See https://f-droid.org/wiki/page/com.simplemobiletools.calendar#2.6.1 and https://github.com/SimpleMobileTools/Simple-Calendar/issues/138#issuecomment-321748848.

Linking against com.google.android.gms:play-services-auth is apparently necessary in order to implement Google sync - see #138.

It seems that as soon as CalDAV support will be implemented (#150) then #138 could go away and Simple-Calendar could again be built in F-Droid.

**Comment by tibbi** [comment]
Hey yea, Ive seen it, they dont want google stuff. The build should be reactivated once the next version is released, so Ill close it now.

**Comment by tpo** [comment]
Hi tibbi,

I'd suggest to keep this open and close it either with a commit, or once you've got the next version released.

The idea behind the reporting of this bug was, that people that run into the same/similar/releated problem, can find the status of the problem quickly. They won't find it in the closed tickets (my guess).

Anyway, many thanks, I very much appreciate your creation and care!
*t

**Comment by tibbi** [comment]
okay, Ill close it when updating the app version :)

**Comment by varakh** [comment]
Fdroid build isn't published yet. Any info on that?

**Comment by tibbi** [comment]
the commit for readding Simple Calendar has been accepted 5 days ago, not sure why havent they published a new app yet. Ill try getting some more info.

**Comment by varakh** [comment]
Ok, thanks. I also updated some german translations. See the pull request.

**Comment by tibbi** [comment]
alright, thanks. I see that the gallery wasnt updated for 4 days either even tho it never had any issues like the calendar. Guess they arent updating the apps every 1-2 days anymore like they used to, just less frequently.

**Comment by varakh** [comment]
Alright. We have to wait then. Meanwhile I translated Camera and Gallery. Have a nice day. :-)

**Comment by tibbi** [comment]
seems to be available on f-droid already

**Comment by tpo** [comment]
Yes! Thanks a lot Tibor!
