### ISSUE TITLE
[Bug] Editing a recurring event restores changed/deleted event occurrences

### ISSUE THREAD

**Issue by e-t-l** [SimpleMobileTools/Simple-Calendar#2103]
### Steps to reproduce
1. Create a recurring event.
2. Change or delete an occurrence of the event, using the "Update/Delete the selected occurrence only" radio option.
3. Edit the recurring event, using either the "Update this and all future occurrences" OR "Update all occurrences" radio option.

### Expected Behavior
All _still-existing_ occurrences of the original recurring event are updated, while changed/deleted occurrences that had been updated or deleted stay that way.

### Actual Behavior
The changed/deleted occurrence is created anew, with the updated event data. If the occurrence had been changed, the changed version event _does_ still exist. 

It's like Simple Calendar is "forgetting" that certain occurrences have been changed/deleted, and is creating the recurring event from scratch.

### Example scenario
1. Create "pick up kids from school" recurring at 2pm weekly on M,T,W,Th,F.
2.  Next Tuesday the kids have a field trip, so _change_ pick-up event to 5pm for that date only. Next Wednesday they'll take the bus home, so _delete_ that date only.
3. The kids have begun after-school football, so change the start time of all 2pm occurrences to 4pm.
4. Observe that a 4pm occurrence has been created on both Tuesday and Wednesday. The 5pm Tuesday event still exists.

### Additional info
My calendars are synced with a remote CalDAV server, so it's possible this bug only exists for CalDAV calendars. I haven't tested it with a local-only calendar yet.
I use Simple Calendar v6.21.9 Pro (F-droid install), running GrapheneOS 13 on a Google Pixel 7.

**Comment by Aga-C** [comment]
This fix will probably solve your problem: https://github.com/SimpleMobileTools/Simple-Calendar/issues/981#issuecomment-1566303726. You can download it and check if it works correctly on this version.

**Comment by e-t-l** [comment]
> This fix will probably solve your problem: [#981 (comment)](https://github.com/SimpleMobileTools/Simple-Calendar/issues/981#issuecomment-1566303726). You can download it and check if it works correctly on this version.

That did it! So should I keep using that debug app version for now? Any estimate of when the changes will be pushed to release version?

**Comment by Aga-C** [comment]
Please wait until the official release.

**Comment by Naveen3Singh** [comment]
@tibbi I guess we can close this as completed by #2093
