### ISSUE TITLE
Local termin crash

### ISSUE THREAD

**Issue by navigithu** [SimpleMobileTools/Simple-Calendar#2107]
Hi, by creating a new  local termin (german version, the english one is, I guess, an appointment or a date) the app crashes.I am using the 6.21.9 version. The Version 6.21.7 is not affected and runs perfectly (on the same type of the  phone and the same android version). Creating a new task works okay. Thanks in advance.

**Comment by navigithu** [comment]
Hi, yes, my standard calender is the one synchronized by the davx5. If I choose the local one as the standard one in the general settings everyting is fine. But if I want to switch the davx5 to local one inside the window for the new appointment there are allways a crash. A new task works in any case. I hope it helps. Thanks a lot.

**Comment by tibbi** [comment]
should be fixed in 6.22.0
