### ISSUE TITLE
[Feature request] Font size setting for the widget and "monochrome" option

### ISSUE THREAD

**Issue by kubuntu-newbie** [SimpleMobileTools/Simple-Calendar#2109]
Would be really awesome to be able to change the font size/weight in the widget, especially in the "event list" view. It would also look great if there was a "monochrome" option or just hide the calendar colors on the widget for those who are using Graphene OS that has a very monochrome look to it

**Comment by tibbi** [comment]
report things one by one please, if they havent been reported yet
