### ISSUE TITLE
Adding nextcloud davcal calendar crashes the app

### ISSUE THREAD

**Issue by mdkuser** [SimpleMobileTools/Simple-Calendar#211]
I tried to add my nextcloud davcal calendar but as soon as I add the calendar the app crashes and keeps crashing until I rewoke calendar permission.
No problem using nextcloud calendar with google calendar app...

**Comment by tibbi** [comment]
Hey, can you please shoot me a mail at hello@simplemobiletools.com? I could send you a test version to find out whats wrong. Thanks

**Comment by mdkuser** [comment]
It was due to an invalid entry, I removed it from the calendar and now it is working.
Thanks for your support finding out the malformed entry.
