### ISSUE TITLE
[Feature] Subscribe to an iCalendar URL

### ISSUE THREAD

**Issue by ShamrockLee** [SimpleMobileTools/Simple-Calendar#2117]
It would be great to support public calendar subscription through the iCalendar URL. They ofen ends with `.ics`.

**Comment by tibbi** [comment]
the app has no internet access, so we cannot fetch anything ourselves. But you can already set it up in DAVx5 app, then enable CalDAV sync in our app to show the events.

**Comment by ShamrockLee** [comment]
For people who have similar questions:

1.  You need to install [ICSx⁵](https://github.com/bitfireAT/icsx5) and manage the .ics URL subscription there.

2.  Then in Simple Calendar,
    1.  Go to `Settings` through the triple-dot menu.
    2.  Check the `CalDAV Sync` checkbox.
    3.  Tap `Manage synced calendars`
    4.  See the subscribed calendar appear under the `CALENDAR SUBSCRIPTIONS` section.
    5.  Check the calendars you would like to see.
