### ISSUE TITLE
Current version 2.7.4 not available in F-Droid Store

### ISSUE THREAD

**Issue by Krawei** [SimpleMobileTools/Simple-Calendar#212]
Good morning Team,

it seems that there's a gap again between Play store 2.7.4) and F-Droid (2.5.7) regarding the available versions.

Please take a look on this.

Kind Regards, Krawei

**Comment by tibbi** [comment]
ye its related to #210 , Ill update f-droid soon

**Comment by varakh** [comment]
Still no update? :(
