### ISSUE TITLE
Widget Preview Events?

### ISSUE THREAD

**Issue by BsNoSi** [SimpleMobileTools/Simple-Calendar#2128]
Instead of previous vevents I would like to see events of the next day(s).

**Comment by tibbi** [comment]
you can already select what events you want to see. If past ones too, or not.

**Comment by BsNoSi** [comment]
How can I configure display of events in wiget taking place tomorrow?

**Comment by tibbi** [comment]
which widget you mean, the event list one?

**Comment by BsNoSi** [comment]
Yes. I would also like to see dates for the following day in the preview, so that I can prepare for them. In the configuration, I have only found one option to display past days.

**Comment by tibbi** [comment]
after you drag the widget on the home screen, at the top you can select what events you want to see. If within 1 week only, or what ones.

**Comment by BsNoSi** [comment]
I removed the widget and placed it again – this setting I have missed. I expected this setting in configuration, where I can set up the display of past events.
Everything fine now – thank you!
