### ISSUE TITLE
[bug] Simple Calendar crash on save of a local event 

### ISSUE THREAD

**Issue by LucileDT** [SimpleMobileTools/Simple-Calendar#2130]
*Note: I use the calendar in French so I may not have the exact labels in English, I'm guessing them*

**Scenario:**
With a setup having Simple Calendar Pro 6.21.9 + DAVx5 4.3.4.1-ose (used to synchronize to a remote CalDav server)
- open Simple Calendar pro on month view
- click on the + button and choose Event
- scroll to the bottom of the form and click on the agenda chooser
- click on Store only locally

**Expected behavior:**
- the event form is displayed, with Store only locally as the chosen option

**Current behavior:**
- the app crashes and restarts on the default view (month in my case)

**Comment by tibbi** [comment]
ye thanks, that has been solved already, will be fixed in 6.22.0

**Comment by LucileDT** [comment]
@tibbi thanks for the quick reply, would it be better to downgrade the app, or will the 6.22.0 version will come out soon?

**Comment by tibbi** [comment]
it just became available on Github and started rolling out to 30% of users on Google Play. If nothing goes wrong, it should be available to everyone in 2-3 days. F-droid releases are usually a couple days behind.
