### ISSUE TITLE
Recurring Events can’t be deleted

### ISSUE THREAD

**Issue by anotherboringuser** [SimpleMobileTools/Simple-Calendar#2134]
Hello, 
I’ve deleted an instance of a recurring event, but I still get notifications for it even though it doesn’t show up in the calendar. When I search for it, it still shows up and I can delete the event as many times as I want without the search result changing. 
Android 11, App version 6.21.9

**Comment by tibbi** [comment]
retest with 6.22.0 once available. Ill close it so I wont forget, reopen if it is still broken.

**Comment by anotherboringuser** [comment]
The deleted events don’t show up in the search anymore, but I’m still getting reminders for deleted instances of recurring events. 
Currently on version 6.22.2

**Comment by qualto** [comment]
I am seeing this behavior Version 6.23.1 Pro, Android 14
