### ISSUE TITLE
Suggestion: new event created from month view should default to current day

### ISSUE THREAD

**Issue by zorbama** [SimpleMobileTools/Simple-Calendar#214]
When pressing "+" in the month view to create a new event, the event day defaults to the day after the event creation's day (tomorrow).
This behavior is not common in other calendar applications, which usually add events on a selected day (the default selected day being the current day)
Since you cannot select a day in the month view, I believe it would make more sense have the current day (today) be the default event day.
I will also add that today I created an event and was very surprised to see that it was assigned to tomorrow, although I wanted it to be today. That's my personal experience.

**Comment by tibbi** [comment]
yea, thats something I want to make like Google has. If you press the Plus button, it should create the event set to today, with time set to the next full hour, instead of the current 13:00.

**Comment by tibbi** [comment]
will be improved in 2.7.5
