### ISSUE TITLE
Widget theming inconsistency

### ISSUE THREAD

**Issue by thechubbypanda** [SimpleMobileTools/Simple-Calendar#2142]
On adding the event list widget, the default colors don't match the actual app, nor does the style match.
The pre-add view also has a different style to the final added widget.

[Pre-add](https://github.com/SimpleMobileTools/Simple-Calendar/assets/33595996/b453a4c3-62c4-4c49-979d-2e444af22720)
[Added](https://github.com/SimpleMobileTools/Simple-Calendar/assets/33595996/cc2709da-05d4-49a0-a87c-17a9a4ca3139)

Is this a bug or an intended feature?

**Comment by thechubbypanda** [comment]
Sorry, the style of the list items doesn't match... i.e. the widget is far less visually appealing than the app itself:

[Inside actual app](https://github.com/SimpleMobileTools/Simple-Calendar/assets/33595996/7570b74f-7dfb-44a4-aaa5-dcc218b7a3b0)

**Comment by tibbi** [comment]
right, widgets are more limited, we dont have as much control there as in the apps. Anyway, it has already been reported and some UI changes are on the roadmap. Thanks
