### ISSUE TITLE
Date -1 issue when adding event in weekly view

### ISSUE THREAD

**Issue by ttes0** [SimpleMobileTools/Simple-Calendar#2143]
After July update, having -1 day issue when adding event in weekly view. 
e.g. Selecting add event on 2023-07-08 opens in edit event screen with date set to 2023-07-07

(on android v.11)

**Comment by tibbi** [comment]
do your weeks start with sunday or monday? Does it matter if you create the event at 2:00 or 22:00?

**Comment by ttes0** [comment]
> do your weeks start with sunday or monday? Does it matter if you create the event at 2:00 or 22:00?

Monday, but I've tried setting either. I've tried setting to 24hr and 12hr clock. I'm unable to downgrade to May version of apk, but I've uninstalled and reinstalled the July version of apk.
I have apk installed on 2 phones, and same issue.

**Comment by Naveen3Singh** [comment]
what timezone are you in?

**Comment by ttes0** [comment]
GMT-7, but when selecting inside app, only shows GMT-8

**Comment by ttes0** [comment]
Selected is 'America/Los_Angeles'

**Comment by ttes0** [comment]
> > do your weeks start with sunday or monday? Does it matter if you create the event at 2:00 or 22:00?
> 
> Monday, but I've tried setting either. I've tried setting to 24hr and 12hr clock. I'm unable to downgrade to May version of apk, but I've uninstalled and reinstalled the July version of apk. I have apk installed on 2 phones, and same issue.

Downloaded May version from github, but get 'app not installed' when trying to install.

**Comment by Naveen3Singh** [comment]
@WessellUrdata this seems related to your recent fix https://github.com/SimpleMobileTools/Simple-Calendar/pull/2077

**Comment by WessellUrdata** [comment]
> @WessellUrdata this seems related to your recent fix #2077

looking into it.

**Comment by Naveen3Singh** [comment]
> I am able to reproduce the bug in the latest version of the app 6.22.1. Cannot be reprduced in 6.21.9. I probably broke it. my bad, trying to fix it now

hey, I'll be working on this so no worries if you can't fix it. Also, everyone breaks things all the time. These kinda of things often have a domino effect.

**Comment by WessellUrdata** [comment]
> > I am able to reproduce the bug in the latest version of the app 6.22.1. Cannot be reprduced in 6.21.9. I probably broke it. my bad, trying to fix it now
> 
> hey, I'll be working on this so no worries if you can't fix it. Also, everyone breaks things all the time. These kinda of things often have a domino effect.

I've spent an hour testing different behaviour when this line is changed:
https://github.com/SimpleMobileTools/Simple-Calendar/blob/b01525a24036a57ad7d0398dce4948a667a0ee23/app/src/main/kotlin/com/simplemobiletools/calendar/pro/extensions/Context.kt#L762

I've tried:
- `date.withZoneRetainFields(DateTimeZone.UTC).withTimeAtStartOfDay()`
- `date.withTimeAtStartOfDay().withZoneRetainFields(DateTimeZone.UTC)`
- `date.withZoneRetainFields(DateTimeZone.UTC).withTimeAtStartOfDay()`

and switched between Los Angeles timezone and Hong Kong timezone. Something always breaks and those lines only work for either timezone or not at all, with misbehavior like:
- Saturday being the first day of the week even when "Start week on Sunday" is enabled
- the Date -1 problem in this issue

---
Timezones really are the bane of my existence

sorry for saying this, but I'll only be able to take a furthur look into this issue myself after finishing my exams on Wednesday. Until then, good luck to everyone tackling this issue.

**Comment by Naveen3Singh** [comment]
@WessellUrdata thanks for the quick analysis. 

It seems this issue is caused by the fact that `getFirstDayOfWeek()` returns `startOfWeek` in UTC but the generated UTC week timestamps are treated as local timestamps in some places e.g. EventActivity: 
https://github.com/SimpleMobileTools/Simple-Calendar/blob/b01525a24036a57ad7d0398dce4948a667a0ee23/app/src/main/kotlin/com/simplemobiletools/calendar/pro/activities/EventActivity.kt#L542-L543

https://github.com/SimpleMobileTools/Simple-Calendar/blob/b01525a24036a57ad7d0398dce4948a667a0ee23/app/src/main/kotlin/com/simplemobiletools/calendar/pro/helpers/Formatter.kt#L106

Of course, changing `var startOfWeek = date.withZoneRetainFields(DateTimeZone.UTC).withTimeAtStartOfDay()` to `var startOfWeek = date.withTimeAtStartOfDay()` fixes this issue but I think this needs to be handled properly in other places. The `getFirstDayOfWeek()` function already does what it says. We either need to handle everything in UTC or everything in the local timezone.

**Comment by ttes0** [comment]
Do you have a possible timeline for the fix? I have a full schedule to deal with, and everything is already committed to Simple Calendar.

Thank you.

**Comment by Naveen3Singh** [comment]
Hi, I will try to fix it by the weekend.

**Comment by Naveen3Singh** [comment]
Discovered another bug related to this:  When using the drag-n-drop feature, the start and end date of the event is moved by ±1 day. Example: If I move an event from **23:00 11 July** to **22:00 11 July**, my event is moved to **22:00 10 July**.

**Comment by ttes0** [comment]
adb install -r -d --user 0 ./21.9.apk helped resolve this temporarily, and didn't seem to adversely affect the database
