### ISSUE TITLE
select time issue

### ISSUE THREAD

**Issue by cheetah747** [SimpleMobileTools/Simple-Calendar#2148]
when you add a new task ,then select the time quickly, just like: selecting the hour by left hand and then press the confirm button by right hand quickly, the selected minute will be wrong.

eg. (left hand) select hour 20--> (right hand) press confirm quickly--> at last the selected time will show "20:52" 
(but the requeired time should be "20:00")

**Comment by tibbi** [comment]
that is handled by the system, not us
