### ISSUE TITLE
[Feature Request]: Option to hide "Event color" in Event or Task screen

### ISSUE THREAD

**Issue by ReaderGuy42** [SimpleMobileTools/Simple-Calendar#2149]
I often hit the "Event Color" option when creating new events or tasks accidentally when I actually want to change the event type.

Would it be possible to add an option to hide the "Event Color" button? I like being able to change the colors from the Options menu but I don't need to be able to change it from the Event/Task screen.

Thanks :)

**Comment by tibbi** [comment]
nope, we dont plan removing it
