### ISSUE TITLE
CalDAV synchronization: choose the account

### ISSUE THREAD

**Issue by guy-teube** [SimpleMobileTools/Simple-Calendar#2150]
Hi there,
I use the 6.22.1 Pro version of Simple Calendar.
My Android phone is connected to one of my accounts, let's say myaccount1@gmail.com account.
My calendar are on another account, myaccount2@gmail.com.

If I go into the menu [gear] > Synchronisation CalDAV and tick yhe checkbox, this is what's proposed:
ACCOUNT_NAME_LOCAL
[ ] calendar_displayname_local
MYACCOUNT1@GMAIL.COM
[ ] Anniversaires (birthdays)
[ ] Jours fériés en France (public holidays in France)
[ ] Numéros de semaine (weeks numbers)
[ ] myaccount1@gmail.com

Here, I cannot select myaccount2@gmail.com.
For another application (DAVx5, used for contacts), I was able to put myaccount2@gmail.com, because my contacts are in this account, and not in myaccount1.
Would it be possible to enter in Simple-Calendar an account other than the Android account?
Thank you

**Comment by tibbi** [comment]
we show whatever the system provides us, there is no room for some custom implementation on our side
