### ISSUE TITLE
No notification with 6.22.1

### ISSUE THREAD

**Issue by Spielmops** [SimpleMobileTools/Simple-Calendar#2151]
I tried it several times, but I get no notification with version 6.22.1. Made a backup, uninstalled 6.22.1, installed 6.21.9, imported the settings and the notification worked again.

device: Samsung Tab S6 light
OS: LineageOS 19 and 20

Spielmops

**Comment by tibbi** [comment]
Check your device battery and notification settings, if there is nothing blocking the reminders, or killing the app in the background. You might also want to take a look at https://dontkillmyapp.com , it has some useful tips.
