### ISSUE TITLE
Use the local colours for events

### ISSUE THREAD

**Issue by federicodilo** [SimpleMobileTools/Simple-Calendar#2163]
I am having problems synchronising locally set colours with Google Calendar colours.
In other words, I would like it to be possible, for the colours set by the application, to be used locally and for events to be synchronised with the colour set by Google Calendar (as colour synchronisation is presumably not possible).

At the moment it is only possible for me to set an event as local using local colours or as a Google Calendar event with the only colour available for Google Calendar.

**Comment by tibbi** [comment]
you mean that you want to pick a custom color instead of the presets?

**Comment by federicodilo** [comment]
I mean that locally I can differentiate between colours while synchronisation with Google Calender provides only one colour.

Since the events are synchronised with Google Calendar, I would prefer to use for events the colours set locally by the application and for the events beign synchronized with Google Calendar to use the default colour.

![Uploading Screenshot_20230724-140140_Calendario_1_1.png…]()

**Comment by tibbi** [comment]
you can change the color at google calendar events too

**Comment by Aga-C** [comment]
Isn't it the same issue as https://github.com/SimpleMobileTools/Simple-Calendar/issues/653?

**Comment by federicodilo** [comment]
@Aga-C It definitely has a correlation, but I would like to be able to use a category within Simple Calendar without losing the possibility to sync the event

**Comment by tibbi** [comment]
that is way too advanced, you can only use either a synced calendar or an event color, not mix them
