### ISSUE TITLE
a lot of birthdays not importing 

### ISSUE THREAD

**Issue by Gitonthegrid** [SimpleMobileTools/Simple-Calendar#2164]
I am using the **_simple contacts_** app also from Simple mobile tools, but for some reason a lot of birthdays are not importing within the calendar application I really dont know what is going on and why some contact birthdays are importing correctly and others just dont import at all. 

I did use the **_add contact birthday_** option.

I also tried to remove the birthday option and then add them again, but still without any succes.

**Comment by tibbi** [comment]
what app version are you using?

**Comment by Gitonthegrid** [comment]
6.22.2

But I think I found the problem
I had some old birthday (just 5 or so) that where somehow imported into the "normal appointment" event. This was causing a problem for the import. Although some birthdays where importing, it was just a small amount. 

I have removed these "normal appointment" birthdays, and voila. Everything was importing right away. 

So maybe you can see what is causing this bug when other birthdays are in the "normal appointment" but for now my problem is fixed.

**Comment by tibbi** [comment]
well, the app cannot know which events are birthdays, so it works as expected
