### ISSUE TITLE
Provide OpenStreetMap location selection

### ISSUE THREAD

**Issue by BuZZ-dEE** [SimpleMobileTools/Simple-Calendar#2169]
Every time I create an appointment in SimpleCalendar and if I need to add a location to it, it is a pain to add it, because I have to write it manually or need to copy it from the webpage for example.

I would be great if it would be possible to search for the required address / location. 

If it is not possible to make [own search http requests](https://github.com/SimpleMobileTools/Simple-Calendar/issues/1026) then allow to select the location from OpenStreetMap apps like  [OSMAnd](https://github.com/osmandapp/OsmAnd), [OrganicMaps](https://github.com/organicmaps/organicmaps) etc.

Related issue: https://github.com/SimpleMobileTools/Simple-Calendar/issues/1026

**Comment by tibbi** [comment]
it cannot be added

**Comment by BuZZ-dEE** [comment]
@tibbi but you understand my problem? I don't like how you close tickets.
