### ISSUE TITLE
[Feature Request] Ability to hide the calendar toggler at the bottom of the screen

### ISSUE THREAD

**Issue by K4LCIFER** [SimpleMobileTools/Simple-Calendar#2173]
![Screenshot_20230820-133856_1](https://github.com/SimpleMobileTools/Simple-Calendar/assets/7829231/031f278d-fa98-4638-b8a6-922cf8c255a6)

For example, as shown above, it would be nice to be able to hide this. I, personally, have no use for it, and would prefer if it were just not shown, so it would be nice if there were an option to toggle it's visibility.

**Comment by Aga-C** [comment]
There is already an option in settings `Manage quick filter event types`.

**Comment by K4LCIFER** [comment]
Ah, so there is! My bad -- I didn't see that. Thanks!
