### ISSUE TITLE
[Feature Request] Hide the "Regular Event" calendar

### ISSUE THREAD

**Issue by K4LCIFER** [SimpleMobileTools/Simple-Calendar#2174]
![Screenshot_20230820-133856_1](https://github.com/SimpleMobileTools/Simple-Calendar/assets/7829231/6a6ff031-4ae8-4707-bd03-05d7dd388a4a)

As shown in the above image, there is always this "Regular Event" calendar. I appear to be unable to remove it. It would be very nice if I could.

**Comment by tibbi** [comment]
you can do it in the app Settings -> Manage quick filter event types.
