### ISSUE TITLE
Allow sharing link to calendar event.

### ISSUE THREAD

**Issue by rokejulianlockhart** [SimpleMobileTools/Simple-Calendar#2176]
Nextcloud – for instance, wim.nl.tab.digital/apps/calendar/ – provides this ability, which means that nothing prevents it.

I find that this is essential when sharing calendar events with other people, because generally they only want access to one event, not the calendar or group.

**Comment by tibbi** [comment]
our app has no internet access, internet related calendar sharing can be done through davx5

**Comment by RokeJulianLockhart** [comment]
> https://github.com/SimpleMobileTools/Simple-Calendar/issues/2176#issuecomment-1686764043

@tibbi, then close as not planned rather than https://github.com/SimpleMobileTools/Simple-Calendar/issues?q=is%3Aissue+is%3Aclosed+reason%3Acompleted. However, why is that a reason not to implement this? At the least, not everyone uses DAVx5, right?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/SimpleMobileTools/Simple-Calendar/issues/2176#issuecomment-1686995156

@tibbi, this still hasn't been closed correctly.
