### ISSUE TITLE
Allow changing the vertical space allocated to each hour in weekly view

### ISSUE THREAD

**Issue by jghq** [SimpleMobileTools/Simple-Calendar#218]
Fitting more hours into the screen would eliminate the need to scroll up and down all the time, enabling a true at-at-glance view.

Thanks for the fantastic application.

**Comment by tibbi** [comment]
the weekly view needs to have overlapping events sorted out too, watch out for that :)

**Comment by jghq** [comment]
Most exciting news today. Commencing watching out.

**Comment by tpo** [comment]
+1

**Comment by robinpaulson** [comment]
I'd like to see this too, Simple Calendar is now my calendar app, replacing stock Android app.

**Comment by sledz** [comment]
+1

**Comment by jghq** [comment]
With the full understanding that a creator of an open-source app has no obligation to make any changes, is this something that can be expected relatively soon for this app?

**Comment by tibbi** [comment]
not really, it isnt on the roadmap for now

**Comment by tibbi** [comment]
weekly view zooming with gestures has been added in 6.9.1 already
