### ISSUE TITLE
Change default time of "the day before" alarm on a "whole day" entry

### ISSUE THREAD

**Issue by firefoxlover** [SimpleMobileTools/Simple-Calendar#2184]
1. create an entry that spans the whole day
2. set the reminder to "the day before"
3. The reminder rings at 12:00 which is pretty bad

It should never use 12:00pm as alarm time by default. Maybe use 15:00 instead? Not sure. Maybe change the dialog?

**Comment by tibbi** [comment]
you can already change how many hours before the event should the reminder show

**Comment by firefoxlover** [comment]
> 

hm, so I think it would be great to have it by default not alarm during the night. Or remove the options "1 day before", as all the days and weeks will result in the app alarming at midnight.
