### ISSUE TITLE
Enable auto-off for reminder

### ISSUE THREAD

**Issue by secretmango** [SimpleMobileTools/Simple-Calendar#2185]
Currently the alarm works really reliably, even though a bit weird, for me it vibrates until I unlock the phone and pull down the notifications.

But it has to have an auto-off setting. If you lose your phone or its at someone elses or so, it should not vibrate until its battery is dead.

I think setting this auto-off to 5min should not hurt? Maybe even 1min?

**Comment by tibbi** [comment]
Havent you enabled "loop reminders until dismissed" in the app settings?

**Comment by firefoxlover** [comment]
Yes I have, turning it off will solve the problem. I think loop is confusing, it could mean in an interval while its actually simply "play the alarm until finished"
