### ISSUE TITLE
upcoming events  (*days) possible in widget?

### ISSUE THREAD

**Issue by Gitonthegrid** [SimpleMobileTools/Simple-Calendar#2192]
Hi all,

I have the widget for simple calender but when a event is tomorrow or the day after, I still see "_no upcoming events_"

In the settings I only see an option "_display events from the past_" where you can set the past days. But I would rather see a option to show (let's say) the upcoming 2 days..

Is this setting hidden somewhere? Because I really don't know why the "past" setting is easy to find, but not the feature that is more obvious like the upcoming hours or days.

**Comment by Aga-C** [comment]
You set the future days to show while creating the event list widget.

**Comment by Gitonthegrid** [comment]
Thanks a lot, I did totally missed that when making the widget. :)
