### ISSUE TITLE
Feature Request: Archive Event Types

### ISSUE THREAD

**Issue by Flashbrick** [SimpleMobileTools/Simple-Calendar#2195]
I am reorganising my calendar and got to the situation that I have certain event types that I don't use anymore at all. I could just delete them but then my past events would lose their distinct category and I don't want that.
My proposal is that event categories can be archived (in the manage event types tab) and past  will stay with the category but I can't create any new events of this category. That would declutter the menu when creating a new event and a cleaner UI as I only see the categories I need.

**Comment by tibbi** [comment]
dont really expect having that
