### ISSUE TITLE
Untitled event don't appear 

### ISSUE THREAD

**Issue by Duffscs** [SimpleMobileTools/Simple-Calendar#2197]
I have a calDav synchronised. 

Sometimes events are untitled, then they simply don't appear in the application.

simple calendar | my default calendar
:-------:|:-------:
![simple calendar screen](https://github.com/SimpleMobileTools/Simple-Calendar/assets/59032377/e6fe8b9f-1f66-4b6e-baa9-b8564d954a74)| ![my calendar screen](https://github.com/SimpleMobileTools/Simple-Calendar/assets/59032377/ad9c69c9-e0a7-419e-93df-816f3e7dff1e)

**Comment by tibbi** [comment]
makes sense, I dont want to show untitled events

**Comment by Duffscs** [comment]
Not any sense title is not a required element in a standard caldav. 
Having a default name like untitled is not that hard btw
