### ISSUE TITLE
[Feature Request] Add custom CalDAV address

### ISSUE THREAD

**Issue by Tjeerd95** [SimpleMobileTools/Simple-Calendar#220]
First of all thanks for the amazing app! Is it possible to add a custom CalDav address? It would be a great feature to sync my CalDav calendars from NextCloud to my phone.

**Comment by tibbi** [comment]
Hey, not sure what you mean by CalDAV address. If you enable caldav sync in Settings, you dont see the wanted calendars? If not, you might need to fix the issue on the caldav sync adapter's side, whatever you use for it. Im using Google Calendar as the sync adapter, so I dont really have experience with others.

**Comment by Tjeerd95** [comment]
Thanks for the fast reply! I didn't saw the calendars i wanted indeed. But your suggestion to look at the sync adapters side helped me out. It was a synchronization issue. My bad. I only saw the Google Calendar's at first, so i thought the app didn't support other CalDAV adapters. It works perfectly now! Thanks for the great app.
