### ISSUE TITLE
Export to .ics missing most events

### ISSUE THREAD

**Issue by roughnecks** [SimpleMobileTools/Simple-Calendar#2203]
Hello,

I've got a caldav and I'm trying to export it to ics file but when I'm asked to select which calendars to back up, even if I select them all (holidays, birthdays, normal events + all of my data in main calendar), what I get is just a Moon phases calendar events.

Is there something I'm doing wrong?
Thanks

**Comment by tibbi** [comment]
what app and OS version are you using?

**Comment by tibbi** [comment]
I need the app version number at the bottom of the About page

**Comment by roughnecks** [comment]
> I need the app version number at the bottom of the About page

6.22.2 Pro

**Comment by tibbi** [comment]
what events are missing though? They have to have something in common

**Comment by roughnecks** [comment]
As I told you, apart Moon phases, everything is missing, from Birthdays, to Holidays in my country, to personal events I added to the caldav, like taking my medicine, doing stuff at fixed hours every day etc..

**Comment by tibbi** [comment]
what is specific about moon phases? Are they in a specific event type? Are they stored locally only or CalDAV synced?

**Comment by roughnecks** [comment]
Oh, right, Moon Phases are a webcal, imported from ICSx5, while the remaining ones are on DAVx5.

Thanks

**Comment by roughnecks** [comment]
Nope, sorry, I'm wrong, it's the weather I imported as webcal, Moon Phases were imported as ics.

Sorry :(

**Comment by tibbi** [comment]
well, it doesnt really matter where do the events come from, they should be exported the same. If you uncheck everything but moon phases, do they export properly?

**Comment by roughnecks** [comment]
If I uncheck everything but Lunar Eclipse and Moon, it says no event found.

I also didn't understand this thing when I set it up.. I believe I imported every ics calendar into my personal one, still on the app I see each calendar with its name and color, but on the events view (like daily) they all have the same color of my personal calendar.

I'd like to delete every other calendar but my personal one and the weather one which is separated anyway.

**Comment by tibbi** [comment]
you can manage event types at the app settings. You seem to be mixing some things and those wanted event types dont even contain events?

**Comment by roughnecks** [comment]
All I know is, everything (but the weather) is stored under my caldav, which I also have synced with thunderbird.

If I uncheck it from the list of calendars to sync, I'm left with this: https://dl3.pushbulletusercontent.com/TmgSltIp98XcuT8LQynrz4mNOBzgAAGb/Screenshot_2023-09-19-19-54-47-531_com.simplemobiletools.calendar.pro.jpg

How do I even remove all of the calendars at the bottom?

**Comment by tibbi** [comment]
you can customize that at the app Settings -> Manage quick filter event types. Anyway, play around the exporting, I think you are confusing something.
