### ISSUE TITLE
past events showing up

### ISSUE THREAD

**Issue by opa-rudi** [SimpleMobileTools/Simple-Calendar#2206]
I set up that past events won´t show up but they are still visible in the widget.

**Comment by Aga-C** [comment]
Change value for the `Display events from the past` option in Settings to e.g. 1 minute.

**Comment by opa-rudi** [comment]
I tried 0 and 1 on Minute setting but without success.

**Comment by tibbi** [comment]
you mean not showing up in the Event List view or anywhere?

**Comment by opa-rudi** [comment]
I want to hide past events in the calendar widget (month view).

**Comment by tibbi** [comment]
you cant hide them at the monthly view
