### ISSUE TITLE
Calendar Data

### ISSUE THREAD

**Issue by Rajesh19573** [SimpleMobileTools/Simple-Calendar#2208]
Due to unknown reasons my Blackberry Key2 crashed and took away everything with it. I had MPE Backup and could restore almost everything.  However, Calendar Entries (Starting from 2007 till date) cannot be restored.
I have the Internal Storage Back up of two days back but cannot find calendar anywhere.

Its data of nearly 25+ years. Can anyone please help me find where is the data stored in internal storage?

Please help.

Thanks & Regards - Rajesh19573

**Comment by tibbi** [comment]
it is in an internal database called events.db, not really in a publicly accessible file

**Comment by Rajesh19573** [comment]
Hello,

How can I get back these entries of 25+ years?

Please help & gude.

Thanks & Regards - Rajesh Pathak
________________________________

**Comment by tibbi** [comment]
I dont know, such things depend on the system and OS version, there is no generic way of accessing the data.

**Comment by Rajesh19573** [comment]
Dear Sir,

I am using BlackBerry Key2.

The complete backup was taken using MPE.

Is there any way I can retrieve the lost data? Please help. If there are any charges for the same, kindly let me know.

Looking forward to your valuable help & support.

Thanks & Regards - Rajesh Pathak
________________________________
