### ISSUE TITLE
Remember last calendar to save events in

### ISSUE THREAD

**Issue by BloodRaven0** [SimpleMobileTools/Simple-Calendar#2210]
I use a CalDAV calendar to store all my events in that I can then sync with my other devices via nextcloud. So I never want to store an event locally, but that is the default option for each new event I create.
Can we have an option that remembers the last calendar and selects it by default for every new event?

**Comment by tibbi** [comment]
it should already do that

**Comment by BloodRaven0** [comment]
@tibbi But it does not. It's always set to "Store locally only" by default for me. Maybe file it as a bug then?

**Comment by tibbi** [comment]
what app version are you using at all? Try picking a different calendar.

**Comment by BloodRaven0** [comment]
@tibbi 6.22.2 from F-droid.
I just created a new calendar from the CalDav app (DAVx5) on my cloud, enabled it in the SimpleCalendar settings, synced and created a new event in it. Then tried to create another new event, and the default was still set to "Store locally only".

**Comment by BloodRaven0** [comment]
@tibbi sorry for wasting your time, somehow I've been blind and didn't see the "Default event type" in the settings.
Everything works fine, thank you for your time and for these awesome apps ❤️
