### ISSUE TITLE
Events shown on wrong day

### ISSUE THREAD

**Issue by Neuwessi11** [SimpleMobileTools/Simple-Calendar#2211]
In week 44 this year in the 14 days view the events are shown one day too late.
An event on Nov/2 is shown on Nov/3.

When switching to 7 days view it is fine, but when switching back to 14 days view it is wrong again.

When I make a new event in 7 days view it is fine, switching to 14 days view it changes to be wrong.

My two devices are affected: Cat S61 running Android 9
                                                     Samsung Galaxy Tab S8 Ultra running Android 13

**Comment by naveensingh** [comment]
Hi!

I tried creating a local event and switching to a 14-day view, I also tested this with a Caldav event and an all-day event but I could not reproduce the issue. Can you share more details about the event you are creating to help me reproduce this issue?

1. Your device's timezone.
2. Event's start, and end time.
3. Event's timezone (if different than device timezone).
4. Is the event an all-day event? Are you creating it in some other client (nextcloud etc.) or using simple calendar?
5. Please share an ICS file if you can.

**Comment by Neuwessi11** [comment]
In between I try to share two screenshots. Maybe they are of use.
![Screenshot_20230928_151957_Calendar](https://github.com/SimpleMobileTools/Simple-Calendar/assets/70072237/5159e5ab-4252-48ca-9056-6cf154afcbea)
![Screenshot_20230928_152039_Calendar](https://github.com/SimpleMobileTools/Simple-Calendar/assets/70072237/b519a57b-5495-4509-96d8-f3603288349e)

**Comment by naveensingh** [comment]
Thanks for the quick reply!

I think I found the issue, while I fixed https://github.com/SimpleMobileTools/Simple-Calendar/issues/2143, I brought back the older https://github.com/SimpleMobileTools/Simple-Calendar/issues/1213 issue (same as this one).

Working on a fix now...

**Comment by naveensingh** [comment]
Hello!

I have uploaded a test APK with a fix here: https://github.com/naveensingh/Simple-Calendar/releases/download/daylight_savings_time_fix/calendar-prepaid-release.apk

If you are willing, please check if the issue is resolved.

**Comment by Neuwessi11** [comment]
Yes, I will try it later today, but weird enough it seems to be ok today. I have no idea why, but today the event of Nov/2 is shown there.

**Comment by naveensingh** [comment]
Thanks. 

Switch to weekly view => Force stop app => reopen the app 

That should bring it back. Make sure your timezone is set to Berlin. Any event starting after Oct 29 should be displaced (as long as Oct 29 is on the same page)

The issue was caused by daylight savings time ending on Oct 29

**Comment by Neuwessi11** [comment]
Seems to work fine.

Thank you!

**Comment by tibbi** [comment]
ok thanks
