### ISSUE TITLE
Unable to run the app, Getting the following Error.

### ISSUE THREAD

**Issue by agrawalswapnesh** [SimpleMobileTools/Simple-Calendar#2213]
An exception occurred applying plugin request [id: 'com.android.application', version: '8.1.1']
> Failed to apply plugin 'com.android.internal.application'.
   > Could not create an instance of type com.android.build.gradle.internal.dsl.ApplicationExtensionImpl$AgpDecorated.
      > Could not create an instance of type com.android.build.gradle.internal.dsl.LintImpl$AgpDecorated.
         > Could not generate a decorated class for type LintImpl$AgpDecorated.
            > com/android/tools/lint/model/LintModelSeverity has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

**Comment by tibbi** [comment]
you arent supposed to republish the app

**Comment by tibbi** [comment]
try googling that error then, it isnt anything related to our code. It is something with your setup.
