### ISSUE TITLE
calendar shows days in incorrect column on year view 

### ISSUE THREAD

**Issue by bilbo-swaggings** [SimpleMobileTools/Simple-Calendar#2227]
ver 6.23.0 from Fdroid if you look at the Yearly View the days can appear in the wrong column.

For example, if you look at the 9th and 10th of October, it appears to be the weekend Saturday and Sunday.

However, on the monthly view, you can see that those dates are in fact Monday and Tuesday, with the correct weekend days being the 7th and the 8th.

![Screenshot_20231006-160832](https://github.com/SimpleMobileTools/Simple-Calendar/assets/126202090/53b7cc42-1cf8-41a9-8839-5004d7478283)
![Screenshot_20231006-160847](https://github.com/SimpleMobileTools/Simple-Calendar/assets/126202090/bb4b6f2e-2d94-465a-b38e-e7af2f684586)

this bug also causes the weekend highlight to apply incorrectly on the yearly view:

![Screenshot_20231006-160900](https://github.com/SimpleMobileTools/Simple-Calendar/assets/126202090/429c5f03-bd92-4da2-9ef6-265286c24e09)
![Screenshot_20231006-160905](https://github.com/SimpleMobileTools/Simple-Calendar/assets/126202090/6edd7575-00a4-4133-bec6-5295a1323b3f)

**Comment by Aga-C** [comment]
This bug has been fixed in 6.23.1.
