### ISSUE TITLE
CalDAV / iCal attachments support

### ISSUE THREAD

**Issue by stinovlas** [SimpleMobileTools/Simple-Calendar#2228]
I'm looking for calendar app that supports CalDAV attachments as specified by [RFC4791](https://www.rfc-editor.org/rfc/rfc4791#section-8.5). It says:

> CalDAV clients MUST support inline attachments as specified in iCalendar [[RFC2445](https://www.rfc-editor.org/rfc/rfc2445)]. CalDAV servers MUST support inline attachments, so clients can rely on being able to create attachments this way.

Also:

>CalDAV clients SHOULD support downloading of external attachments referenced by arbitrary URI schemes, by either processing them directly, or by passing the attachment URI to a suitable "helper application" for processing, if such an application exists.  CalDAV clients MUST support downloading of external attachments referenced by the "http" or "https" URI schemes.

I was surprised that I could not find any Android app that supports calendar events attachments. Only Google calendar allows them, but only for google calendar server and only when attachments are saved on Google Disk, which obviously violates the RFC.

Does Simple Calendar have any plans of supporting calendar attachments as specified by the aforementioned RFC? Right now, it not only doesn't allow to add new attachment (either inline or external), but doesn't even show already present attachments in existing events.

**Comment by tibbi** [comment]
that isnt really on the roadmap
