### ISSUE TITLE
CalDAV event invite status and response options not visible in version 6.23.0

### ISSUE THREAD

**Issue by varaki** [SimpleMobileTools/Simple-Calendar#2229]
In version 6.23.0 the CalDAV event invite status is not visible and also no response options available.
In the **previous** 6.22.2 version it's fine:

![Screenshot_20231007-201627_Calendar](https://github.com/SimpleMobileTools/Simple-Calendar/assets/23281360/133e03fb-f219-4464-819f-a978b4de2dc8)

**Comment by tibbi** [comment]
has been fixed in 6.23.1 already, just update whenever you can
