### ISSUE TITLE
[FEATURE REQUEST] Add quick events for day, evening and night shifts

### ISSUE THREAD

**Issue by Gitonthegrid** [SimpleMobileTools/Simple-Calendar#2233]
I first want to say that I Love the app.

I (and a couple of friends) do use the app quite a lot.
The only thing is that we all work in shifts. And we do hate to type all the shifts manually in a digital calendar.
So almost all of us do still use a normal hadwrtitten calendar.

I really don't know why almost none calendar apps use something like quick events (pre formated events). It would be so much easier to ad quick events to you calendar like shifts.

So let's say my evening shifts start at 15:00n and stops at 23:00 in the. It the would be super handy to have quick events (next to, or implemented in the normal events) so I can really quickly add the shift, like day, evening, night. _It would be even better if you could press and hold on the day you want to add, and that a 'quick event popup' pops op with the pre formated shifts/events._ You could afcourse use it for all kinds of other stuff that always have the same time and description. 

**Lets be clear. Normally it is not a big deal to type a event. But if we get our shifts, we are talking about 100+ days that you have to manually type into your calendar, and that is a pain to do (digitally)**

I can make some sort of sample (mockup) if you would like that. Iike I said, I know some other people here that would love a function like this.

**Comment by tibbi** [comment]
that isnt really on the roadmap

**Comment by inson1** [comment]
I think there should be option to create some templates. And adding one template event to x days and creating from him separate events.

**Comment by Gitonthegrid** [comment]
But I ask at it as a feature request...So why just say that it is not on the roadmap?

I know a lot (a lot) of people are searching for some kind of functionality in a calendar.

**Comment by inson1** [comment]
> But I ask at it as a feature request...So why just say that it is not on the roadmap?
> 
> I know a lot (a lot) of people are searching for some kind of functionality in a calendar. 

It isnt on the roadmap means that he thinks there are more important tasks. 

If that is true, then they can like your issue and he can change his mind.

**Comment by Gitonthegrid** [comment]
> > But I ask at it as a feature request...So why just say that it is not on the roadmap?
> > I know a lot (a lot) of people are searching for some kind of functionality in a calendar.
> 
> It isnt on the roadmap means that he thinks there are more important tasks.
> 
> If that is true, then they can like your issue and he can change his mind.

yeah I know, but he could also say, it is not at the roadmap, but we leave the post open for a while to see if it will be upvoted right? I think I never had anyone closed a feature request this fast  :)

**Comment by Gitonthegrid** [comment]
> I think there should be option to create some templates. And adding one template event to x days and creating from him separate events.

Can you explain it a bit further? Because my weeks are never the same. So I cant use the same x days. I always have to put in all days manually even if I do it on paper. That is why quick events will be super helpful. Almost no one I know uses a digital calendar if they works in shift, because it is a pain in the *** to ad them in a digital calendar.

**Comment by inson1** [comment]
Well on other hand Its good that it was fast, wee can see him working.

But yea there should be at least label for that, so it can be one day reopen.

**Comment by inson1** [comment]
Well on other hand Its good that it was fast, wee can see him working.

But yea there should be at least label for that, so it can be one day reopen.

**Comment by Gitonthegrid** [comment]
> @Gitonthegrid Well on other hand Its good that it was fast, we can see him working.
> 
> But yea there should be at least label for that, so it can be one day reopen.

totally agree, I do use all of the apps he made (besides the note app), so I really love the work he does and all the quick responses. So maybe the question to @tibbi, can you at least let people upvote or downvote it, to see if it is something you can add?

**Comment by inson1** [comment]
@Gitonthegrid People can still upvote it, even uf the issue is closed. Just search for it is bad. That is why I talked about labels.

**Comment by inson1** [comment]
@Gitonthegrid Well I meant If you work lets say 3 day same hours then you just select the 3 days and add the event from template.
Normally people, who works shifts, have 5 days same same. Or at least few days same. Of course not everybody

**Comment by Gitonthegrid** [comment]
@inson1 
I understand what you are saying about the labels. I also don`t know why it is getting closed: At least give it a label

I have also added an screenshot of how it could look like in the begin post. It would be even nicer the way you say it. There are indeed multiple day, evening and night shifts every month, So if you then could select multiple day would be even better. But we should be really glad already if you can add it per day.

**Comment by Gitonthegrid** [comment]
You mean something like this then, where you can select multiple days right?

![top-image-calendar2](https://github.com/SimpleMobileTools/Simple-Calendar/assets/74937678/b2a3ef8e-d67d-4e9e-ab64-afb68424cb70)
