### ISSUE TITLE
Opening calender from widget does not open monthly and daily view by default

### ISSUE THREAD

**Issue by Jejd222342** [SimpleMobileTools/Simple-Calendar#2234]
Even i enabled it by default in settings,  but still it is not opening in monthly and yearly view

**Comment by Aga-C** [comment]
Which widget do you mean and where exactly are you tapping?

**Comment by Jejd222342** [comment]
> which widget you mean?

"Simple Calendar widget in Amdroid" when i open it, i don't see full calender by default, even i enabled "monthly and daily view" it stills opens to a blank white screen with only current date written above.

**Comment by Aga-C** [comment]
<img src="https://github.com/SimpleMobileTools/Simple-Calendar/assets/85929121/de03dbf9-9921-47e0-afa1-7c3befb9dfe2" width="400">

Which one and where exactly on the widget are you tapping?

**Comment by Jejd222342** [comment]
Calendar monthly 4×4. I see this..>>
![Screenshot_20231018-125621_Calendar](https://github.com/SimpleMobileTools/Simple-Calendar/assets/144002964/6ec5f06c-db99-4a93-a3e9-a37603cfcc95)

Instead of this. >>
![Screenshot_20231018-125819_Calendar](https://github.com/SimpleMobileTools/Simple-Calendar/assets/144002964/c2b29772-4a42-4ffb-92ef-b09cc0885036)

**Comment by Jejd222342** [comment]
I selected it to be opened as monthly view as shown in 2nd photo, but it still opens to blanks white screen.

**Comment by Aga-C** [comment]
The option in settings you mean is `View to open from the event list widget`, so it only applies to the event list widget.
