### ISSUE TITLE
Overwritten auto export

### ISSUE THREAD

**Issue by DavidHenryThoreau** [SimpleMobileTools/Simple-Calendar#2236]
Auto export is a nice feature but I want all my backup named : `events.ics` but if that file already exists I can't save it.
In order to use my backup script with : `adb pull events.ics`

**Comment by tibbi** [comment]
why doesnt it work? The file is not changed at all?

**Comment by DavidHenryThoreau** [comment]
If I'm deleting events there's no new export.

**Comment by DavidHenryThoreau** [comment]
If I want to manuel export as events if events.ics already exist in folder I'm getting `A file or a folder with that name already exists`
