### ISSUE TITLE
[DOCS] Add table with countries and if their holidays are added

### ISSUE THREAD

**Issue by inson1** [SimpleMobileTools/Simple-Calendar#2238]
#2232
#2030 
#1906 
#1684 
etc.

**Comment by inson1** [comment]
@tibbi Why did you close that?

**Comment by tibbi** [comment]
well, this bug report doesnt bring anything new..

**Comment by inson1** [comment]
Its isnt Bug report.
There are x people want their nationals holidays, so I created issue for table to track what countries are done
