### ISSUE TITLE
Countdown for events

### ISSUE THREAD

**Issue by rofe33** [SimpleMobileTools/Simple-Calendar#2239]
Hey all,

I would like to know how many days/hours/minutes are left for my event to start. 

I was creating a recurring birthday event and I created a 2 weeks reminder before the start of the event. After saving, I saw how many days/hours/minutes until my alarm (Like a pop-up on my android device).

I thought it would be amazing and useful to have the countdown feature in the app and in each event.

Thank you :)

**Comment by tibbi** [comment]
that isnt really planned
