### ISSUE TITLE
[Bug] color preferences not honored/reset for CalDAV calendars

### ISSUE THREAD

**Issue by sans-c** [SimpleMobileTools/Simple-Calendar#2243]
Hi, using the latest fdroid-release at time of writing.

I've set up three calendars, one is local only, the other two are CalDAV calendars.

Regardless of the overall UI preferences,  settings in "manage event types" are not corretly applied/reset. I've customized the colors of all my event types and those which are linked to the CalDAV calenders always reset to the same color, regardless of what I choose. I can customize the colors and most of the time the change is reflected in "Monthly View", but it resets after I close and open SimpleCalendar again. Sometimes it happens that the colors I set up do _not_ show up correctly in monthly view, too.

Sorry for the rushed report - if you need any more info or clarification, please let me know!

**Comment by tibbi** [comment]
for each individual account, DAVx5 allows you to change the setting for "Manage calendar colors" from (1) 'Calendar colors are reset at each sync' to (2) 'Calendar colors can be set by other apps'. You have to use the second option.
