### ISSUE TITLE
Yearlyview - weeks start with Saturday or Sunday

### ISSUE THREAD

**Issue by HensonHorkson** [SimpleMobileTools/Simple-Calendar#2246]
Hi,
I noticed yesterday, that in yearly view (12 month overview) the weeks start with Saturday or Sunday, depending on the month. All in spite of choosing "start week with monday". (Led to some discussions with my brother finding a day für a birthday event ;-) )
In monthly view everything works out like selected. 
Could you provide a solution?
Thanks!

**Comment by Aga-C** [comment]
What app version are you using?

**Comment by HensonHorkson** [comment]
6.23.0

**Comment by HensonHorkson** [comment]
Thanks, didn´t get a notification the next version was out as usually.
