### ISSUE TITLE
Please: Some feedback for #2194 

### ISSUE THREAD

**Issue by michaelof** [SimpleMobileTools/Simple-Calendar#2255]
Hi,

I've opened #2194 two months ago, and didn't get any feedback, hint, or whatever, until now. 

@tibbi: as you are reacting usually pretty fast, esp. when closing issues you don't want to accept, why are you ignoring my really painful problem report for 2 months now?

Sorry for this way of a "reminder"...

Sadly,
Michael

**Comment by tibbi** [comment]
battery issues are difficult to solve and they are usually caused by something system or device specific, not the app itself
