### ISSUE TITLE
Fix Escape Character Issue in String Resource

### ISSUE THREAD

**Issue by KBenMessaoud** [SimpleMobileTools/Simple-Calendar#2256]
An incorrect escape sequence in one of the string resources causes the build to fail during resource compilation. The current escape sequence is not properly escaping the single quote character, leading to a TaskExecutionException.

Affected Resource
The issue is located in strings.xml:
<string name="holidays_imported_successfully">Les jours fériés ont été correctement importés dans le type d\'évènement \'Jours fériés\'</string>
Proposed Fix
To resolve this issue, we need to correct the escape sequence by adding an additional backslash before the single quote:

<string name="holidays_imported_successfully">Les jours fériés ont été correctement importés dans le type d\\'évènement \'Jours fériés\'</string>

**Comment by Aga-C** [comment]
It's already fixed.
