### ISSUE TITLE
bug with new default event time

### ISSUE THREAD

**Issue by Binary1011011** [SimpleMobileTools/Simple-Calendar#227]
When adding an event between 23:00 and 00:00 (system time),  the default time for the event is 00:00 as expected (the next full hour.) However, the default date gets moved one day ahead and you have to change it back manually. 
Example: It is a few minutes before midnight and I want to add an event for the 7th, 9:00 pm. I navigate to the 7th and klick on "add a new event".  The default time shows 00:00 and I change it to 9:00 pm. I don't pay attention to the (false) date and hit "save". Now that event will be one day late on the 8th, 9:00 pm.

**Comment by tibbi** [comment]
thats the expected behaviour, I dont really want to change it. It should always add an hour

**Comment by Binary1011011** [comment]
The problem is that it shifts the day when your system time is between 23:00 and 00:00 as in the example above. Is that also intended?

**Comment by tibbi** [comment]
it is, why would you schedule something 23 hours in the past?

**Comment by Binary1011011** [comment]
No, it is about the future. This is how I understand it: 
Lets say that tonight (25th of September 2017, 23:33) I try to add an event for the 3rd of October. When I navigate to the 3rd of October and hit "add event", the app calculates: the next full hour is 00:00 on the next day. This means the suggested time is 00:00 on the 4th, not the 3rd. So you have to enter the time and also change the date back from the 4th to the 3rd.

**Comment by tibbi** [comment]
Aha I get it. I still want to keep it the current way, just for consistency. We will see if more people will have issues with it.

**Comment by Binary1011011** [comment]
Yes, I find it confusing when I want to add sth for the 3rd and it wants to show up on the 4th when not paying attention. 
Thank you for being patient and trying to understand the problem.
