### ISSUE TITLE
Allow custom location for automatic backups. 

### ISSUE THREAD

**Issue by xusiai** [SimpleMobileTools/Simple-Calendar#2290]
Manual backup allows for selecting a custom location. I would appreciate the option to do this for the automatic backup function too. As of now it seems limited to Internal/Download (Android 14). I suspect this is because the application doesn't request file permissions? Perhaps this can be requested when enabling automatic backups. 

I'm opening this issue for the Calendar application but I would appreciate it across all Simple applications which allow automatic backup as I noticed this limitation seem to occur in all of them.

**Comment by inson1** [comment]
@xusiai this project is dead, it was sold to ad company. Fork https://github.com/FossifyOrg.

**Comment by xusiai** [comment]
@ inson1 Thanks. Wasn't aware of that.
