### ISSUE TITLE
Multiselection not working properly and deleting events

### ISSUE THREAD

**Issue by frankyxcs** [SimpleMobileTools/Simple-Calendar#23]
Hi very nice app but there is a bug. 

in DayActivity.java if you multiselect items they are never getting deleted . 
Only if you select one item it works. Also i´m getting a database error while selecting multiply items. 

In DBHelper i have changed deleteEvent to make it working if i select multiply items like this:

public void deleteEvents(String[] ids) {
StringBuilder placeholders = new StringBuilder();
        for (int i = 0; i < ids.length; i++) {
            if (i != 0)
                placeholders.append(", ");

            placeholders.append("?");
        }
        final String selection = COL_ID + " IN (" + placeholders.toString() + ")";
        db.delete(TABLE_NAME, selection, ids);
        db.close();

       if (mCallback != null)
          mCallback.eventsDeleted(ids.length);
    }

greets frank

**Comment by tibbi** [comment]
cool, thanks for the report and the code. Ive solved it a bit nicer tho ;)

**Comment by frankyxcs** [comment]
Hi i see ! Good solution :) 

but also in dayactivity.java there is a little logic bug because deleteevents() are never getting called and the snackbar is always active ! So also it should delete the entries but cannot undo anything because the snackbar is alwas open 

i hope you understand what i mean :) 

greets frank

**Comment by tibbi** [comment]
the real delete is called once you interact with the app. You can either close the app, switch day or click anything but Undo. Seems OK to me.
