### ISSUE TITLE
Feature Request: navigate to weekly/monthly view from the widget...

### ISSUE THREAD

**Issue by dardoor** [SimpleMobileTools/Simple-Calendar#230]
When I open the app from the widget I can add or modify an event. But from there, I can't navigate to the calendar overview. To see that overview, I have to tap the app shortcut, so I have to have both the widget and the shortcut on the home screen.

Perhaps the "back" button could take you to the overview. But it's probably better if there's a separate button.

**Comment by tibbi** [comment]
I wanted the Back button at the top actionbar behave like that, but couldnt implement it so far. Ill retry someday.

**Comment by tibbi** [comment]
I couldnt make it work as I wanted with the top back button as it's messed up, but Ive made the app go back to the main screen after pressing the navigation Back button. I will see on user feedback if it's ok, it should be good enough.
