### ISSUE TITLE
Calendar events which invited attendees don't execute e-mail notification 

### ISSUE THREAD

**Issue by stoneubi** [SimpleMobileTools/Simple-Calendar#2302]
Using latest nextcloud version 28.0.1 causes a problem with calendar invitations. 

Usually if you create an event on a Android device using simple mobile calendar having attendees invited nextcloud sends an invitation email to the user. 

Since the last update of simple calendar this emails are not sent anymore. This means if you invite members to an event in simply calendar and you sync it to next cloud then this invitation emails are not sent anymore. Even if you update any shared events updates are not sent via email. Only if you delete an event with attendees an email will be sent to this users.

If you use Google calendar on the Android device or if you create any calendar entries with NTS in for example Thunderbird calendar these emails are sent correctly.

So it seems that within simple calendar that must be an issue that causes nextcloud not sending any emails.

Hopefully you can invest some time to check if this can be fixed within simple calendar app as this app is gorgeous.

Thank you

**Comment by inson1** [comment]
@stoneubi SMT apps were sold to ad company. Fork is here https://github.com/FossifyOrg
