### ISSUE TITLE
Notifications for birthday events pop up one day too early

### ISSUE THREAD

**Issue by mhoyer** [SimpleMobileTools/Simple-Calendar#2308]
I noticed already with several recent birthdays (and maybe even other All-Day events, but not 100% sure), that the notifications of the reminders show up a full day too early.

![Screenshot_20240222-063917_Calendar~2](https://github.com/SimpleMobileTools/Simple-Calendar/assets/76611/460a7194-5460-448f-95e8-b98faaed3890)

Given the example in the screenshot above, with a reminder set to `at start` for a birthday event of 22 Feb I would expect the notification to happen on midnight between 21 and 22 Feb. But the bells rang already at 12am of 21 Feb (00:00).

I am on Android 13 with SimpleCalendar version 6.23.1 Pro. The search for similar issue here didn't match any, nor did I find a setting.

Any clue what can cause this behavior?

**Comment by inson1** [comment]
@mhoyer SMT apps were sold to ad company. Fork is here https://github.com/FossifyOrg

**Comment by mhoyer** [comment]
Ah thanks for the hint. Maybe it's then worth to put a banner to each SMT repo with that hint? Or even archive the repos?

**Comment by inson1** [comment]
@mhoyer I dont have the permissons.  I'm just nice guy giving hint :)

**Comment by mhoyer** [comment]
Okidoki. No offense, @inson1. My advise was more on a general level.
