### ISSUE TITLE
Synchronized events not displayed in the widget

### ISSUE THREAD

**Issue by dardoor** [SimpleMobileTools/Simple-Calendar#231]
When I add a CalDav event from another device, the event doesn't show up in the SC Widget, until I open SC (the main app).

**Comment by tibbi** [comment]
I check new events only once every couple hours, or when you open the app. I can check in the future how to improve it

**Comment by dardoor** [comment]
Hmm, I don't see events updated in the widget even after 2 hours.

**Comment by tibbi** [comment]
I check it every 4 hours :D

**Comment by dardoor** [comment]
Alright, no problem. :)
BTW, I found a widget that kinda does what I need ("Simple Calendar Widget") and it also has a setting that lets you define the calendar app that it opens.
