### ISSUE TITLE
[feature request] Custom automate backups

### ISSUE THREAD

**Issue by Erz3** [SimpleMobileTools/Simple-Calendar#2321]
Would be nice If SimpleTool's suit was improved with the possibility to custom backups frequency. For example, time-triggers or modification-triggers (make bakcups when a new/existent event or task is created/edited/removed)

Thanks in advance

**Comment by Maxitendo1** [comment]
@Erz3 SimpleMobileTools apps were sold to ad and spyware company. Fork is here:

https://github.com/FossifyOrg
