### ISSUE TITLE
WearOS?

### ISSUE THREAD

**Issue by cy1der** [SimpleMobileTools/Simple-Calendar#2329]
This app could be a great alternative to the Google Calendar (that doesn't support third party calendars :( ) that comes pre-installed on WearOS watches.

**Comment by Maxitendo1** [comment]
@cy1der SimpleMobileTools apps were sold to ad and spyware company. Fork is here:

https://github.com/FossifyOrg

**Comment by cy1der** [comment]
Thanks, I'll try asking there
