### ISSUE TITLE
When updating via F-Droid, pending notifications disappear

### ISSUE THREAD

**Issue by akavel** [SimpleMobileTools/Simple-Calendar#234]
I have the Calendar app installed via FDroid. I like it very much, and especially the notifications, which I find better for me than in Google's Calendar - thanks! :)

My typical use case is that I keep numerous past notifications pending in the notifications tray, as a kind of a todo list. It works nice for me, but there's one unfortunate issue: when I upgrade the app to newest version, the past notifications disappear and don't seem to come back. Would it be possible to re-issue them in such case?

I suspect similar thing may happen if I reboot the phone, but I haven't verified this yet. I can try if you want.

**Comment by tibbi** [comment]
Hey, I dont really want to readd them, nor show again after a phone reboot. It's not the purpose of a calendar. You might want to use some application focused on notes for it, like https://play.google.com/store/apps/details?id=com.nisahnt.nishantbafna.notifydemo (havent tested) or so.
