### ISSUE TITLE
Feature request: .ics import / synchronization from URL

### ISSUE THREAD

**Issue by jszwedko** [SimpleMobileTools/Simple-Calendar#236]
Thank you for this fantastic app!

I was wondering if adding importing an ICS by a URL (rather than just a file) was on the roadmap. Ideally it would pull down updates to the calendar on a regular basis. Specifically I'm interested in this as a way to import an Outlook calendar that updates.

**Comment by tibbi** [comment]
Hey,
the app has no Internet permission, as that would discourage many people from using it. It also prevents me from downloading a file, so it wont be added anytime soon. CalDAV sync is supported tho, maybe you can find some way of making it work with that. 
Thanks

**Comment by jszwedko** [comment]
Aha, yes, I do like that the application requires no internet permissions.

I haven't found a way to synchronize Outlook to the local Android CalDAV system, but I'll keep looking.

**Comment by tibbi** [comment]
it should be doable, you just need some third party "CalDAV sync adapter". Google Calendar includes one for google calendars, Simple Calendar doesnt have any yet. There should be some around the playstore.

**Comment by jszwedko** [comment]
Indeed, I found iCal Import/Export which seems to work pretty well (then added it as synced calendar in Simple Calendar).

Thanks for the tip and keep up the great work!

**Comment by unhammer** [comment]
I use https://icsx5.bitfire.at/ , seems to work.

I first tried checking through the settings for any "Import url" menu items, and I suspect that's what other people do too. Perhaps there could be such a menu item which simply suggests to install another app, so that people at least know it's possible? (I was considering dropping this app because I didn't think it was possible.)

**Comment by tibbi** [comment]
Caldav sync is described in the FAQ, and since the vast majority of people use Google Calendar, it just works without having to do anything extra.
