### ISSUE TITLE
Error building: unable to merge dex

### ISSUE THREAD

**Issue by maxlinux2000** [SimpleMobileTools/Simple-Calendar#239]
Hi

I just downloaded the source but I can't build the app form android studio beta7 due this error:

```
Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

```

the build.gradle look:

```
android {
    compileSdkVersion 25
    buildToolsVersion '26.0.2'

    defaultConfig {
        applicationId "com.simplemobiletools.calendar"
        minSdkVersion 16
        targetSdkVersion 25
        versionCode 97
        versionName "2.8.2"
        multiDexEnabled true 
    }

    signingConfigs {
        release
    }

```

I tryed to do:

. Clean
. Rebuild Project

but there are 15 new errors like this:

```
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/squareup/leakcanary/watcher/R; 

```

Any hint to fix it?

regards
MaX

**Comment by tibbi** [comment]
It is their issue and it is already reported at https://github.com/square/leakcanary/issues/815 . Not sure in what cases is it happening, just remove everything leakcanary related if you want.

**Comment by maxlinux2000** [comment]
You are rigth!  the problem is the android studio version. I'm back to 2.3.3 and now this app compile well.

sorry for the trouble
