### ISSUE TITLE
Text color of events

### ISSUE THREAD

**Issue by privacy-wolf** [SimpleMobileTools/Simple-Calendar#244]
I do have a default setup (i.e. I did not mess around with any color settings) and loaded one test-event via DAVDroid from an online calendar. The text color is set to white, however makes it extremely hard to read at all due to the light color of the event itself (the text color should be set to black instead in this case) - cf. screenshot below.

If there is some logic about the text colors in the app it might need to be improved - make it white for dark event colors and black text for light event colors.

![calendar](https://user-images.githubusercontent.com/26414712/31885280-43d99f48-b7f0-11e7-85f6-5726c08282f3.png)

**Comment by tibbi** [comment]
Ive already tried using an automatically chosen contrast color (black or white), I will probably get back to it. I didnt like that black was chosen on orange, but as I check the month view, it is black on orange too, and its ok. I will add the automatic black/white in the next version. Plan B was adding another color at the customization screen, like "Text color on primary color", but I disliked that idea even more.
