### ISSUE TITLE
week-view vs. n-day-view

### ISSUE THREAD

**Issue by privacy-wolf** [SimpleMobileTools/Simple-Calendar#245]
Something I miss is a possibility to view the current and a few future days - similar to the available week-view.

The week-view is sometimes not that useful I think: Imagine it's Sunday. Since the week-view is fixed to start on Monday it either shows today with the past week or the next week (but without today). However, it would be more interesting for me to see today's events together with the next few, upcoming days.

What I personally would prefer - make the week view scrollable left-right to start with any weekday (not locked to start on Monday). E.g. I could see Saturday to Saturday, etc.

Only as an additional option on top of the above: a user might want to select how many days are shown (currently hard-coded to seven; for smaller screens a lower number might be helpful).

**Comment by ankitguptaiphone** [comment]
@tibbi  how I use the n-day-view functionality

**Comment by tibbi** [comment]
You cannot use it, it doesnt exist yet.

**Comment by tibbi** [comment]
weekly view day count customization has been added already, vertical zooming too
