### ISSUE TITLE
CalDAV-sync dependence on google calendar app

### ISSUE THREAD

**Issue by jojbak** [SimpleMobileTools/Simple-Calendar#258]
Hi,

I've noticed that the CalDAV-sync does not work if I've disabled the google calendar app. I've exported a calendar which is provided through an URL leading to an iCal-file using a dedicated google account which is then synced and displayed in Simple Calendar. Since I use this app as my primary calendar app I've disabled the google calendar since I thought that Simple Calendar could sync without using the google app, but this does not seem to be the case.

Is it possible for Simple Calendar to sync with the google account without the google calendar app enabled?
Alternatively, is it possible to add functionality for the app to sync with the URL leading to the iCal-file? In other words fetching the file with a GET and then add the new items and delete/change entries from the old file according to the new one. This seems like an easier solution.

Great app by the way and thanks for adding the location field!

**Comment by tibbi** [comment]
Hey, Ive created an issue #259 for it, so Ill keep that issue only. Fixing this issue requires creating an own CalDAV sync adapter, which is a bit more difficult, but I will take a look at it in the future. Thanks
