### ISSUE TITLE
Current day does not change with local device day/time

### ISSUE THREAD

**Issue by picklecat** [SimpleMobileTools/Simple-Calendar#26]
This issue was present as early as v1.17 and is present in v1.20.

Problem: 
The default behavior of the app/widget on the month view is to 'highlight' the current day by displaying the numerals in a larger font and/or bolding them. This is the indication to the user that the calendar has switched days.

Thus, when the local device time changes from 11:59pm to 12:00am (or 23:59 to 00:00), it is expected the the current day would highlight the next numeral in the sequence of days, but this does not occur immediately.

Instead, the local device date (day) changes, but the calendar remains on the same day for a period of time (hours?). I am not sure how much time passes before the calendar matches the local device time. I suspect this is a locale or timezone related bug.

**Comment by tibbi** [comment]
the calendar was updating itself just once every 5 hours. Ive changed it to 1 hour, we will see if its good enough. I will improve it later to update at midnight.

**Comment by picklecat** [comment]
Thanks for the note/update. I'll test the new version (v1.21) when the build makes it to fdroid.

I noticed a new problem that I think might be related: 
- On the widget, if a given day has an event, then the day numeral is highlighted (bold). After creating a new event, the day numeral does not immediately become highlighted. To get the day numeral to update, one must navigate to a different month (previous or next) then navigate back to the current month.

From your response above, I assume that the highlighting occurs when the calendar updates itself.

Should I create a new issue for this problem?

**Comment by tibbi** [comment]
its not needed, I will reuse the updating function whenever something changes

**Comment by tibbi** [comment]
Days should be updating immediately after some event update now, also days with events will be marked with underline instead of bold. Ill leave the widget update on that 1 hour period instead of updating at midnight, it should be good enough.
