### ISSUE TITLE
bug in adding birthdays without year from contacts

### ISSUE THREAD

**Issue by vishsci** [SimpleMobileTools/Simple-Calendar#261]
When adding birthdays without year from contacts, there is an offset of 21 days.

i.e., if 21 Jan is the birthday, then the event would get added on 1 Jan.

(This happens on DD/MM/YYYY format)

**Comment by tibbi** [comment]
Thanks for reporting, on my devices I had yyyy-mm-dd format, guess Ill have to make it more robust by somehow figuring out the format :/
