### ISSUE TITLE
time axis is not scrolling in week view

### ISSUE THREAD

**Issue by tpo** [SimpleMobileTools/Simple-Calendar#264]
Hi,

when I scroll down in the week view, the events are in fact scrolling down, but the time axis does not. That's a bug I guess. Simple-Calendar is v 2.9.2 here.

Greets and many thanks for the nice application!
*t

**Comment by tibbi** [comment]
works fine to me, I can take a look at it someday

**Comment by tibbi** [comment]
can you reproduce it reliably? It's always broken, or it depends on something? Thanks

**Comment by tpo** [comment]
On Tue, 7 Nov 2017, Tibor Kaputa wrote:

> can you reproduce it reliably? It's always broken, or it depends on something? Thanks

No, I can not reproduce it reliably. Today scrolling in the week overview 
works. I have no idea what changed or why it works today.

Thanks,
*t
