### ISSUE TITLE
events in android notifications disapear after update or reboot

### ISSUE THREAD

**Issue by tpo** [SimpleMobileTools/Simple-Calendar#265]
Hi again,

I use the Simple-Calendar's Android notifications in the same way they work in Outlook:

In Outlook you have a little reminder window, that lists calendar entries that are current at this instant or have gone past. One you "close" (aka "acknowledge" them), the disapear from the list.

That is very handy since that way one can keep track of a kind of a "TODO" list. I.e. you can see what things have gone by without you noticing or without you actually doing them justice. Once you've "done" them or "actually met the person" or such, you can click them away.

Simple-Calendar's Android notifications events work the same way except, when (as far as I can tell), you update the application or the Smartphone reboots (because of no more electricity or whatever). Then those events will disappear.

It'd be nice if they wouldn't i.e. if the notifications would survive a reboot/update.

Thanks & greets,
*t

**Comment by tibbi** [comment]
I dont really want to reshow any notifications after reboot, Tasks will be added someday for such purposes

**Comment by tpo** [comment]
:-(
