### ISSUE TITLE
better monthly view

### ISSUE THREAD

**Issue by azlux** [SimpleMobileTools/Simple-Calendar#266]
Hi,
Just one feature for the next release.
When we create a 3 days event. The monthly view present this event like 3 event of 1 day. Is it simple to make a multiple day event having a better look, like one bar on the 3 day ?

Thank.

**Comment by tibbi** [comment]
Hey, it isnt really simple so it wont be added in the next release yet, but I will take a look at it someday.

**Comment by tibbi** [comment]
Ill actually close it as a duplicate of #173
