### ISSUE TITLE
Event name cut

### ISSUE THREAD

**Issue by azlux** [SimpleMobileTools/Simple-Calendar#267]
Hi,
Why on the Monthly view, the name of the events are not always cut in the same way ?
If I write : 
- `Aaaaaaaaaa` : it's will make `Aaaaaaa`
- `Testtestta` : it's will make `Testtestt`
- `Hamilton` : it's will make `Hamil-`
- `Ampoule` : it's will make `Am-`

Az

**Comment by tibbi** [comment]
Hey, can you maybe send a screenshot? The labels should occupy all available space and split words in the middle too. Thanks

**Comment by azlux** [comment]
![screenshot_20171106-200021](https://user-images.githubusercontent.com/11210117/32458673-70ecd4d0-c32d-11e7-95db-31a794962747.png)
![screenshot_20171106-200153](https://user-images.githubusercontent.com/11210117/32458674-710b0ec8-c32d-11e7-9e4a-38b6205ed3ad.png)
As asked !

**Comment by tibbi** [comment]
Interesting, I will take a look at it. Thanks
