### ISSUE TITLE
Simple Calendar crashing everytime after update to 1.21

### ISSUE THREAD

**Issue by anonimou0** [SimpleMobileTools/Simple-Calendar#28]
I updated the to 1.21. The widget crashed instantly.
Then, I tried to open the app. Crashed again.
So, I tried to downgrade. Even in 1.20 or 1.19 versions, the app is crashing after the update. Even after cleaning data.
So, I cannot use the app. Here is the logcat:

[logcat.txt](https://github.com/SimpleMobileTools/Simple-Calendar/files/476742/logcat.txt)

EDIT: changed the logcat file. It seemed "broken" on notepad on Windows. I used linux to generate it.

**Comment by tibbi** [comment]
hey, thanks for the report. According to everything I have its crashing only to you, I will take a look at it :)

**Comment by tibbi** [comment]
It was still just your device crashing and Ive changed some things around that issue, shouldnt be happening from version 22

**Comment by anonimou0** [comment]
Not sure why, on 17 september 2016, it started working again, both on 1.21 and 1.20. Thanks anyway!
PS: not going to open another issue, for not being so annoying, but on 1.22, the numbers are cropped on the widget. I've to increase de size of the widget too much to get it showing up complete. And the borders grew up as well!
Thanks for the great job!!
![screenshot_20160922-224921](https://cloud.githubusercontent.com/assets/14253996/18771677/133c1ff2-8117-11e6-9b9e-40a3a246256e.png)

**Comment by tibbi** [comment]
it was crashing with day code 161016 which contains the year, month and day. Since the year and day were both 16, the app didnt know what to do with it :D Ive changed it now to 20161016, maybe it wont be crashing.
Ill doublecheck the widget issue, apparently the size paddings were increased.

**Comment by tibbi** [comment]
should be fixed with 1.23
