### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by FTno** [SimpleMobileTools/Simple-Calendar#281]
Refers to the newly added norwegian translation. I have just tested the new version of Simple Calendar (2.12.0) and the translated strings are not displayed (neither on Samsung Galaxy S7 nor an Acer tablet).

I'm not sure about this, but in the source I see that the language code 'no' is used, maybe changing it to 'nb' is worth a try. I could then test again.

**Comment by tibbi** [comment]
Ive just added an "nb", we can test. The Norwegian flag appears properly at both "no" and "nb" in android studio, not sure if it's an alternative, dialect or wtf. I cannot upload .apk files here, so Im uploading a calendar-release.apk.zip. Just remove the .zip extension from the filename, then get the file on your device and run it. If you have enabled "Install apps from unknown sources" in the security settings of your device, the app should update properly.
[calendar-release.apk.zip](https://github.com/SimpleMobileTools/Simple-Calendar/files/1505587/calendar-release.apk.zip)

**Comment by FTno** [comment]
Yes, this solved the issue, although some strings are still untranslated, but I presume you did not change the language code for the 'commons' file.

By the way, 'nb' and 'nn' are the language codes for the two official written languages (with 'nb' being the main), and 'no' a general language code.

**Comment by tibbi** [comment]
Ah ye right, I havent updated the Commons in that version. Ive done it already, so everything should be fine in the next version released in a couple days. Thanks

**Comment by tibbi** [comment]
@FTno  I wrote a guide how to set up a file watcher which will send you an email whenever a file changes, you can check it out at https://github.com/SimpleMobileTools/General-Discussion#how-can-i-get-notified-if-a-translated-file-changes . That way you won't have to keep checking files over and over.
