### ISSUE TITLE
Notifications / reminders broken

### ISSUE THREAD

**Issue by weskamm** [SimpleMobileTools/Simple-Calendar#282]
Notifications / alarms / reminders that have been set up are not working.
I am using simple calender for 2 weeks now and never received a reminder, even if they have been set up correctly.
OS: Android 8.0
Comments in playstore show the same issue also on other versions, at least 6.0

**Comment by tibbi** [comment]
ye, fixing it is on the roadmap, I will need to rewrite it quite a lot as it is broken to some people. However, since Google Calendar notifications are broken to some people too, I guess it will never be perfect :)

**Comment by tibbi** [comment]
Android 8 got a new feature that broke the notifications, it will be fixed in the next version 3.0.0. Other Android OS versions apparently have other issues.
