### ISSUE TITLE
v2.10.1 and newer fails to build on F-Droid

### ISSUE THREAD

**Issue by breversa** [SimpleMobileTools/Simple-Calendar#283]
https://f-droid.org/wiki/page/com.simplemobiletools.calendar#2.10.1

**Comment by tibbi** [comment]
they apparently dont have the latest SDKs on their machine yet... They fail quite a bit lately, it is reported at https://forum.f-droid.org/t/is-the-f-droid-build-process-currently-broken/195/32 . Ill leave the ticket here just as reminder to check f-droid from time to time, but there's nothing I can do on my side.

**Comment by breversa** [comment]
Thank you for your lightning-fast reply. :-)
I'm glad to know that this issue is on the F-Droid side. I thought of it but I wasn't sure.

**Comment by tibbi** [comment]
so ill close this as a duplicate of https://github.com/SimpleMobileTools/General-Discussion/issues/42

**Comment by breversa** [comment]
2.12.0 builds fine again on F-Droid : https://f-droid.org/wiki/page/com.simplemobiletools.calendar#2.12.0 :-)

**Comment by tibbi** [comment]
thats a good sign, Ill see if the 3.0 versions build too
