### ISSUE TITLE
[FR] Disable or silence reminders for specific calendars

### ISSUE THREAD

**Issue by mtbu** [SimpleMobileTools/Simple-Calendar#284]
Would it be have an option to make some calendars silent or not show reminders at all? This would be useful for synced calendars where all events have annoying reminders, while still allowing reminder sounds for personal events

**Comment by tibbi** [comment]
could be added someday in the future, but dont really expect it anytime soon

**Comment by madduck** [comment]
I would also really like this feature. Pleeeeeaaaaaase? ;)

**Comment by tibbi** [comment]
it is handled by the system from Android 8+, which supports Audio streams. A button for quickly customizing notifications will be added in 6.13.0's app settings.
