### ISSUE TITLE
Fix multiple days lasting events on event list

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Calendar#285]
Especially if some past events are also shown (email from 30.11.2017)

**Comment by 741N** [comment]
Do you mean by this that the widget will show the first date of the multi-day event at the top, and ignore the current date? Because that's what I have, but it doesn't show old events.

**Comment by tibbi** [comment]
it's a bit hard to explain. The current date should always be written at the top, the issue is that the multi-day event doesnt have the start date written anywhere now, if I remember correctly.
