### ISSUE TITLE
[CalDAV Sync] Duplicate events, if single repetitive event is modified externally

### ISSUE THREAD

**Issue by MichaIng** [SimpleMobileTools/Simple-Calendar#294]
Hey there,

I use Nextcloud as caldav server and sync my calendar(s) from there to desktop and mobile device. On desktop I use thunderbird lightning + sogo connector extension, which works great. On mobile device I so far used the stock android calendar. But I found simple calendar to be nice, with dark theme, fast startup and interface, thanks for that 👍.

But if I configure simple calendar to use caldav sync (enabled via davdroid), changing a single event a row of otherwise repetitive events externally (via thunderbird or directly on Nextcloud web ui), those appear doubled on simple calendar: one is the old one from repetitive row, which seems to be not removed as expected, the other one appears as a single non repetitive new event, as expected. After using the calendar this week, I even found some events to appear trippled and attached to the wrong calendar instance.

Also after editing some events of repetitive rows on simple calendar, they appeared doubled (or worse) on thunderbird and Nextcloud. I guess the gap in the repetitive row, if a single event of it gets changed, simple is not handled/created correctly.

I hope I explained it understandable enough. Simple steps to reproduce:

1. Create a repetitive event (mine are without ending) externally on dav synced calendar.
2. Sync the calendar via e.g. davdroid onto android device.
3. Configure simple calendar app to sync/show it.
4a. Edit a single event of the repetitive event "row" externally (on caldav server or 3rd client)
5a. See synced result on simple calendar (in case compare to result on android stock calendar)
4b. Edit a single event of the repetitive event "row" on simple calendar.
5b. See synced result on caldav server or 3rd client (in case compare to result, if this was done via stock calendar.

Best regards and thanks for the otherwise great work!

**Comment by Zero3** [comment]
I'm seeing this issue too. It's quite bad :(.

**Comment by tibbi** [comment]
fixed many issues related to repeating event exceptions, will be added in version 3.1.0 released soon. If you find more problems, open a new issue. Thanks

**Comment by Zero3** [comment]
@tibbi :+1:
