### ISSUE TITLE
use this calendar with java 

### ISSUE THREAD

**Issue by ankitguptaiphone** [SimpleMobileTools/Simple-Calendar#296]
how to use use this kotlin calendar  with native java

**Comment by tibbi** [comment]
theres no java involved, just run the project in android studio as usual.

**Comment by Sourabh3133** [comment]
@tibbi  I know your full calendar written in kotlin , I have a existing java project , can I use  this calendar with my java project  , is it possible ?

**Comment by tibbi** [comment]
I dont know what you mean by using the calendar. It is not a library that you just add somehow, so probably not.
