### ISSUE TITLE
Dark background color

### ISSUE THREAD

**Issue by rugk** [SimpleMobileTools/Simple-Calendar#3]
It would be nice to be able to use a dark mode (preferable a #000 background), especially for AMOLED devices where this can save battery.

Of course this is basically valid for all SimpleMobileTools.

**Comment by tibbi** [comment]
good point as dark themes are always getting more popular in the Android world too, will take a look at all apps soon

**Comment by tibbi** [comment]
there is a dark theme in the Calendar from 1.11, check it out. Its not #000, I just used the default system dark theme. It will be implemented to other apps the same way.

**Comment by tibbi** [comment]
So Ive already added dark theme to all apps. As Ive said its not #000, Im just invoking the default system dark theme so it might differ a bit by device (on my its #303030). Ive checked some popular app dark themes but they werent really #000 so I might have to do some research on the proper colors.

**Comment by rugk** [comment]
This theme uses #000 for the background in my testing: https://play.google.com/store/apps/details?id=com.chummy.jezebel.material.dark.regression

**Comment by tibbi** [comment]
okay Ive updated all apps with a black #000 background, should be downloadable within a couple hours from Play Store, maybe 1-2 days on Fdroid.
