### ISSUE TITLE
Invite to event by email

### ISSUE THREAD

**Issue by BuZZ-dEE** [SimpleMobileTools/Simple-Calendar#303]
I would like invite people to an event by email. Plesse add this feature.

**Comment by tibbi** [comment]
well I don't have the concept of participants, you can just open an existing event, click Share, then send it  to them. It sends an .ics file which is parsed nicely by some email clients, Gmail too. Right after the email opening he will see all event info in a human readable format.

**Comment by BuZZ-dEE** [comment]
Okay, then you need this concept. 😉 I you want to add more email addresses, it is a pain to do it by sharing.

**Comment by tibbi** [comment]
adding participants isnt on the roadmap, maybe in the very far future. Especially if my app would have to send the invitations it would need the internet permission, which I dont want to add. Maybe Google sync handles it somehow on its own, not sure.

**Comment by AeliusSaionji** [comment]
> I you want to add more email addresses, it is a pain to do it by sharing.

Seems like a problem with your mail client 😄 

For me, I can simply share to mail, then type in as many participants as I want...

If you want an internet connected calendar, you might as well just use google or microsft's calendar app. They have these features worked out already. IMO they are very far out of the scope of a simple calendar.

**Comment by git001** [comment]
I would like also to have this feature.  
Is there a sponsoring possible?

This is the part of the iCalendar spec which I refer to  
https://tools.ietf.org/html/rfc2445#section-4.8.4

**Comment by git001** [comment]
What can you motivate to add this feature?

I mean "Just" to add the field and option to add Attendee.  
Some caldav servers send the mail to the Attendee, so you don't need to send mails.

This feature could add a requirement for permission to access contacts.

**Comment by tibbi** [comment]
Contacts permission is already listed anyway, it is needed at adding birthdays. I dont know when will I get to it, not much you can do there.

**Comment by downeym** [comment]
Another voice hoping for support of the ATTENDEE component of the iCalendar standard. 

Sending invitations is handled by the server once there is a value for this field. 

Right now this is the only thing keeping me and others from switching from the stock proprietary Android/Google calendar app. I use Nextcloud for my calendar server, and it works fine with Google's app, but I really don't want to be stuck relying on Google anymore.

Also happy to donate for this critical feature. 😃

**Comment by agherzan** [comment]
This is a core feature needed in any calendar app. It's one year now since this issue was created. Any plans for addressing it?

**Comment by tibbi** [comment]
ye, I will add it soon to CalDAV synced events

**Comment by tibbi** [comment]
will be added in 6.4.0

**Comment by agherzan** [comment]
Very nice. Does it include replying to invitations as well?

**Comment by tibbi** [comment]
if you mean changing your status, it might be added. Im not yet sure.

**Comment by feutl** [comment]
> ye, I will add it soon to CalDAV synced events

Sorry for replying on such an old issue, but how exactly should this feature work?
And what are the requirements to have it working correctly?

**Comment by tibbi** [comment]
well once you select some CalDAV synced event type, like your email, a new field with Attendees will show up. You can insert emails there, and your caldav server decides if it sends an email or not. After creating an event, if you invited someone, their attendance status will show up too.

**Comment by feutl** [comment]
ok thanks, seems my nextcloud instace which I am using für caldav does not send out invites for events. even though it sends emails for everything else.
hmm, if someone knows sth bout this I would be more than happy to know about it, otherwise I start digging around.

thanks

**Comment by feutl** [comment]
> 
> 
> For me it does not work. If I try it with [Etar](https://github.com/Etar-Group/Etar-Calendar) than it does work with my [Nextcloud instance](https://disroot.org).

Because for the same reason as mentioned here ?
https://github.com/SimpleMobileTools/Simple-Calendar/issues/991
