### ISSUE TITLE
Add Australian holidays

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Calendar#304]
http://www.industrialrelations.nsw.gov.au/oirwww/NSW_public_holidays/NSW_Public_Holidays.page

**Comment by ryliejamesthomas** [comment]
FYI public holidays in Australia vary by state, so just adding the NSW ones will not be so useful.

**Comment by tibbi** [comment]
oh gosh, you really dont like easy lives over there
