### ISSUE TITLE
[FEATURE] "Add to calendar" support

### ISSUE THREAD

**Issue by cryptomilk** [SimpleMobileTools/Simple-Calendar#311]
I have the FOSDEM Companion installed to check talks at the event. You can find the app here: https://f-droid.org/packages/be.digitalia.fosdem/

If you go to a talk on the top right is a button to add the event to the calendar. If you press the button you get an error: "No compatible calendar found."

It would be great if Simple-Calendar would be a compatible calendar.

**Comment by tibbi** [comment]
done, will be added in 3.1 which will start rolling out maybe today. I plan handling more calendar intents, just couldnt really find any real world case scenarios or apps using them. Thanks
