### ISSUE TITLE
Check Nextcloud caldav synchronizing

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Calendar#312]
check proper event time + all-day event dates

**Comment by tibbi** [comment]
what app version do you use? Some related things have been fixed in 3.2.0.

**Comment by ainola** [comment]
I'm using the latest version in the F-Droid repositories (3.2.1)

**Comment by ainola** [comment]
Here's a side-by side of the same CalDAV source with the stock LineageOS calendar application and version 3.2.1. Note that the person's birthday is today, the 28th and not the 27th. Gave me a bit of of a scare, then some confusion last night :)

![bug](https://user-images.githubusercontent.com/5383525/35489251-850340de-0451-11e8-8b4e-f38065cdc447.jpg)

**Comment by ainola** [comment]
I have two all day events on the first of every month. I just noticed that one of those events is one day before, and one of those events is two days before.

**Comment by tibbi** [comment]
recheck with 3.2.5 please, it should be fixed (or at least improved)

**Comment by tibbi** [comment]
Ill close it, reopen if it is still broken. Thanks

**Comment by ainola** [comment]
The new version just arrived in Fdroid and it looks like it works! Thank you for your great work!

**Comment by tibbi** [comment]
alright, cool. There can still be issues with editing single instances of recurring events, but thats a different topic :)
