### ISSUE TITLE
Reminder notification not working

### ISSUE THREAD

**Issue by evitalis** [SimpleMobileTools/Simple-Calendar#33]
Using Android 6.0.1 stock ROM with root I set a reminder of 30 before an event but never recived any sort of notification. I do not use the widget on my home screen so I am unsure if that is related. 

What type of notification should be expected, and can a default reminder be set? For instance always use 1 hour before an event.

**Comment by tibbi** [comment]
it should be a simple icon at the status bar, by default its set to fire at the event start. Thats how I like it, 1 hour is too much if you have more things scheduled during the day. Ill check it soon.

**Comment by tibbi** [comment]
should be working from version 1.24
