### ISSUE TITLE
Add event button doesn't work

### ISSUE THREAD

**Issue by af9** [SimpleMobileTools/Simple-Calendar#334]
The (+) add button doesn't work for me. After installing the app, the button was working fine. I just configured the CalDAV sync but even then it was still OK. Later I tried to add a new event, but nothing happened. The menu button works fine, same as the button for changing the calendar view.
If I have a long list of events and I'm pressing the add button, the app opens the modification screen of that event, which is located right behind the add button. Looks like the button is shown but not really there. Any idea, what might be wrong?

**Comment by tibbi** [comment]
Not sure, what app version and Android OS version do you have?

**Comment by af9** [comment]
App version is 3.2.2 (from Play Store) on an Samsung Galaxy S4 with Android 5.0.1
I know, it's rather old, but still working properly and I don't have problems with other apps.

**Comment by tibbi** [comment]
ye thats fine. So the button is broken only at the Event List view? At others it works fine? Ive just tested it and it works fine to me.

**Comment by af9** [comment]
No, the button doesn't work at all anymore. It worked at the beginning for a while. I changed some settings and synced with CalDAV. Even then it still was working. Then I closed app and locked phone. And later I want add new Event but button doesn't react, no matter what view.

All other buttons still work fine. Just the add event button does not react.

**Comment by tibbi** [comment]
weird, I dont think it is related to caldav. I wont be home tomorrow, but I can take a look at it someday i guess

**Comment by af9** [comment]
Would be nice. I was looking for an easy-to-use app like this just focusing on the main functions: managing events and syncing with my calendar. So I was happy when I found this app.
I already played a lot with it today in order to find the cause of the issue. But no matter what I did (reboot, killing all running apps, clean cache, ...) I could not solve it. Tomorrow I can try to delete and reinstall the app again. Maybe I'll get more information.

**Comment by af9** [comment]
So, my today's investigation bring up, that it seems to be related or even caused by [Simple Calendar Widget](https://play.google.com/store/apps/details?id=com.anod.calendar).
I'm using this widget to see all upcoming tasks and appoinments on my home screen and easily start the calendar app just by touching the widget.
Now I figure out that if I start the Simple Calendar app from Simple Calendar Widget, the add button in the app does not react at all. If I start the app directly from app launcher, the add button works fine.
Any idea, what could cause such different behavior depending on the way how the app ist started?

**Comment by trubitsyn** [comment]
Adding when started from widget works for me. Version 3.2.2, Android 6.0.

**Comment by af9** [comment]
Unfortunately Android 6.0 is not available for Galaxy S4 and currently I do not plan to update to inofficial ROM.
Which widget are you using? I can try to test, if this is working for me as well.

**Comment by trubitsyn** [comment]
I've tried with "Calendar events" and "Calendar month"

**Comment by af9** [comment]
There are plenty of widgets, so not sure I found same you've tried. Anyway I tested with this [one](https://play.google.com/store/apps/details?id=sk.mildev84.agendareminder) and with this the add button works fine too. So that means my problem is somehow related to the combination of Simple Calendar app and Simple Calendar Widget (maybe with some influence from Android 5.0.1).
I guess, if I start a new issue at the widget development board, they assume the problem is caused by calendar app. And since nobody else seems to observe this issue, I think there is not enough motivation to spend time for investigations in that problem.
Reinstalling the app doesn't help either. Always same behavior. So I guess the best solution is, I will just start the calendar app using another widget or directly from launcher until I will buy new phone.
Thank you anyway guys
A.

**Comment by tibbi** [comment]
aha didnt know you use a third party widget. Anyway I dont see how would that be a problem, Ill check it out soon.

**Comment by af9** [comment]
Yes, I didn't mention the widget when I start the thread because I did not expect any influence from the widget either. I had to test a while in order to find out that it is related to the widget. And yes, I think it's not easy to find the actual cause of the problem. So since debugging is not easy especially for this particular constellation of OS, app and third-party widget and because it is probably not a common combination upon the users of the Simple Calendar app, its not worth to spend a lot of time for investigations. Its just interesting if someone else observe same behaviour when using the same [widget](https://play.google.com/store/apps/details?id=com.anod.calendar) like me to start the Simple Calendar app for trying to add a new event using the add button.

**Comment by tibbi** [comment]
its actually already fixed, will be added in the latest version 3.2.3 released soon.

**Comment by af9** [comment]
Ohh, that's great. Sorry, I didn't notice the commit...
I will test as soon as 3.2.3 is released and give a feedback.
Thank you very much!

**Comment by af9** [comment]
Today I updated to version 3.2.3 and now the add button works like a charm!
Great work! Thank you very much!
