### ISSUE TITLE
User data

### ISSUE THREAD

**Issue by juergenroland** [SimpleMobileTools/Simple-Calendar#336]
Hello,

i want to backup my data from the calendar manually. Is there a file where all events are stored? If so, where can i find it?

Thanks,
juergen

**Comment by trubitsyn** [comment]
Hello! You can export all events manually by clicking "Export events to an .ics file" in the dropdown menu (three dots in the top-right of toolbar) and selecting a location where to save the file.

**Comment by juergenroland** [comment]
Hi, thanks for the quick response.

i can't launch the app right now due to the phone running in safe mode after being stuck in a boot loop (because of an issue not related to the calendar app). To resolve the issue, I need to reinstall some apps, among them the calendar and am afraid to lose my data. Is there a way to backup the files without launching the app? Because of the safe mode i am not able to use any of the usual backup apps like titanium.

Regards

**Comment by trubitsyn** [comment]
Hello. You can flash a custom recovery (CWM or TWRP) and save a full Nandroid backup of the desired partition somewhere on your internal storage or SD card and then move it  to your desktop PC with ADB. Please note that flashing a custom recovery requires your phone's bootloader to be *already* unlocked.

There's also an [adb backup](https://developer.android.com/studio/command-line/adb.html#issuingcommands) command (see "Backup and Restore Commands" section) that does *not* require an unlocked bootloader, but I haven't tried it in the safe mode. Maybe it will work for you.
