### ISSUE TITLE
[Feature request] Allow default reminder time in minutes

### ISSUE THREAD

**Issue by evitalis** [SimpleMobileTools/Simple-Calendar#34]
Would it be possible to have a setting that allows for a custom default time rather than needing to enter the minutes each time? Having both side by side would be good but having a default of 30 or 60 minutes would be fairly helpful. Would save time adding a bunch of events and typing in the minutes each time.

**Comment by tibbi** [comment]
yeah, I could remember the last inserted time and set it as the default for the next created event
