### ISSUE TITLE
[FR] Add setting for setup the default calendar view

### ISSUE THREAD

**Issue by af9** [SimpleMobileTools/Simple-Calendar#340]
It might be useful to have a setting in preferences for configuring the default calendar view. So for instances someone might prefers the week-view or the simple event list as default view when starting the Simple Calender app.

**Comment by tibbi** [comment]
there is a button on the actionmenu for changing view, it will be remembered once changed.

**Comment by af9** [comment]
Ohh, I see. Then it is again related to my special widget, which always starts the calendar app in today's day-view or with the particular event that I've touched. So no new feature necessary...

**Comment by tibbi** [comment]
ye because the widget sends an extra field defining the day that should be open, so I open the proper view
