### ISSUE TITLE
Is iCloud Sync possible? 

### ISSUE THREAD

**Issue by maracuja-juice** [SimpleMobileTools/Simple-Calendar#346]
Is it possible to sync this beautiful calendar UI to iCloud?

**Comment by tibbi** [comment]
it should be possible, but I have no experience with it. You will need some third party "CalDAV sync adapter" and point it to the icloud servers, then enable CalDAV sync in Simple Calendar settings and select the proper calendars. Here is one tutorial which explains it, but I havent tried it, it is just a fast google search result https://miapple.me/android-sync-icloud-calendars-android-phones-tablets/
