### ISSUE TITLE
"Default event reminder" missing

### ISSUE THREAD

**Issue by Tuffiglig** [SimpleMobileTools/Simple-Calendar#347]
Hello folks.
In the new version, when i'm creating a new event, there is now always the last chosen value the default.
That is not very helpful. Most of my events have my old default "At start". The others are mixed with different time values.
I prefer the "Default event reminder" at a value of my own choice to a fixed value.

Tuffi

**Comment by tibbi** [comment]
Ye this one was changed intentionally too to make it more dynamic, I dont really plan changing it anytime soon, only if too many people would be having issues with it. Thanks

**Comment by Tuffiglig** [comment]
:(
