### ISSUE TITLE
Snooze interval

### ISSUE THREAD

**Issue by Tuffiglig** [SimpleMobileTools/Simple-Calendar#348]
Hello folks.
In the new version when there is an event and i click "Snooze", after that there comes up a selection box with different times. That is not simple anymore.
In the old box I clicked "Snooze" and I know, that in 10 minutes the event will pop up again.
Now, when I'm in stress or think about something, this new box is to much distraction and I'm absolute annoyed and out of my workflow.
Please bring back a setting where I can choose if i want a variable Snooze interval each time I click "Snooze".

Tuffi.

**Comment by tibbi** [comment]
Hey, well if you chose 10 minutes once, it will be selected as the default so just press OK. Theres many cases when users want different snooze reminder, so this way suits them a lot better. Thanks

**Comment by Tuffiglig** [comment]
Yeah. But I don't want to ask everytime for the same Answer. Everytime.

**Comment by tibbi** [comment]
I might add some toggle for it in the future, we will see. I dont promise any date.

**Comment by Tuffiglig** [comment]
Thank you very much.
And also for your work.

**Comment by tibbi** [comment]
a toggle will be added in 3.2.5 released soon

**Comment by Tuffiglig** [comment]
Thank you very much. Works very chaming.

**Comment by tibbi** [comment]
alright, cool
