### ISSUE TITLE
No entries shown in day view

### ISSUE THREAD

**Issue by oldspace** [SimpleMobileTools/Simple-Calendar#349]
After installing the newest version of simple calendar, the app doesn't show anything in day view. In the week or month view I can see the entries in the calendar. 

I have a Sony Xperia Z1 Compact (D5503) with Android 5.1.1 from Sony.

**Comment by tibbi** [comment]
Do you at least see the day header like "February 5", or not even that? Do you launch the app from some widget, or through the app launcher? Just to make sure, what app version do you have? It is at the bottom of About page. Thanks

**Comment by oldspace** [comment]
Usually I start it with the widget (full screen). Then I don't even see the header. After some switching between the different views (day/month/year) it works sometimes. If I start the app directly everything works fine.
The app version is 3.2.3.

**Comment by tibbi** [comment]
ok, please retry with 3.2.4 once it is available, it should be fixed there. Reopen if it is still broken.

**Comment by oldspace** [comment]
It seems to work now. Thanks!
