### ISSUE TITLE
[Feature] Solarized color scheme

### ISSUE THREAD

**Issue by evitalis** [SimpleMobileTools/Simple-Calendar#35]
Would it be possible to get the [solarized](http://ethanschoonover.com/solarized) color scheme as an option for this? It might contrast with the orange header but soloarized is much easier to read, especially the dark version.

**Comment by tibbi** [comment]
Solarized theme will be added to all apps, for now I just couldnt figure out some nice combination of colors, as the Primary color palette is limited from 3.0.
