### ISSUE TITLE
Show repeatable events at search results

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Calendar#351]

**Comment by michaelof** [comment]
Simple-Calender 4.0.0
Android 6.0
calDAV synced calendar from Nextcloud 13.0.2 via DAVDroid 1.11.2-ose


Hi Tibor,

not sure about the status of this issue - as searching for repeatable events is finding "some" events. 

"Some" means I've no idea which instances are found, and which not :) On my device for a search string some past events from 2016 and 2017 are found, and future events - which I wanted to find - are not.

So if "feature-request" means "feature-request" and the strange results are pure by chance: +1 for this feature, and fine for me to wait, Google Calender already finds them, in the meantime :)

If they already should be found, this issue might be changed to "bug"


Regards,
Michael

**Comment by tibbi** [comment]
Well the issue is quite simple. Only the first occurrence of the event is shown, no other repetition.
