### ISSUE TITLE
Add a mechanism to get additional feature via plugin APK

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [SimpleMobileTools/Simple-Calendar#353]
I have mentioned this feature in #67, but now I think I should open a split issue for this. Whis this mechanism you'll be allowed to add additional feature to the main app, especially additional calendar. 
The plugin APK should be performanced as this:
1. This app does not operate by itself independently and show its icon in the launcher.
2. This app running as component of main app while main app is opened.

For the main app, it should add some hooks to accept features from plugin apps. Some examples can be found [here](https://apkpure.com/developer/J2%20Interactive).

**Comment by tibbi** [comment]
Ill actually close this as I dont plan adding plugins etc
