### ISSUE TITLE
support per-event colors of CalDAV calendar

### ISSUE THREAD

**Issue by MyLogins** [SimpleMobileTools/Simple-Calendar#360]
DAVdroid support per-event colors for events (RFC 7986 COLOR) since version 1.7, but unfortunately Simple-Calendar handle all events from a CalDAV calendar as one event type with the same color.

**Comment by 532910** [comment]
Not only event, but whole calendar color should be taken from CalDAV. Same RFC 7986.
```
# cat .Radicale.props 
{"tag": "VCALENDAR", "ICAL:calendar-color": "#b7d841ff", "D:displayname": "calendar", "C:supported-calendar-component-set": "VEVENT,VJOURNAL,VTODO"}#
```

**Comment by stavros-k** [comment]
Hey, is there any plans for this? :)

**Comment by fohfuu** [comment]
Adding to this also. I can barely read the text when the colours are so random - if you have more than a couple of calendars, no colour for the background will suit all of them. It's really inaccessible for anyone with sight issues.

**Comment by azzamsa** [comment]
To have multiple color, I create separate calendar in my Nextcloud calendar. 

If this issue solved, It means I can use different color types in Simple-Calendar with only one CalDav calendar?
I never know it was a thing.

**Comment by allmynamesweretakenomoreideas** [comment]
My wife is using per-event colors like crazy, she has her own color scheme for different types of events and their priority (more then 10 colors). I am trying to convice her to use our own calDAV server instead of google calendar. I already managed to import her calendar with all its colors to our calDAV server. But its a no-go for her, that simple-calendar does not show these colors nor is it editable within the event options. There seems to be no other calendar on f-droid supporting this basic feature, so simple calendar with this request is as close at it gets - so I am patient and wait...it is for a good purpose ;)

**Comment by Josh-Reimer** [comment]
I use Googles calendar(their calendar not their calendar app) for all my events and tasks. Simple Calendar makes all my events the same color then and I want to be able to color code some of them. Would be a nice feature.

**Comment by hackrid** [comment]
Maybe one day this becomes reality :)
That's the only feature I'm missing since years.

Would be really happy about it. Thanks for your work on Simple Calendar.

**Comment by Naveen3Singh** [comment]
Hello!
I have uploaded a test APK with support for CalDAV event colors here: https://github.com/Naveen3Singh/Simple-Calendar/releases/download/untagged-2c4ac5427e11b92736df/calendar-prepaid-debug.apk
If anyone is willing, please check it out and let me know in case of any issues. Alternatively, if you have the skills you can build an APK from this PR: https://github.com/SimpleMobileTools/Simple-Calendar/pull/2041 

Thanks!

**Comment by PowerUser64** [comment]
Nice work @Naveen3Singh! I tested the debug APK you sent. For some reason, it can't change colors in the CalDAV calendar on my nextcloud server (it only shows "Default" in the menu. When I try modifying the colors on a Google calendar, I am allowed to change them. Do you know what might be causing this?


|![Screenshot_20230408-104245_Calendar_debug](https://user-images.githubusercontent.com/24578572/230735613-83a56429-4900-474e-b62d-e08683e3d6c4.png)|![Screenshot_20230408-104353_Calendar_debug](https://user-images.githubusercontent.com/24578572/230735626-4632d997-c5f4-44c3-a595-04f4447d6340.png)|
|---|---|

*Colors on a nextcloud calendar event (left) vs colors from a google calendar event (right)*

I also tried viewing events from Nextcloud that I had already created with custom colors, they didn't show up (this is the behavior of the release version as well).

Additionally, something that would be nice to have is if the color got reselected in some way upon opening the color menu for the second time.

Here's a screenshot of a color picker from another app called [Iconify](https://github.com/Mahmud0808/Iconify) that I like a lot, if you're looking for design ideas.

|![Screenshot_20230408-110314_Iconify](https://user-images.githubusercontent.com/24578572/230736725-c7aecd9a-eb8d-4def-b89e-b697dbc04466.png)|
|---|

**Comment by tibbi** [comment]
@PowerUser64 does changing colors of DAVx5 calendars work in any other app? If you dont have any other calendar app, would be good if you could test it.

**Comment by PowerUser64** [comment]
Thanks for the ideas, @tibbi! I checked DAVx⁵'s calendar settings, and it turns out the options to let apps manage colors were disabled. With these options enabled, I can change event colors in another calendar 
app, [Etar](https://github.com/Etar-Group/Etar-Calendar), but when I try changing them with this debug build, the app crashes when I tap the *change color* button.

||![DAVx⁵ Settings](https://user-images.githubusercontent.com/24578572/230739826-06706b76-fe1e-47a9-9746-44765dc4222b.png)|![debug app crashing](https://user-images.githubusercontent.com/24578572/230740079-ccc17d42-4d31-4cf5-b611-ad6f5abf04a3.png)||
|---|---|---|---|
||*the DAVx⁵ settings I changed are the two at the bottom here*|*debug app crashing*||

**Comment by Naveen3Singh** [comment]
@PowerUser64 thanks!
I would have tested with Nextcloud but the trial website was down for some reason. I'll try to reproduce and fix this crash.

> would be nice to have is if the color got reselected in some way upon opening the color menu

already fixed it in the PR. The release version won't have this issue. 



> I checked DAVx⁵'s calendar settings, and it turns out the options to let apps manage colors were disabled

@tibbi  I think we should simply hide or disable the event color setting in this case, what do you think?

**Comment by tibbi** [comment]
sure, we can hide it. Lets implement the most common usecase first.

**Comment by Naveen3Singh** [comment]
@PowerUser64 updated APK is here: https://github.com/Naveen3Singh/Simple-Calendar/releases/download/event_color_test_release/calendar-prepaid-debug.apk

**Comment by PowerUser64** [comment]
It all works! 🥳

<img src="https://user-images.githubusercontent.com/24578572/231251310-6a544e65-687e-4f49-81e0-da8700973279.png" width=200>

**Comment by hackrid** [comment]
amazing! confirm working on my side, too.


ot:
sad to find out colors are not reflected in thunderbird... is anyone of you seeing colors synced to thunderbird?

**Comment by petitengineer** [comment]
@Naveen3Singh Thank you for supporting colors for Caldav!!! I was shocked when I read the change log. **I noticed a minor glitch: colors do not seem to show for All-day events on version 6.21.7. Screenshot shown below.**

![Colors not showing for all day events](https://user-images.githubusercontent.com/100378915/232356518-503b7cf7-b823-4b94-870a-092e2c19417f.jpg)

Any chance for a fix, or is this just a glitch showing up on my end?

**Comment by Naveen3Singh** [comment]
@petitengineer I'll check that and respond soon, thanks!

**Comment by Naveen3Singh** [comment]
@petitengineer all day events works perfectly for me. Not sure why it's not working with your setup. 

Tested with Google Calendar.

**Comment by PowerUser64** [comment]
I tested it with my nextcloud setup and I found the same problem. It seems the problem is only with the top bar in the week view that displays all-day events. it displays fine from google calendar though.

**Comment by Naveen3Singh** [comment]
Right, events in the top bar are still using the default color, I will fix it soon (It's a UI glitch)

**Comment by boardend** [comment]
Just got the update from F-Droid (6.21.7) and now see the colors form Nextcloud synced with DAVx⁵ :rocket:

Thank you so much :clap:

**Comment by tibbi** [comment]
should be working just fine already
