### ISSUE TITLE
[Feature Request] choose calendar for term list

### ISSUE THREAD

**Issue by Micha-Btz** [SimpleMobileTools/Simple-Calendar#362]
Hey,

at first thanks for the nice apps. I have four calendar and also imported the holiydays.
In the calendar widget this is good and useful but in the term list all this is shown.
Like Valentins Day and so on. Would be great if I can choose which calendars are shown in the term list.

Thanks Micha

**Comment by tibbi** [comment]
Hey, maybe it will be solved somehow in the future. Thanks

**Comment by lambtho12** [comment]
I would also really like an option similar to that, where it would be possible to select which calendars are shown in a widget.

I have multiple calendars (personal, work, shared with spouse,...) and what I would ideally like to use is
- the month view widget with all personal and shared with spouse stuff.
- the list widget only for work as I tend to fill in every minute of my workday in that calendar.

**Comment by daxcore** [comment]
+1 👍

**Comment by Micha-Btz** [comment]
out
