### ISSUE TITLE
Disable/Toggle Widget Transparency

### ISSUE THREAD

**Issue by freakin-c** [SimpleMobileTools/Simple-Calendar#364]
I'd appreciate the possibility to toggle background transparency completely instead of using the slider next to the color picker.
Basically this is due to my damaged screen so I can't reach the rightmost area of this slider.
Thank you in advance!

**Comment by tibbi** [comment]
Well the vast majority of users dont have a damaged screen tho, I dont want to modify the app just for that. Thanks

**Comment by freakin-c** [comment]
I agree with that but some more users than me are likely to have a damaged screen and others might want an even more simplified solution to disable transparency. 
Would you accept a pull request implementing this?

**Comment by tibbi** [comment]
No, I dont plan redesigning the widget config screen for now.

**Comment by freakin-c** [comment]
Ok, good to know. Thanks a lot for your great work!
Let me know, if/when you plan to redesign it :)
