### ISSUE TITLE
Missing Widget

### ISSUE THREAD

**Issue by nerjamartin** [SimpleMobileTools/Simple-Calendar#366]
Impossible to add Widget to main screen.

Simple Calendar Widget does not appears on Widget selection.

Version: `Downloaded from F-Droid (last version v3.3.0)`
Device: `Motorola MotoG4 Plus with Android 7.0 kernel 3.10.84 (Thu Nov 23, 2017) `

Thanks in advance

**Comment by tibbi** [comment]
Hey, have you moved the app on an SD card? If yes, you wont see the widgets. It is an Android system limitation, not much to do against it, just move it back on the internal storage.

**Comment by nerjamartin** [comment]
Ahhh!!! That works for me!!! 

Nice!!! Thanks a lot for the lighting fast answer :)

**Comment by tibbi** [comment]
Ye, Google should mention it at moving the app, sadly the user experience of their products is legendarily bad. I will be adding a FAQ someday, that will mention it.
