### ISSUE TITLE
All-day CalDAV events show up one day early

### ISSUE THREAD

**Issue by angelsl** [SimpleMobileTools/Simple-Calendar#368]
Caused by 91d5c3dd00e16320ede02b71ca07eb7acd1f9fa7

I'm not sure what the intention was behind that commit (is there some calendar sync adapter that is inserting non-UTC timestamps into the calendar provider?), but this breaks Google account calendar all-day events _if the user's timezone is greater than GMT+5_:

Google has `startTS` set to midnight UTC on the day itself, and `endTS` set to midnight UTC on the day after.

([CalDAVHandler.kt L237](https://github.com/SimpleMobileTools/Simple-Calendar/blob/master/app/src/main/kotlin/com/simplemobiletools/calendar/helpers/CalDAVHandler.kt#L237))

```kt
// 1
if (allDay == 1 && timeZone == "UTC") {
    val offset = DateTimeZone.getDefault().getOffset(System.currentTimeMillis()) / 1000
    val FIVE_HOURS = 5 * 60 * 60
    startTS -= offset
    startTS += FIVE_HOURS
    if (endTS != 0) {
        endTS -= offset
        endTS += FIVE_HOURS
    }
}
// 2
```

After this, if the user's timezone is further ahead than GMT+5 i.e. `FIVE_HOURS - offset < 0`, the timestamp is now some time in the previous UTC day.

([CalDAVHandler.kt L261](https://github.com/SimpleMobileTools/Simple-Calendar/blob/master/app/src/main/kotlin/com/simplemobiletools/calendar/helpers/CalDAVHandler.kt#L261))

```kt
if (event.getIsAllDay() && endTS > startTS) {
    event.startTS = Formatter.getShiftedImportTimestamp(event.startTS)
    event.endTS = Formatter.getShiftedImportTimestamp(event.endTS)
    event.endTS -= DAY
}
// 3
```

`getShiftedImportTimestamp` takes the UTC timestamp and reinterprets it as local time, and then sets the clock time to 0500 local time, then converts it back to a Unix timestamp (i.e. UTC).

The problem is that if the local TZ is ahead of GMT+5, the UTC timestamp and consequently the reinterpreted local timestamp end up one day earlier.

Here's some real values for an all-day event on 11 April 2018. My timezone is GMT+8.

* @ 1: 1523404800: 2018-04-11 00:00:00 UTC = 2018-04-11 08:00:00 GMT+8
* @ 2: 1523394000: 2018-04-10 21:00:00 UTC = 2018-04-11 05:00:00 GMT+8
* @ 3: 1523307600: 2018-04-09 21:00:00 UTC = 2018-04-10 05:00:00 GMT+8

**Comment by jlamoure** [comment]
Android 7.1.2
simple-calendar v. 6.6.1

I'm in Central Standard Time (GMT-5?) new all-day events are one day *late.*

Create all-day event.
Event shows as correct day.
Refresh CalDAV.
Event gets pushed one day into the future.
Editing the event to the correct day and then refreshing does stick, i.e., I'm not required to edit it and tell it to save as the day before to actually save it as the day in question.
