### ISSUE TITLE
Incorrect Holiday Date

### ISSUE THREAD

**Issue by DS2X** [SimpleMobileTools/Simple-Calendar#371]
Using the app's menu:
Menu > Add Holiday > United States

The holiday "President's Day" is on 2018-02-19 (Monday), while the holiday added from the Simple Calendar app is 2018-02-21 (Wednesday). (YYYY-MM-DD)

• Google Calendar installed is set to Disabled.
•Calendar Storage's data was cleared before installing Simple Calendar and importing holidays.
• No Google Account on the device.

**Comment by tibbi** [comment]
ye some more advanced repetition rules arent supported yet, will be improved in the future.

**Comment by tibbi** [comment]
holidays in USA should be better from version 4.x
