### ISSUE TITLE
Exchange Integration 

### ISSUE THREAD

**Issue by F3000** [SimpleMobileTools/Simple-Calendar#373]
Ability to see the exchange calendar . Accept meeting invitations or deceline it. 

Maybe a push notification when I receive a new meeting

**Comment by tibbi** [comment]
You mean CalDAV syncing Microsoft Exchange calendar? You should already be able to sync the events and see them if you enable CalDAV sync in the settings and select the proper calendar, if you see it. Invitations and notifications wont come anytime soon.
