### ISSUE TITLE
Birthdays and holidays off by one day only when syncing from Google Calendar

### ISSUE THREAD

**Issue by Fred-Barclay** [SimpleMobileTools/Simple-Calendar#374]
G'day @tibbi ! This may be a duplicate of #368, #246, and possibly #371 , though my understanding is that those issues were fixed in 3.2.0 and I'm seeing this in 3.3.1 on Android 7.0:

When adding people's birthday's or public holidays by syncing with my Google Calendar, the birthdays/holidays are shown one day early. However, if I import either by selecting the menu (three dots in right-hand corner) and choose "Add holidays" or "Add contact birthdays", they're shown correctly.

Here's a sample from an exported .isc file:
```
BEGIN:VEVENT
SUMMARY:Easter Sunday
UID:Caldav-4-28
CATEGORY_COLOR:-6644481
CATEGORIES:Holidays in <redacted region>
LAST-MODIFIED:19700101T000000Z
DTSTART;VALUE=DATE:20180331
DTEND;VALUE=DATE:20180401
STATUS:CONFIRMED
END:VEVENT
```
This lists Easter Sunday as beginning on March 31st (which is, in fact, a **Saturday**) instead of April 1st :grin: This even was synced from my Google calendar.
```
BEGIN:VEVENT
SUMMARY:Easter Sunday
UID:d869e442-0b4d-40c4-b34c-6780afce8c46
CATEGORY_COLOR:-13070788
CATEGORIES:Holidays
LAST-MODIFIED:19700101T000000Z
DTSTART;VALUE=DATE:20180401
DTEND;VALUE=DATE:20180402
STATUS:CONFIRMED
END:VEVENT
```
This was added by choosing "Add holidays" from the menu.

A birthday example:
```
BEGIN:VEVENT
SUMMARY:<Redacted Name>'s birthday
DESCRIPTION:This is <Redacted Name>'s birthday!
UID:Caldav-3-144
CATEGORY_COLOR:-3365204
CATEGORIES:Contacts
LAST-MODIFIED:19700101T000000Z
DTSTART;VALUE=DATE:20180615
DTEND;VALUE=DATE:20180616
STATUS:CONFIRMED
END:VEVENT
BEGIN:VEVENT
SUMMARY:<Redacted>'s birthday
UID:Caldav-1-218
CATEGORY_COLOR:-6299161
CATEGORIES:<redacted>@gmail.com
LAST-MODIFIED:19700101T000000Z
DTSTART:20180615T170000Z
DTEND:20180615T180000Z
STATUS:CONFIRMED
RRULE:FREQ=YEARLY;INTERVAL=1
END:VEVENT
```
This was added by syncing my Google calendar and is a day too early.
```
BEGIN:VEVENT
SUMMARY:<Redacted Name>
UID:914
CATEGORY_COLOR:-15374912
CATEGORIES:Birthdays
LAST-MODIFIED:20180203T220859Z
DTSTART;VALUE=DATE:19700616
DTEND;VALUE=DATE:19700617
STATUS:CONFIRMED
RRULE:FREQ=YEARLY;INTERVAL=1
END:VEVENT
```
This was added by "Add contact birthdays" and is the correct date.

Cheers, and thanks! I've just stumbled across this app and I'd love to replace Google Calendar with it. :)
Fred

**Comment by tibbi** [comment]
So if you try importing a casual all-day event created by you, it works fine? Or that is off by a day too?

**Comment by tibbi** [comment]
Also, are you in Australia? Thats the timezone your Google Calendar is set to too?

**Comment by tibbi** [comment]
please retry with 3.3.2 once it becomes available, let me know if it is still broken
