### ISSUE TITLE
Custom colors not applied to time selector

### ISSUE THREAD

**Issue by matiasblomqvist** [SimpleMobileTools/Simple-Calendar#378]
The time selector when creating new events is still orange. Tested on 8.1 and 6.0

**Comment by tibbi** [comment]
ye I tried changing it already, but it is a system dialog and I cannot customize it easily. I dont think this will be fixed anytime soon, but it isnt a big issue anyway.

**Comment by SylvainGirod** [comment]
Hi @tibbi ,
There may be a way by creating a theme for each of the possible colors, and set this theme to your pickers... It may be gross, but should work.

**Comment by tibbi** [comment]
ye but I dont feel like creating like 190 new themes just for this

**Comment by SylvainGirod** [comment]
Yep, the app would be to heavy just for customization stuff..

What's about creating your own pickers instead ?

**Comment by tibbi** [comment]
I dont want to reinvent the wheel, people are used to a particular kind of date/time picker. There might be a third party library adding the circle timepicker where I could customize the colors, but it is a really minor issue and I dont feel like spending time on it now.

**Comment by tibbi** [comment]
this has been reported in the General Discussion already as it affects multiple apps
