### ISSUE TITLE
allow setting reminder time in other units too, not just minutes

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Calendar#38]

**Comment by evitalis** [comment]
Can this be paired with an update to #34 but also not remember the last set, but allow for either a few presets or adding custom presents? A time set for one task may not be applicable for another. In either case manually updating the time hampers the usability, especially when switching between adding a bunch of things with different reminders for all.

This could be as simple as adding something similar to the following presets: short (30 min), medium (60 min), long (90 min). Allowing the user to create their own presets would be ideal, but this could be a good middle ground. With these though still allowing for them to be modified if needed.

**Comment by tibbi** [comment]
version 1.29 will have a default value changeable in settings. Just one value, should be good enough for very most cases.
