### ISSUE TITLE
month view: blank page

### ISSUE THREAD

**Issue by 11m11** [SimpleMobileTools/Simple-Calendar#380]
Since version 3.3.0 the moth view mostly shows a blank page. The other views work. I can only fix it by restarting the app.
OS: Androis 7.1.1

**Comment by tibbi** [comment]
please update your app, it should be fixed.

**Comment by 11m11** [comment]
Can you please add the update to f-droid? There 3.3.0 is still the last one.

**Comment by tibbi** [comment]
they are updating it automatically themselves, I cannot do anything
