### ISSUE TITLE
Event list widget: layout improvements

### ISSUE THREAD

**Issue by genodeftest** [SimpleMobileTools/Simple-Calendar#385]
### Steps to reproduce:
1. add the event list widget to your android home screen. In my case, it is 5 tiles wide and 3 tiles high.
2. add any event with start and end date

### What happens:
Each event takes 3 rows of text:
```
February 28 (Wed)
  13:37    this is an event title
  14:01
```

### What should happen:
Only take 2 rows of text, for example:
```
February 28 (Wed) 13:37-14:01
    this is an event title
```
This way, more of the event title can be read. The time can be line-wrapped if it is too wide.

Another example:
```
February 28 (Wed)
  13:37-14:01  this is an event title
```
This way, events can be grouped by date, saving another line of text for multiple events on one day.

### Additional info:
I am running Simple Calendar 3.3.2 (installed from F-Droid) on Android 8.0.0

**Comment by tibbi** [comment]
should be better already

**Comment by tibbi** [comment]
not closing it yet, can still be better

**Comment by genodeftest** [comment]
It improved quite much. Thank you!

**Comment by tibbi** [comment]
UI has been changed in 6.16.0 again
