### ISSUE TITLE
No Reminders after Restart on Android 8

### ISSUE THREAD

**Issue by mirgleich** [SimpleMobileTools/Simple-Calendar#386]
Since I'm using Android 8 I'm not getting Reminders for events after rebooting my phone.
Steps to reproduce on Android 8
1. Create a new Event having a reminder at least 5 minutes in the future
2. reboot your phone
3. Do NOT open Simple Calendar

Expected Behaviour:
Simple Calendar is showing the reminder for the Event

Acutal Behaviour:
Simple Calendar is not creating a reminder
But if I'm opening Simple Calendar before the Reminder should be displayed it is displayed as expected

Using Nokia 5  on Android 8.0.0

**Comment by tibbi** [comment]
it will hopefully be fixed in version 3.4.1, reopen if not. Thanks
