### ISSUE TITLE
Wrong additional Birthday-Date is shown

### ISSUE THREAD

**Issue by wktools** [SimpleMobileTools/Simple-Calendar#389]
The correct Date is Monday 5. Mar. 18. The additional wrong one is shown at Monday 26. Feb. 18. But only in the Week-Mode.

**Comment by tibbi** [comment]
You mean that you used the "Add contact birthdays" feature and it imported the date wrong? Does it show well in other apps?

**Comment by wktools** [comment]
Yes.
Here some Screenshots.
Its the Claudia-Date. It is imported Form my Kontakts. Wenn i tipp on the 26. one then opens the 5. one.




Am 3. März 2018 22:10:17 MEZ schrieb Tibor Kaputa <notifications@github.com>:
>You mean that you used the "Add contact birthdays" feature and it
>imported the date wrong? Does it show well in other apps?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/SimpleMobileTools/Simple-Calendar/issues/389#issuecomment-370180075

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by tibbi** [comment]
I dont see the screenshot. Anyway, does the contact have the year filled out too? If it does, what year is it?

**Comment by wktools** [comment]
Yes, the year is filled out. It is 1963.

**Comment by tibbi** [comment]
Ok Ill take a look at it, thanks

**Comment by wktools** [comment]
here are the Screenshots:
http://www.wktools.de/Garten/

**Comment by tibbi** [comment]
ye years before 1970 might not be handled properly, it needs a bigger rewrite

**Comment by tibbi** [comment]
should be fixed in 6.0.2
