### ISSUE TITLE
Activate CalDAV only shows google account and Exception

### ISSUE THREAD

**Issue by alabre** [SimpleMobileTools/Simple-Calendar#390]
Simple Calendar 3.3.2 (F-Droid)
LineageOS 14.1 up to date
-------

Hi there,

when I select CalDAV sync I only see my google account calendars and an error message saying:

IllegalStateException: ownerName must not be null.

I also have DAVDroid installed and I can use calendars from the linked sources successfully in other calendar apps. It would be greate to see the calendars in Simple Calendar, too.

Cheers, Achim

**Comment by tibbi** [comment]
it should at least show up properly in the next version, thanks for the error message.
