### ISSUE TITLE
Add landscape mode

### ISSUE THREAD

**Issue by rugk** [SimpleMobileTools/Simple-Calendar#4]
I would like to use this app landscape mode too. Currently it forces the device in portrait mode.

This is also valid for all other SimpleMobileApps.

**Comment by tibbi** [comment]
thats a valid point, I will soon allow landscape for all apps with maybe some redesign for tablets here and there

**Comment by tibbi** [comment]
most apps have landscape mode already so Ill close this issue. The remaining ones will be handled individually.
