### ISSUE TITLE
Unable to edit single event for recurring task

### ISSUE THREAD

**Issue by evitalis** [SimpleMobileTools/Simple-Calendar#40]
In relation to #16 which has been working, I have found that a single event of a recurring set cannot be modified. Instead it modifies all entries even if those in the future should remain at a set time.

To duplicate: create a recurring task (in my case I used bi-weekly). Edit one of the sonnest upcoming task times. You will notice all in the set have the time changed.

**Comment by tibbi** [comment]
this has been added already
