### ISSUE TITLE
Wrong data in the widget

### ISSUE THREAD

**Issue by Primokorn** [SimpleMobileTools/Simple-Calendar#400]
Hi,

I don't know if I do something wrong or if there's a bug but the data displayed by the widget doesn't match the data put into the app.

The app:
![screenshot_calendar_20180316-141942](https://user-images.githubusercontent.com/5938828/37522882-a385b94e-2925-11e8-8caa-c01675c5eaa5.png)

The widget:
![screenshot_nova_launcher_20180316-141935](https://user-images.githubusercontent.com/5938828/37522900-a96c19a2-2925-11e8-948b-3c76b69480a5.png)

OnePlus 3T - Resurrection Remix Oreo 8.1 - Calendar app v3.3.2

**Comment by tibbi** [comment]
you mean that Brice and Dentiste are missing on the widget? Havent they happened already? The widget event list doesnt show past events, unless set to in Settings.

**Comment by Primokorn** [comment]
Actually the 3 events doesn't appear in the widget:
• Kccki   u (testing purpose)
• Brice
• Dentiste 17h30

These events were/are in the future.

**Comment by tibbi** [comment]
I cant seem to reproduce, Im sending the same time at both the app and widget :/ Can you still reproduce some related issue? Are the events that wont appear repeatable, or single-occurrence ones? Can you try scrolling down both lists, like how many events do you see? Thanks

**Comment by Primokorn** [comment]
@tibbi 
Here is a video when I create a new event: https://ncloud.zaclys.com/index.php/s/D80ZGs7TjCptDwu

It happens with single-occurence and repeatable events, stored locally or my nextcloud.

**Comment by tibbi** [comment]
nice, thanks. So that missing event doesnt reappeat even after recreating the widget? Maybe it is just some refreshing glitch.

**Comment by Primokorn** [comment]
> So that missing event doesnt reappear even after recreating the widget?
Exactly.

**Comment by Primokorn** [comment]
@tibbi Forget this issue. I changed my ROM and installed your app again.
I also had the problem with KWGT app (calendar widget) so I don't think it was related to your app.
