### ISSUE TITLE
Delay showing entries in day view

### ISSUE THREAD

**Issue by realthargor** [SimpleMobileTools/Simple-Calendar#406]
There is a noticeable delay when switching from month view into a day before event entries show up.
The events are stored in a caldav synced calendar.

If the phone has an internet, which has a high delay the  time before events show up is even longer.

Same is true when updating events. The event disappeares and shows up again after a delay.

**Comment by tibbi** [comment]
should be working better from 3.4.1. It is not related to internet, as even if you are online, Im syncing only with the device. None of the apps from the suite has access to the internet. Reopen if it will still be too slow.
