### ISSUE TITLE
All-day events created/listed with hidden start time

### ISSUE THREAD

**Issue by Phanx** [SimpleMobileTools/Simple-Calendar#415]
**Steps to reproduce:**

1. Create a new event, marking it as "all day"
2. Create a second event on the same day, with an early start time (e.g. 7:00 AM)

**Expected result:**

The "all day" event is listed before the 7AM event in all views.

**Actual result:**

The 7AM event is listed first.

**Additional notes:**

If I un-check the "all day" option, set the start time to a very early hour (e.g. 2 AM), then re-check "all day"and save the event, then it is listed first, so it seems that the "all day" option is actually just hiding the time fields in the form, and not affecting how the event is created.

Furthermore, since the start time when creating a new event seems to default to whatever the last time used was, the hidden start time of "all day" events is effectively random.

**Suggested fix:**

If possible (I don't know how Android calendars work internally) don't set a start time at all on events flagged as "all day". If a start time is required internally, then set it to 00:01 when marking an event as "all day".

Additionally, when displaying "all day" events, any time information should be ignored, and the event should be treated as if it starts at 00:01 and ends at 23:59.

**Versions etc.**

- Simple Calendar 3.3.2 from F-Droid
- Using CalDAV sync with a Google calendar for work events and local calendars via [Offline Calendar](https://f-droid.org/packages/org.sufficientlysecure.localcalendar/) for personal events
- Android 7.1.2 / LineageOS 14.1 on Moto G5+
- US English locale

**Comment by tibbi** [comment]
should be working fine from 3.4.1 already

**Comment by Phanx** [comment]
Is there an ETA for updating on F-Droid? 3.3.2 is the latest version available there.

**Comment by tibbi** [comment]
3.4.1 just started rolling out now, f-droid is updating the apps itself, I cannot affect it in any way. It should arrive there in a few days, maybe even tomorrow if you are lucky.
