### ISSUE TITLE
Change font size is not working. 

### ISSUE THREAD

**Issue by PeerzadaZeeshan** [SimpleMobileTools/Simple-Calendar#417]
#### Expected behavior
Want to change the font by clicking on the font feature, it must be change the font of the whole app. 

#### Actual behavior
When I changed the font by tapping on the three option shown by it, its font remains same as it was, no change occurs in it. 

#### How to reproduce
Install the app from f droid. 

Open the app

Go to the settings

Go to the bottom of the page

Then there appears font option

Press on it

It shows three option small, medium, large. 

Press on any one

It is not working, no change occurs in the app. 

* Browser: simple calendar 
* Version:3.3.2
* Operating system:5.1.1

#### Recording Of The Bug
https://youtu.be/9MU13wOvR98 
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@peerzadazeeshan/change-font-size-is-not-working">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by tibbi** [comment]
the settings section title says "Widgets" as it is applied to widgets only
