### ISSUE TITLE
Set Title in All Views

### ISSUE THREAD

**Issue by wbrawner** [SimpleMobileTools/Simple-Calendar#418]
For the Weekly and Yearly screens, the title changes from "Calendar" to whatever the date range being displayed is. I think it would be best to keep this behavior across all pages (e.g. the month view should set the title to the current displayed month instead of "Calendar")

**Comment by aavsss** [comment]
Hey, I would like to work on this fix. Could you please tell me how I can contribute?

**Comment by tibbi** [comment]
that is already shown for some time now
