### ISSUE TITLE
[FR] Make default view selectable

### ISSUE THREAD

**Issue by knusprjg** [SimpleMobileTools/Simple-Calendar#424]
Hi,

I would find it really helpful to make the default view selectable in the settings.

Currently: when I press the top bar of my widget I end up in the daily view.

What I would like to see: monthly view.

Best regards and many thanks for the great apps (will donate soon) ;)

**Comment by madroach** [comment]
When on it you may also add on option to always use the last used view or simply always use the last used view with no specific option.
