### ISSUE TITLE
Unable to navigate more than 30 days in Details view

### ISSUE THREAD

**Issue by gethob1** [SimpleMobileTools/Simple-Calendar#43]
From whatever date is tapped, I can't navigate back or forward more than 30 days.
It would be better unlimited.
Thanks.

**Comment by tibbi** [comment]
Ive doubled the size to 60 to both sides. I dont feel like making it unlimited, as that would require some hacks. This should be good enough ;)

**Comment by gethob1** [comment]
Thanks.  I'm not an app programmer, but just out of curiosity can you describe how the code is structured such that this limitation would require laborious re-working?  Is it a problem of the programming platform or the way this particular app was written?

**Comment by tibbi** [comment]
well, when Im creating that so called viewpager, the adapter normally has to have a preset amount of pages. There probably are some solutions for unlimited pages which I might check in the future, but currently I dont think anyone needs more than 60 days in one direction. Why would they keep swiping so much..
