### ISSUE TITLE
Add Indonesian holiday

### ISSUE THREAD

**Issue by azzamsa** [SimpleMobileTools/Simple-Calendar#434]
Hi Mr. Kaputa.

I use this awesome app almost everyday. I use it since last year. Now the additional feature and UI changes are more more awesome.

However, I can't find Indonesian Holiday. I find the online list [here](https://www.officeholidays.com/countries/indonesia/index.php) but not the ics file.

**Comment by tibbi** [comment]
I found some ics file and added some events in 2019 manually, we will see if it is good. They will be added in the next version released within a couple days. Im generally having problems with finding .ics files, but it should be improving over time. Thanks

**Comment by azzamsa** [comment]
There is an email in `UID` section

> +UID:20171212T045342Z-268948299@marudot.com

Are you ok with that ?

**Comment by tibbi** [comment]
ye i usually leave the original UIDs there as some credits

**Comment by azzamsa** [comment]
Ok.

Thank you so much for your contribution to community. Thanks lot.

**Comment by azzamsa** [comment]
Can we add infinite recurrence public holiday to SimpleCalendar?

e.g

Ascension Day
Bali Hindu New Year
Birthday of the Prophet Muhammad
Chinese New Year
Christmas
Easter
Hari Raya Idul Fitri
Idul Adha
Independence Day
Islamic New Year
Isra Mi'raj
Labour Day
Pancasila Day
Waisak Day

So we don't need to update the ICS file every release.
the cons are the Islamic holidays (Hari Raya Idul Fitri, Idul Adha,..)  are changing throughout the year because it's decided according to the Hijri date. Maybe we could put non-Islamic day only.

source: https://publicholidays.co.id/id/2020-dates/

**Comment by tibbi** [comment]
well some events that repeat with some configurable repetition rule should be repeating forever already. At some events it is hard to find out some repetition rule, dates have to be hardcoded there.

**Comment by azzamsa** [comment]
Yes, because I can't find holiday event at this year even though I've added 'add holidays -> indonesian'

**Comment by tibbi** [comment]
what app version are you using at all?

**Comment by azzamsa** [comment]
I've checked from 2020-2022 and found no holiday events.

I am using `v6.9.1 pro`

**Comment by tibbi** [comment]
okay, many country holiday improvements are needed, hope Ill get there soon
