### ISSUE TITLE
Allow Timezones on Times

### ISSUE THREAD

**Issue by bj-github** [SimpleMobileTools/Simple-Calendar#436]
As someone who travels, I'd like to be able to specify the timezone for a time when putting events into the calendar. (If it already exists, I couldn't see it. Although it does appear that it already handles the complementary function of translating times to the current timezone?) With thanks in anticipation - B.

**Comment by wompydomp** [comment]
I would like to see the same feature. Similar to the implementation in nextcloud, where I can select a timezone for the start date and a time zone for the end date separately, which comes in handy for flights for example. 
- default time zone would be nice
- favourite time zones/ranking by last usage would be nice as well. On nextcloud I have to scroll half minute to get to the Tokyo time zone.

**Comment by OlgaMorales** [comment]
@tibbi can i work on this issue yet?

**Comment by tibbi** [comment]
well timezone handling is a quite complicated thing, Im not sure how do I want to do it yet. But you can take a look at it I guess.

**Comment by tibbi** [comment]
time zone customization and handling will be added in the next version 6.8.0 released soon. It will be disabled by default, enable it at the bottom of the app settings. It will most likely need some glitches fixed later, as well as improve the behaviour at exporting/importing events.
