### ISSUE TITLE
Create new events as "confirmed" instead of "tentative"

### ISSUE THREAD

**Issue by flberger** [SimpleMobileTools/Simple-Calendar#438]
CalDAV calendar events support the status "`TENTATIVE` / `CONFIRMED` / `CANCELLED`".

Currently, _Simple-Calendar_ events show up as "tentative" in Thunderbird Lightning when synced via CalDAV.

This is a bug that has plagued the AOSP calendar and its derivates for a long time. See https://issuetracker.google.com/issues/36936061  It has since been fixed there, but _Simple-Calendar_ now shows the same buggy behaviour.

**Actual Behaviour:** Newly created events show up as "tentative" in CalDAV-synced calendars, requiring annoying manual fixing in other applications, such as Thunderbird Lightning.

**Expected Behaviour:** Newly created events should show up as "confirmed" in CalDAV-synced calendars, unless explicitly specified otherwise.

Thanks for considering.

**Comment by tibbi** [comment]
I wasnt setting any status so the given provider used its default one. I couldnt reproduce the issue with Google Calendars (guess they use Confirmed as default) but I added some quickfix as Im just going to release a new version, reopen the issue if it is still broken in 3.4.2.
