### ISSUE TITLE
Set default reminder

### ISSUE THREAD

**Issue by andreapx** [SimpleMobileTools/Simple-Calendar#449]
Hi!
I can't see the way to set the default reminder.
Is it possible to add it?
Thanks!

**Comment by tibbi** [comment]
The last used reminders are always applied to the new events.

**Comment by andreapx** [comment]
Oh, now I see, but It would be really usefull to have a default reminder because for example now I've set a particular reminder of 14 hours and I will not need it for the next one.
Another usefull thing is that if you forget to set a reminder...there is the default one!
Thanks!

**Comment by tibbi** [comment]
I dont really want to add new unnecessary settings, so far nobody needed it. We will see in the future.

**Comment by andreapx** [comment]
But all the calendar apps have this settings.
...I don't want to be rude...sorry!
Your choice!
