### ISSUE TITLE
Alarm uses notification sound not alarm sound

### ISSUE THREAD

**Issue by pager72** [SimpleMobileTools/Simple-Calendar#452]
Currently Simple Calendar uses the notification sound and wrongfully says its the system wide alarm sound.

**Comment by tibbi** [comment]
what app version do you have?

**Comment by pager72** [comment]
3.4.2

**Comment by tibbi** [comment]
I cannot reproduce it, what Android OS version do you have?

**Comment by tibbi** [comment]
should be fixed in 4.0.4 which will start rolling out soon
