### ISSUE TITLE
Event every weekday, forever

### ISSUE THREAD

**Issue by jebaum** [SimpleMobileTools/Simple-Calendar#456]
I've managed to create a "work" event that repeats on Monday - Friday, but I'd like to be able to do that out through the rest of the calendar, instead of just one week at a time.

Is there a way to apply the "repeat forever" option to an event that happens on weekdays?

Related: https://github.com/SimpleMobileTools/Simple-Calendar/issues/16

**Comment by tibbi** [comment]
well if you select Weekly repetition, 2 new fields appear under it. In the first one you can select specific days, in the second one you can select infinite repetition. What doesnt work on it?

**Comment by jebaum** [comment]
Hah, my brain apparently. Thank you so much, that's exactly what I wanted.

great work on these tools!
