### ISSUE TITLE
Move "suppress all events" option in a safer place

### ISSUE THREAD

**Issue by mickours** [SimpleMobileTools/Simple-Calendar#458]
To improve UX, put this button in a submenu (some kind of danger zone, like on github.com) to avoid accidents. 

I accidentally suppress all events my events from all my calendars, this should not happen!

**Comment by tibbi** [comment]
it even has a confirmation dialog, I dont plan moving it somewhere else.

**Comment by mickours** [comment]
Sorry to hear that... Your app is very good but I won't recommend it to inexperienced people because of this. 

I really think you should reconsider this, If it happens to me it may happen to other users. Moreover, this kind of erase everything features should not be mixed with simple configuration.
