### ISSUE TITLE
Events added from Simple-Calendar on Lineage don't have correct time when viewed on Fruux web

### ISSUE THREAD

**Issue by clnhlzmn** [SimpleMobileTools/Simple-Calendar#460]
Hello,

I'm not sure if this is the correct place for this. Please let me know if its not or if this problem already has a solution. 

I am using Fruux calendar service for syncing. When I add an event on my Android using Simple-Calendar at time, say, 1600, it will appear on the Fruux web app at 1200. I have the Fruux calendar time zone set to GMT -4 which is the same as my Android device, but I wonder if this has something to do with the event time problem as there seems to be an offset of 4 hours. I don't see any option in Simple-Calendar for a time zone setting. Can anyone help with this?

-Colin

**Comment by tibbi** [comment]
should be fixed in 6.2.0
