### ISSUE TITLE
Many Unresolved reference errors when using Simple-Commons as an AAR library 

### ISSUE THREAD

**Issue by don-prog** [SimpleMobileTools/Simple-Calendar#465]
I want to build Simple-Commons as an AAR library and use it in the Simple-Calendar as a module.
To achieve this, I did the following:

- In the Simple-Commons: Gradle menu -> :commons -> Tasks -> build -> build (right click) -> Run Simple-Commons
- In the Simple-Calendar:  File -> New -> New Module -> Import .JAR/.AAR Package -> Select `/Simple-Commons-master/commons/build/outputs/aar/commons-release.aar` -> Finish
- Add in the build.gradle (Module: app) string `compile project(":commons-release")` and delete `implementation 'com.simplemobiletools:commons:3.18.23'` in the `dependencies`
- Add in the build.gradle (Module: app) string `compile "com.android.support:design:27.1.1"` in the `dependencies`, due to the many  `error: style attribute ... not found.` errors
- I get 1.212 `Unresolved reference: ...` errors, next I see `Kotlin not configured` message and click `Configure`
- Choose `All modules containing Kotlin files: app` and `Kotlin compiler and runtime version: 1.2.40`

After these steps I got the following errors:

> 
> /home/user/Downloads/Simple-Calendar-master/app/src/main/kotlin/com/simplemobiletools/calendar/fragments/DayFragmentsHolder.kt
> Error:(40, 21) Unresolved reference: id
> Error:(52, 13) Unresolved reference: adapter
> Error:(53, 13) Unresolved reference: addOnPageChangeListener
> Error:(69, 13) Unresolved reference: currentItem
> Error:(84, 21) Unresolved reference: currentItem
> Error:(84, 47) Unresolved reference: currentItem
> Error:(88, 21) Unresolved reference: currentItem
> Error:(88, 47) Unresolved reference: currentItem
> Error:(102, 21) Unresolved reference: adapter
> Error:(102, 80) Unresolved reference: currentItem
> /home/user/Downloads/Simple-Calendar-master/app/src/main/kotlin/com/simplemobiletools/calendar/fragments/MonthFragmentsHolder.kt
> Error:(40, 21) Unresolved reference: id
> Error:(51, 13) Unresolved reference: adapter
> Error:(52, 13) Unresolved reference: addOnPageChangeListener
> Error:(68, 13) Unresolved reference: currentItem
> Error:(84, 21) Unresolved reference: currentItem
> Error:(84, 47) Unresolved reference: currentItem
> Error:(88, 21) Unresolved reference: currentItem
> Error:(88, 47) Unresolved reference: currentItem
> Error:(102, 21) Unresolved reference: adapter
> Error:(102, 82) Unresolved reference: currentItem
> /home/user/Downloads/Simple-Calendar-master/app/src/main/kotlin/com/simplemobiletools/calendar/fragments/WeekFragmentsHolder.kt
> Error:(66, 13) Unresolved reference: adapter
> Error:(67, 13) Unresolved reference: addOnPageChangeListener
> Error:(85, 13) Unresolved reference: currentItem
> Error:(91, 66) Unresolved reference: currentItem
> Error:(130, 21) Unresolved reference: adapter
> Error:(130, 80) Unresolved reference: currentItem
> /home/user/Downloads/Simple-Calendar-master/app/src/main/kotlin/com/simplemobiletools/calendar/fragments/YearFragmentsHolder.kt
> Error:(37, 21) Unresolved reference: id
> Error:(48, 13) Unresolved reference: adapter
> Error:(49, 13) Unresolved reference: addOnPageChangeListener
> Error:(69, 13) Unresolved reference: currentItem
> Error:(86, 21) Unresolved reference: adapter
> Error:(86, 81) Unresolved reference: currentItem

It is all about MyViewPager, as I see. 
So, how can I fix it and make it work properly?
Regards.

**Comment by tibbi** [comment]
Not sure, Simple Commons is not meant to be used by other people
