### ISSUE TITLE
Delete single occurrence of recurring event not synched correctly to Nextcloud/CalDAV

### ISSUE THREAD

**Issue by michaelof** [SimpleMobileTools/Simple-Calendar#470]
3.4.2

When deleting a single occurrence of a recurring event, single occurrence is deleted/invisible locally, but still exists in Nextcloud.

Tested with Google calendar app: single occurrence also still in Nextcloud, but shown with status "cancelled", visible as striked-through in e.g. week view.

Status when deleted in SimpleCalendar: still "confirmed"

**Comment by tibbi** [comment]
should be fixed in 4.0. Deleted instances of repeating events will be removed from NextCloud completely as I dont like the idea of just crossing them out.
