### ISSUE TITLE
Remove "Apply colors to all the Simple apps" Option

### ISSUE THREAD

**Issue by Lambdat** [SimpleMobileTools/Simple-Calendar#475]
Hello Tibbi, how can I remove this option(located in color settings) in android studio?
Please I need your help..

![screenshot_20180504-184905](https://user-images.githubusercontent.com/32133439/39640732-31de23da-4fcc-11e8-846e-9d9b6a10f2dc.png)

**Comment by tibbi** [comment]
well fine the layout file and delete it

**Comment by Lambdat** [comment]
which file?
 I only want to remove that button,not the entire activity(color settings)

**Comment by tibbi** [comment]
you need to do it in the Commons library

**Comment by Lambdat** [comment]
Commons Library that I think are is located in Gradle scripts?
Sorry i'm an ignorant..

**Comment by Lambdat** [comment]
Tomorrow I will have to show this modified project,please help me :(

**Comment by Lambdat** [comment]
I know that,but my teachers suck and they have never taught me how to create apps

**Comment by tibbi** [comment]
nobody can teach programming, you have to learn it yourself. I learnt it myself too. One way of getting rid of the button is purchasing https://play.google.com/store/apps/details?id=com.simplemobiletools.thankyou and activating the button.
