### ISSUE TITLE
New logo offer

### ISSUE THREAD

**Issue by familqasimov** [SimpleMobileTools/Simple-Calendar#477]
Hi sir. I'm graphic designer. I have studied your work and I think a new design will make you more visible. I would like to offer logo. I can give you all the formats of the design free. If you want I send you PR or a change please specify.

![untitled-1](https://user-images.githubusercontent.com/36432269/39663493-67d9db46-5085-11e8-872e-35078046fc3e.png)

**Comment by tibbi** [comment]
Hey. Thanks, but Im currently not looking for a new logo.
