### ISSUE TITLE
widget stopped responding to press a day

### ISSUE THREAD

**Issue by GuitarBilly** [SimpleMobileTools/Simple-Calendar#486]
nokia6   android 7.1.2   SC 4.0.0
It seems since the last update that i cannot launch the app anymore by pressing a day on the calendar-month widget. The only keys that respond the widget into any action are 
< > +.

I removed the calendar-month widget and added it again but nothing changed. Also having the SC app already open or not does not matter.

Expected behavior: launch the Simple Calendar app with the day that was pressed on the widget.

**Comment by tibbi** [comment]
ye, it will be fixed in 4.0.2 which just started rolling out
