### ISSUE TITLE
Events not considered alarms

### ISSUE THREAD

**Issue by pager72** [SimpleMobileTools/Simple-Calendar#487]
Currently if one prefers to use Do Not Disturb - Alarms Only mode Simple MobileTools/Simple-Calendar DOES NOT successfully notify user of scheduled events. It is also wrong to specify in settings dialog that an alarm sound is being chosen when in reality its not an alarm, which is misleading and would make users miss scheduled events.

**Comment by GuitarBilly** [comment]
nokia6   android 7.1.2   SC 4.0.3
FYI on my phone in DND-alarms-only mode i also hear no sound (unexpected) but the scheduled event is shown in the notification area at the defined reminder time. 
The event does not disappear from there until i take action (expected behavior).

**Comment by tibbi** [comment]
should be fixed in 4.0.4. If it still wont work and you have Android Oreo, go in the device notification settings and explicitly allow reminders to be shown/play during dnd.
