### ISSUE TITLE
dimming makes text unreadable

### ISSUE THREAD

**Issue by lvmm** [SimpleMobileTools/Simple-Calendar#493]
Dimmed events are very low contrast and impossible to read, check the attached screenshot.
![screenshot_2018-05-17-10-12-24](https://user-images.githubusercontent.com/11752339/40162164-b3d03f38-59bb-11e8-987c-239a0e021cca.png)

**Comment by tibbi** [comment]
well because you have too dark colors picked. Just disable dimming at the bottom of settings

**Comment by lvmm** [comment]
I don't quite see how colours come into this: event colours are defined in google calendar, not in simple calendar, and anyway I believe that dimming should work well with all colours and should not be a consideration when picking a colour scheme. More importantly, as as I mentioned in #492 , dimming cannot be disabled completely.
