### ISSUE TITLE
Events that repeat weekly or daily don't account for daylight saving (regression)

### ISSUE THREAD

**Issue by tom93** [SimpleMobileTools/Simple-Calendar#505]
Events that repeat weekly or daily have the wrong time-of-day when there is daylight saving.

To reproduce:
Use a timezone with daylight saving. Create an event at 12pm with daily repetition. Look at the times of occurrences during DST and during standard time (e.g. by jumping ~6 months forward).
Expected behaviour: All events should be at 12pm (in the offset for their day).
Actual behaviour: Events will be off by 1 hour.

Cause:
c44abf2 ("simplify daily repeatable event fetching for better performance", 2018-05-06)
bc7b1f0 ("improve weekly and custom repetitions too", 2018-05-06)

Please revert these commits until a way is found to improve performance while still respecting daylight saving.

Thanks,
Tom

**Comment by tibbi** [comment]
so you are sure that it used to work fine previously?
