### ISSUE TITLE
Add support for drop-down monthly view

### ISSUE THREAD

**Issue by lokesh-krishna** [SimpleMobileTools/Simple-Calendar#508]
It would be really nice to have a drop-down monthly view the way that Google Calendar does to quickly view the month irrespective of which view you are using.  

A possible use-case scenario is when one prefers the simple event list view but needs the monthly view when they want to check which date/day falls on which day/date.

**Comment by moshpirit** [comment]
This is one of the main points of why I keep using Etar, it would also allow the app along with #418 and #327 to have a way much more efficient use of the screen.

**Comment by dumblob** [comment]
Does the new "Monthly and daily view" solve your issue? If so, feel free to close this thread :wink:.
