### ISSUE TITLE
v4.0.4: Duplicate Events

### ISSUE THREAD

**Issue by michaelof** [SimpleMobileTools/Simple-Calendar#510]
v4.0.4 on Android 6.0
calDAV via DAVdroid 1.11.2-ose
Nextcloud 13.0.2

Hi Tibor!

always after some time, not precisely reproducible, I'm getting some, not always the same,  synced from Nextcloud events shown more than once. As duplicates, same time, same length, some comments etc..
In day view and list view, not in week, month or year view.

Currently up to four duplicates  per event.

Maybe a display only error, as stock calendar does not show duplicates.

And as there are no duplicates in my Nextcloud for these events, 
*** WORKAROUND *** 
is to disable all affected calDAV calenders, wait until all events have dissapperad from simple calender (the duplicates also disappear), and re-enable all needed calDAV calendars. 

For a while from then only single instances are shown, no idea what might trigger the duplicates

**Comment by michaelof** [comment]
Same duplicating on my wife's smartphone, but other events, although we're using shared Nextcloud calendars.


WORKAROUND is simpler: No need for any actions in DAVdroid. Just disable calDAV sync in SimpleCalendar's settings, wait some seconds, maybe not necessary, and enable again.

**Comment by neolovich** [comment]
I have the same problem with birthday calendar. When I import birthday events from contacts more than one time, birthday entries are shown twice or more. But not all birthday entries. I cant find out on what it depends, that a view entries shown only on time.

**Comment by tibbi** [comment]
recheck with the pro version 6.0 released soon please
