### ISSUE TITLE
Feature request: Show grid in montly view

### ISSUE THREAD

**Issue by joaofl** [SimpleMobileTools/Simple-Calendar#511]
Would be good to have an option in the config to show the grid lines in the monthly view (like the weekly view has).

It may sound dumb, but sometimes, when I quickly look at my montly tasks, sometimes I don' t know if the colored task belongs to the day above or below. The same when tapping a given day. Not sure I have tapped which day.

It may be a simple thing to do. Let me know if I can help on anything. And congrats for the whole bunch of nice apps. You did a better job than Google, Apple, Microsoft and many many others on making things as simple as possible, but functional! 

Thanks

**Comment by tibbi** [comment]
there is already an option for displaying a grid in the settings, at Monthly view section.
