### ISSUE TITLE
CalDAV sync shows empty list

### ISSUE THREAD

**Issue by NotSoImportant** [SimpleMobileTools/Simple-Calendar#515]
How can I somehow debug why there is no calendars shown?
App restart did not fix it.
In DAVdroid there is the calendar set up and visible.

**Comment by tibbi** [comment]
what app version and Android OS version do you have?

**Comment by NotSoImportant** [comment]
oh, just found out. It was a problem of DAVdroid permissions. It did not have "change calendar" permission (only "read calendar") and was not asking for it.

**Comment by NotSoImportant** [comment]
thanks tibbi :-)
