### ISSUE TITLE
Events created with SimpleCalendar not shown in Smooth Calendar

### ISSUE THREAD

**Issue by philblue1** [SimpleMobileTools/Simple-Calendar#516]
Hello,
I am using Smooth Calendar widget for showing the next upcoming events.
Unfortunately events created with Simple-Calendar are not visible in Smooth Calendar, but in Nextcloud (and of course Simple-Calendar). My calendar is synced with DAVDroid to my own Nextcloud, events created or edited in Nextcloud are visible.

I like to help with debugging stuff if needed.

(maybe related to #460 and #427 in some kind?)

**Comment by tibbi** [comment]
retry with pro version 6.1.0 released soon please
