### ISSUE TITLE
Show events at same time 

### ISSUE THREAD

**Issue by jeanpalaz** [SimpleMobileTools/Simple-Calendar#517]
Hello
I have multiple Calendars (and sharing others)
But if 2 events (or more) are at the same time/date, we don't have a clear view, only one is shown, hiding the others.
Is there a way to display or show multiple events, please?

PS: Nice Apps, THX

**Comment by tibbi** [comment]
you mean the weekly view? That needs to be improved.

**Comment by tibbi** [comment]
ok Im aware of it, it is a duplicate of #194
