### ISSUE TITLE
access to db (sqlite) or import from csv file

### ISSUE THREAD

**Issue by dapgo** [SimpleMobileTools/Simple-Calendar#522]
I would like to import my current calendar from another app using sqlite to Calendar.
Having access to db i can write a query to migrate my data.
Otherwise a a csv import function would be appreciated ;)
what do you think?

I know that Simple calendar imports .ics file but the other app doesn´t export to ics and i dunno how to generate an ics file from sqlite :(

**Comment by tibbi** [comment]
You cannot just export their db, it can have a totally different structure. The only way is finding some .ics exporting there, or sync the events via CalDAV.

**Comment by dapgo** [comment]
Yes, I know  that db structure and field names will be different but I am sure that I can manage to find out a the relation and the method to insert into.  In fact I did before with other apps which are using sqlite.

**Comment by tibbi** [comment]
You cannot import an sql dump into Simple Calendar, I dont even plan adding that.
