### ISSUE TITLE
Notification sounds when cell phone is set to silent mode

### ISSUE THREAD

**Issue by gtessi** [SimpleMobileTools/Simple-Calendar#528]
Simple Calendar vibrates and plays the selected sound on reminders regarding the cell phone mode. My cell phone is set to silent mode and is working fine, it only vibrates when receiving calls and notifications from other apps. But still Simple Calendar sounds on remineders.

I have a Samsung Galaxy S3 phone, with Android 7.12 and Simple Calendar 4.0.4. If you know a simple user fix (app or OS setting) or need any other information, please let me know.

Thank you in advance.

**Comment by tibbi** [comment]
that is the responsibility of the system, not me. If the device is silenced, the app shouldnt be allowed to play any sound. Check some system sound settings, the app uses the Alarm stream.

**Comment by gtessi** [comment]
Already checked that, and the Alarm doesn't sound when set to Silent mode. As I said before, the only app that emits sounds while on Silent mode is Simple Calendar.

**Comment by szilardx** [comment]
> that is the responsibility of the system, not me. If the device is silenced, the app shouldnt be allowed to play any sound. Check some system sound settings, the app uses the Alarm stream.

Thanks for the application @tibbi , I really like it. My minor annoyance is that as with other calendar and task apps, I would expect that the calendar reminder is a notification, not an Alarm. This way if I am at a meeting, the Calendar won't give out sounds if I set my phone to Silent (vibrate) or DND.

Would it be possible to have an option in settings, to change the Alarm stream to behave like other apps notificatons?

Thanks a lot!

**Comment by tibbi** [comment]
there is already a setting for that, "Audio stream used by reminders" in the Simple Calendar settings
