### ISSUE TITLE
Event notifications are bypassing phone do-not-disturb rules

### ISSUE THREAD

**Issue by esmoak** [SimpleMobileTools/Simple-Calendar#530]
Version 4.1.0, Android 6.0.1

Have phone do not disturb set to "alarms only."

If an event reminder happens it notifies me audibly and in the top notifications.

Expected behavior is that it would be treated as a regular notification and be ignored via do not disturb.

My best guess is that my phone thinks it is an alarm.

**Comment by tibbi** [comment]
because calendar reminders are set as an alarm, thats how most calendars work. It is the expected behaviour.

**Comment by esmoak** [comment]
Thanks @tibbi

I didn't remember having that happen before and I appreciate the clarification.

**Comment by tibbi** [comment]
ye it used to behave differently in the past, that old behaviour was actually broken. The current version is the expected one.
