### ISSUE TITLE
feature request：support alarms clock to reminders 

### ISSUE THREAD

**Issue by ivysrono** [SimpleMobileTools/Simple-Calendar#534]
not only one sound。

**Comment by tibbi** [comment]
not sure what you mean by this

**Comment by ivysrono** [comment]
sorry for my poor English.
This is similar with https://github.com/SimpleMobileTools/Simple-Clock/issues/72

**Comment by tibbi** [comment]
aha I see what you mean. It wont be added anytime soon though.
