### ISSUE TITLE
Calendar colors as background color in event list

### ISSUE THREAD

**Issue by teatwig** [SimpleMobileTools/Simple-Calendar#537]
Really happy with your app since it appears to be the only one to display reoccurring CalDav events without any problems.

I'd like an option to set the background color of events in the "simple event list" to the color of the calendar.
At least for me the colored dot isn't enough to see which events belong to which calendar at a glance.

**Comment by tibbi** [comment]
the colored dot will be changed into a bar on the left side from version 4.2.0

**Comment by tibbi** [comment]
UI has been remade again in 6.16.0
