### ISSUE TITLE
Feedback when saving an event

### ISSUE THREAD

**Issue by woutgg** [SimpleMobileTools/Simple-Calendar#541]
On my device, when saving a new or edited event, it takes about 2 seconds to do so before it is done and the editing interface closes.
During this time the UI does not provide any feedback at all, causing me to wonder if something went wrong ("Did I miss the save button?", "Has the phone become unresponsive?").

I'd like some feedback (e.g. animation, overlay popup) indicating the app is busy saving the event.

**Comment by tibbi** [comment]
a toast will be shown in the next version 4.1.1 with also showing the reminder time, if any. Maybe it will show too late and wont fix your issue though, we will see.

**Comment by woutgg** [comment]
The toast is a nice addition, unfortunately it only shows after saving is complete so it does not resolve the issue. The save button (tick icon) now also animates with a circle around it, but this also does not happen until after saving is complete.

**Comment by tibbi** [comment]
this should be better already
