### ISSUE TITLE
Incorrect description on main page / README.md

### ISSUE THREAD

**Issue by kaoneko** [SimpleMobileTools/Simple-Calendar#543]
The main GitHub page / README.md incorrectly states:
> An offline calendar without any other calendar integration.

The F-droid and Play Store descriptions read:
> A simple calendar with optional CalDAV synchronization.

If someone were to stumble upon Simple Calendar on GitHub looking for a calendar that supports CalDAV they may now conclude Simple Calendar isn't for them. I think it's time to update the README.md file (I would do it myself if I knew how).

**Comment by tibbi** [comment]
heh ye, those READMEs can be outdated. Here is a guide for updating it https://github.com/SimpleMobileTools/General-Discussion#how-can-i-suggest-an-edit-to-a-file . Basically just press the pencil at the top right corner of the file, edit changes and submit them. Thanks
