### ISSUE TITLE
Event List Widget: Refresh imcomplete/incosisent for calDAV entries

### ISSUE THREAD

**Issue by michaelof** [SimpleMobileTools/Simple-Calendar#547]
SimpleCalender 4..1.0
DAVdroid 1.11.5-ose
Android 6.0
Lenovo K10a40
Calendar entries etc. stored in Nextcloud 13.0.4

Hi Tibor,

I'm trying to narrow down some smaller refresh issues, both for simple-contacts and also simple-calendar.
Smaller, no big issue s:-)

Steps today:

- created event in Simple-Calendar, saved.
- shown correctly in widget, small delay, but very fine.
- recognized that event date is wrong, edited, changed, saved
- NOT refreshed in widget automatically

Checked in Nextcloud: automatically synced after saved in Simple-Calendar via DAVdroid, event in Nextcloud is correct.

WORKAROUND: when scrolling down, to the point where the widget starts to refresh/read/poll whatever additional events, and scrolling backwards, widget data are getting refreshed, in sync again.

Remark: I'm using (and LOVING :)) KISS as launcher (https://f-droid.org/packages/fr.neamar.kiss/), and the widget functionality is still shown as beta, so maybe a KISS issue, not sure.

2nd remark: Of course not your issue, but  I must say it, no need to answer :-) : It's a pain in the neck how Android deals with Adoptable Storage, I've read the docs but totally disagree for the reasons why a widget of a stored-on-sdcard-app could not be used :-(

**Comment by tibbi** [comment]
ye the fact that widgets get disabled if the app moves on an SD card is stupid. At least Google could give a warning about it, I get many emails related to that, even if I added it to FAQ.

**Comment by tibbi** [comment]
widgets should be updated at every event insert/update. Does it glitch at both repeatable and not repeatable events? Can you reproduce it reliably? It works fine to me.

**Comment by michaelof** [comment]
Issue can be CLOSED

Switched temporarily to "Launcher3", Lenovo's default launcher for my device.
--> Widget is working fine.

Switching back to KISS: No standard refresh, as.described, reproducible.

So a small KISS issue, report there.

Sorry, and thank.you, Tibor!

**Comment by tibbi** [comment]
KISS has quite a few issues, Im not really a fan of it.
