### ISSUE TITLE
Why does it take so long to load events?

### ISSUE THREAD

**Issue by mberasategi** [SimpleMobileTools/Simple-Calendar#555]
It takes it's good 5-10 seconds to load events in any view, which makes it impractical when I want to check availability quickly (it's misleading to see the day free when I actually have appointments). Why could this be?

**Comment by tibbi** [comment]
not sure, do you maybe have a huge amount of events in the app? Are they CalDAV synced? What app version and Android OS version do you have?

**Comment by mberasategi** [comment]
- I don't know what qualifies as "huge", but my ICS export file is 893KBs
- Yes, they are all CalDAV synced (with DAVDroid)
- App version 4.1.1, Android version 7.0

Thanks!

**Comment by tibbi** [comment]
ye, that is a lot :) Some performance improvements will certainly come in the future, but it isnt really a priority for now, so theres not much you can do.

**Comment by mberasategi** [comment]
Ok, at least knowing the reason helps. I still want to keep all of them, so I know what I'm playing with. Thanks for the response!
