### ISSUE TITLE
Does Android app caldav sync with default Android calendar app, or with Google directly? 

### ISSUE THREAD

**Issue by elijahtlang** [SimpleMobileTools/Simple-Calendar#556]
I enabled caldav and am syncing this app with my Google calendar. I ask because the default Android calendar app doesn't sync well, so I want to use this instead. So, does caldav sync with the Android calendar, which syncs with Google? Or does it sync with Google directly? Thanks

**Comment by tibbi** [comment]
CalDAV sync syncs with the device, it just shows the calendars and events already stored on the device itself. The app is offline, so it isnt fetching anything from anywhere online. Id say it syncs with Google itself, with Google Calendar taking care of the online syncing between the device and the servers.
