### ISSUE TITLE
Option to set the timeframe of widget's events list

### ISSUE THREAD

**Issue by maverick74** [SimpleMobileTools/Simple-Calendar#558]
Now widget shows all events in the next year timeframe.
It would be good if we could customize the timeframe range (e.g.: show only events in the next 3 days, 7 days, next month, etc)

ATM the list is always full, even if the events are a few months away. Having other options would be good as the list would be cleaner and would more easily call on user's attention when it has events.

**Comment by Aga-C** [comment]
It's done in the newest version 6.17.0. Should be closed.

**Comment by maverick74** [comment]
Where can i configure it?

**Comment by tibbi** [comment]
you have to recreate the widget, the timeframe can then be updated at the config screen, where you are customizing the colors.

**Comment by maverick74** [comment]
Oh, i see!!!

Thank you soo much :D
