### ISSUE TITLE
It does not notify a past event when you turn on your phone.

### ISSUE THREAD

**Issue by GarySheldon** [SimpleMobileTools/Simple-Calendar#560]
Hi,
My problem is that when an event occurs when the mobile phone is turned off, when I turn it on, it does not notify me. Is that normal?
Thanks

**Comment by tibbi** [comment]
well if the event is already over, it obviously wont notify you. It should notify you only if the event is currently running. If that doesnt work, please reopen the issue with specifying your app version too. Thanks
