### ISSUE TITLE
CalDAV sync DTSTART TZID

### ISSUE THREAD

**Issue by cSharpSharp** [SimpleMobileTools/Simple-Calendar#561]
When the Simple Calendar synchronizes events with CalDAV server, it creates something like this in the ics file (I had skipped parts that are not important here.):
`BEGIN:VEVENT`
`DTSTART:20180725T120000`
`DTEND:20180725T130000`
`END:VEVENT`

`BEGIN:VTIMEZONE`
`TZID:Central European Standard Time`
`END:VTIMEZONE`

Please notice that in the VEVENT section the DTSTART and DTEND fields are not referencing the time zone specified in the VTIMEZONE section. This is causing some CalDAV clients to interpret this file incorrectly, for example Synology Calendar thinks that it's an all-day event. I believe that the DTSTART and DTEND sections should reference the time zone like this:
`DTSTART;TZID=Central European Standard Time:20180725T120000`
`DTEND;TZID=Central European Standard Time:20180725T130000`

The notation above seems to be more universal across different iCalendar clients.

**Comment by aunwin** [comment]
I am not 100% sure but this might play a roll in troubles I experience when trying to import the ics files on my nextcloud-calender once I exported them from my simple mobile tool calender.
It seems like the export is not compatible with RFC 5545 specification (see https://icalendar.org/validator.html#results)

**Comment by Salvoxia** [comment]
I encountered that same behavior described by OP with Synology Calendar and came to the same conclusion of missing timezone information causing that before finding this issue. 
Posting to raise awareness for this problem.

**Comment by mlawren** [comment]
It appears that DSTART and DTEND now include timezone designations, at least with version 6.21.3 Pro synchronizing with DAVx5. I would suggest this issue can now be closed.
