### ISSUE TITLE
Field "Title" too short

### ISSUE THREAD

**Issue by pancobe** [SimpleMobileTools/Simple-Calendar#564]
The field "title" is too short, I often events get invitations for events with quite long titles, needing almost two lines: Asking for an option for showing more lines if needed. At the moments titles are limited to a relatively small number of characters

**Comment by tibbi** [comment]
what do you mean by invitations? Are you syncing events via some .ics file? That is the only limitation Ive found, 80 characters. I changed it to 180, just to have some limit at all.
