### ISSUE TITLE
Fix year 2038 problem

### ISSUE THREAD

**Issue by earboxer** [SimpleMobileTools/Simple-Calendar#572]
In January 2038, 32-bit (signed) unix time comes to an end.

In this app, my repeated events don't go past december 2037 in month or year views. Birthdays also stack up on incorrect days leading up to january 19.

Events created january 19 or later reset the time in the widget to december 14,1901.

Yearly view can't scroll past 2048 (for some reason).

Using a 64 bit time stamp will increase the maximum date significantly beyond any living human's expected lifespan.

https://en.m.wikipedia.org/wiki/Year_2038_problem

**Comment by tibbi** [comment]
will be fixed in 6.0
