### ISSUE TITLE
FileNotFoundException when importing ics file via Firefox

### ISSUE THREAD

**Issue by gleichda** [SimpleMobileTools/Simple-Calendar#575]
System: Nokia 5 TA-1053 Android 8.1 Security Patch July 2018

### Steps to Reproduce:
1. Check if Simple Calendar has Permission to access File system. If so revoke.
2. Download a ics File (e.g. https://www.blutspendedienst.com/blutspendetermine/79308/ical ) via Firefox
3. Open file from Download Menu of Firefox via Simple Calendar and try to add event to Calendar

### Excpected Behaviour:
Simple Calendar asks for Permission to access File System if it doesn't have it

### Actual Behavior
Simple Calendar is Showing the FileNotFoundExcepion in a Toast

**Comment by tibbi** [comment]
proper handling for such cases has already been added a long time ago
