### ISSUE TITLE
Better spacing between day names and first line in month view

### ISSUE THREAD

**Issue by bb1a2** [SimpleMobileTools/Simple-Calendar#583]
Also, More emphasis on day names (e.g. bigger, longer and bold: "**Tue**" instead of "T") would be nice.

Thanks

**Comment by arshadkazmi42** [comment]
I am interested to take this up. Is it still available for grab?

**Comment by tibbi** [comment]
not sure if I want it yet, it would make the screen too crowded

**Comment by tibbi** [comment]
UI has been changed since this
