### ISSUE TITLE
[FR] Toggle to disable notifications completely

### ISSUE THREAD

**Issue by woj-tek** [SimpleMobileTools/Simple-Calendar#587]
Currently there is no way to disable notifications - it would be helpful if there were a master switch/toggle to actually enable showing them.

**Comment by tibbi** [comment]
you can just set "No reminder" in the events, or use some third party app to block them. Maybe DND mode too.

**Comment by tibbi** [comment]
well ignoring notifications is something that should be the systems' responsibility, not something that should be toggled in an app

**Comment by woj-tek** [comment]
IMHO option whether to generate them or not in the first place should be app responsibility.

Let's think about the amount of work/resources:
* app generates unwanted notifications (cpu used); system has to filter them (cpu used);
* app doesn't generate notifications (no cpu used)
;-)
