### ISSUE TITLE
App Icon Color Doesn't Change

### ISSUE THREAD

**Issue by 0pLuS0** [SimpleMobileTools/Simple-Calendar#588]
Hello,

```System Specs```
Essential PH-1
CarbonRom-6.1 (Oreo 8.1.0)
No Gapps installed

If I try to change the ```App icon color``` I see my App Drawer flash, which is the time it changes, but nothing happens it just stays Orange.

I also have the same problem for the ```Simple Gallery```.

I do have both of these apps running on a Xiaomi Mi A1 with the AospExtended-5.8 Rom and this works, so I'm not sure what's wrong with it on Essential with CarbonRom.

I've attached a logcat, hopefully it will be of some help.

Thanks

[logcat.txt](https://github.com/SimpleMobileTools/Simple-Calendar/files/2299931/logcat.txt)

**Comment by tibbi** [comment]
logs dont help in these cases, it is a launcher issue. Whta launcher are you using? Please test it with Nova Launcher, or some other popular one.

**Comment by 0pLuS0** [comment]
I was using it with Lawnchair in both Roms, and the AospExtended Rom worked on the Mi A1, but didn't work on the Essential using CarbonRom...

I personally like Lawnchair, I'll keep playing then, if it's the Launcher...

**Comment by tibbi** [comment]
Ill test the icon customization with Lawnchair too, so far havent heard anyone using it

**Comment by 0pLuS0** [comment]
I've been playing with as many as I can get my hands on today, but only through F-Droid, I'm pretty much GappLess in my Roms, so no Play Store for me...

**Comment by tibbi** [comment]
Ive created an issue at the General Discussion for it, as the issue is not specific to the Calendar. It is at https://github.com/SimpleMobileTools/General-Discussion/issues/83

**Comment by 0pLuS0** [comment]
@tibbi hi,

I've loving your apps, keep up the great work!

I've been playing around with every launcher out there, and truthfully I don't really care for any of them, either to much bloat, or not enough features.

The ```Rootless Pixel Launcher``` would be great if it just had the ability to remove the Google search bar at the bottom and change the App Labels... As far as a Launcher goes, this is as simple and all I want.

So for now I'm just using ```Launcher 3``` and I wanted to ask, is there anyway possible to get the icons to change color using the ```Launcher 3```?

Thanks

**Comment by 0pLuS0** [comment]
@tibbi hi,

I'm really loving your apps, keep up the great work!

I've been playing around with every launcher out there, and truthfully I don't really care for any of them, either to much bloat, or not enough features.

The ```Rootless Pixel Launcher``` would be great if it just had the ability to remove the Google search bar at the bottom and change the App Labels... As far as a Launcher goes, this is as simple and all I want.

So for now I'm just using ```Launcher 3``` and I wanted to ask, is there anyway possible to get the icons to change color using the ```Launcher 3```?

Maybe in time you can make the ---> ```Simple Launcher``` like the ```Rootless Pixel Launcher``` but with the ability to remove the Google search and edit the Labels. This would be GREAT! :+1: 

THANKS

**Comment by tibbi** [comment]
some standalone launcher might be added someday in the further future, we will see. I cannot affect Launcher 3 for now. Cant you long press the home screen icon, and somehow change it? Thats the way you can work around the restrictions in Nova. You can find the icon files at https://github.com/SimpleMobileTools/Simple-Calendar/tree/master/app/src/main/res , basically just change the url manually to get to other apps.

**Comment by 0pLuS0** [comment]
@tibbi what do you mean pressing the Home screen, to bring up the Launcher options/settings?

Simple-Calendar/app/src/main/res/ I have no idea where/what you are trying to show me?

**Comment by 0pLuS0** [comment]
I'm just using the Stock Launcher3 that came shipped with the phone on Stock Oreo. This has no such options.

For me lauchers are either to bloated or not enough features. So I settled on using the Launcher3 which is as small as they come, then I installed the ```Pixel Launcher Mods```

https://labs.xda-developers.com/store/app/com.kieronquinn.app.pixellaunchermods

It shows you can change the icon, when I press on it, I get two options ```Icon Pack Icon``` and ```Icon From File```, but I don't have any icon packs installed or icon files, and this seems to be about changing to a completly new look, not the color.
