### ISSUE TITLE
Merge to Etar

### ISSUE THREAD

**Issue by davidhedlund** [SimpleMobileTools/Simple-Calendar#59]
Why not merge your project to [Etar](https://github.com/xsoh/Etar-Calendar/issues/108)?

**Comment by tibbi** [comment]
well its a different project with a different mindset, why would we merge? :)

**Comment by davidhedlund** [comment]
@tibbi Because Task is not yet implemented in Etar. I think you would be a good team, you would still have your copyright and work on your source files.

**Comment by tibbi** [comment]
I dont think that would work out well. That app looks quite confusing to me, and from what Ive checked their code is really complicated too, and written in java :p (Im in kotlin). They require 11 permissions, I require 2. The fact that they dont allow using their app without local calendar permission sums up their attitude quite well, thats definitely not the direction I want to go in. They got less than 10k installs in 8 years, I already have 30k in 6 months. Maybe they are popular in the arabic countries, but that is not the area I want to focus on. I have a weekly view and some calendar synchronizations on the roadmap too, just stay tuned :)

**Comment by davidhedlund** [comment]
@tibbi Thanks for your interesting feedback.

Let's twist this: Currently it is only possible to add Tasks, so are you going to implement Events (as seen in Etar) to Simple Calendar as well?
