### ISSUE TITLE
Feature request: Option to disable all reminders

### ISSUE THREAD

**Issue by spocko** [SimpleMobileTools/Simple-Calendar#593]
It would be nice to have an option in the settings that globally enables/disables all reminder notifications. 

This would be useful when Simple Calendar is installed on a secondary device, such as a tablet, where reminders are not needed.

**Comment by tibbi** [comment]
that should be a system responsibility, not the apps. Just disable it in your device.

**Comment by spocko** [comment]
I respectfully disagree. If notifications are disabled at the system level, then the app is still running a schedule in the background and generating the notifications, but the system is just not showing them to you. This is different than having a setting in the app to tell it not to generate notifications. The later option, in theory at least, could reduce background CPU usage because the app no longer needs to perform the work necessary to generate the notifications. 

It's always better to disable notifications in-app when possible, rather than hiding them at the system level.

From the UI perspective, I envision a simple toggle slider next to "Event Reminders" in the settings, so no significant UI changes would be needed.

**Comment by tibbi** [comment]
starting with Android 7, 8 or so, you can mute notifications on a per-app basis, even temporarily. The CPU makes plays no role there, it is a really tiny operation. I dont want to flood the app settings with such options.

**Comment by spocko** [comment]
Even with the improved notification management features in newer Android versions, that approach is still suppressing the notifications after they have been generated, instead of preventing them from being generated. 

I also think it's more convenient for users to manage notifications within the app, instead of having some settings in the app and some settings at the system level. 

Anywho, I respect your opinion on the matter, and thank you for responding.
