### ISSUE TITLE
Notification for a recurring event: first occurance instead of next event

### ISSUE THREAD

**Issue by klawdhfzasjhaa** [SimpleMobileTools/Simple-Calendar#596]
- Type: recurring appointment (all 4 week's Tuesday)
- End date: never
- Time span: whole day
- Reminder: 7 hours before start / 17 o'clock the day before

In the screenshot you can see the start date of the event: 16.01.2018. Expected is the 27.08.2018.
![screenshot1](https://user-images.githubusercontent.com/2808094/44739580-749f2c00-aaf8-11e8-9ca9-4cf4dad8c0ec.png)

The event was created with aCalendar+ and synced by DAVDroid over Nextcloud.

The export gives me the following ics:
BEGIN:VCALENDAR
PRODID:aCalendar
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VEVENT
SUMMARY:Papiertonne
DTSTART;VALUE=DATE:20180116
DTEND;VALUE=DATE:20180117
RRULE:FREQ=WEEKLY;INTERVAL=4;BYDAY=TU
UID:20180828T193500Z-8684@acalendar
DTSTAMP:20180828T193500Z
END:VEVENT
END:VCALENDAR

**Comment by tibbi** [comment]
this should be already fixed, please update your app if not

**Comment by klawdhfzasjhaa** [comment]
I'm already on Version 4.1.3 (2018-08-06).
LineageOS 14.1(Android 7.1.2).

In what version it should have been fixed?

**Comment by tibbi** [comment]
it should be fixed in 4.1.3 already for some time. Can you reproduce it by scheduling an event repeating daily starting some days ago, and seeing the issue on todays reminder?

**Comment by klawdhfzasjhaa** [comment]
Ok. I created a new daily repeating whole-day event for Saturday with a reminder the day before 8 o'clock. Will get back to you on Sunday with the result.

**Comment by tibbi** [comment]
I mean if you try scheduling an event like 2 minutes into the future, repeating daily, with the first occurrence last week, does the notification show wrong date? I guess it is the same usecase.

**Comment by klawdhfzasjhaa** [comment]
Ah I see. In this case it shows only the time (21:41 - 22:42), but no date at all. My guess is that there is something about whole-day events. I've scheduled like explained in [above](https://github.com/SimpleMobileTools/Simple-Calendar/issues/596#issuecomment-419213106). We'll see what happens.

**Comment by klawdhfzasjhaa** [comment]
As described, with the event 2 minutes in to the future (on the same day, reminder 1 minute before), the reminder is correct. But with the event for + 1 day and reminder one day before, it only displays: "whole day" (translated) and the title of the event. You don't even know, that the event is tomorrow. This is different to the initial screenshot ("Januar 16, Ganztags"). Now, it's only "Ganztags"..

I know you re-saved the old events, maybe that help. Next occurance is 21st September (reminder on 20th September).

**Comment by tibbi** [comment]
so I managed reproducing it, it should be fixed in 4.2.0. Reopen if it will still be broken, thanks.
