### ISSUE TITLE
Cannot add Tasks

### ISSUE THREAD

**Issue by davidhedlund** [SimpleMobileTools/Simple-Calendar#60]
In Samsung's S Planner it is possible to add both Events and Tasks. In Simple Calendar it is possible to add Events but not Tasks, are you going to implement it?

**Comment by tibbi** [comment]
i might add it in the future, but its not on the roadmap currently

**Comment by davidhedlund** [comment]
Thanks.

**Comment by jkc88** [comment]
I'm also hoping for a tasks feature to be added at some point, it's the only reason i need to keep a separate todo app on my phone in addition to the calendar. I didn't want to open a new ticket for this so i'll ask here if it's possible/intended to also have a separate tasks widget, and will tasks also have the ability to be scheduled with alarms? The calendar app gets cluttered and slows down with multiple daily and repeating events.

**Comment by tibbi** [comment]
more info at https://github.com/SimpleMobileTools/General-Discussion/issues/40

**Comment by ahstro** [comment]
Hate to bump an old issue, but this would be so good. If Simple Calendar had tasks, I might actually finally use them 😅

**Comment by KonstantMan** [comment]
Yeah I would like to have this feature too, especially with nextcloud and http://tasks.org/

**Comment by azzamsa** [comment]
The only feature that keeps me searching for another app for a to-do list.

**Comment by azzamsa** [comment]
I think what if we keep using  Simple-Calendar + NextClould + Tasks.org?
To avoid adding more complexity to the code-base.

I am okay with the current workflow.

**Comment by tibbi** [comment]
An initial implementation of tasks has just been added in 6.17.3. They can be stored locally only for now, adding caldav sync and other fields like repetition etc are on the roadmap.

**Comment by davidhedlund** [comment]
Thank you very much for your work.
