### ISSUE TITLE
Use event type color for descriptions in event lists

### ISSUE THREAD

**Issue by linuxcaffe** [SimpleMobileTools/Simple-Calendar#600]
This feature request is for an optional enhancement to event lists (especially in the widget), displaying the event description text using the event-type color. I think this would make is much clearer, at a glance, what type of event one was looking at. Optional in the settings become some users might not like it, and I really would :)

**Comment by tibbi** [comment]
I want to handle the colors somehow else, not by coloring the description. Some events dont have any description so it would be inconsistent.
