### ISSUE TITLE
Saving a note with active notification takes unusually long

### ISSUE THREAD

**Issue by woutgg** [SimpleMobileTools/Simple-Calendar#601]
Updating an existing note *without* active notification happens quickly or even almost instantly as expected, but doing so with a note that *does* have a notification takes up to about six seconds on my phone (Moto G5).
Especially in combination with #541, this is very impractical.

Is there are relatively easy way to profile the app? I'd be happy to do so and see if the cause can be tracked down that way.

**Comment by tibbi** [comment]
you mean if an event reminder triggers, and you open the app via the app launcher and update the event like that, it misbehaves?

**Comment by woutgg** [comment]
Sorry for the delay; actually I'm not sure. And when I tried to determine this, all attempts to update and save a note suddenly happened quickly (in < 1 sec).
So perhaps it is caused by something else after all, I don't know. I'll have to wait until

**Comment by tibbi** [comment]
well reopen it if it happens again, I dont really see any reason why would it be slow, maybe just a more general freeze somewhere in the device. Having a reminder displayed shouldnt affect it at all either.
