### ISSUE TITLE
Widget date redundancy

### ISSUE THREAD

**Issue by linuxcaffe** [SimpleMobileTools/Simple-Calendar#602]
imho, the widget could be improved/ streamlined, by eliminating the inherent date display redundancy, whenever there is an even happening today.
for example;
today my widget shows me 

September 01 (Saturday)   +
**September 1 (Sat)**
 10:00 R&S yard sale
...

which simply consumes screen real-estate while showing me duplicate information.
When there is an event today, why not Simply:

**September 01 (Saturday)   +**
 10:00 R&S yard sale
...

?

thanks!

**Comment by tibbi** [comment]
I want to keep the date there for consistency
