### ISSUE TITLE
repeat event semantics

### ISSUE THREAD

**Issue by GuitarBilly** [SimpleMobileTools/Simple-Calendar#606]
Nokia 6, android 7.1.2, SC v4.1.3
When creating a repeat event, one can enter the number of repetitions: "repeat x times".

**Current behaviour:**
 the "repeat x times" field value is equal to the total number of events.

**Expected behaviour example:**
 entering 3 at "repeat x times" should create 4 events; the original event and three repetitions.

Thank you for your wonderful apps.

**Comment by GuitarBilly** [comment]
@tibbi , i consider this a bug. if you take the description literally, the action is not correct. One more event needs to be created.

So in my view you have to fix the action, or change the description of the item.

But since i am not a native english speaker, i would like one to confirm or negate my statement about the repeating event.

**Comment by tibbi** [comment]
it doesnt matter how I mark it, Ill take a look at it once Ill work on the calendar.

**Comment by tibbi** [comment]
I changed the string to keep it consistent with Google Calendar and avoid having to adding/subtracting 1 at exporting/importing.
