### ISSUE TITLE
Add birthdays/anniversaries with calculating age/years

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Calendar#61]

**Comment by Docbroke** [comment]
Also add tags, for holiday/birthday/anniversary etc., with automatice yearly recurrence for birthdays/anniversaries

**Comment by Anke** [comment]
+1
This feature request dates back to 2016!? I'd also love to see a persons age behind a birthday.

**Comment by duesseldorferjung** [comment]
+1

**Comment by tibbi** [comment]
will be added in 6.15.1
