### ISSUE TITLE
Caldav sync drop down empty

### ISSUE THREAD

**Issue by vhoen** [SimpleMobileTools/Simple-Calendar#612]
Since a few days ago, Simple calendar shows an empty list in the "CalDav Sync" drop down.
I am using Davdroid to sync data from icloud and calendars are properly setup.

I have read this : https://github.com/SimpleMobileTools/Simple-Calendar/issues/515, but permissions are enabled.

Thanks in advance.

**Comment by tibbi** [comment]
so it used to work previously? Do you see the events in any other calendar on your device?

**Comment by vhoen** [comment]
My bad. It seems I messed up something on my phone a few weeks ago and didn't realize it before today. Sorry about that.
