### ISSUE TITLE
CalDAV - event shown as 'All-Day' when it's not (Synology Calendar)

### ISSUE THREAD

**Issue by Keenuts** [SimpleMobileTools/Simple-Calendar#621]
Hi,

When creating an event on SimpleCalendar, event is always shown as 'All-Day' on Synolgy Calendar.
Creating the same event using another android app solve the issue.

## To reproduce:
- create an event using SimpleCalendar on a CalDAV synced calendar
- set the time to something, like 1PM -> 2PM

## Expected:
- SimpleCalendar shows the event: 1PM -> 2PM
- Every other app shows the event: 1PM -> 2PM
- Synology Calendar shows the event: 1PM -> 2PM

## Observed
- SimpleCalendar shows the event: 1PM -> 2PM
- Every other app showd the event: 1PM -> 2PM
- Synology Calendar shows the event: "full-day"

The WebApp clearly have something wrong, but the same process done on any other application displays a correct event on the WebApp.
**ex: creating the event using the Google Calendar app, Synology Calendar shows the correct information**

### Phone:
- Simple Calendar 4.2.0
- DavDroid 2.0.4-gplay
### Server:
- DSM - 6.2-23739
- WebApp: Synology-Calendar 2.2.1-0518

Have a nice day !

**Comment by tibbi** [comment]
retry with the pro version 6.1.0 released soon please, some possibly related issues have been fixed
