### ISSUE TITLE
Widget always shows first entry in calendar

### ISSUE THREAD

**Issue by knut-hildebrandt** [SimpleMobileTools/Simple-Calendar#645]
The widget always shows the first entry - in my case almost four months ago - instead of the current day. I do not see any way to configure the widget and change this behavior. The calendar I use is a DAVdroid resource.

Installed version: 4.2.1 -> had the same issue with older versions
Android version: 7.1.1

**Comment by tibbi** [comment]
You mean that if you create the monthly widget now, it is set to June by default?

**Comment by knut-hildebrandt** [comment]
No, I'm talking about the event-view (in German Termin-Liste). It always shows events starting about three months before the current date, even though this is shown correctly in upmost line. If I touch this upper line calender opens correctly with event-view of current day. If I hit one of the shown events in the widget I see it's details.

**Comment by knut-hildebrandt** [comment]
Little correction. It's not the first event in calendar - as I stated in my first post - that is shown in the widget but one about three months before the current date.

**Comment by tibbi** [comment]
if you go in the app settings -> Events Lists section -> Display events from the past, what value do you have there?

**Comment by knut-hildebrandt** [comment]
3 month is shown. My interpretation was, that the calender show three months in the past when I scroll back and not that it starts there: But when calendar app is open I even can go back beyond these three months and the widget starts exactly then. Is this intentional?

**Comment by knut-hildebrandt** [comment]
Just changed it to 0 and every thing seems to be right.

**Comment by tibbi** [comment]
ye, by scrolling you can get a lot further than that, it is the intentional behaviour. Maybe the text could be tweaked, we will see in the future. Thanks
