### ISSUE TITLE
Add the dot in the widget back as an option

### ISSUE THREAD

**Issue by zekooooo** [SimpleMobileTools/Simple-Calendar#652]
Hey, sorry for nitpicking, it's kinda stupid to complain about a minor change when you've made such a great app :) can you add the calendar color dot instead of the vertical line as an option in the menus somewhere? It went really well with my theme... thanks

**Comment by tibbi** [comment]
Sorry, but I want to keep the lines :) It is easier to see and I dont want to add a toggle for that.
