### ISSUE TITLE
Importing holidays

### ISSUE THREAD

**Issue by Domino2017** [SimpleMobileTools/Simple-Calendar#654]
Not exactly an issue, more of a comment. 

After this last update, I was able to set the language to my local one (Greek) and when I try to import holidays I get an error message. When I switch the app language back to English, importing holidays works perfectly. The phone itself is set to Greek and it's android 6. It's not a big issue. Importing them in English and translating them myself is really no problem at all, just thought it may be something you would want to know.

Domino

**Comment by tibbi** [comment]
what is written on that error message?

**Comment by Domino2017** [comment]
"Η εισαγωγή αργιών απέτυχε" (the message is in Greek. This is the literal translate "Error, importing has failed")
The app version is 4.2.1.

**Comment by tibbi** [comment]
hm, if I send you a test version, can you try it out? It should show some more descriptive message. Ideally send me a mail at hello@simplemobiletools.com so I can reply easily and send the app there

**Comment by Domino2017** [comment]
Sure thing

**Comment by tibbi** [comment]
so it got fixed already if I remember correctly
