### ISSUE TITLE
Set reminder sound to something default if the selected file doesnt exist anymore

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Calendar#656]
Even system files can get deleted during some upgrade.

**Comment by J0n1k4** [comment]
I had this problem for a few weeks. I missed all my apointments, untill I figured out that the notification sound was not available anymore...
I had a java.lang warning that "randomly" informed me of some sound problem, but I couldn't connect it to Simple calendar (see the attached file - nothing implies to Simple calendar). I have a phone profile plus app to tweak the ring / notification / alarms sounds, and I was looking in that direction. 
It is interesting that no event notification pop-up from Simple calendar was presented, just that java warning...
![IMG_20200408_115000](https://user-images.githubusercontent.com/26709833/78771472-7bf31080-7990-11ea-8763-522cd2956730.jpg)

**Comment by tibbi** [comment]
notification customization is already handled by the system, not us
