### ISSUE TITLE
Show calendar color and have a more prominent place for calendar name in event view

### ISSUE THREAD

**Issue by ouzowtf** [SimpleMobileTools/Simple-Calendar#659]
I think it would be helpful to move the calendar name of an event up in the event view between the time and the notifications and show the calendar color instead of being the last information in that view.

**Comment by charBap** [comment]
Are you talking about the simple event list view ?

**Comment by tibbi** [comment]
calendar colors have been remade since then, now it shows as a bar instead of a dot
