### ISSUE TITLE
some alternative to caldav, since it does not save the colors when

### ISSUE THREAD

**Issue by cetrun** [SimpleMobileTools/Simple-Calendar#668]
some alternative to caldav, since it does not save the colors when

**Comment by tibbi** [comment]
there is no alternative

**Comment by tibbi** [comment]
there is no alternative

**Comment by cetrun** [comment]
since caldav does not save event by color, it could be assigned color by title, and this is an indicator for the user, I saw it in the samsung calendar

**Comment by cetrun** [comment]
please, implement it as a priority, it would be very helpful
