### ISSUE TITLE
week view broken on re-open sometimes

### ISSUE THREAD

**Issue by duchampdev** [SimpleMobileTools/Simple-Calendar#675]
From time to time, if I re-open the app to week view after a longer time, the header (dates and weekdays) is missing.
Do you know a quick fix for that? Otherwise I could also have a look into it and try to fix it by myself.

**Comment by tibbi** [comment]
Im not sure what is wrong there, I plan taking a look at it soon, maybe even today. Duplicate of #359

**Comment by duchampdev** [comment]
Sorry, didn't find the old one. Thank's a lot!
