### ISSUE TITLE
Week number shifted by -1

### ISSUE THREAD

**Issue by SebiderSushi** [SimpleMobileTools/Simple-Calendar#69]
On my device (OnePlus X (ONE E1003)) running ResurrectionRemix 5.7.4 with german system date format the displayed week numbers are shifted by -1 as well as this years week 1 (Jan 4-10) is numbered 53 of the previous year.

**Comment by tibbi** [comment]
hm thats weird, cant reproduce it. Does it happen at other calendars too, like https://play.google.com/store/apps/details?id=ws.xsoh.etar ? (its opensource, I could check how are they doing it if its ok)

**Comment by SebiderSushi** [comment]
It happens when Sunday is set as first day

**Comment by tibbi** [comment]
please recheck with version 2.1.0, Ive changed something there
