### ISSUE TITLE
Free Pro version not found in Play Store

### ISSUE THREAD

**Issue by rstruminski** [SimpleMobileTools/Simple-Calendar#691]
I am asked to upgrade to the temporarily free Pro version of the app, and the link does take me to the Play Store, but there it says "not found". Can't find it manually either.

**Comment by Wasnix** [comment]
Same here at twelve o'clock. I clicked [UPGRADE] in f-droid version (5.1.2) in the nag screen popup, but new version (6.0.0) in Play Store could not be found. WTF

**Comment by tibbi** [comment]
there is no Pro calendar yet, the f-droid version got updated by mistake with their script.
