### ISSUE TITLE
"Display past events of a day ago" doesn't show yesterday's recurring event

### ISSUE THREAD

**Issue by youdly** [SimpleMobileTools/Simple-Calendar#692]
using v5.1.1.

I set "Display events from the past" to "1 day" and enabled "Dim past events".

I have two events:
**A** (from https://github.com/SimpleMobileTools/Simple-Calendar/blob/master/app/src/main/assets/malaysia.ics)
```
BEGIN:VEVENT
DTSTART;VALUE=DATE:20181112
DTEND;VALUE=DATE:20181113
UID:20181112_60o32e1j64o30c1g60o30dr568@google.com
STATUS:CONFIRMED
RRULE:FREQ=YEARLY;INTERVAL=1
SUMMARY:Birthday of the Sultan of Kelantan (Day 2) (Kelantan)
END:VEVENT
```

**B**
```
BEGIN:VCALENDAR
BEGIN:VEVENT
DTSTART;VALUE=DATE:20181015
DTEND;VALUE=DATE:20181016
UID:topup_card
STATUS:CONFIRMED
RRULE:FREQ=WEEKLY;INTERVAL=4;UNTIL=20191231T000000Z
SUMMARY:Topup Card
END:VEVENT
END:VCALENDAR
```

Both events occurred on 12 Nov and displayed correctly by the app and monthly view widget.

On 13 Nov (14:00 as of writing), the (Event View) widget showed dimmed **A** (as expected) but not **B**.

Dimmed **B** is only shown (on the event widget) if I set it to display past events of >= 25 hours ago.

Might be relevant https://github.com/SimpleMobileTools/Simple-Calendar/issues/662 https://github.com/SimpleMobileTools/Simple-Calendar/commit/5ec19501f35fcb9f4d111e7e296ff32e1aaa86bc https://github.com/SimpleMobileTools/Simple-Calendar/issues/185

**Comment by youdly** [comment]
Event **B** was hand-written and imported into the app. I recreated the reminder using the app and the widget displays it fine. This is what the app wrote:

```
SUMMARY:Topup Card
UID:Caldav-1-277
CATEGORIES:Events
DTSTART;VALUE=DATE:20181015
DTEND;VALUE=DATE:20181016
STATUS:CONFIRMED
RRULE:FREQ=WEEKLY;INTERVAL=4;UNTIL=20191231;BYDAY=MO
END:VEVENT
```

My version has `T000000Z` but lacks `BYDAY=MO`. So, the cause could be one of them.

**Comment by tibbi** [comment]
recheck with the pro version 6.0 released soon
