### ISSUE TITLE
Notification not working

### ISSUE THREAD

**Issue by Emml-Anim** [SimpleMobileTools/Simple-Calendar#693]
Hi I have version 5.1.2, but I don't receive notification when an event is set

**Comment by tibbi** [comment]
if you schedule an event 1-2 minutes into the future and keep the app foregrounded, does it work? What Android OS version do you have?

**Comment by Emml-Anim** [comment]
No. I am using Android OS version 8.0

**Comment by Emml-Anim** [comment]
Can we chat via some other means, maybe conversations or whatsapp or messenger

**Comment by tibbi** [comment]
check your device battery or notification settings, disable the battery savers. You can write me at hello@simplemobiletools.com, Ill reply when I get back home. Sadly there are many device related things that can break reminders, what brand do you have?

**Comment by Emml-Anim** [comment]
Okay. Samsung A8+(2018)

**Comment by Emml-Anim** [comment]
Hi I have made sure the battery saver is disabled but still don't receive reminders

**Comment by tibbi** [comment]
try scheduling an event 1 minute into the future with a reminder and keeping the app in the foreground. As you schedule it, do you see  message like "Time remaining till the reminder trigggers..."? Does it properly show just a couple seconds? Or try scheduling an event with reminders in the past, does a reminder show up instantly at saving the event?

**Comment by Emml-Anim** [comment]
Yeah after today's update my reminder started working. Thanks for your time and effort
