### ISSUE TITLE
PRIVACY NEEDED! Don't send my data to anyone — make the calender private again like version

### ISSUE THREAD

**Issue by Violinchen** [SimpleMobileTools/Simple-Calendar#694]
I don't want my contacts to be read and my private events or other information to be changed or sent by email automatically. Please remove these unreasonable rights of the app and give an update with normal rights like on version 2.5.7.

**Comment by tibbi** [comment]
you decide who sees your events, there is no sending anywhere unless you enable it

**Comment by Violinchen** [comment]
Seems not possible to attach a screenshot with a mobile device.
I feel ignored. Privacy is the most important thing nowadays. The calender should not be able to send my information to anyone, so these permissions are totally unneeded.
