### ISSUE TITLE
Filter by type settings ignored after restart in new pro version 6.0.0

### ISSUE THREAD

**Issue by ouzowtf** [SimpleMobileTools/Simple-Calendar#695]
I have several calendars synchronized via CalDav.
Two of them should not be shown normally, so I uncheck them at the filter by type menu option.
If simple calendar is swiped away from recent apps list or gets killed by Android ~13 seconds after the next app start all calendars are shown again, including the two I unchecked/filtered out.

This does not happen in 5.1.1

**Comment by tibbi** [comment]
and if you check the Filter dialog after app relaunch, are those 2 unwanted types checked too? Does exiting the app properly via back button work fine?

**Comment by ouzowtf** [comment]
The filter dialog shows one of them (Outlook calendar) checked right after app relaunch, the other one is not checked.
When I leave the filter dialog and open it again after their events are shown in the calendar, the second filter option is checked too.
Exiting via back button has the same behavior as killing it/swiping it away from recent apps.

**Comment by tibbi** [comment]
will be fixed in 6.0.1
