### ISSUE TITLE
request: default time for events

### ISSUE THREAD

**Issue by gerhardbeck** [SimpleMobileTools/Simple-Calendar#696]
Hi, one thing I really miss on simple calendar ist a default time for events. When creating a new event start and end time is always the same time, which is not useful.
Would it possible to change that

**Comment by jmespadero** [comment]
This should be nice. Even something as simple as default duration of 60 minutes would be nice.

**Comment by charBap** [comment]
Can I work on this? @tibbi

**Comment by NWuensche** [comment]
Sorry, I already tried to solve this in the last days without saying anything.
