### ISSUE TITLE
Simple calendar 6.0.1 shows an event one hour later

### ISSUE THREAD

**Issue by ouzowtf** [SimpleMobileTools/Simple-Calendar#704]
This is an event I created today:

BEGIN:VEVENT
SUMMARY:Test 18
UID:Caldav-25-3621
CATEGORY_COLOR:-1642563
CATEGORIES:Einmalige Termine
LAST-MODIFIED:19700101T000000Z
DTSTART:20181124T180000Z
DTEND:20181124T190000Z
STATUS:CONFIRMED
END:VEVENT

In version 6.0.1 the event is shown from 19-20 (7pm to 8pm).
In version 5.1.2 the event is shown (correctly) from 18-19 (6pm to 7pm)

Seems like Simple Calendar 6.0.1 falsely adds 1 hour because of central European winter time when showing an event.
Events with central European summer time seem to show fine in both versions.

**Comment by tibbi** [comment]
it is shifted to me in the old version too, maybe you actuall tested it before the winter time. The datetime ends with Z which means that it is UTC time and should be shifted accordingly to the users timezone. It is mentioned at https://www.kanzaki.com/docs/ical/dateTime.html too.

**Comment by ouzowtf** [comment]
I just tested it again creating an event tomorrow at 6pm with the old version.
After CalDAV sync its shown shifted in the old and new version to 7pm.
However, I logged in in the online calendar and it's shown correct there at 6pm!
 
Do you by any chance change the shown date/time in simple calendar again after CalDAV sync and add the 1 hour again?

My Android system and online calendar settings are both set to GMC+1/UTC+1.

**Comment by tibbi** [comment]
there is no way currently to shift all events by some time. Some timezone improvements are definitely needed in the app, I will get there someday.

**Comment by ouzowtf** [comment]
I didn't mean to shift several events by some time to correct them. This was just an assumption by me that this happens in the background and triggers this behavior.

**Comment by tibbi** [comment]
the given .ics event got imported in your device correctly. There are some timezone related things in CalDAV which I might be ignoring currently.
