### ISSUE TITLE
Event repetition does not work across years

### ISSUE THREAD

**Issue by Zer0-One** [SimpleMobileTools/Simple-Calendar#705]
I've set up a test event that reoccurs every 3 weeks. For some reason, the event isn't repeated correctly when the year changes.

![1](https://user-images.githubusercontent.com/1117820/48919692-4b691000-ee49-11e8-97e0-c30fe1bc0ac1.png)
![2](https://user-images.githubusercontent.com/1117820/48919693-4dcb6a00-ee49-11e8-93fc-8028582f0e64.png)

That repetition on the 31st is obviously unexpected.

**Comment by tibbi** [comment]
should be fixed in 6.0.2 released soon
