### ISSUE TITLE
Minimum android version

### ISSUE THREAD

**Issue by Mistress-Anna** [SimpleMobileTools/Simple-Calendar#714]
In all "simple mobile tools" apps, it seems the minimum android version is 5, why? This changed recently, and since then I cannot update any of the simple mobile tools anymore. My phone won't receive system updates since the phone constructor won't.

**Comment by tibbi** [comment]
there was a really small amount of Android 4 users remaining and it isnt easy to keep the apps working on those devices, so it wasnt worth supporting anymore

**Comment by Mistress-Anna** [comment]
Allow me to disagree, as of september 2018, [android 4.4 (the version I use) alone represents ~8% of users](https://www.statista.com/statistics/271774/share-of-android-platforms-on-mobile-devices-with-android-os/) which isn't negligible at all. If you add other 4.x versions, you are well over 10%.

**Comment by tibbi** [comment]
that is the theory involving inactive devices, but Ive seen it on my actual usage. It was usually around 1-2%
