### ISSUE TITLE
Configure Reminders for imported birthdays

### ISSUE THREAD

**Issue by knut-hildebrandt** [SimpleMobileTools/Simple-Calendar#719]
Since I've got problems with showing the birthday calendar generated by Birthday Adapter I would rather use the integrated contacts birthday import feature. The big disadvantage, the reminders have to be set birthday by birthday which is cumbersome. Thus I'd wish for a setting that allows to configure up to three standard reminders.

Thanks

Knut

**Comment by Esokrates** [comment]
Really useful feature. I want at least be reminded of my contacts birthdays. In many cases however I want to be notified up to two weeks beforehand in order to organize presents and stuff.

**Comment by Esokrates** [comment]
@tibbi Thanks very much for implementing this. I tried it on a fresh installation of the app and I select a notification when importing, but afterward when clicking on the event there is no notification shown.

**Comment by tibbi** [comment]
I see, I can actually reproduce it too :) Thanks
