### ISSUE TITLE
Alarms do not go off if phone is set to Do Not Disturb

### ISSUE THREAD

**Issue by GitHubRub** [SimpleMobileTools/Simple-Calendar#720]
This is on version 6.0.1 (Android version 8.0.0). It doesn't matter what audio stream I select under settings, the alarm will not play if DND is enabled. If I turn on the screen I can see that a notification for the event has been created. DND is set to alarms only. Setting DND to custom and allowing event/task alerts makes no difference. Enabling DND reminders causes the notification to show up on my watch, but the alarm still does not play on the phone.

(alarm plays fine when DND is disabled)

**Comment by tibbi** [comment]
recheck with 6.1.0 please

**Comment by GitHubRub** [comment]
I downloaded the APK onto my phone and opened it. I was then asked if I wanted to install an update to an existing application (or do nothing), but clicking install results in a brief "Installing" animation followed by the error "App not installed." 

Do you recommend uninstalling the app and then installing the APK, or simply waiting for the Google Play version to be updated to 6.1.0?

Thanks.

**Comment by tibbi** [comment]
if you installed the initial version from Google Play, you have to update it from there. You cannot get one version from one source and the other version from another source.

**Comment by GitHubRub** [comment]
Now that the Google Play edition has been updated, I can confirm that it works if I set DND to custom mode and enable the "event/task alerts" option.

Thanks!
