### ISSUE TITLE
No icon on Android 9 with Pro versions

### ISSUE THREAD

**Issue by SamWhited** [SimpleMobileTools/Simple-Calendar#722]
Hi,

I was surprised there's no issue for this because there are a ton of bad reviews in the playstore because of it, so pardon me if it exists already and I just couldn't find it:

I downloaded the pro version of the tools, but now there is no way to launch them. They don't show up in the Android menu, the icons disappeared from my home screen, and "simple app launcher" launches the Google Play Store and tries to get me to install the non-pro versions.

I am on Android 9, though I don't know if that's part of the problem or not.

The only way I've found to launch some of them is to add widgets, eg. the calendar widget to my home screen and click that, but that takes up a lot of room and isn't really something I want to do long term.

The icon is there immediately after I install the app, by the way. It only disappears after I launch any of the pro apps for the first time.

**Comment by tibbi** [comment]
do you maybe have Simple Thank You installed with Shared Theme enabled? If you do try uninstalling it. Some launchers do not handle icon customization properly.

**Comment by SamWhited** [comment]
This is the standard Android launcher, nothing special or vendor customized and not the new Pixel only one Google made. I tried uninstalling Simple Thank You and restarting, but the icons aren't there and I can still only access calendar or any of the pro apps through a widget.

**Comment by tibbi** [comment]
so try launching the app, go into the app settings -> customize colors and change the icon color to something. Or try the default #F57C00.

**Comment by SamWhited** [comment]
That seems to have fixed the calendar app. Is this something you can auto-apply in an update? I can access calendar because it has a widget, but I don't have a way to get to most of the other pro apps.

**Comment by tibbi** [comment]
you can launch all apps via playstore, the "Install" button is replaced with "Open". It cannot really be made fully reliable, as it depends on the launcher and some do not handle icon customization properly.

**Comment by SamWhited** [comment]
The open button on the play store also goes away, there is only an uninstall button now so I still can't launch most of the apps.

Also, this is the standard Android 9 launcher, not some custom nonsense form Samsung so if anything it seems like the one you'd want to support. Maybe a "remove all custom themes" setting could be added to simple thank you?

**Comment by tibbi** [comment]
well that is weird, so far nobody had issues launching the apps. Google Play always has the Open button there, if the app is installed. Can you send me a screenshot of Google Play?
I plan doing some Simple Thank You changes, just not yet sure what ones.

**Comment by SamWhited** [comment]
![screenshot_20181206-081424](https://user-images.githubusercontent.com/512573/49589522-86973300-f961-11e8-88e3-40996f467ac7.png)

**Comment by tibbi** [comment]
heh, strange. Maybe they are doing some A/B testing and Open wont be added there anymore. You might have to remove Thank You and reinstall the Pro apps to see the icon again. You wont have to pay again for any of the apps, dont worry about that.

**Comment by SamWhited** [comment]
> You might have to remove Thank You and reinstall the Pro apps to see the icon again. You wont have to pay again for any of the apps, dont worry about that.

Please, please don't make me do this :( it's not about paying for them again (in fact, I'm happy to support these apps, they're great!), it's about both keeping my data in some apps, and just the thought of having to go through each and every app and reinstall, set it up again, try to clear the theme, etc. wearies me. I got these apps to make my life easier, not to do more work messing with a phone.

**Comment by SamWhited** [comment]
> Maybe they are doing some A/B testing and Open wont be added there anymore

Oh, I forgot to say (and it might be important): Open *does* show up immediately after I install the app (when the icon is still visible). It goes away as soon as I've launched the app, just like the icon so maybe it's the same underlying problem and it can't find the main intent or something? I don't actually know how the custom icon stuff works, so I'm just speculating, but maybe having that info will help :)

**Comment by tibbi** [comment]
the shared theme gets applied at the first launch. Since you cannot launch the apps, how do you have any data in them? I want to fix all thoes shared theme related issues, but it seems like the general experience is pushing developers out of easy icon customization. Nova 6 doesnt allow it anymore either.

**Comment by SamWhited** [comment]
On Thu, Dec 6, 2018, at 09:15, Tibor Kaputa wrote:
> the shared theme gets applied at the first launch. Since you cannot 
> launch the apps, how do you have any data in them

When I updated to the pro app I spent time with each one getting it setup the way I wanted it and making sure all my data was moved over before moving on to the next one. After setting them all up, I discovered I couldn't access them anymore.

> I want to fix all 
> thoes shared theme related issues, but it seems like the general 
> experience is pushing developers out of easy icon customization. Nova 6 
> doesnt allow it anymore either.

Seems worth removing; I can't imagine it's an easy to maintain feature anyways (though I'd be curious to know if I'm wrong)

**Comment by tibbi** [comment]
I will add some warning there, then Ill see where will Android go with it.
