### ISSUE TITLE
Caldav is not  being synced properly

### ISSUE THREAD

**Issue by finzzz** [SimpleMobileTools/Simple-Calendar#725]
Take a look at same open source calendar, etar, it sync immediately when refresh. Simple cal is stuck and won't update an event.

**Comment by tibbi** [comment]
I dont understand what you mean. If you create an event, it doesnt get synced? Or what happens?

**Comment by tibbi** [comment]
retry with 6.1.1, I updated something

**Comment by robjloranger** [comment]
I'm having this issue with an existing caldav calendar on initial installation of simple cal pro.

It never loads any events from the caldav calendars. They are present in the default app though. And online, etc.

**Comment by robjloranger** [comment]
Sorry, I have `6.1.0` f-droid does not have `6.1.1` yet?

**Comment by tibbi** [comment]
it has it already, maybe you didnt have it yet

**Comment by finzzz** [comment]
@tibbi the problem still persists

**Comment by robjloranger** [comment]
@tibbi fixed now that I am using `6.1.1`.

**Comment by tibbi** [comment]
guess it is fixed then
