### ISSUE TITLE
force close when opening settings

### ISSUE THREAD

**Issue by Docbroke** [SimpleMobileTools/Simple-Calendar#73]
Phone: sonim xp6, android 4.4.2, rooted, all google things removed, with microG & xposed
simple calendar version: 1.42 (F-droid)

Issue: application force close when settings selected.

Previous versions works fine.

**Comment by tibbi** [comment]
It was caused by allowing reminder sound customization and some devices were giving errors. It should be fixed in the next version 1.43 which Im just going to upload, let me know if there will be any issues around reminder notification sound. Thanks!
