### ISSUE TITLE
Signing signature

### ISSUE THREAD

**Issue by jamesthedisciple** [SimpleMobileTools/Simple-Calendar#734]
Flashed andriod rom to Mokee (Moto x 2014 8.1) and found Simple Calendar installed v6.0.1 - nice surprize.
As the signature is different I am unable to update the app the v 6.1.1 from F-Droid
Will I have to delete the app from the rom to be able to install and update the app?
I have posted this here as I have been unable to find a way of contacting you! 
Kind regards

**Comment by tibbi** [comment]
Im not aware of anyone preinstalling the apps. Anyway, it might be different, so just remove the preinstalled one and get the one from f-droid I guess. If you have some events already, you can export them in an .ics file, then import.

**Comment by jamesthedisciple** [comment]
The colour is different, that's about all I can see.
Mokee is like a Chinese LineageOS with their own apps that track and monitor you!
Thanks, I'll see how I go :)

**Comment by jamesthedisciple** [comment]
The colour is different, that's about all I can see.
Mokee is like a Chinese LineageOS with their own apps that track and monitor you! (which I have disabled)
I've uninstalled the preinstalled app, installing now, Thank you )
