### ISSUE TITLE
[Enhancement] Go to a date

### ISSUE THREAD

**Issue by meaz** [SimpleMobileTools/Simple-Calendar#741]
It would be nice to be able to go directly to a specific date, like on Etar.
What I mean is that for example if you're in the day view, you could click on a "Go to" button, then a calendar could appear and you could navigate to it to find the date you're interested in. Then, when you click on the chosen date, you'd be back on the day view of this chosen date.

**Comment by tibbi** [comment]
just click on the current date at the top at the daily view for Go to

**Comment by leafcutterant** [comment]
Request for re-open.

I think this would be handy to access in all views, and also it's not obvious how to access this function. I propose adding it to the "..." menu.

**Comment by tibbi** [comment]
it will be added by clicking on the date everywhere, not at the menu

**Comment by tibbi** [comment]
a new "Go to date" menu button will be added in 6.3.2 in all views except the list view. Making the year/week clickable at the top left corner is a bit more difficult and less intuitive.

**Comment by leafcutterant** [comment]
Thank you!
