### ISSUE TITLE
SimpleCalender: Erratic event times when creating new

### ISSUE THREAD

**Issue by thekure23** [SimpleMobileTools/Simple-Calendar#743]
This is the only "bug" (it might me a bad feature tho) I have discovered in a year. But every time I set up a new event, I designate the start time first, and the end time last. Sometimes that happens flawlessly, and sometimes it will cause the start-time to change, based on the newly set end-time. 

What will happen every single time though, is when I subsequently have to change the times for the event, pushing one time, say 15 minutes, will also push the other one. This is an automacy that I don't need, and certainly one the doesn't function properly. What caused me to write the issue here is, the last time I created an event, it took me 3 times of changing the times, because start- and end kept changing to THE SAME value, which made absolutely no sense.

So please, get rid of this or add a setting for it. I really don't wanna get a new calendar now.

**Comment by tibbi** [comment]
I want to avoid adding such redundant settings, so far nobody else requested it. Try reproducing it with setting the start time first, you will probably see that it works just as I explained.

**Comment by thekure23** [comment]
I really don't see how that's redundancy. And as I said, that's already
what I do, so I have succesfully reproduced it many times.

I know you probably don't care about one simple user, but I really like the
app, and if this isn't gonna change in any way, I have to find another app
for this.

**Comment by tibbi** [comment]
Can you maybe do a screen recording with how changing the End date/time changes the Start date/time? I dont see how would that be possible Thanks

**Comment by tibbi** [comment]
Or what app version do you have? Maybe some old one?

**Comment by thekure23** [comment]
It says 6 1.2

**Comment by tibbi** [comment]
seems to work as expected
