### ISSUE TITLE
Error when create an event via another app.

### ISSUE THREAD

**Issue by searoso** [SimpleMobileTools/Simple-Calendar#748]
Hello! I use function "add to calendar" @ "Tasks (Fork of Astrid Tasks & To-Do List) - https://f-droid.org/app/org.tasks" .
After pressing the button it opens calendar and pop up "Unknown error occurred" instead of settings for event. AND the event is created in calendar with _default_ parameters. 
Version 6.1.2.

**Comment by tibbi** [comment]
it apparently happens if you dont have CalDAV sync enabled at all, or the new event just isnt synced in Simple Calendar yet. I added a toast message explaining the error, the user has to enable the calendar syncing then.
