### ISSUE TITLE
[Feature request] Improvement suggestions

### ISSUE THREAD

**Issue by buongiorgio** [SimpleMobileTools/Simple-Calendar#749]
Hi,
I've been using the app for some days now and love its simplicity.

Some suggestions to improve it:

1. Add reminder via email
2. Maybe this is related to #663. On event list, when I scroll up or down a lot of events appears (I have a caldav calendar with contacts' birthdays, so they are repeated yearly: when I scroll I got birthdays from 2018, 2017 etc.). My suggestion is to create a label saying "Show events before 2018-mm-dd" at the top and one "Show events after 2018-mm-dd" at the bottom: if the user wants to show events, he taps on the label. This is how Etar deals with it.
3. Add a shortcut to show/hide calendars. I have a few calendars and often switch them on/off. Currently I need to select the ... menù, select settings, scroll to "Manage synced calendars" and then switch them on/off.

**Comment by tibbi** [comment]
usually you should create 1 ticket per issue, but point 1 wont be added anyway because the app is offline and I dont want to add 3. You can also use menu -> filter for that.

**Comment by buongiorgio** [comment]
You are right on point 3 (I just missed the feature, sorry).

Let me explain a little better on point 1 (in case, I will open a separate issue if you wish). When I say "reminder via email" I do not mean that the app itself should send the reminder: as you pointed out, it is an offline app and it would make no sense. What I mean is: to add the option to set in the CalDAV entry an "ACTION" of type "EMAIL": it will be the server where the CalDAV is hosted that will take care of sending the email. AFAIK this is a CalDAV standard property and the only difference between a "normal" reminder is that the "ACTION" property is set to "EMAIL" (ref. pages 61-68 of the [RFC 6638](https://tools.ietf.org/html/rfc6638) ). This is more or less how Google Calendar works, and the good folks at Nextcloud [are working on this](https://github.com/nextcloud/server/pull/3044).

**Comment by tibbi** [comment]
emails will be added in 6.4.0. Create separate issues for the remaining issues, if still valid
