### ISSUE TITLE
Check some Google Sync event multiplication related issues

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Calendar#754]
More info at email from Bradley on January 12

**Comment by DJCrashdummy** [comment]
IMHO this is similar if not a duplicate to #758.

i also get duplicate entries especially in conjunction with recurring events!
i haven't figured it out completely, but my guess is, that at least modified single entries of a recurring event get added every time you sync _Simple Calendar_.

**Comment by tibbi** [comment]
well Ive already fixed some duplication issues that I could reproduce, but there are so many things done differently depending on what CalDAV service you use. Thats why I keep Google sync and posteo.de as different issues.

**Comment by tibbi** [comment]
should be fixed in 6.2.2, we will see
