### ISSUE TITLE
Add VCard property EMAIL

### ISSUE THREAD

**Issue by schlagi123** [SimpleMobileTools/Simple-Calendar#767]
Hi

it were very nice, if you support the EMAIL field from VCards. A field to add/modify the mail address were greate.

**Comment by tibbi** [comment]
it should already be there. You dont have contact emails imported properly? If so, please open the .vcf file with some text editor and send me the line containing the email, to see in what format is it. Feel free changing the actual email value.

**Comment by schlagi123** [comment]
Sorry my fault. Yes it is there. Thanks.
