### ISSUE TITLE
Usability improvements

### ISSUE THREAD

**Issue by 01123zeka** [SimpleMobileTools/Simple-Calendar#769]
Weekview:
-> current-time-bar is hidden behind the events
-> conflicting events are hiding each other. 
Maybe enable to view them in parallel.
-> enable to scale the visible hour-area. It would be perfect to view the hole day within the weekview without scrolling. 

General:
-> enable to assign an event to multiple calendars (calDAV) 
-> enable to select a color not only for different calendars but for every single event
-> when app ist starting the default color (orange) is shown in the top bar even when colors for icon and app are changed

**Comment by tibbi** [comment]
some of them are already reported, and create + issue per point. Thanks
