### ISSUE TITLE
Question:Is there currently any way to export events in any other format instead of ics?

### ISSUE THREAD

**Issue by Domino2017** [SimpleMobileTools/Simple-Calendar#786]
I'm looking into apps to make backups regularly and they all seem to only backup into xml files and read from xml files but SimpleCalendar only exports/imports into ics files,. If not, is there any way you could look into allowing the import/export to different formats? Or, if you know of an app that works with ics files so I can use that?

**Comment by tibbi** [comment]
you cannot export events in xml and dont really even expect having it anytime soon. Ics is the most widely used format for transferring events.

**Comment by Domino2017** [comment]
That's okay, just thought I'd ask. Do you happen to know of any apps that would import/read/export ics files? The one I ended up using (Super Backup) doesn't even acknowledge SimpleCalendar and when I asked its creators they told me it's because of the file type. It reads the phone's native calendar only (which does use xml as a format).

**Comment by tibbi** [comment]
not really, I wasnt even researching formats. The phones native calendar uses a database, using xml anywhere would be just ridiculous. I dont even like that format, it is just too verbose and hard to read/parse.

**Comment by Domino2017** [comment]
Okay, thanks for giving me an answer :)

**Comment by genodeftest** [comment]
With adb backup or the built-in android backup feature you can export the events as SQLite database. You'll need `adb backup` to get the backup (preferably only of the calendar app, ID is `com.simplemobiletools.calendar.pro`) and extract it with the backup extractor from https://github.com/nelenkov/android-backup-extractor. You'll find an `events.db` file somewhere in that backup.

**Comment by tibbi** [comment]
Ill close this as I dont plan supporting any other format. .ics is the standard for sharing events.
