### ISSUE TITLE
Swipe down syncing has a too high sensitivity

### ISSUE THREAD

**Issue by Skyrid3r** [SimpleMobileTools/Simple-Calendar#793]
First, wanted to say.. Love your app!

Without further ado, wanted to share that when you enable  swipe down syncing, it's sensitivity is way too high. Often when I attempt to swipe left or right to check other months, it often doesn't react as the swipe sync icon attempts to drop down for syncing. 

I'd assume it's swipe down reaction degree has to change so it's less sensitive? 

Small EDIT:
This seems to effect Simple Gallery as well.

**Comment by tibbi** [comment]
That is a system element, I cannot customize it. All apps have the same sensitivity. Thanks
