### ISSUE TITLE
Adding Birthday and holidays fail

### ISSUE THREAD

**Issue by NicoHood** [SimpleMobileTools/Simple-Calendar#795]
Since a few weeks adding birthdays from my contacts fail. Today I also tried the holidays option and it failed too for some reason. I normally do that update very frequently, as I constantly add new people to my (simple) contacts.

Is this a known issue or only applies to me!?

**Comment by tibbi** [comment]
Doesnt it fail just because there have been no new contact birthdays found? The error message might not be good enough. Try removing the Birthdays event type in Settings -> Manage event typey, then retry the importing.

**Comment by NicoHood** [comment]
Removing and readding worked. If I try to add them again it fails again. Before the overwriting worked perfectly.

**Comment by tibbi** [comment]
so it is just the duplication prevention. I will try tweaking the error message, but that should already be reported somewhere.
