### ISSUE TITLE
Can't add events in weekly view by tapping on the hour slot

### ISSUE THREAD

**Issue by leafcutterant** [SimpleMobileTools/Simple-Calendar#796]
I'm on v6.3.0, but this was also present for me in an unknown number of preceding versions. It had been working sometime before a certain version.

Right now, when I tap, the orange highlight and the "+" char is displayed for a fraction of a second, but nothing happens.

**Comment by tibbi** [comment]
weird, so far nobody reported such issues. Update to 6.3.1, maybe something got improved. Also try swiping to a week where you dont have any events whatsoever.

**Comment by leafcutterant** [comment]
6.3.1 is not yet on F-droid. Also, I can't swipe to an empty week because I have recurring weekly events until forever, and I can't go too far into the past because that's only feasible by staying in daily view (if I go to e.g. 30 years back in the daily view, then switch to weekly view, it resets my position to the present).

**Comment by tibbi** [comment]
try just going to Menu -> Filter events by type and filter out every type, it is good enough. If you dont see the filtering button it means that you have only 1 type created, in that case go into the app settings -> Manage event types and just create a new empty type.

**Comment by leafcutterant** [comment]
I tried the way you described. Managed to create and "empty" week, but the  adding still won't work.
