### ISSUE TITLE
[Feature request] List contacts' adresses in event's location field

### ISSUE THREAD

**Issue by breversa** [SimpleMobileTools/Simple-Calendar#798]
Hi,

Once upon a time, I used a calendar that had a nifty feature :
In the "location" field of an event, I could type the name of a contact, and the app would list their adresses for me to choose.

It was very useful when being invitated at a friend's home, or to pick up someone at (their) work, etc. I'd love to see this feature in Simple Calendar. :-)

**Comment by tibbi** [comment]
that sounds weird, dont really expect having it
