### ISSUE TITLE
Notification behavior seems odd

### ISSUE THREAD

**Issue by evitalis** [SimpleMobileTools/Simple-Calendar#809]
When I get a notification for an upcoming event and swipe it away it then comes back a short while later even if the event passed. If I click on it I am taken to an edit page for said event. I would expect a way to simply dismiss the event without removing it from the calender, and thus losing historical data.

Is this something I am not doing correctly or the expected behavior of the application?

**Comment by tibbi** [comment]
definitely not expected. What app version and Android OS version do you have?

**Comment by evitalis** [comment]
SimpleCalendar Pro version 6.3.2
Android version 8.1.0

**Comment by tibbi** [comment]
hm, doesnt the notification come back because you open the event edit screen and confirm it with the Check mark?

**Comment by evitalis** [comment]
Sometimes I don't click the notification and just swipe it away so it comes back. But clicking the notification opening the edit screen may be what causes an issue.

**Comment by evitalis** [comment]
Meant to update this sooner but forgot. Still seeing the same issue. Not sure why the edit screen should pop up. For me it would make more sense to have a dedicated edit button on the notification, and/or a button to clear it. If edits are needed as the event is happening something else may be wrong.

**Comment by tibbi** [comment]
there is no View screen yet, just an edit one. So people might want to open it to see more info. Anyway still nobody else reported anything similar, might be some device specific glitch.

**Comment by evitalis** [comment]
@tibbi I haven't seen a release note fixing this but the issue seems to no longer be present for me. I will close this and reopen it if the issue occurs again. Thanks for the hard work on this.
