### ISSUE TITLE
[Feature request] Syncing with other calendars

### ISSUE THREAD

**Issue by cabaleiro** [SimpleMobileTools/Simple-Calendar#81]
I can certaintly say that this application has the potential to become one of the most powerful calendar applications. In my opinion, it lacks integration with other calendar services; importing a calendar from the GCalendar, exporting a calendar or an event... Even integration with OwnCloud.

Thank you for reading. I'm really interested in the simple application's project.

**Comment by tibbi** [comment]
it will be the best calendar out there :) Syncing is on the roadmap, but it might take more time. Anyway Ill close this issue, to keep all sync related discussion at #2
