### ISSUE TITLE
RFE: Option to remove current date from event list widget

### ISSUE THREAD

**Issue by kavol** [SimpleMobileTools/Simple-Calendar#810]
I've put the calendar widget on my front screen right below the clock. As the clock already displays current date, it is superfluous for the calendar widget to display the date too, and it could use the saved space to display more of events. While I can turn off displaying the date in the clock widget, it won't save me widget space - help to see more events at once - so a better option is to turn the date display off in the calendar widget.

Current:
```
March 12 2019 (Tuesday)           +
March 12 (Tue)
| 18:00 volejbal
| 19:00

March 13 (Wed)
```

Desired:
```
March 12 (Tue)
| 18:00 volejbal
| 19:00

March 13 (Wed)
| 16:30 Letokroužek
```

p.s. Yes, I've intentionally removed also "+" in the example, as I can live also without this event adding shortcut, I can do the extra click after opening the calendar.

**Comment by tibbi** [comment]
some UI changes will be added in 6.16.0, but removing the current date isnt really planned
