### ISSUE TITLE
No option to remove holidays

### ISSUE THREAD

**Issue by AkashPratik** [SimpleMobileTools/Simple-Calendar#813]
There is no option to delete the holidays of a country if added accidentally.

**Comment by tibbi** [comment]
just remove the Holidays event type in the app settings -> manage event types

**Comment by AkashPratik** [comment]
But that would also hide the holidays from the country we originally wanted to see (the one not added accidentally).

**Comment by tibbi** [comment]
ye, you cannot delete them separately, just events one by one. The simplest solution is deleting them all, then readding the proper country. It should be pretty fast.
