### ISSUE TITLE
German translation issue, several different app names 

### ISSUE THREAD

**Issue by michaelof** [SimpleMobileTools/Simple-Calendar#816]
Not sure if all contributors will get notified about this issue, but I'll give it a try.

I'm a little confused about the different names ALL Simple Mobile Tools apps are getting when installed on a device with German language settings.

E.g. Simple Calendar:
- is offered in Google Play Store as "Einfacher Kalender"
- is offered in F-Droid as "Simple Calendar"
- is installed finally as "Kalender"

IMHO this is confusing, esp. it was during the phase of switching to the pro apps!

My idea: What about taking "Simple Calendar" as Tibors designated "product name", NOT to be translated (anymore)? Ditto for all other app, like "Simple Contacts" etc.

No one would ever have thought about translating "Microsoft Word" into "Microsoft Wort" :-)

I didn't want to make this change on my own, directly with a pull request, to get this discussed with the relevant audience.

**Comment by tibbi** [comment]
app names should be translated. "Microsoft" obviously cannot be, it is a brand name. F-droid doesnt really support translations, at least Im not aware of it.

**Comment by michaelof** [comment]
Ok, if this is your wish, your apps :-)

But why two different translated names, Play Store name and final installed name? Couldn't at least they are going to be harmonized?

**Comment by tibbi** [comment]
Apps like "Gallery" for google play are too generic. Launcher icons initially used to have names like "Simple Gallery" but many people have multiple apps installed and that bunch of orange icons looked weird.
