### ISSUE TITLE
CalDav sync broke with latest version - IllegalStateException: Name must not be null

### ISSUE THREAD

**Issue by rndmh3ro** [SimpleMobileTools/Simple-Calendar#823]
I use the calendar with CalDAV-Sync to sync my calendar. With the latest update, the sync stopped working, my calendar entries disappeared. However only the entries synced from caldav.

When I try to sync from within the app, I get a Java exception:

```
IllegalStateException: Name must not be null
```

It was working fine with the old version.

BTW your apps are great!

**Comment by tibbi** [comment]
try inserting some attendees, does it work? Are you syncing via Google, or what service?

**Comment by rndmh3ro** [comment]
I am using nextcloud as a caldav service. When I insert an attendee in the meeting in nextcloud, syncing to the calendar still does not work, throwing the same exception.

 However I just noticed that other meetings still sync so it must be one particular meeting that causes this issue. Now to find out which one...

**Comment by dohseven** [comment]
I have the same issue when syncing with Nextcloud. I tried to retrieve logs with `adb logcat`, but I don't see the `Name must not be null` exception.

The only exception I see in the logs is the following, not sure if this is the same or if it is related:
```
E/DatabaseUtils(18807): Writing exception to parcel
E/DatabaseUtils(18807): java.lang.IllegalArgumentException: Color type: 0 and index -1 does not exist for account.
E/DatabaseUtils(18807): 	at com.android.providers.calendar.CalendarProvider2.verifyColorExists(CalendarProvider2.java:4637)
E/DatabaseUtils(18807): 	at com.android.providers.calendar.CalendarProvider2.updateInTransaction(CalendarProvider2.java:4407)
E/DatabaseUtils(18807): 	at com.android.providers.calendar.SQLiteContentProvider.update(SQLiteContentProvider.java:153)
E/DatabaseUtils(18807): 	at android.content.ContentProvider$Transport.update(ContentProvider.java:334)
E/DatabaseUtils(18807): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:222)
E/DatabaseUtils(18807): 	at android.os.Binder.execTransact(Binder.java:446)
```

Feel free to ask if you need more information or more tests. Thanks!

**Comment by tibbi** [comment]
okay, I think I know where is the issue. Can you maybe try this version? To install the test version just allow installing apps from unknown sources in the security settings of your device. Once you download the file on your device just remove the .zip extension and run it, it should be straightforward. If it won't work, try uninstalling your current version first. Thanks
[calendar-release.apk.zip](https://github.com/SimpleMobileTools/Simple-Calendar/files/2998413/calendar-release.apk.zip)

**Comment by rndmh3ro** [comment]
With this version it is working again! Thanks for your fast support!

**Comment by tibbi** [comment]
Alright cool. I will release a new fixed version today. Thanks

**Comment by dohseven** [comment]
Thanks @tibbi for the incredibly fast support!
