### ISSUE TITLE
Missing event and error message after last update 

### ISSUE THREAD

**Issue by datn** [SimpleMobileTools/Simple-Calendar#828]
Upon upgrading to 6.4.0, an event on my calendar for today, which i can see in the web view of my online CalDav-compatible calendar in NextCloud and which Simple Calendar has been showing me for days, is no longer visible. In addition, the following error message pops up sometimes: 

'An error occurred: java.lang.illegalStateException: name must not be null'

**Comment by tibbi** [comment]
hey, it has already been fixed, a new version will start rolling out soon. Thanks

**Comment by datn** [comment]
I didn't see the existing issue. Thank you!

**Comment by tibbi** [comment]
ye it was actually already closed by the time you created this one, as I was creating the release :)
