### ISSUE TITLE
More than three notification events

### ISSUE THREAD

**Issue by tgc12** [SimpleMobileTools/Simple-Calendar#841]
When creating a new event or opening a synced one, I can only see/add three notification/reminders at most.

I'm currently using Simple Calendar Pro 6.4.1 from F-Droid

**Comment by legendofa** [comment]
It would be helpful if there are also more default options. One day reminders are pretty standard.

**Comment by tibbi** [comment]
you can already set default reminders in the app settings, just disable the "Use the last events' reminders as the default for new events" option.

**Comment by dumblob** [comment]
This does not seem to be an issue any more. Please check if it works for you now :wink:. If so, feel free to close this issue.
