### ISSUE TITLE
Slightly rounded corners instead oft sharp edges

### ISSUE THREAD

**Issue by daehruoydeef** [SimpleMobileTools/Simple-Calendar#843]
Would be really nice if the event inside the calendar would get slightly rounded corners instead of this sharp edges. This would go way better with the new Android Design and would look cleaner and more modern.

**Comment by rjain90** [comment]
Hi, Can I work on this?

**Comment by tibbi** [comment]
sure

**Comment by rjain90** [comment]
Fixed in #884
