### ISSUE TITLE
Make it clear that exported events are for the selected month

### ISSUE THREAD

**Issue by davidhedlund** [SimpleMobileTools/Simple-Calendar#845]
The menu bar gave me the impression that all events (for all years, or a whole calendar) should be exported
> Export events to an .ics file

I suggest that you make it more clear that only events for the selected month (I get the same result in both monthly view and yearly view) will be exported by adding the name of the month to the menu text like this:
> Export April events to an .ics file

**Comment by tibbi** [comment]
that is not the expected behaviour. By default all future events should be exported, or if you toggle the "Export past events" at the exporting dialog, then past events should be there too. Can you reproduce the issue reliably by creating a single-occurrence event in the next month? What app version do you have?

**Comment by davidhedlund** [comment]
> if you toggle the "Export past events" at the exporting dialog

Can you please give exact instructions how to find it.

**Comment by tibbi** [comment]
well after you select a folder for exporting, there is a dialog where you can customize the filename. The check is right under it. What app version are you using?

**Comment by davidhedlund** [comment]
> well after you select a folder for exporting, there is a dialog where you can customize the filename. The check is right under it.

Thanks!

> What app version are you using?

6.4.2


The generated filename title:
> Events_2019-04-10_09-56

I suggest that you add the end date/time to the filename as well like this:
> Events_2019-04-10_09-56-2019-04-30_13-30

**Comment by tibbi** [comment]
I dont want to complicate it in such a ridiculous way. Closing this, as exporting of the events doesnt export the current month only.
