### ISSUE TITLE
Default Reminders

### ISSUE THREAD

**Issue by Biepa** [SimpleMobileTools/Simple-Calendar#853]
Hey,
as already mentioned in #449 i also would like to set at least two default reminders.
Is it possible to implement.

I'm moving away from google calender an sync my own via dav and this is the only setting I'm missing.

Thanks for Simple-Calendar

**Comment by tibbi** [comment]
Hey, you can already do that in the Pro version by unchecking the "Use the last events reminders as the default for new events" and selecting some default reminders there.

**Comment by Biepa** [comment]
Cool. 
Is there a way to pay for the pro version without Google Play?

**Comment by Biepa** [comment]
Sorry. Got a little confused with "pro" "no pro" "google play" and "fdroid".
Already having this version installed via fdroid. Thanks a lot. Donation on the way :+1:
