### ISSUE TITLE
Cannot see any event from local calendar

### ISSUE THREAD

**Issue by OhSoGood** [SimpleMobileTools/Simple-Calendar#854]
Hi,
I must be missing something... I get my PC's calendar synced with my android's local calendar (with myphoneexplorer). In the default calendar app on my android (Pie on a S7, if that matters), I see all events. But when I open SimpleCalendar Pro 6.4.2, I see nothing. I then enabled CalDav sync in the settings, selecting the internal calendar, but then when I click "Refresh CalDav calendars" in the main menu, the popup "Refreshing..." appears and no event is shown. If I swipe downward, the refresh 'icon' rolls for ever (until I kill the app) and no event is shown neither.

Is that a bug, or am I missing something? Any idea?

**Comment by tibbi** [comment]
Do you see any new event types created in the app settings -> manage event types? Dont you maybe have a huge amount of events, so it just stucks, or takes long? Have you tested the event visibility in some downloaded calendar app? Stock apps often work differently than the downloaded ones, as they have more permissions.

**Comment by OhSoGood** [comment]
Well, I forgot there was the magical esoteric black-magic way of solving things: clear cache & Dalvik. Just did it, and synchro went fine.
Thanks for the quick answer anyway, and even more for your time & effort on that nice app.
