### ISSUE TITLE
"Unmute" (suggested feature)

### ISSUE THREAD

**Issue by davidhedlund** [SimpleMobileTools/Simple-Calendar#856]
I suggest a new setting, "Unmute", plus a sub setting for it to customize the volume level.

Case scenario: Sometime I mute the volume on my smartphone during the day but forget about it when I go to sleep. I don't hear the alarm during the morning consequently because I forgot to raise the volume to maximum level or medium level if I sleep in the same room as other people.

**Comment by davidhedlund** [comment]
https://github.com/Etar-Group/Etar-Calendar/issues/487
https://github.com/httpdispatch/MissedNotificationsReminder/issues/27

**Comment by tibbi** [comment]
well that is a system feature, not related to the calendar at all

**Comment by davidhedlund** [comment]
I accept you decision.
