### ISSUE TITLE
Synchronisation not working at all

### ISSUE THREAD

**Issue by NicoHood** [SimpleMobileTools/Simple-Calendar#857]
Since some weeks the caldav synchronisation is not working anymore. The events from the PC are not transmitted to the Phone, and the phone events are not shown on the PC. There are no errors when synchronizing using davx5.

davx5 is also responsible for synchronizing my contacts on the same radicale server. Contact synchronisation works perfectly, which gives me the impression that something went wrong on the calendar app site.

Any Ideas how to debug this? v6.4.2 on android 9

**Comment by tibbi** [comment]
do you see the events in some other calendar mobile apps?

**Comment by NicoHood** [comment]
Yes, they appear on the google calendar app.

**Comment by NicoHood** [comment]
Any ideas?

**Comment by tibbi** [comment]
not sure, try creating some new calendar with like 1 event on your server, then selecting only that one at the Simple Calendar app settings -> Manage synced calendars item.

**Comment by NicoHood** [comment]
The newly added calendar on the same server works fine in both directions. All existing calendars do not work. Is there a way to reset the whole calendar on the server side, but keep the events from the phone? My phone has all important events, I dont want to lose them.

**Comment by tibbi** [comment]
if you see the important events in your phone, just use Menu -> Export events to an .ics file. Select the proper calendars and maybe also enable "Export past events". That way you will have an .ics file for backup, which wont be changed in any way.

**Comment by NicoHood** [comment]
Yes, I could solve it like this. Export, disable synchronisation in davx5, delete all events on pc, enable synchronization again and import the events from the file. All events are still there. Thanks!
