### ISSUE TITLE
Add categories, and colors for events

### ISSUE THREAD

**Issue by davidhedlund** [SimpleMobileTools/Simple-Calendar#859]
Lightning 6.2 (integrated in Thunderbird 60.0) will color indicate with 1) Calendar color 2) Category (optional) colors:

![Screenshot at 2019-04-14 13:08:53](https://user-images.githubusercontent.com/6416073/56091982-77e3fe00-5eb6-11e9-8ae2-83663d84d533.png)

Here's the data:

<table>
  <tr>
    <td><strong>Category</strong></td>
    <td><strong>Hex triplet color</strong></td>
  </tr>
  <tr>
    <td>Multiple Categories[1]</td>
    <td> 3366ff</td>
  </tr>
  <tr>
    <td>Anniversary</td>
    <td>333333</td>
  </tr>
  <tr>
    <td>Birthday</td>
    <td>996633</td>
  </tr>
  <tr>
    <td>Business</td>
    <td>ffffcc</td>
  </tr>
  <tr>
    <td>Calls</td>
    <td>99ff99</td>
  </tr>
  <tr>
    <td>Clients</td>
    <td>ff9900</td>
  </tr>
  <tr>
    <td>Competition</td>
    <td>cc9933</td>
  </tr>
  <tr>
    <td>Customer</td>
    <td>cccccc</td>
  </tr>
  <tr>
    <td>Favorites</td>
    <td>3366ff</td>
  </tr>
  <tr>
    <td>Follow up</td>
    <td>6600cc</td>
  </tr>
  <tr>
    <td>Gifts</td>
    <td>ff99ff</td>
  </tr>
  <tr>
    <td>Holidays</td>
    <td>663366</td>
  </tr>
  <tr>
    <td>Ideas</td>
    <td>003333</td>
  </tr>
  <tr>
    <td>Issues</td>
    <td>99ffff</td>
  </tr>
  <tr>
    <td>Meeting</td>
    <td>ffff66</td>
  </tr>
  <tr>
    <td>Miscellaneous</td>
    <td>ffcc00</td>
  </tr>
  <tr>
    <td>Personal</td>
    <td>003333</td>
  </tr>
  <tr>
    <td>Projects</td>
    <td>ffcc99</td>
  </tr>
  <tr>
    <td>Public Holiday</td>
    <td>ffcc66</td>
  </tr>
  <tr>
    <td>Status</td>
    <td>ffff33</td>
  </tr>
  <tr>
    <td>Suppliers</td>
    <td>000099</td>
  </tr>
  <tr>
    <td>Travel</td>
    <td>663300</td>
  </tr>
  <tr>
    <td>Vacation</td>
    <td>660000</td>
  </tr>
</table>

1: "Multiple Categories" are not found in Preferences -> Calendar -> Categories but will be added by adding an event with two or more Categories.

**Comment by davidhedlund** [comment]
https://github.com/Etar-Group/Etar-Calendar/issues/491

**Comment by tibbi** [comment]
I dont understand what are you trying to achieve here. Adding some premade categories? That wont happen.

**Comment by davidhedlund** [comment]
> Adding some premade categories?

Yes, premade color indication not premade text.

**Comment by tibbi** [comment]
I dont really plan adding such premade types to local events. I will see what is the situation at CalDAV synced event categories once I will be working on it, but that is already reported.

**Comment by davidhedlund** [comment]
Alright.

The table reported herein is useful, do you want me to merge it or references it to the CalDAV issue?

**Comment by tibbi** [comment]
That is used just at thunderbird, I dont want to copy it. Every calendar can have a different list of premade categories. Maybe it is possible to fetch them too, which would be a lot more flexible.

**Comment by davidhedlund** [comment]
> That is used just at thunderbird, I dont want to copy it. Every calendar can have a different list of premade categories. Maybe it is possible to fetch them too, which would be a lot more flexible.

I updated the screenshot to make it more clear.
