### ISSUE TITLE
bug: dates invisible when rescheduling event

### ISSUE THREAD

**Issue by gethob1** [SimpleMobileTools/Simple-Calendar#86]
It's just a white backdrop with only the current date showing.  I have to guess where the other dates are and find out by touching.  It doesn't matter that I specified black background with white text.  I get white background, white text.  Thanks kindly if you can fix.

**Comment by tibbi** [comment]
Are you on Android 7? That seems to have some dialog color issues in some cases.

**Comment by gethob1** [comment]
Using 6.0.1.  It was working before the latest update to Simple Calendar.

On January 9, 2017 7:43:01 AM CST, Tibor Kaputa <notifications@github.com> wrote:
>
>-----BEGIN PGP MESSAGE-----
>Version: CounterMailEngine v1.1
>
>hQIMA7siww+GXt8sAQ//ZGoObhfJvVJENofH87Ypj7J2Z1xSMJ1VB16y96Oiy0fZ
>gYOh6o3JQL+GeAb+nIYyL2Zmsa8pMmgkhPCalkpu9cBZkoVcEthmnKN9uE81JTxq
>N83EOmt0ccu1Eq5EfDHVI76wmlisZV8Fc2cjZSxSWH/qhqD9hrqGGMHC15Wl6H2M
>mrNgTAg8s9y+AKD8r8N7tiT+Ha3OdnjrRyiz3W93fZZZSDcqEUapiJHz1NzoMy5p
>5kMj4NjtmQqyi2pON6MRNzixiBDR8aXAtKZlMNKDNnhkobBv5g22QIpslIlhnw2w
>H2kxnApf41Ss42IHTZ0qrsaq6RqtaJcNjmqGMsq2MYPCgfK+UUiYtvzY/1CehII+
>e3kcs+i6pPZ30qn6jsYkNan8/xZTLMzx/CexZtsU0rD3iivILnP0+pN2sWIKo5MG
>YoCH1Yl95lesJHvRqMoTJ5oEIIF8UQmN4O2c6jVZ4ObVdt2I7qbhoDw/fBSFl11B
>aBZdY+MJxc4XWyhjehdiJsw9lUScQFo/SSPrgOR5lY8/Lnghy6Ka7eWZ7kfRjtFv
>nTR65zKO7H+uxl+hoV6+hyqK8gly05rxGjgKJHxOiZvxbhfuAOwVmfJH8aWBYXZO
>QbVyyqyPxjgUm0gvqGnahp9MoBytBRlVwsoLXNQkVH6ciRJ5Gxi+CtN5HB2/yerS
>wFMBgeCfGYu+jXLF7O2ZQ3RATJrve22yD20fz49Gm96qWvpDvVdcTinxwip5kXRX
>4ZyazvHlE74SYqTaazc8IgR4MOEAfEYKlGuKVyWauDJnoA89eIY9104kDTGPa1PQ
>bcEjRlCUrAlIyJcgPqDgU0X6JfuUSHt+QJ9m1fcb3w/cVIARIuFF90Kz9C/RveUE
>zdcAVVGiigkXIpJtmLcHQRwuNfPdE02M3rvF1s8lJia7bpRqBIUfCXAZXgS9PPcj
>qnpOnPrmCGx2NOEsLwgBODrtMcM4J7okrar57V/fsH8N5pkK08288QtxE8vM8NI9
>UdBiu2qrnHCfu83153q3v/MiFXyKUlXWuF7lbPuT/sgvJzplbg==
>=BQqs
>-----END PGP MESSAGE-----

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tibbi** [comment]
Hello, is it ok already? There have been quite a few customization changes recently.

**Comment by gethob1** [comment]
It's improving beautifully.  If you can make it so I can zoom in and out
of the weekly view, allowing me to see the days' events in more or less
detail per zoom level, that would take productivity to the next level! :)

The zoom would ideally be in both axes, so the grid and labels would
expand, contract, and move proportionally.  I wonder, can you achieve
control of the weekly view similar to google maps using existing code?
Just generate a custom vector-based map and pop it in?

Another helpful option would be auto-deleting events.  Events could be
set to delete so many DDD:HH:MM after the scheduled time elapsed.
Optional notification of deletion and optional subsequent prompt to
reschedule would be a huge plus too.

If that's too time-consuming I might donate to the project if that's
okay if you can give me some idea of the man-hours and expertise involved.

Thanks

On 01/24/2017 03:23 PM, Tibor Kaputa wrote:
> Hello, is it ok already? There have been quite a few customization
changes recently.
>

**Comment by tibbi** [comment]
Hah, please create separate issues per requests, so it can be tracked. Not sure about a map-like controlling, we will see in the future. Im already using pinch gestures at the gallery for changing column counts.

Auto-deleting events may not be added anytime soon as I dont think many people need it, and I dont want to bloat the app by features used by 1% of users.

I want to work on the most requested features, not the ones people pay me for, so you cannot buy features ;)

Anyway, if the reported bug has been fixed, please close the issue.

**Comment by tibbi** [comment]
event screen has been redesigned, should be better now
