### ISSUE TITLE
#393939 on #00000 is invisible

### ISSUE THREAD

**Issue by 532910** [SimpleMobileTools/Simple-Calendar#864]
![image](https://user-images.githubusercontent.com/14617699/56440977-065fe180-62f4-11e9-8ac8-dc263cda595c.png)

**Comment by tibbi** [comment]
well of course dark text on dark background is hard to see

**Comment by 532910** [comment]
Is it fixed?

**Comment by tibbi** [comment]
how could I fix it? If you set black background and dark event type, of course it is hard to read. Nothing to fix on my side.

**Comment by 532910** [comment]
I did not choose these colors! My setting is: `Background color`: #000000, `Text color`: #bebebe.

**Comment by 532910** [comment]
Even if I choose pure green #00FF00 as `Text color` I'll receive #004d00, whith is also invisible on black!
![image](https://user-images.githubusercontent.com/14617699/56456204-ad369300-6371-11e9-9da8-ce87fbdae8b5.png)

**Comment by 532910** [comment]
And if I choose white #FFFFFF as Text color I'll receive #4d4d4d, which has better visibility comparing #393939 in subject bit is also invisible on black!

![image](https://user-images.githubusercontent.com/14617699/56456248-3d74d800-6372-11e9-9f06-5b2de0fc04e0.png)

**Comment by tibbi** [comment]
aha, that is caused by past events being dimmed. Colors are taken from the given event type, not the text color from the app settings.

**Comment by 532910** [comment]
So you confirm the issue and fact it should be fixed?

**Comment by tibbi** [comment]
dimming in general will be rethought, not only this view
