### ISSUE TITLE
Holidays are manually added

### ISSUE THREAD

**Issue by nettnikl** [SimpleMobileTools/Simple-Calendar#866]
At the moment holidays are added to the apps assets - manually by the maintainer, if I see that correctly. I think that is not a core feature he should have to take care of. What's the reason a library, or an extra app is not used here?

**Comment by tibbi** [comment]
it is just an extra, people dont have to use it. The app is offline, so I cannot fetch holidays in any other way. Max if someone has them in Google Calendar and enabled CalDAV sync, he can get the holidays into the app.

**Comment by nettnikl** [comment]
I did not mean to add an online sync for holidays. I though of using Jollyday (under Apache) or similar.
