### ISSUE TITLE
Next day when default start time already passed

### ISSUE THREAD

**Issue by szpak** [SimpleMobileTools/Simple-Calendar#867]
A default start time is nice, however, it could be tuned up even more. If that time already passed the current day it (usually) makes no sense to propose the past date/time for a new event. Probably the best solution would be to propose that time, but an another day.

E.g. Default start time: 21:00, now: 20190426 - 22:30, proposed date/time for a new event should be: 20190427 - 21:00.

**Comment by tibbi** [comment]
that would be too confusing, I dont want to be too smart there

**Comment by szpak** [comment]
In that case, just set the next full hour (instead of a default one).
Keeping the past date doesn't have sense in most of the cases.

**Comment by szpak** [comment]
@tibbi What do you think about my last comment to put the next full hour instead of keeping a date in the past (if a default time already past)?

**Comment by tibbi** [comment]
you can just use the "Next full hour" for that. If a user explicitly sets a default time for starting an event, why on earth would I chang eit.

**Comment by szpak** [comment]
Because it is already in the past for that given day :). A default time is nice (let's say 5pm), but how often it is sensible to set 5pm of that day for the new event if it is already 7pm?

**Comment by tibbi** [comment]
I dont care how often does that make sense. If the user explicitly sets an event start time at 5 pm, it will start at 5 pm.

**Comment by szpak** [comment]
My original proposal was to keep 5pm, but switch to another day. Yes didn't like it. Another one was just to bump to the next full hour if set time is in the past. You rejected it as well.  Maybe I'm the only person who don't like see time proposals for new events in the past. In that case, let's keep it as is.

Btw, just an academic question, will you potentially be open to accept a PR adding a new option for "default start time" (next to "Next full hour" and "Other time") named: "Other time (or next full hour if in the past)" or just "Smart other time"?

**Comment by tibbi** [comment]
no, it isnt needed
