### ISSUE TITLE
"Refreshing Complete" message toast displayed twice.

### ISSUE THREAD

**Issue by KidusMT** [SimpleMobileTools/Simple-Calendar#869]
The toast message that displays after the completion of the refresh is twice. one after the other. It can be handled easily I guess. Just a point out on the app feature.

**Comment by KidusMT** [comment]
I think one of the toast for the message is from the **MainActivity** and the other from the **fragment**.

```
private fun calDAVChanged() {
        refreshViewPager()
        if (showCalDAVRefreshToast) {
            toast(R.string.refreshing_complete)
        }
        runOnUiThread {
            swipe_refresh_layout.isRefreshing = false
        }
    }
```

**Comment by tibbi** [comment]
what app version are you using?

**Comment by KidusMT** [comment]
![photo_2019-05-05_02-42-04](https://user-images.githubusercontent.com/18373774/57185989-82a31900-6edf-11e9-97e1-4285bc69048a.jpg)

I think -> V 4.2.1 from the about screen.

**Comment by tibbi** [comment]
omg, that is an ancient version. Upgrade to the latest one, ideally to the Pro one at https://play.google.com/store/apps/details?id=com.simplemobiletools.calendar.pro . Reopen if it is still broken.

**Comment by KidusMT** [comment]
I just installed V 6.5.0, which is the latest version, and there is no "Refresh CalDAV calendar" option in the menu popup at all on this version. which I think is fixed too.

**Comment by tibbi** [comment]
you have to enable "CalDAV sync" at the app settings first with some calendars, then it will appear. CalDAV is disabled by default.

**Comment by KidusMT** [comment]
This is working perfectly now. This issue is no longer in the latest version of the apk. 
Thanks!
