### ISSUE TITLE
bug: reminder goes off even if event set to 'off'

### ISSUE THREAD

**Issue by gethob1** [SimpleMobileTools/Simple-Calendar#87]
Since the latest update all my events trigger reminders.  My events are all set to off, and the default setting is also 'off'.  Thanks much if you can fix.

**Comment by tibbi** [comment]
I had to change something around the reminders which could break some cases, hopefully I wont have to do it again. Can you please try creating a new event, or going to an existing one, switch the reminder to At start, back to Off and save it, if it helps? thanks

**Comment by gethob1** [comment]
I tried your suggestions to no avail, the reminders go off in all cases.  I'm going to have to find a replacement app if it can't be fixed.  Bummer!

On January 9, 2017 7:42:32 AM CST, Tibor Kaputa <notifications@github.com> wrote:
>
>-----BEGIN PGP MESSAGE-----
>Version: CounterMailEngine v1.1
>
>hQIMA7siww+GXt8sAQ/9FgUfjPUZlcKldE6O/zCym88XZsRMq2s/aTfsz3BKao+S
>aBiCOGPfdxelf/BHWPTPLT+J7OibCDI56T74QhKYzg7IooLsytDatu9wJHt2Qu8Y
>k1Q6563n/JejU9HjXYHpgisbbk+TM0OsA0gPOmLm6vtCuPFf0ObAgUartH2WTEHx
>wk8lXMyyY8YXSoGkZS0A3zxYe7BJmlyrOJ5+1GnnCumKnLRtoDKhAH0MvfghOjvf
>kYxhI74DzCV33tq/bWzzocfe2mi1qVNtgxYxv9fQLwwKIKd/FGU7Bxo4PmFMGjn9
>fcMqWo+y7gpZYkBCPA52QVSFYKPmfrSDT9FZLRvJgJCYBAWeJUpVO2cXje72IDUc
>j8UqaxNCiMXwvqbvUOGIAGOI88EjE6kKctB3cPgwgaxLhUCS3RFKiOQhOEKbRIlk
>1Tb0R1w2bKNKmkUGKKsjfV8bxYD+Hx8b9Y+P/3YXL4g7q8NOIDqft0ZsEtZ4u3Ds
>oK6w8J9HShydDfu1KdUm7nt/SaxCT87ABU6pEipT+kfdw8L7wToDHgJ9B9Q7y2UR
>POkGzdVMKjzYyELMxkWHXyc0l2/7vetfCtIN3JNsAjsOY3v8j6x3Wn165e0xkjuy
>NlyW/2pbO3GCz0ShvWDuQoYPQR9XRGXevhxTbWBi1DsbCpCVHTePmd3bZf0mMLHS
>wL4B6bmxgwufQQm6EqZR7hSGPzsK55PhURN8I/h4HwYEyzBFBGSY5kUoDiR3av7r
>7+GiNpa54jkqzhYKR+41D8ci0m31Zif5z4l6E3XRFVPc2oCNj9xnP5lWHY7L4ohX
>/xlN0kXp2Em2yLuqu2oVbMbWM8yIquvytKzTRq3FzKYQg2b14MtxqTuynf5cLETk
>QpBhh/mGOHR4hC4v/TG7pmjQwTeGABuBVtx8VlpxJQ2BfdWqfE2n2ZKukIPEI3sO
>yreac3nJGIBG1eXuM55JZP8mjiiqezeKYLSNlIlxqgSXt9WB7AKqmoaLD57usTv5
>nyTmlNA+0J/27iH5IdqRh3sxq1buViSxP43Tu1KUhBvR9bZXxiwcRhJuICNqncBj
>+jxUjSwXXNXpKjSy3GhGXrh1MIeIgMkvvKECTmCcVyfa6z4D4sxFrU4sdWfxcktF
>+lotxZ1MedRdwejsJB2fsd8tOYlVjoaNqNOE+Jqt2xKtOsjHUjvsa6Vgr3bS93ju
>=igZw
>-----END PGP MESSAGE-----

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tibbi** [comment]
should not be happening anymore
