### ISSUE TITLE
"Go to now/today" button/link in simple event list

### ISSUE THREAD

**Issue by szpak** [SimpleMobileTools/Simple-Calendar#889]
I'm occasionally looking into the future tasks (or maybe the past events) on the list and then I need to scroll back to "now". It's especially important on the "Simple event list" view, but not only.  
There could a new "button" in the top bar or just a double tap on the "Calendar" text in that bar would be sufficient (assuming people know about that :) ).

**Comment by szpak** [comment]
After upgrade to Android 9/10 the application being in the "Simple event list" accidentally scrolled up to the first (past) event on the list. In my case a few months ago. I had to scroll manually to today which is somehow tedious and having a button/link to scroll to today would make it easier.
I don't know how to reproduce the issue with unintended scrolling to the first element, but it happened a few times in 2 weeks. I didn't observe that with Android 5.1 before.

**Comment by tibbi** [comment]
what app version are you using?

**Comment by szpak** [comment]
The latest from Play store - 6.6.1.

**Comment by lriesebos** [comment]
I would like to note that this issue still persists. When using the "simple event list" view and scrolling to the future or past, the "change view" button does not change to the "go to today" button. Other views do support this feature and it would be great if the "simple event list" view would also have it!

Using version 6.8.3 and android 10.

**Comment by szpak** [comment]
Thanks!
