### ISSUE TITLE
Add yourself as an attendee

### ISSUE THREAD

**Issue by virhonestum** [SimpleMobileTools/Simple-Calendar#891]
Hey,
it would be great if you could easily add yourself as an attendee. More specifically, be able to quickly select whether you are going or not. For now you have to manually add your own email address as an attendee, then save, open the event again and select your going status. You also have to enter your full email address, since the contact suggestion unfortunately does not suggest the data saved in the 'my info' section from the contacts app.

Thanks!

**Comment by tibbi** [comment]
attendees are shown only if you are inviting someone other than yourself. If you arent going the event will disappear anyway, so for now I dont want to add anything extra there.
