### ISSUE TITLE
Check missing reminders when event is imported from an .ics file

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Calendar#892]
sample data at email from Tony on 15th may

**Comment by vn971** [comment]
Yes! When you export events from Simple Calendar and then import them on another device, all reminders get lost. It's very painful because there's no list of all events as well. I have to go through all the days or smth like that. Not sure yet how I would fix it locally.

**Comment by vn971** [comment]
Didn't open any issues in this repo though, so just want to mention -- big thanks for the project(s)! Using them in F-Droid for some time. Want to donate some BTC-s (well, satoshi-s) in a few weeks as well.

**Comment by tibbi** [comment]
sample email sent by Tony on 28th July
