### ISSUE TITLE
App not registered for .ICS files

### ISSUE THREAD

**Issue by svenb1234** [SimpleMobileTools/Simple-Calendar#893]
When I import .ICS files from within the app it works perfectly. However, if I want to open an .ICS file directly from the Downloads folder, android tells me that it cannot open the file.

Expected behaviour would be that simple calendar is offered as app to open the .ICS file.

**Comment by tibbi** [comment]
it works fine to me, what app version and android OS version do you have?

**Comment by svenb1234** [comment]
App v 6.5.0 on lineageos 15.1 for Nexus 5x. Simple calendar was installed via fdroid.

**Comment by svenb1234** [comment]
Found a way to reproduce.

Opening the ICS file directly from the email (Gmail app) only works with the Google calendar app. If only simple calendar is installed, a black screen opens and states that a preview cannot be opened.

If one downloads the ICS file and tries to open it by clicking on the download notification in the notification bar it does not work either.

Opening the lineageos default file app, a downloads section is shown. From there it does not work either. The notification shows "file cannot be opened".

If one selects the SD card or internal storage in the same files app, the file can be opened with simple calendar.

So there seem to be differences between how one opens the same file.


![Screenshot_20190530-071227-01](https://user-images.githubusercontent.com/46424536/58611644-1cc46a00-82b0-11e9-8e80-736d5092d915.jpeg)
![Screenshot_20190530-071148-01](https://user-images.githubusercontent.com/46424536/58611645-1cc46a00-82b0-11e9-80b5-5cd696185aea.jpeg)
![Screenshot_20190530-071543-01](https://user-images.githubusercontent.com/46424536/58611646-1cc46a00-82b0-11e9-9f32-1f972a0a3593.jpeg)
![Screenshot_20190530-071433-01](https://user-images.githubusercontent.com/46424536/58611647-1d5d0080-82b0-11e9-96af-6cdd8e7fb6b0.jpeg)
![Screenshot_20190530-071130-01](https://user-images.githubusercontent.com/46424536/58611648-1d5d0080-82b0-11e9-9fd9-b02cccfe6941.jpeg)
![Screenshot_20190530-071512-01](https://user-images.githubusercontent.com/46424536/58611649-1d5d0080-82b0-11e9-8119-b1701f025a21.jpeg)
![Screenshot_20190530-071533-01](https://user-images.githubusercontent.com/46424536/58611650-1d5d0080-82b0-11e9-937e-98db08db1bc2.jpeg)
![Screenshot_20190530-071449-01](https://user-images.githubusercontent.com/46424536/58611651-1df59700-82b0-11e9-8264-3c5a807c3f22.jpeg)
![Screenshot_20190530-071522-01](https://user-images.githubusercontent.com/46424536/58611652-1df59700-82b0-11e9-9fd0-cead25ac9580.jpeg)
