### ISSUE TITLE
[Feature] Handle some Calendar intents

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Calendar#9]
Samples at https://android.googlesource.com/platform/packages/apps/Calendar/+/master/AndroidManifest.xml

**Comment by tibbi** [comment]
sample app for "Add to calendar" button https://play.google.com/store/apps/details?id=com.mobilebizco.atworkseries.professional

**Comment by kscz** [comment]
Anything I can do to push this a bit ahead in the feature schedule?  This is basically the only feature which is missing for my general use when I don't have Google Calendar installed (I can't generate "reminders" from other apps)

**Comment by tibbi** [comment]
Im not sure how should it actually work, I will take a look at it someday. Might take a couple more weeks before it is implemented and published. Could you give more info from what app, or how do you plan using it? Thanks

**Comment by tibbi** [comment]
check if it fixes "Calendar Widget" (email from 27.9)

**Comment by kscz** [comment]
Sorry for the delay, the app I currently use is the Oneplus "shelf" app, where you can make memos and then set reminders for those memos.  When I pick a date and a time, the error I get is "No Calendars Found"

"Mincal widget" (in F-droid) also fails to load when I place it on the screen.

**Comment by tibbi** [comment]
I added some intent handling, not sure about the Shelf usecase. Is it downloadable from playstore? Do you have any other app that should open the calendar? Thanks
