### ISSUE TITLE
Auto refresh to add Phone contacts Birthday and Anniversary

### ISSUE THREAD

**Issue by s0uthk1ng** [SimpleMobileTools/Simple-Calendar#906]
I do not see any option to auto sync my phone contact's Birthday and Anniversary. Every time i update or add a contacts birthday i have to manual click on "Add contact birthdays/anniversaries".

**Comment by thenktor** [comment]
Just wanted to add the same feature request.

**Comment by tibbi** [comment]
will be added in 6.16.0
