### ISSUE TITLE
cannot delete last few repetitions of an event

### ISSUE THREAD

**Issue by TjrGithub** [SimpleMobileTools/Simple-Calendar#908]
The last few appointments of a regularly recurring appointment cannot be deleted on the Android device. After synchronizing, the deletion is undone again.
This occurs with Mailbox.org  and DavX5. I've also reported the bug with mailbox.org at https://help.mailbox.org/servicedesk/customer/portal/15/MAILBOX-10046 because I cannot find out who can fix it.

    Steps to reproduce:

        Set up Android device with lineageos 15.1 and davx5 and simple mobile calendar (apps from Fdroid, all current version)
        Set up a recurring weekly event that ends after 25 times
        sync
        wait a few weeks, so that there are only some repetitions in the future
        on the Android erase today's and all future events
        synchronize and use for a few days, i.e. sync other changes as well
        Check on Android and Webclient, when the next repeat date is

    Expected result:
    The deleted event should actually no longer occur on both clients.

    Actual result:
    Both clients behave as if it had never been deleted.

Translated with www.DeepL.com/Translator

**Comment by tibbi** [comment]
should be ok already
