### ISSUE TITLE
feature request: busy / free events

### ISSUE THREAD

**Issue by TjrGithub** [SimpleMobileTools/Simple-Calendar#909]
Hi, would you please implement blocking and non-blocking events? Thunderbird/Lightning Calendar calls this show time as available / occupied (translated from German). Outlook calls this Show calendar as busy, free, tentative, and out of office. Icalendar calls this Free/busy time (VFREEBUSY).

The use case is "deliveries can be picked up from 4 to 7" or "daycare is closed" etc. This kind of thing doesn't block other commitments, but needs to be taken into account.

Feature request #808 is slightly different: ical status property tentative means that I don't know for sure yet if the event will take place. But busy/free means if I can have concurrent events.

**Comment by madb1lly** [comment]
Hi @tibbi,

This is an important distinction which I would find useful and is one of the reasons that I'm not using this calendar app atm but am using another FLOSS app instead.

Cheers 🙂

**Comment by romor** [comment]
> Icalendar calls this Free/busy time (VFREEBUSY).

@TjrGithub, are you sure?
I wonder if this is covered by `X-MICROSOFT-CDO-BUSYSTATUS` instead?
Also refer to the discussion here in [StackOverflow](https://stackoverflow.com/questions/798016/vcalendar-show-as-free-busy-tentative-out-of-office).

I am also missing this feature a lot. @tibbi, would you accept a pull request for this?

**Comment by tibbi** [comment]
not sure, seems too advanced for most users. The proper tag definitely isnt X-MICROSOFT-CDO-BUSYSTATUS though, it seems something Microsoft specific

**Comment by romor** [comment]
> seems too advanced for most users. 

It depends. If you use the calendar for business purposes you definitely need this and #1022. It is daily business to query the calendars of colleagues to schedule cooperate meetings and this gives the basic information needed.

If you use this app only for personal/private purposes, these features are not very relevant.

> The proper tag definitely isnt X-MICROSOFT-CDO-BUSYSTATUS though, it seems something Microsoft specific

Yes, this is Microsoft specific, but I think Microsoft set an industry standard here as iCalendar allows such extensions...

**Comment by TjrGithub** [comment]
Thunderbird/Lightning Calendar, Microsoft Outlook Calendar, Apple Calendar, Mailbox.org Webinterface calendar -- they all have this feature, and I miss it all the time.

A typical usage case would be events that I can but not need not participate in; time windows where something works (e.g. call me today); all-day events (cancel Comcast today, sometime); taxes are due today, etc.

**Comment by yue-dongchen** [comment]
I came back to revisit this issue. Below is an example of handling free / busy events by the Nextcloud web calendar client:

```
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//SabreDAV//SabreDAV//EN
X-WR-CALNAME:Example
X-APPLE-CALENDAR-COLOR:#BC5C91
REFRESH-INTERVAL;VALUE=DURATION:PT4H
X-PUBLISHED-TTL:PT4H
BEGIN:VTIMEZONE
TZID:Australia/Sydney
BEGIN:STANDARD
TZOFFSETFROM:+1100
TZOFFSETTO:+1000
TZNAME:AEST
DTSTART:19700405T030000
RRULE:FREQ=YEARLY;BYMONTH=4;BYDAY=1SU
END:STANDARD
BEGIN:DAYLIGHT
TZOFFSETFROM:+1000
TZOFFSETTO:+1100
TZNAME:AEDT
DTSTART:19701004T020000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=1SU
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20210429T093608Z
DTSTAMP:20210429T093623Z
LAST-MODIFIED:20210429T093623Z
SEQUENCE:2
UID:ba14c7c8-f5c9-4ccf-abd6-596932952f0b
DTSTART;TZID=Australia/Sydney:20210501T091500
DTEND;TZID=Australia/Sydney:20210501T093000
SUMMARY:Busy event
END:VEVENT
BEGIN:VEVENT
CREATED:20210429T093627Z
DTSTAMP:20210429T093636Z
LAST-MODIFIED:20210429T093636Z
SEQUENCE:2
UID:15911e7a-d638-47d9-b76f-648a80acba8f
DTSTART;TZID=Australia/Sydney:20210501T100000
DTEND;TZID=Australia/Sydney:20210501T104500
SUMMARY:Free event
TRANSP:TRANSPARENT
END:VEVENT
END:VCALENDAR
```

Notice the `TRANSP: TRANSPARENT` parameter in the free event. This is defined as a **standard parameter** in [RFC 5545 3.8.2.7](https://tools.ietf.org/html/rfc5545#section-3.8.2.7). Unlike `FREEBUSY` (which [doesn't have a set of established standard values](https://tools.ietf.org/html/rfc5545#section-3.8.2.6)), `TRANSP` _[defines whether or not an event is
      transparent to busy time searches](https://tools.ietf.org/html/rfc5545#section-3.8.2.7)_. 

Values:

- `TRANSP: OPAQUE` - opaque on busy time searches (i.e. "busy")
- `TRANSP: TRANSPARENT` - transparent on busy time searches (i.e. "free")

![Busy event](https://thedreamsky.site/index.php/apps/files_sharing/publicpreview/DntzsbozKFfsc9D?x=2880&y=1088&a=true&file=Screenshot_20210429_200736.png&scalingup=0)
![Free event](https://thedreamsky.site/index.php/apps/files_sharing/publicpreview/7KKKaka3W97fKmx?x=2880&y=1088&a=true&file=Screenshot_20210429_201143.png&scalingup=0)

This corresponds to the use cases that this issue's initiator and I have mentioned

> The use case is "deliveries can be picked up from 4 to 7" or "daycare is closed" etc. This kind of thing doesn't block other commitments, but needs to be taken into account.

> There are personal uses. For example, Android has the option to activate "do not disturb" on busy events.

I've tested the `TRANSP` property by syncing a calendar created via the Nextcloud web interface onto my Android phone with DAVx⁵. The "do not disturb" on busy events functionality works as expected.

@tibbi If you're convinced of this being a standard parameter, would you consider accepting pull requests?

**Comment by yue-dongchen** [comment]
@tibbi Would you accept such a pull request?

**Comment by tibbi** [comment]
I wasnt researching it, so not sure how it works. Guess you can add it, but obviously visible to CalDAV synced events only.

**Comment by yue-dongchen** [comment]
I'm implementing it now. Should be ready within the next few days

**Comment by tibbi** [comment]
has been added already
