### ISSUE TITLE
Error when importing event email attachments (ics)

### ISSUE THREAD

**Issue by virhonestum** [SimpleMobileTools/Simple-Calendar#911]
When opening an event attached to an email (ics file) the event is imported successfully, however there is still a toast with an error message. It says 
```
org.joda.time.IllegalInstantException: Cannot parse "19810329020000": Illegal instant due to time zone offset transition
```
And then something in brackets I cant read since the toast notifying me of the successful import overlaps it.

Here is a sample (but anonymized) ics file where this happens:
[anonymized_event.zip](https://github.com/SimpleMobileTools/Simple-Calendar/files/3261395/anonymized_event.zip)

**Comment by tibbi** [comment]
where are you from? What timezone is it? What app version are you using?

**Comment by virhonestum** [comment]
Germany, so timezone Europe/Berlin and the app version is 6.5.0
