### ISSUE TITLE
Kotlin Error

### ISSUE THREAD

**Issue by Wadbox** [SimpleMobileTools/Simple-Calendar#912]
Hi good works,
I am Download from Github without making any changes upload android studio and 
I press Make Project button but build error kotlin compiler.

how can I solve this problem

![image](https://user-images.githubusercontent.com/50862272/59034649-1fa4f900-8874-11e9-9fd7-a2c1eefb9422.png)

**Comment by tibbi** [comment]
im not giving support for app building, it is something on your side
