### ISSUE TITLE
Problem of swiping right/left to next/previous month

### ISSUE THREAD

**Issue by delphinuz** [SimpleMobileTools/Simple-Calendar#914]
It's not easy to swipe left to next month. Swipe right also has the same issue, but better then swipe left.

**Comment by tibbi** [comment]
I dont understand why would it be hard. Do you have CalDAV sync with pull to refresh enabled?

**Comment by delphinuz** [comment]
Yes, pull to refresh is enabled. Everything works fine if pull to refresh turn off.

**Comment by tibbi** [comment]
it isnt an issue then, thats how system elements work. Try dragging your finger a bit upwards too, not just to the side.
