### ISSUE TITLE
Icon doesn't change (F-Droid)

### ISSUE THREAD

**Issue by floppyD** [SimpleMobileTools/Simple-Calendar#917]
I downloaded the F-Droid version of Simple-Calendar and set the theme to Black and White but the icon didn't change, even after restarting the launcher. Just to be sure I downloaded the Play Store version (latest free one) and did the same and the icon changed without any issues. I have both Simple Gallery and Simple Draw installed and I can change their icons just fine, so it's probably a Simple Draw issue.
![Screenshot_20190619-090335](https://user-images.githubusercontent.com/29208110/59764501-4864bf80-9272-11e9-8466-4d6c34e8ec66.png)

**Comment by tibbi** [comment]
I see a black calendar icon there. Icon glitches are usually launcher related, I just cannot support it better in the app.

**Comment by floppyD** [comment]
I should have worded better, but the black icon you see is the free Play Store version of Simple Calendar, and the orange one is the F-Droid version, both are using the black theme and are just there for comparison. The Play Store icon changes like every other Simple App I have installed, but the F-Droid version doesn't.

**Comment by tibbi** [comment]
both versions are the same, so it is some launcher glitch. Keep just one app, remove the second one.

**Comment by floppyD** [comment]
Is the current Calendar "dynamic" icon implementation the same as other Simple Apps like Gallery (F-Droid/Pro), Notes (F-droid/Pro) and Simple File Manager (F-Droid/Pro)? If it is this is indeed a weird launcher issue and I'll report to the developers. I'm asking because I remember having this issue with Gallery some time ago and you fixed it with an update.

**Comment by tibbi** [comment]
sure, the whole code is reused there between apps
