### ISSUE TITLE
Clicking the widget doesn't open the right view

### ISSUE THREAD

**Issue by Drhaal** [SimpleMobileTools/Simple-Calendar#920]
When clicking a day in the widget it always open the month view even when set to day view in options.
Version: 6.5.1 (latest on f-droid)

**Comment by tibbi** [comment]
if you exit the app with the back button instead of the home button, does it work better?

**Comment by Drhaal** [comment]
No still the same. 
It only happens with the montly view widget. Since the option for the widgets only talk about the list event widget it might be a normal beahaviour but it seems kinda counter-intuitive.

**Comment by tibbi** [comment]
well, actually even the settings option says "View to open from the event list widget", so it works as expected.
