### ISSUE TITLE
Current time not updating on week view

### ISSUE THREAD

**Issue by hjkl** [SimpleMobileTools/Simple-Calendar#931]
On the week view, sometimes the line showing the current time does not update. The only way I can move it forward is to kill and restart the app.

**Comment by hjkl** [comment]
It also appears to duplicate sometimes, please see below:

![Screenshot_20190709-090103_Calendar](https://user-images.githubusercontent.com/151291/60871632-0bfe0100-a22b-11e9-9428-42dcfb3d5228.png)

**Comment by tibbi** [comment]
what app version do you have?

**Comment by hjkl** [comment]
6.5.4 from fdroid.

**Comment by tibbi** [comment]
should be fixed in 6.5.5
