### ISSUE TITLE
Do you need help translating FAQ ?

### ISSUE THREAD

**Issue by gcoimbra** [SimpleMobileTools/Simple-Calendar#937]
https://github.com/SimpleMobileTools/Simple-Calendar/blob/84b73517f178b0775880ca4aa836a7f23794e7da/app/src/main/res/values-pt/strings.xml#L228

**Comment by tibbi** [comment]
sure, translating everything is needed. You can find the instructions at https://github.com/SimpleMobileTools/General-Discussion#how-can-i-suggest-an-edit-to-a-file . Thanks
