### ISSUE TITLE
Notifications/Events overriding Do not disturb

### ISSUE THREAD

**Issue by vaseer** [SimpleMobileTools/Simple-Calendar#939]
For some time now I have problem with Simple Calendar's notification overriding Do not disturb option.
Android: 9
Simple Calendar: 6.5.4

**Expected behavior:** When DND is turned ON, there should be NO sound (or vibration) from Calendar app.

**Observed behavior:** Calendar is overriding DND. It does not turn off or cancel DND, it just play notification sound.

Native (Google) Calendar app is working as described in Expected behavior.

I read somewhere that this (issue) is expected behavior. If so, can it be added to settings to manually choose if DND should be overridden or not?

**Comment by tibbi** [comment]
that has to be set at your device, not in the app. Try long pressing the notification which appears and go into its settings.
