### ISSUE TITLE
Notifications cannot be dismissed from lock screen

### ISSUE THREAD

**Issue by squatica** [SimpleMobileTools/Simple-Calendar#941]
Android 8.1.0
Calendar version 6.5.4

My lock screen is protected with password, but I assume it works the same with pin or gesture protection. When a calendar notification pops up while the screen is locked, the alarm sound continues indefinitely and clicking the lock screen notification only asks me for my unlock password while the sound is still ringing. The notification cannot be swiped away either. It only has a snooze button, but if I snooze it, it will just repeat the same situation later, no way to fully dismiss the snoozed alarm before it starts ringing again.

This is annoying for example when I forgot to switch my phone into silent mode before going to a theater or meeting. The alarm will be ringing all the time while I'm trying to unlock the screen, which now takes longer than normal because I make 20 typos due to the embarrassment.

There should be a way to at least mute the sound (vibration may go on) even from lock screen, either by swiping, or an on-screen button (not preferred) or a hardware button such as the screen lock (power) button.

Thanks for all your apps, great stuff. I wish I had more android programming skills to be able to help.

**Comment by tibbi** [comment]
I dont think it is an apps issue. Such notifications and lock screen related things are handled by the system.
