### ISSUE TITLE
How to imprt events from other calendars?

### ISSUE THREAD

**Issue by J0n1k4** [SimpleMobileTools/Simple-Calendar#942]
Hi,
I am in a process of ditching GApps and other phone maker's default apps.
I have significant amount of events in default calendar (that is set to be sync-ed with my Mi account).
I can't find a way to import the events in the Simple Calendar. 
Is there a way to do it, or I have to manually do it?
Thanks in advance, 
cheers,
Nenad
Xiaomi Redmi Note 3.
MIUI Global 10.2
Android 6.0.1

**Comment by tibbi** [comment]
try somehow exporting the events from the old calendar in an .ics file, then you can import it in Simple Calendar. The importing item is at Menu -> Import events from an .ics file.

**Comment by J0n1k4** [comment]
Hm.
I should have searched a bit more before I rouse the question.
Anyway - it might be a good info for others:

I used a iCal Import/Export CalDAV app to export the current (was current) calendar to .ICS file, and then imported it to Simple Calendar.
I encountered the error saying that all the events might not be imported, but I will look into it.

Cheers :)
