### ISSUE TITLE
Simple calendar, crash when clicking add event.

### ISSUE THREAD

**Issue by Xilnu** [SimpleMobileTools/Simple-Calendar#943]
Hello,
On Android, I installed Simple Calendar version 6.5.4 via F-Droid.
When I want to click Add or the + sign for new event, the app closes.
The calendar is open in the background.
I try again, the app crash all the time.
I have already emptied the cache, without success.
Clear all the cache and delete the app, then reinstalled, but still the same problem.
What should be done ?
Thanks for your help.

**Comment by tibbi** [comment]
do you already have any events in the app? Do you have CalDAV sync enabled, or are you storing the events locally only?

**Comment by Xilnu** [comment]
** - Do you already have events in the app?**
Yes, there are events. This is the second time I have this problem. Every time I have to reset my smartphone.
Then everything comes back normally.
 **- Is CalDAV synchronization enabled or do you store events locally only?**
I tested both. With or without CalDav, I had the same problem.
I do nothing special when that happens.
Sometimes for months, I have no problem.

**Comment by tibbi** [comment]
try updating to 6.5.6 whenever it becomes available, that is the latest one. Not sure now what is the issue, if it works just fine for months, then it crashes. Maybe it is some specific timezone/time related combination causing the issue.

**Comment by Xilnu** [comment]
Ok, thanks, I waiting of the last version.
What do you mean by: that is the last one?
Do you stop the development?

**Comment by tibbi** [comment]
I said the "latest" one, so the newest one..

**Comment by Xilnu** [comment]
Ah, Ok.
