### ISSUE TITLE
Exporting ics fails in Glide with setDataSource failed: status = 0x80000000

### ISSUE THREAD

**Issue by genodeftest** [SimpleMobileTools/Simple-Calendar#945]
I'm using Simple-Calendar in version 6.5.4 from F-Droid store on a stock Android 9 security patch level 2019-07 on a Nokia 5 device.

Whenever I try to export any calendar, it only generates an empty file although it finishes with "Export successful" or a similar message.

I've attached the relevant logs.
[calendar-export-glide.txt](https://github.com/SimpleMobileTools/Simple-Calendar/files/3438051/calendar-export-glide.txt)

This issue is known to glide: bumptech/glide#3345, bumptech/glide#980, bumptech/glide#2979, but they don't seem to be able to fix it, probably because it is not in their domain.

Would it be possible to exclude the images from the backup? Would it be possible to skip the image if it is not present? Why should an event even have an image?

**Comment by genodeftest** [comment]
It seems like the issue was caused by the fact that my Android device was connected to a computer. After detaching it, the export was successful.

Note: The skia error message is still present, but the Glide error message is now gone.

**Comment by mochadwi** [comment]
> It seems like the issue was caused by the fact that my Android device was connected to a computer. After detaching it, the export was successful.
> 
> Note: The skia error message is still present, but the Glide error message is now gone.

It seems due to corrupted file or incomplete file download, see [here](https://stackoverflow.com/a/45231625/3763032)
