### ISSUE TITLE
[Feature Request] .ics file import

### ISSUE THREAD

**Issue by d5ve** [SimpleMobileTools/Simple-Calendar#95]
I have an .ics file containing a work roster for the next year. Is there a way to import it into Simple Calendar without having to enter every thing manually? I can get the calendar file in other formats if needed.

Thanks.

Dave

**Comment by tibbi** [comment]
Hello, its currently not possible. There are some export and importing functions on the roadmap, but it might still take a couple weeks.

**Comment by tibbi** [comment]
should be implemented in the latest 2.1.3, check if it works

**Comment by d5ve** [comment]
Great, cheers @tibbi!

I'll test it out once the new version is on f-droid.

**Comment by d5ve** [comment]
I installed v2.1.3 and it works very well.
Thanks for you time on this @tibbi
