### ISSUE TITLE
Repeating events, deletions in between are handled wrong

### ISSUE THREAD

**Issue by michaelof** [SimpleMobileTools/Simple-Calendar#950]
Hi Tibor,

Simple-Calendar 6.5.6
Android 6.0
(Nextcloud current, DAVdroid current)

Some sort of never-ending story with these repeating events, seems to be bloody complex :)

- have an event with n repeats. Weekly at a specific date and time. Sports, for my son.
- delete specific recurrences, during summer school holidays. One after the other

Just recognized, that
- SimpleCalendar shows all repeats as I wants them, correct deletions
- Calendar Widget "Todo Agenda" from F-Droid still shows some "deleted" recurrences
- same "some" recurrences are shown in Google's Android Calendar
- and, brave to say, iOS shows the "some deleted" recurrences also
- Nextcloud itself, as single source of TrueType, does not show ANY deletions = still shows ALL recurrenced. But this is currently to be expected, NC says "repeating rule not supported yet"

FYI when I tap on one of these "deletions" in calendar widget "Todo Agenda" (not [!] SimpleCalendar's widget), Android asks in which app these event should be opened. Selecting SimpleCalendar opens the FIRST occurrence in this case, from 2018.

**Comment by tibbi** [comment]
well it works just fine to me, with Google Calendar. Sadly there are many ways such repetition exceptions can be done, not all services use the same way. Ill try reproducing some possible issues.

**Comment by michaelof** [comment]
Is there anything I can do/provide to make it easier for you, when narrowing down this bug?

FYI it might be, not sure to be honest, that not me, with my current SimpleCalendar, made the deletions. But maybe my wife, with her previous smartphone. Replaced in June this year, Android KitKat, that's why also SimpleCalender, but unfortunately in an old, outdated version

**Comment by tibbi** [comment]
not really, not sure how could you help now
