### ISSUE TITLE
CalDAV cannot be toggled on

### ISSUE THREAD

**Issue by ErinVoid** [SimpleMobileTools/Simple-Calendar#961]
Pro v6.5.7 on Android 9. All permissions on. Was working correctly, toggled CalDAV toggle in settings off in error, now can no longer toggle back on. 

Related to [#921](https://github.com/SimpleMobileTools/Simple-Calendar/issues/921)?

**Comment by tibbi** [comment]
what did the error message say?

**Comment by ErinVoid** [comment]
Thew error was mine, not the software. Think I may have found a cause outside of Simple-Calendar's control. Will confirm when I can get to the server so ignore for now.

**Comment by ErinVoid** [comment]
Delayed reply due to holidays. It was a user error with the Cloud.

However, it would be good if the CalDAV toggle gave some feedback as into why it won't toggle.
