### ISSUE TITLE
Make Daily View Geometric Like Weekly and Monthly

### ISSUE THREAD

**Issue by landry314** [SimpleMobileTools/Simple-Calendar#962]
I love this app, it is much better than the default android calendar app, but one thing I really miss is the way the daily view is geometric with boxes lined up on the times. Simple Calendar already does this in the weekly view but in the daily view it is just a list of events in chronological order. Can you add a feature to view the daily in list mode or in geometric mode? That would make me stick with this app. I am considering going back to the stock app just because of this :-( . I am a visual thinker and seeing the day geometrically really helps me.

**Comment by tibbi** [comment]
some UI changes will be added in 6.16.0. If you prefer the daily view, you can customize the weekly one to show 1 day only, it also has zooming now
