### ISSUE TITLE
Zooming weekly view feature request

### ISSUE THREAD

**Issue by gethob1** [SimpleMobileTools/Simple-Calendar#97]
If you can make it so I can zoom in and out
of the weekly view, allowing me to see the days' events in more or less detail per zoom level, that would take productivity to the next level!

The zoom would ideally be in both axes, so the grid and labels would expand, contract, and move proportionally.  I wonder, can you achieve
control of the weekly view similar to google maps using existing code?  Just generate a custom vector-based map and pop it in?

**Comment by gethob1** [comment]
And be able to pan the view of course.

**Comment by NotSoImportant** [comment]
My request goes into the same direction, therefore adding it here.
I would like to have a one or two weeks overview view. Means like the month view (without times beeing displayed), with a rectangle per event displaying the full title.
Example: https://ibin.co/3pHZlBMr9ypm.png

**Comment by tibbi** [comment]
vertical zoom will be added in 6.9.1. Horizontal will be solved in some different way, doing horizontal gestures is just weird :) You cannot even do it normally while holding the phone in your hand.
