### ISSUE TITLE
Swiping left/right aborts when dragging down

### ISSUE THREAD

**Issue by madduck** [SimpleMobileTools/Simple-Calendar#973]
Possibly this is what #914 was all about:

Unless I swipe exactly horizontally and instead slightly swerve down when e.g. trying to switch to the next day, the swipe is aborted, because the update-action on pull-down takes preference.

If the update is already running, the problem goes away.

If I disable pull-to-refresh, the problem goes away.

I think that pull-down should not be able to interrupt an existing pull-right/pull-left action.

![simple-calendar-swipe-bug](https://user-images.githubusercontent.com/195073/64392407-c5991700-d0a0-11e9-96d3-97a09121b355.gif)

**Comment by tibbi** [comment]
those are system elements, of course they cancel each other. Just disable pull to refresh, or swipe your finger a bit upwards too at swiping to sides.

**Comment by madduck** [comment]
Hm, no other software I know exhibits a similarly conflicting interaction. Sure, turning this off "fixes" it, and I respect that you don't want to do anything about it in the code.
