### ISSUE TITLE
Calendar events updated remotely often show up too late

### ISSUE THREAD

**Issue by madduck** [SimpleMobileTools/Simple-Calendar#974]
Unlike Etar, Simple-Calendar does not seem to pick up modifications DAVx5 downloads from the CalDAV resources. Often, new events or modifications don't show up until hours later, and the widget usually takes even longer.

I am unsure why Simple-Calendar has a setting "Sync CalDAV", and what "Refresh CalDAV calendars" does, especially since local, non-CalDAV calendars show up in the list of "Manage synced calendars", which only shows up if "Sync CalDAV" is true.

Is S-C trying to speak CalDAV on its own, bypassing DAVx5?

Furthermore, it doesn't seem that running a manual sync with DAVx5, and then hitting "refresh CalDAV calendars" does anything. Sometimes, modifications show up, but not reliably so.

Ideally, there'd be a hook such that S-C updates automatically when DAVx5 downloads modifications. Then we wouldn't need manual refresh either.

This should then also update the contents displayed in the widget.

**Comment by tibbi** [comment]
Simple Calendar displays only events already stored locally on the device, as it is an offline app it definitely has no CalDAV syncing on its own. What calendar app version do you have?

**Comment by madduck** [comment]
I was using 6.5.7, and I just updated to 6.6.0. Let's see if the problem persist. It's hard to reproduce…

If it only reads local calendars (some of which may be CalDAV, but not all), then why do the settings even mention CalDAV?

Apart from manual updates, when does S-C read the local calendars? Does it do so regularly on a schedule, like every hour?

**Comment by madduck** [comment]
Also, when/how do the events shown in the widget get updated?

**Comment by tibbi** [comment]
everytime some event gets added, or open the app. There is a background listener triggering at CalDAV updates, but it works from Android 7 only. What OS version do you have?

**Comment by tibbi** [comment]
should be improved in 6.7.0 released soon
