### ISSUE TITLE
Possibly wrong DTEND value für single-day event

### ISSUE THREAD

**Issue by ddast** [SimpleMobileTools/Simple-Calendar#976]
When creating an All-day event for a single day Simple Calendar (version 6.6.0) sets DTSTART and DTEND to the same value: 
```
DTSTART;VALUE=DATE:20191001
DTEND;VALUE=DATE:20191001
```

My desktop calendar program (khal) warns about these kinds of events:
> The event's end date property contains the same value as the start date, which is invalid as per RFC 5545. Khal will assume this is meant to be single-day event on 2019-10-01.

I guess this is correct since [RFC 5545](https://tools.ietf.org/html/rfc5545#section-3.8.2.2) states
> its [DTEND] value MUST be later in time than the value of the "DTSTART" property.

I also confirmed that the default AOSP calendar app would create a single-day event with the following values:
```
DTSTART;VALUE=DATE:20191001
DTEND;VALUE=DATE:20191002
```

**Comment by tibbi** [comment]
you mean at using the "Export events in an .ics file"? DTEND should be by a day more

**Comment by ddast** [comment]
When using "Export events to an .ics file" the DTEND is indeed one day after DTSTART.

However, when using a CalDAV calendar that is synchronized by DAVx5 to a Radicale server, the event that is created on the server has the same value for DTSTART and DTEND (checked by looking at the .ics file of Radicale). I was assuming that this is a problem with Simple Calendar since it does not occur with the AOSP calendar.

**Comment by tibbi** [comment]
well it works just fine in Google Calendar and NextCloud, so it might be glitchy on the Radicales side aswell. It seems like a quite deprecated project.
