### ISSUE TITLE
New all-day events synced with CalDAV are pushed to the next day

### ISSUE THREAD

**Issue by jlamoure** [SimpleMobileTools/Simple-Calendar#987]
Android 7.1.2
simple-calendar v. 6.6.1
CavDAV server Radicale 0.9

I'm in Central Standard Time (GMT-5?) new all-day events are one day late.

Steps to reproduce:
Create all-day event in simple-calendar, on a CalDAV calendar.
Event shows as correct day.
Refresh CalDAV with a swipe-down.
Event gets pushed one day into the future.
Editing the event to the correct day and then refreshing does stick, i.e., I'm not required to edit it and tell it to save as the day before to actually save it as the intended day.

If I create the event locally, there is no issue.

Seems related to #369, #246, #371, #374.

**Comment by tibbi** [comment]
should be fixed already, especially in 6.13.0
