### ISSUE TITLE
Request : timetable view mode

### ISSUE THREAD

**Issue by CloneMMDDCVII** [SimpleMobileTools/Simple-Calendar#988]
Hello,
I enjoy your suite of apps very much, and it really feels like all the stock Android apps can just go away with these.

I'd like you to add a timetable display in calendar view if possible.

This means you could get a good idea of when you are free in the day at a glance. I have difficulties with visualising times in a mental timesheet, and have a bit of trouble using day view as a result.
If the timetable view could display multiple events overlapping, it would be perfect.

**Comment by tibbi** [comment]
doesnt the weekly view work for that? zooming in/out there is on the roadmap.

**Comment by CloneMMDDCVII** [comment]
I hadn't noticed weekly view did that 😅


Although I do think having one day fitting the whole screen could be a good option too.

Thank you very much for the hard work

**Comment by tibbi** [comment]
well adding configurable columns at the weekly view is on the roadmap, so Ill close this. Having 1 day on the full screen doesnt seem like a good idea though.
