### ISSUE TITLE
Calender monthly widget, sorting differently from in-app monthly view

### ISSUE THREAD

**Issue by MysterionNH** [SimpleMobileTools/Simple-Calendar#992]
Hi Tibor,

Simple-Calendar v6.6.1 (F-Droid)
Android 9.0 (LineageOS, MicroG, no root)
(Nextcloud current, DAVx5 current)

There seems to be an issue with having multiple events on the same day, with different start and end times, not overlapping.

Whilst the in-app monthly view (and the list widget) do sort the events in the order they take place, the monthly view widget does not sort them in the correct order (in my case it currently is third, first and the second event).

I tried to look into as to why this is happening, and what they are sorted by instead, but my results are inconclusive (it seems like the last-update time of an event plays a role? But I am not sure)

**Comment by tibbi** [comment]
please send me some sample events, so that I could reproduce it. Just select the events on the list view by long pressing them, Menu -> Share and send yourself the generated .ics file, then paste it here. Thanks

**Comment by MysterionNH** [comment]
`BEGIN:VCALENDAR
PRODID:-//Simple Mobile Tools//NONSGML Event Calendar//EN
VERSION:2.0
BEGIN:VEVENT
SUMMARY:First Event
UID:2f020c8a3d0d4e6da65870b491bc98991570187914042
CATEGORY_COLOR:-13070788
CATEGORIES:Regular event
LAST-MODIFIED:20191004T111834Z
DTSTART:20191018T090000Z
DTEND:20191018T104500Z
STATUS:CONFIRMED
END:VEVENT
BEGIN:VEVENT
SUMMARY:Second Event
UID:aa8bd336f93641c889f1cf282140e12a1570187929921
CATEGORY_COLOR:-13070788
CATEGORIES:Regular event
LAST-MODIFIED:20191004T111945Z
DTSTART:20191018T114500Z
DTEND:20191018T121000Z
STATUS:CONFIRMED
RRULE:FREQ=WEEKLY;INTERVAL=1;BYDAY=FR
END:VEVENT
BEGIN:VEVENT
SUMMARY:Third Event
UID:34f54589752f461b9bcc1bc442f1a7831570187964520
CATEGORY_COLOR:-13070788
CATEGORIES:Regular event
LAST-MODIFIED:20191004T111924Z
DTSTART:20191018T134000Z
DTEND:20191018T154000Z
STATUS:CONFIRMED
END:VEVENT
END:VCALENDAR
`

**Comment by MysterionNH** [comment]
It feels like it has to with whether or not an event is repeating (and maybe how long?)
The actual case I have is with two events repeating until a set date, whilst one event is repeating forever, the forever repeating event is shown last, but the order of the other two is wrong too, so I am not sure :/
I can provide an example for that specific case too, if you need it

**Comment by tibbi** [comment]
this should be good enough for now, Ill take a look at it soon. Thanks

**Comment by tibbi** [comment]
should be improved in version 6.7.0. It might still be glitchy in some more advanced cases involving events lasting multiple days etc, but it should be better than previously
