### ISSUE TITLE
[Feature request] Calendar icon shows currend day / 1x1 widget shows current day

### ISSUE THREAD

**Issue by andregpinto** [SimpleMobileTools/Simple-Calendar#993]
Great work on ALL these apps.
My feature request:
Calendar icon shows actual day of the month in it.
OR
1x1 widget with same look as app icon but with actual day in it (clicking opens the calendar)

**Comment by martkop12** [comment]
Hi, i would like to work on this, can you assign it on me

**Comment by tibbi** [comment]
I dont know how should it be done yet. The app icon color can be customized, that means that the icon can have 19 colors * 31 days versions, which means uploading 589 different icons. That would really increase the app size.

**Comment by andregpinto** [comment]
@tibbi @martkop12 , thanks for the quick reaction.

Just now noticed that there is already one icon per color(19) per DPI(5), currently 95 png files.

After some brainstorming and search I found that it might be possible to use vector drawables.[1]
I believe that these work since api21, which is the minimum here. Example in [2].
This would remove duplicate entries for each DPI.
Note that this is not the same as adaptive icon, only available on api26+.

The xml that defines the shapes and colors would have a default color, but it could be changed programmatically. This would reduce the total files to 31, one per day of the month.

Note: read carefully all answers and comments! accepted answer is outdated
[1] hxxps://stackoverflow.com/questions/35912428/android-vector-drawable-for-launcher-icon-and-other-images-on-android-n
[2] hxxps://github.com/code-schreiber/QuickCode/blob/develop/QuickCode/mobile/src/main/res/drawable/ic_launcher.xml

**Comment by tibbi** [comment]
Well that is the theory, but sadly vectors arent reliable enough to be used as launcher icons. There are some launchers which dont support them, just like not every launcher supports icon color customization at all. Some people change the icon color and that makes the icon disappear. Thats the reason why I added the warning there at changing the icon color for the first time. I will experiment with it again someday in the future, but I dont see like vectors will be usable for launcher icons anytime soon.

**Comment by andregpinto** [comment]
@tibbi I see..
The other option seems to be the widget, the calendar app already has 2 widgets, so a new widget would not add much more code, but the images are a problem there..
Another option is to have a separate widget, a totally independent one (separate apk) just for this purpose, then only people that want this would have to bear the extra KB..

**Comment by tibbi** [comment]
If I add something like that, it will most likely be a widget. The color and sizes could be customized even further with it.

**Comment by andregpinto** [comment]
It's great to hear that.
On the downside it would not show the current day on the app drawer.
Bu I guess we can't have everything we want. 

Thanks for taking the time.

**Comment by andregpinto** [comment]
You actually did it! Thanks! can't wait for the release to try it out.

**Comment by tibbi** [comment]
well it is just the initial version, boring as usually :) It might need some tweaks or customization later in the future
