### ISSUE TITLE
Fix the inability to create events in some CalDAV calendars

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Calendar#999]
most likely caused by missing write permissions, but it seems to work fine without it too

**Comment by Honk2** [comment]
I have a similar issue (Lineage 17.1 / DAVx5)

The default calendar of Lineage 17 is Etar. When I mark a CalDAV calendar in Etar as "do not sync", I can still add an event using SimpleCalendar and the event is shown in SimpleCalendar, but the event does not get synced with the external resource.

The setting in SimleCalendar/DAVx5 is set to sync. The settings from Etar and SimpleCalendar do not interfere, but the setting in Etar prevents SimpleCalendar from syncing.

My solution so far is to set all CalDAV calendars in Etar to sync but do not show.

**Comment by br4nnigan** [comment]
I am using LineageOS with SimpleCalendar 6.11.2 pro and a caldav calendar hosted at fruux.com (free up to 2 devices!).

New events created in SimpleCalendar are not pushed to the caldav.

I can create events fine via Thunderbird calendar.

**Comment by tibbi** [comment]
Are you sure you selected the proper calendar for storing the event? I mean the last field at creating a new event.

**Comment by br4nnigan** [comment]
No, it was set to "store locally", I never realized this existed. Maybe it should default to sync? Idk why you wouldn't want to sync. Thanks for the answer.

**Comment by tibbi** [comment]
well because by default CalDAV sync is disabled, thats how the majority of people use the app. They have events stored locally only.

**Comment by br4nnigan** [comment]
why would I need CalDav when I only store locally? It's a protocol for syncing calendars isn't it? I think that when you use a caldav calendar then it should be synced both ways. It is being read synced anyway - why not write synced?

**Comment by tibbi** [comment]
it is synced if the user selects so. Just select the proper calendar.
